### ISSUE TITLE
Suggestion needed for multi jpeg scanner output workflow.

### ISSUE THREAD

**Issue by zorglups** [jbarlow83/OCRmyPDF#101]
Hello,

My ocrmypdf options are:
--language fra --output-type pdfa --rotate-pages --deskew --clean-final --skip-text 

My input is multi jpg files produced by a scanner.
Those jpeg are rather large (because the scanner does not have the cpu power to make a great job at compression).

Would you suggest me to:
1) Use ImageMagik 'convert' to compress the images to jpeg2000.
2) Pass the resulting images to ocrmypdf with:
   img2pdf --pagesize A4 <my jpeg2000 files> | ocrmypdf <my options> - output.pdf

Or, since I deskew and clean-final the pages, would you suggest to go straight with:
1) img2pdf --pagesize A4 <my scanner files> | ocrmypdf <my options> - output.pdf

The idea being to avoid useless rendering iterations.

Best regards,

Pierre

**Comment by jbarlow83** [comment]
I suggest using ImageMagick to recompress at a lower JPEG quality setting:

```
convert input.jpg -quality 75 output.jpg
```

`-quality` ranges from 0 to 100.

You could also use ImageMagick `-density 200 -units PixelsPerInch` to downsample to a lower DPI. 

And then pass the images.

I recommend against JPEG2000. JPEG encoders usually outperform JPEG2000 with the same bit budget. I don't remember for sure, but I think ghostscript might transcode JPEG2000 to JPEG in some workflows including those used in ocrmypdf.

**Comment by zorglups** [comment]
Sorry for the delay.

Thanks a lot for the suggestion.

Based on the fact that 99% of my input files will A4 format, I decided to compress any file greater than 500KB before passing all files to img2pdf.

In a few lines, this is what I do:
```
                    with Image(filename=full_filename, resolution=200) as original_image:
                        with original_image.convert('jpeg') as converted_image:
                            converted_image.compression_quality = 60
                            converted_image.save(filename=compressed_image_filename)
```

Thank you for your time.
