### ISSUE TITLE
Can't run sphinx-build

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#102]
I'm trying to build the docs, but there is an import error.  Am I using the wrong invocation?

```
hephaestus ~/src/ocrmypdf % sphinx-build docs html            
Running Sphinx v1.4.8

Exception occurred:
  File "conf.py", line 63, in <module>
ImportError: cannot import name 'VERSION'
The full traceback has been saved in /tmp/sphinx-err-5qjvbndf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by jbarlow83** [comment]
It's trying to do

```python
from ocrmypdf import VERSION as OCRMYPDF_VERSION
```

So you need to have ocrmypdf installed (possibly in the current virtualenv) at the time the script is called. Or you could patch the current version into conf.py if that's easier for your build script. AFAIK that's the only thing it needs from the ocrmypdf package.

**Comment by spwhitton** [comment]
`PYTHONPATH=. sphinx-build docs html` does the trick.  Thanks for your reply!
