### ISSUE TITLE
how to retrain existing Tesseract model

### ISSUE THREAD

**Issue by wanghaisheng** [jbarlow83/OCRmyPDF#108]
i have used  this wonderful tool for a little time.though the existing Tesseract model for Chinese is good enough.
i wonder have u ever got a best practise and tips to retrain them against bad case to improve the accuracy?
i have looked up Tesseract docs and  got some material now

**Comment by jbarlow83** [comment]
It's quite difficult and very tedious to train Tesseract on any language or font at this point in time. I don't have any suggestions other than the Tesseract documentation. Commercial software like Abbyy does much better than Tesseract.

Scanning at a higher resolution should help for Chinese. You might need to go as high as 600 DPI.

I believe it helps to provide a word list in many cases, although I don't know how how much that will help for Chinese.
