### ISSUE TITLE
OCRmyPDF test suite failing with ghostscript 9.20

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#110]
It looks like [the test suite is failing](https://ci.debian.net/packages/o/ocrmypdf/unstable/amd64/) because ghostscript's exit codes have changed in version 9.20.  I'm not sure whether it is only the test suite that needs to be updated, or whether OCRmyPDF itself needs some changes.

Thank you for your time.

**Comment by jbarlow83** [comment]
4.3.3 fixes this.

Details for reference:

The change in Ghostscript 9.20 behaviour is described here:
http://www.ghostscript.com/pipermail/gs-commits/2016-May/019965.html

Ghostscript's return codes did not change. OCRmyPDF misspelled a Ghostscript parameter requesting feature elision to create a PDF/A if necessary, and Ghostscript silently accepts the misspelling. Without the parameter, Ghostscript used its default behaviour which is to give up PDF/A and create a regular PDF. ocrmypdf returns error code 4 when it fails to get a PDF/A. The test suite insists on getting a PDF/A when it asks for one, hence the error.

**Comment by spwhitton** [comment]
Thank you for addressing this so quickly.
