### ISSUE TITLE
Possibility to manage --oem and --psm options (tesseract 4.00)

### ISSUE THREAD

**Issue by raymanzarek1984** [jbarlow83/OCRmyPDF#113]
Would be possible to be manage --oem and --psm Tesseract options by OCTmyPDF?

**Comment by jbarlow83** [comment]
Sounds like a good idea.

**Comment by Wikinaut** [comment]
I wanted to ask this, too.....

Perhaps as an OCRmyPDF option `--tesseract-parameters` 

Example:
`$ ocrmypdf --tesseract-parameters --oem 2 in.pdf out.ocr.pdf`

**Comment by jbarlow83** [comment]
The version in the develop branch supports tesseract 4, a --tesseract-oem
argument, text-only mode via --pdf-renderer=tesstop (top=text only pdf,
will rename) and should remove the need to add -j1.

Please try it out and report issues. It's a big change set with some
non-Tess 4 changes as well.
