### ISSUE TITLE
High page count files: speed up split_pages

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#117]
Splitting pages also seems to take a long time probably because it calls one qpdf process per page. Previous tested this with Ghostscript and it's slower.

qpdf's c++ API claims to be faster.

Another option is produce an empty file per page and introduce a transform step that reads that page. At least this would parallelize each qpdf call.

**Comment by ikcalB** [comment]
@jbarlow83 another alternative may be spawning the OCR engine, as soon as there are a few split pages available? (admittedly I did not think about who to implement that using that pipelined approach, just came to my mind)

**Comment by joewiz** [comment]
I'm just curious, what would constitute "high page count"?

**Comment by jbarlow83** [comment]
"It depends" is the best answer I can give but the pause gets noticeable (i.e. a few seconds) around 100 pages. It's still a small delay compared to OCR work.

I confirmed that qpdf's C++ API is much faster. The only thing holding a fix back right now is the release engineering work to add a C++ extension.

#115 is the bigger problem for large files.

**Comment by joewiz** [comment]
Ah, I see, thanks.  I have a 1000 page PDF that chugs for some time at low CPU usage before pegging all 4 cores (on a 2012 Mac Mini, 2.6 GHz Intel Core i7, 16 GB RAM, macOS 10.12.5).  I was wondering if this first step was perhaps the result of the splitting up of files.  Nearly 45 minutes later, the conversion choked with this error:

```text
open /var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/000254.rendered.pdf: Too many open files
  ERROR - Error occurred while running this command:
(Command '['qpdf', '--min-version=1.6', '/var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/000001.rendered.metadata.pdf', '--pages', '/var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/000001.rendered.metadata.pdf', '/var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/000002.rendered.pdf', '/var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/000003.rendered.pdf',`

... and so on until:

```text
'/var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/001135.rendered.pdf', '/var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/001136.rendered.pdf', '--', '/var/folders/_h/142sh8xn1sxclzp4kj0bk06w0000gn/T/com.github.ocrmypdf.rsxqsgq1/merged.pdf']' returned non-zero exit status 2.)
```

`ulimit -n` returns 256. Perhaps I need to raise this limit - or do you have other suggestions? I'm happy to open a new issue or provide the file or other info if it would be helpful.

**Comment by jbarlow83** [comment]
Oh, that's a new issue. It failed to merge the final results after successfully OCRing every single page. :(

Most likely that is a qpdf bug – looks like it leaks file handles when asked to merge a lot of files. 

Your options for now:
-raise ulimit to more than 1000 (assuming qpdf needs one handle per page)
-split PDF into increments of 200 pages to stay under ulimit
-try `--output-type pdfa` to merge with Ghostscript (if PDF/A is suitable) since it may not have this file handle limit problem

I likely won't be able to fix this without creating the C++ extension I mentioned.

**Comment by jbarlow83** [comment]
This is fixed now
