### ISSUE TITLE
Installing on Ubuntu 16.04 using some PPAs

### ISSUE THREAD

**Issue by adamlove86** [jbarlow83/OCRmyPDF#118]
Am running a Dreamcompute 16.04 image attempting to install:

Thanks for your help!

**attempt 1:**
apt-get install ocrmypdf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ocrmypdf

**alternative:**
ubuntu@snappy-nextcloud:~$ sudo add-apt-repository ppa:vshn/ghostscript -y
(key info)
OK

ubuntu@snappy-nextcloud:~$ sudo add-apt-repository ppa:heyarje/libav-11 -y
(key info)
OK

ubuntu@snappy-nextcloud:~$ sudo apt-get update
Ign:1 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease                                            
Hit:3 http://iad-2.clouds.archive.ubuntu.com/ubuntu xenial InRelease                                         
Hit:4 http://iad-2.clouds.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://iad-2.clouds.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:6 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial InRelease 
Ign:7 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial Release
Ign:8 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial Release
Ign:9 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main amd64 Packages
Ign:14 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main all Packages
Ign:15 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en_US
Ign:16 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en
Ign:9 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main amd64 Packages
Ign:14 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main all Packages
Ign:15 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en_US
Ign:16 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en
Ign:9 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main amd64 Packages
Ign:14 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main all Packages
Ign:15 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en_US
Ign:16 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en
Ign:9 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main amd64 Packages
Ign:14 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main all Packages
Ign:15 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en_US
Ign:16 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en
Ign:9 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en
Ign:13 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main amd64 Packages
Ign:14 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main all Packages
Ign:15 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en_US
Ign:16 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en
Err:9 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:10 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en_US
Ign:12 http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial/main Translation-en
Err:13 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:14 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main all Packages
Ign:15 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en_US
Ign:16 http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial/main Translation-en
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/heyarje/libav-11/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/vshn/ghostscript/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/heyarje/libav-11/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/vshn/ghostscript/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

ubuntu@snappy-nextcloud:~$ sudo apt-get install \
>    zlib1g-dev \
>    libjpeg-dev \
>    libffi-dev \
>    libavformat56 libavcodec56 libavutil54 \
>    ghostscript \
>    tesseract-ocr \
>    qpdf \
>    python3-pip \
>    python3-pil \
>    python3-pytest \
>    python3-reportlab
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libavformat56
E: Unable to locate package libavcodec56
E: Unable to locate package libavutil54

**Comment by jbarlow83** [comment]
The first ubuntu to support ocrmypdf is 16.10 hence the error on 16.04. I
haven't specifically checked how to get it working on 16.04.

Try replacing the various libav* packages with simply "unpaper" and letting
Ubuntu figure out how to satisfy those dependencies. Ocrmypdf does not
require the libav* packages itself, these are used by unpaper. Unpaper is
optional anyway, only required for the --clean argument.

**Comment by adamlove86** [comment]
Thanks for your help - will give it a try and let you know

**Comment by jbarlow83** [comment]
I updated the installation instructions with steps for Ubuntu 16.04. I have tested them on a fresh Docker image of Ubuntu 16.04. Please try the new steps and re-open this issue if you have any trouble.

https://ocrmypdf.readthedocs.io/en/latest/installation.html

**Comment by ninetyfivenorth** [comment]
Just got the source .list file for the libav PPA in your /etc/apt/sources.list.d/ directory and using $nano just edit the deb / deb-src lines to use "trusty" in place of the "*your ubuntu dist*" / "xenial" etc. 

P.S. if you don't know what your system is go to terminal and run;
`uname -a`
this will give you a liner of your systems spec

then more importantly though, if you don't know which _release_ of ubuntu you are on, then you can run;
`lsb_release`
if this shows nothing or an error such as "no LSB release" etc then just **yank** out the damn distro;
`sudo nano /etc/lsb-release`
take note of the release version number i.e. 14.04,16.04,18.04 etc. and specifically, the name of your dist.

I have done this in the past sucessfully but be forewarned here... this is placing your system in danger of breaking (technically). You just don't usually mix dist types of PPA's on a system... leads to bad conflicts--as a rule of thumb. Since I am familiar with this exact repository and what it contains, I am confident in suggesting your "testing" of my provided suggested course of action(s).  =]

email me at artik@cock.li if you need further help
[that is a very real and very mine--email address, don't worry] lolpce

**Comment by jbarlow83** [comment]
@ninetyfivenorth This is quite an old issue, it's not current, and your instructions seem to be giving general advice about Ubuntu rather than ocrmypdf. I welcome contributions generally, but I am letting you know that I am removing your comment because I don't believe it will be helpful to any users. For one thing, I'm not entirely sure what your concern is. If you do have a specific comment on the installation instructions for ocrmypdf, please open a new issue and we can discuss them there.
