### ISSUE TITLE
from __future__ import ...

### ISSUE THREAD

**Issue by amitdo** [jbarlow83/OCRmyPDF#119]
https://github.com/jbarlow83/OCRmyPDF/search?utf8=%E2%9C%93&q=__future__

I think you can drop it since you only support python 3.x

**Comment by jbarlow83** [comment]
Thanks.

I still need it in a few places for users who try to install/run on python 2.x and get a syntax error on print(). Because people have done this before and opened issues for it.

Users, you know....
