### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by DeliciousPickle** [jbarlow83/OCRmyPDF#120]
Hi, James, sorry for entering this as an issue, but I didn't know how else to contact you.  I'm thrilled to finally find OCRmyPDF as it's the first app I've found that makes this truly easy.  Congrats to you and the other contributors for an excellent effort.  

I have a large directory tree of PDFs that need to be OCR'ed.  I am thinking about writing a Python script that will iterate through the directory tree and OCR the pdf files one by one.  I don't much care how long it takes to run as this is an archival collection of files with no urgent search need.

Before doing this, I wanted to ask you if OCRmyPDF has a built-in batch mode that would handle the directory traversal for me.  I read your docs on Batch Jobs at https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#batch-jobs 
but I didn't understand the syntax of the example command shown there.  Can you advise me as to the best approach to take for this?
Thanks,
Phil

**Comment by jbarlow83** [comment]
You're welcome, glad you find it useful.

There's no batch mode because other programs and scripts do a fine job of it.

To walk through a directory and replace all files in place you could do

```bash
find . -name '*.pdf' -exec ocrmypdf --deskew '{}' '{}' \;
```

`find -exec` runs the command and replaces each occurrence of `'{}'` with the filename, so you can use this twice. Files that cannot be OCR'd will be left unmodified by this command.

You can also use find to generate the names and use GNU parallel to [change the name of the output file](https://www.gnu.org/software/parallel/parallel_tutorial.html#Replacement-strings) since it has more options for that. In this example `./input/a/test.pdf` would be saved to `./output/a/test_ocr.pdf`

```bash
find input -name '*.pdf' | parallel -j1 ocrmypdf --deskew '{}' 'output/{.}_ocr.pdf'
```

`parallel` also has options to capture the output of each command so you can use it to organize log files. ocrmypdf only writes to stderr.

I am working on some changes that will ultimately lead to an API so that ocrmypdf is scriptable from Python, but at the moment the interface is the command line.

**Comment by DeliciousPickle** [comment]
Thanks for your help with this.  Here's a little script I wrote that seems to work pretty well:

`
#!/usr/bin/env python

import logging
import os
import subprocess
import sys

scriptDir = os.path.dirname(os.path.realpath(__file__))
print scriptDir + '/ocr-tree.py: Start'

if len(sys.argv) > 1:
    startDirectory = sys.argv[1]
else:
    startDirectory = '.'

if len(sys.argv) > 2:
    logFile = sys.argv[2]
else:
    logFile = scriptDir + '/ocr-tree.log'

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s', filename=logFile, filemode='w')

for directoryName, subdirectoryList, fileList in os.walk(startDirectory):
    logging.info('\n')
    logging.info(directoryName + '\n')
    os.chdir(directoryName)
    for eachFileName in fileList:
        fileExtension = os.path.splitext(eachFileName)[1]
        #print fileExtension
        if fileExtension == '.pdf':
            fullPath = directoryName + '/' + eachFileName
            print fullPath
            ocrCommand = [r"ocrmypdf",  "--deskew", eachFileName, eachFileName]
            logging.info(ocrCommand)
            proc = subprocess.Popen(ocrCommand, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            result = proc.stdout.read()
            if 'page already has text' in result:
                result = 'Skipped document because it already contained text'
                print result
            else:
                print 'OCR complete'
            logging.info(result)
`

**Comment by DeliciousPickle** [comment]
Here is a shell script that will watch a single folder and OCR any file that is placed there:
```bash
#!/usr/bin/env bash

# OCR command:
# ocrmypdf --deskew <fileName> <fileName>
watchmedo shell-command \
    --patterns="*.pdf" \
    --ignore-directories \
    --command='echo "$(date) ${watch_src_path}" >> ocr-watch.log; echo "  Event: ${watch_event_type}" >> ocr-watch.log; ocrmypdf --deskew "${watch_src_path}" "${watch_src_path}" >> ocr-watch.log 2>&1'&
```
The script requires the Python **watchdog** library and the **watchmedo** utility.

**Comment by jbarlow83** [comment]
Thanks. Do you mind if I add these to the documentation?

There is a list of return codes currently in __init__.py (due to move in the next release) which is more reliable than parsing output text. Return code 6 is issued whenever "page already has text".

**Comment by DeliciousPickle** [comment]
By all means, happy to share.  Good to know about the return codes.  Right now my watcher just errors out for events where the file has moved or been deleted.  It would be better to read the error codes and only attempt to scan for a new file or file changed event.

**Comment by jbarlow83** [comment]
Examples added to v4.4 docs.
