### ISSUE TITLE
/home/docker: Permission denied

### ISSUE THREAD

**Issue by bubblefish432** [jbarlow83/OCRmyPDF#122]
I become the Error:
root@omv2:~# docker run --rm -v /media/53db9167-314a-44c9-ba9a-d29ea28404f6/dokumente/temp:/home/docker ocrmypdf OCR000544.pdf OCRtest.pdf
/application/docker-wrapper.sh: line 4: cd: /home/docker: Permission denied
  ERROR - File not found - OCR000544.pdf

I tried with CHMOD 777 for both directorys
/media/53db9167-314a-44c9-ba9a-d29ea28404f6/dokumente/temp
/home/docker

but the same Problem

**Comment by bubblefish432** [comment]
Debian Jessie with
Docker version 1.12.5, build 7392c3b
ocrmypdf:latest

**Comment by jbarlow83** [comment]
Try copying the file to your local drive rather than whatever the /media
device is, and running from that folder.

**Comment by bubblefish432** [comment]
OK thats it, 

root@omv2:~# docker run --rm -v /home/docker:/home/docker ocrmypdf OCR000544.pdf OCRtest.pdf
   INFO - Output file is a PDF/A-2B (as expected)

also i must move the PDFs to the /home/docker and then after OCR return to the /media/53db9167-314a-44c9-ba9a-d29ea28404f6/dokumente/temp  directory

**Comment by jbarlow83** [comment]
> also i must move the PDFs to the /home/docker and then after OCR return to the /media/53db9167-314a-44c9-ba9a-d29ea28404f6/dokumente/temp directory

I realize this is inconvenient, but this is beyond my control. The volume needs to be writable from docker, and if the mount point is a special device or read-only file system "chmod 777" will not override that.

**Comment by usharf** [comment]
I'm trying to copy training  data to ```/usr/share/tess```...  etc. and seeing the same error message even though it's mapped to my ```/home/user directory```. It is a LUKS filesystem.... could this be the problem?

**Comment by jbarlow83** [comment]
It's better to use `docker cp` to copy data into a Docker container from the outside, than anything where you're inside the Docker container trying to copy in data from the host. The latter case requires *mutual* agreement on permissions since both try to enforce permissions.

You could also fork the Dockerfile.

**Comment by usharf** [comment]
Ok, thank you. I'm not that familiar with Docker and forgot you can copy this way. BTW, the documentation recommends copying from inside the container.
