### ISSUE TITLE
OCRmyPDF not correctly working with tesseract 4

### ISSUE THREAD

**Issue by Wikinaut** [jbarlow83/OCRmyPDF#124]
ocrmypdf is not working as expected on my machine (INTEL NUC i7 and debian 8 Jessie). 

Tesseract (current git version incl. updated traineddata) however is working and is quick.

my command line:
```
$ ocrmypdf -l deu+eng -g -c --force-ocr x.pdf x.out.pdf
....
WARNING -    2: [tesseract]  took too long to OCR - skipping
WARNING -    3: [tesseract]  took too long to OCR - skipping
WARNING -    1: [tesseract]  took too long to OCR - skipping
INFO - Output file is a PDF/A-2B (as expected)
```
No txt is extracted.

When I use
```
$ ocrmypdf -l deu+eng -g -c --force-ocr -pdf-renderer tesseract x.pdf x.out.pdf
```
it takes a long time and then badly ocr-ed pdf is generated.

I have tesseract installed from github:
```
$ tesseract --version
tesseract 4.00.00alpha
 leptonica-1.74.1
  libjpeg 6b (libjpeg-turbo 1.3.1) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

 Found AVX
 Found SSE
```
and tesseract as such works perfectly, especially with its new LSTM algorithm.

Please can you assist ? I suppose there's a problem with the preprocessing or detection of Tesseract.
I also tried the `-v` verbose option. Cannot find a real problem.

**Comment by jbarlow83** [comment]
I haven't made any tesseract 4.0 adjustments yet. Whenever I've tried to test it something always seems to be broken. It seems to me that the "osd.traineddata" file is out of date in the latest set - if you know how to get that working let me know. I can't get rid of:

```
Failed loading language 'osd'
Tesseract couldn't load any languages!
Warning: Auto orientation and script detection requested, but osd language failed to load
```

`--tesseract-timeout` is the maximum amount of time ocrmypdf will allow per page, defaulting to 3 minutes. "took too long to OCR" is the message the limit is exceeded. This error message should be made clearer.

Could you send me a sample PDF/image and let me know what command you are running tesseract with so I can compare results on my end?

**Comment by jbarlow83** [comment]
Figured out the osd thing... I found three bugs in tesseract 4.0 today while trying to get set up to understand your issue, never mind actually solve it. :|

**Comment by Wikinaut** [comment]
`-rw-r--r--  1 root staff 10562727 Jan 13 03:00 osd.traineddata`

Some days ago I started with a fresh checkout of tesseract and the data:

```
cd /usr/local/src
git clone https://github.com/tesseract-ocr/tesseract

(autogen, configure, make, make install)

cd /usr/local/share

(complete checkout of all language data:)
git clone https://github.com/tesseract-ocr/tessdata

(copy profile data from the code to the tessdata directory)
cp -r /usr/local/src/tesseract/tessdata/ .

**Comment by Wikinaut** [comment]
and this (tesseract as such) works and is very quick and returns high quality results.

**Comment by jbarlow83** [comment]
After I finally got tessdata set up correctly (had a corrupt osd.traineddata, thanks for listing the file size, that tipped me off), I got ocrmypdf 4.3.5 to use Tesseract 4.00 without any changes to ocrmypdf.

My best guess is that your ocrmypdf isn't finding tesseract 4.0. Bad OCR means it's probably finding an older tesseract :). It should be just be searching the system PATH.

You could confirm this by checking the Producer tag in the output file, e.g. with `pdfinfo` (from poppler-utils), because I embed the Tesseract version in output files:

```
Creator:        ocrmypdf 4.3.5 / Tesseract OCR 4.00.00alpha
Producer:       GPL Ghostscript 9.19
```

Try setting the environment variable OCRMYPDF_TESSERACT to point at the 4.0 binary to see if that changes the results. You might also need to set TESSDATA_PREFIX to the parent of the 4.0 tessdata/ directory.

**Comment by Wikinaut** [comment]
@jbarlow83 works for a single page pdf, but fails for a three-pages pdf.

#### single page doc:
```
$ ocrmypdf -l deu --force-ocr singlepage-in.pdf singlepage-out.pdf
   INFO -    1: page already has text! – rasterizing text and running OCR anyway
   INFO - Output file is a PDF/A-2B (as expected)

$ pdfinfo singlepage-out.pdf
...
Creator:        ocrmypdf 4.3.5 / Tesseract OCR 4.00.00alpha
Producer:       GPL Ghostscript 9.06
...
Page size:      1036.8 x 1686.86 pts
Page rot:       0
File size:      105930 bytes
Optimized:      no
PDF version:    1.4
```

#### three pages doc:
```
$ ocrmypdf -l deu --force-ocr threepages-in.pdf threepages-out.pdf
   INFO -    3: page already has text! – rasterizing text and running OCR anyway
   INFO -    2: page already has text! – rasterizing text and running OCR anyway
   INFO -    1: page already has text! – rasterizing text and running OCR anyway
WARNING -    3: [tesseract]  took too long to OCR - skipping
WARNING -    2: [tesseract]  took too long to OCR - skipping
WARNING -    1: [tesseract]  took too long to OCR - skipping
   INFO - Output file is a PDF/A-2B (as expected)

$pdfinfo threepages-out.pdf
...
Creator:        ocrmypdf 4.3.5 / Tesseract OCR 4.00.00alpha
Producer:       GPL Ghostscript 9.06
...
Page size:      1022.4 x 1678.63 pts
Page rot:       0
File size:      581462 bytes
Optimized:      no
PDF version:    1.4
```

**Comment by jbarlow83** [comment]
From what I gather you don't have a sample PDF you can send.

Ghostscript 9.06 is quite old (almost 5 years old). I recommend at least 9.15, ideally 9.20. Use the argument `--output-type pdf` if you can't find a suitable backport; that will skip PDF/A conversion. Some older versions of Ghostscript have a bug that corrupts Unicode OCR text in some cases. However, this is probably not the issue.

* Could you running the same tests on `tests/resources/linn.pdf` and `cardinal.pdf`? These files are based on the same image. The second is just the first page four times and rotated.

* Could you try `ocrmypdf -j1` and see if behavior is different? This restricts ocrmypdf to a single CPU. Perhaps tesseract 4.0 starts and ocrmypdf together start too many threads.

* Could you check if tesseract is using multiple threads while it runs?

Thanks.

**Comment by Wikinaut** [comment]
@jbarlow83 I tried to start with `ocrmypdf -j1` and, bingo!, this worked immediately.

I have a NUC i7 and the CPU http://www.intel.com/content/www/us/en/nuc/nuc-kit-nuc5i7ryh.html is dual core:

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 61
Model name:            Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
Stepping:              4
CPU MHz:               1696.039
CPU max MHz:           3400,0000
CPU min MHz:           500,0000
BogoMIPS:              6185.95
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
NUMA node0 CPU(s):     0-3
```

The PDF output quality is bad, but this is of course a totally different issue.

**Comment by Wikinaut** [comment]
@jbarlow83 regarding ghostscript, I use the "regular" (but as I now know, hopelessly outdated) package from the repo.

**Comment by Wikinaut** [comment]
Note to myself: `ocrmypdf -j1 --output-type pdf  -l deu --force-ocr in.pdf out.pdf`

**Comment by Wikinaut** [comment]
(I reported this issue. Solved now. Add `-j1` )

**Comment by hongyi-zhao** [comment]
I meet the same problem with git master version of [tesseract](https://github.com/tesseract-ocr/tesseract) and [tessdata_best](https://github.com/tesseract-ocr/tessdata_best).
