### ISSUE TITLE
[Question] get_program()

### ISSUE THREAD

**Issue by Wikinaut** [jbarlow83/OCRmyPDF#127]
@jbarlow83 pls. allow me the question, where and how in `tesseract.py` and `__init.py__`  `get_program('tesseract')` seems to get the path of that program (this is what I understand).

**Comment by jbarlow83** [comment]
It checks the environment variable OCRMYPDF_TESSERACT (for the absolute
path to any executable) followed by searching the current PATH for a
program named "tesseract".

**Comment by Wikinaut** [comment]
In __init.py__, but - "where and how" is that value actually set ? I was puzzled because I could not find any description of the get_name() method. Pls. can you assist ?

**Comment by jbarlow83** [comment]
def get_program(name):
    envvar = 'OCRMYPDF_' + name.upper()
    return os.environ.get(envvar, name)

If the environment variable is not set by the user then it return name
(the fallback value given to .get).

**Comment by Wikinaut** [comment]
I saw that code, yes.

Thanks for enlightment regarding the default. So on my system, when I do not export OCRMYPDF_TESSERACT=/usr/local/bin/tesseract then it will call `tesseract`in tesseract.py.

This is now my understanding, ty. (closing this).
