### ISSUE TITLE
OCRmyPDF with Tesseract 4 docker image

### ISSUE THREAD

**Issue by marios88** [jbarlow83/OCRmyPDF#129]
Do you have any plans on making a docker image with tess4 LSTM? 

Saw the release notes on using "--tesseract-oem 2" but got
`WARNING - --tesseract-oem requires Tesseract 4.x -- argument ignored`

**Comment by jbarlow83** [comment]
Yes, I do. Of course, if you're feeling inspired to take a stab at it, please do. You could probably extend the existing Ubuntu based tesseract 4 docker image.

**Comment by marios88** [comment]
I tried to, but failed miserably, i will give a another shot over the weekend tho :)

**Comment by jbarlow83** [comment]
Created:
https://hub.docker.com/r/jbarlow83/ocrmypdf-tess4/
