### ISSUE TITLE
command line option to disable tesseract dictionary

### ISSUE THREAD

**Issue by marios88** [jbarlow83/OCRmyPDF#130]
Would be great to have an option to completely disable the dictionary tesseract uses internally

**Comment by jbarlow83** [comment]
Probably not hard to do, but...

* Out of curiosity why do you want to do this?

* Do you happen to know how to do this with tesseract standalone? There are several dictionary-related features in tesseract:

```
$ tesseract --print-parameters | grep dict
stopper_smallword_size	2	Size of dict word to be treated as non-dict word
suspect_short_words	2	Don't suspect dict wds longer than this
tessedit_enable_doc_dict	1	Add words to the document dictionary
tessedit_enable_bigram_correction	1	Enable correction based on the word bigram dictionary.
tessedit_enable_dict_correction	0	Enable single word correction based on the dictionary.
rej_1Il_use_dict_word	0	Use dictword test
tessedit_override_permuter	1	According to dict_word
output_ambig_words_file		Output file for ambiguities found in the dictionary
segment_penalty_dict_frequent_word	1	Score multiplier for word matches which have good case andare frequent in the given language (lower is better).
segment_penalty_dict_case_ok	1.1	Score multiplier for word matches that have good case (lower is better).
segment_penalty_dict_case_bad	1.3125	Default score multiplier for word matches, which may have case issues (lower is better).
segment_penalty_dict_nonword	1.25	Score multiplier for glyph fragment segmentations which do not match a dictionary word (lower is better).
segment_penalty_garbage	1.5	Score multiplier for poorly cased strings that are not in the dictionary and generally look like garbage (lower is better).
stopper_nondict_certainty_base	-2.5	Certainty threshold for non-dict words
stopper_certainty_per_char	-0.5	Certainty to add for each dict char above small word size.
doc_dict_pending_threshold	0	Worst certainty for using pending dictionary
doc_dict_certainty_threshold	-2.25	Worst certainty for words that can be inserted into thedocument dictionary
language_model_penalty_non_freq_dict_word	0.1	Penalty for words not in the frequent word dictionary
language_model_penalty_non_dict_word	0.15	Penalty for non-dictionary words
```

**Comment by marios88** [comment]
The current use case is automated ocring and archiving of invoices. The relevant data is not dictionary based as they are not real written language.

scanned text includes
`SOME COMPANY NAME`
`phone numbers - addresses`
`inventory codes like "S145874000-H3344"`
`prices "100,00" or "100.00"`


I believe the options to disable are 
`load_system_dawg = 0`
`language_model_penalty_non_dict_word = 0`
`language_model_penalty_non_freq_dict_word =0`
source https://github.com/tesseract-ocr/tesseract/wiki/ControlParams

**Comment by jbarlow83** [comment]
Turns out this is already possible using tesseract config files:

For example, create a file named "no-dict.cfg":

```
load_system_dawg 0
language_model_penalty_non_dict_word 0
language_model_penalty_non_freq_dict_word 0
```

and then passing the name of the config file to OCRmyPDF and tesseract via ``--tesseract-config``:

```
ocrmypdf --tesseract-config no-dict.cfg tests/resources/ccitt.pdf _nodict.pdf
```

That is equivalent to ``tesseract <image> <output-prefix> nodict.cfg <hocr/pdf>``.

This works for tess 3 as well.

**Comment by jbarlow83** [comment]
I will update the documentation to describe this feature.

**Comment by jbarlow83** [comment]
Documentation updated.
https://ocrmypdf.readthedocs.io/en/latest/advanced.html#changing-tesseract-configuration-variables

I think that should be sufficient. It's less convenient admittedly than a dedicated argument, but more configurable. (For example, one could suppress use of the dictionary without disabling it entirely.) That said I am open to suggestions if you feel a dedicated argument is warranted.
