### ISSUE TITLE
OCRmyPDF in cron

### ISSUE THREAD

**Issue by libelle17** [jbarlow83/OCRmyPDF#131]
When ocrmypdf is called from within a cron job (in my example from within a c++-program), the path to all called sub-processes need not be found automatically.
Therefore, my ocrmypdf could not find 'unpaper' and therefore stopped, in contrast to calling ocrmypdf manually, where it works without error.
I could repair this feature for me by creating a symbolic link on "unpaper" (in this case, in /usr/local/bin) called "unpaper" in the directory of OCRmypdf (in this case, /usr/bin).

**Comment by jbarlow83** [comment]
Most likely the user that runs cron does not have `/usr/local/bin` on its PATH.

If that doesn't resolve the issue please feel to reopen.
