### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by libelle17** [jbarlow83/OCRmyPDF#132]
With which script could I uninstall OCRmyPDF?

**Comment by jbarlow83** [comment]
apt-get uninstall ocrmypdf on Debian/ubuntu or pip remove ocrmypdf if you
installed using Pip. Remove the docker image if you installed with docker.

May I ask why you are planning to uninstall?

**Comment by libelle17** [comment]
Thank You for the quick answer!
Im am writing a program for sending automatically and receveiving faxes (https://github.com/libelle17/autofax) which shall call Your ocrmypdf optionally and I want to add an uninstall-script to my program which can also uninstall dependant programs.

**Comment by jbarlow83** [comment]
Interesting project.

For that kind of use, I recommend installing ocrmypdf to a Python virtual environment when installing, to isolate it from the system. Then delete the whole virtual environment folder on uninstall. That way if user has a separate installation of ocrmypdf it won't be affected by uninstalling your program. It would also let you choose which version of ocrmypdf to include.

```bash
python3 -m venv autofax-venv
source autofax-venv/bin/activate
pip install ocrmypdf==4.4.1

deactivate
rm -r autofax-venv/
```
