### ISSUE TITLE
Proportions of non-square aspect ratio images distorted

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#137]
@AEgit The images in the file have a non-square aspect ratio (about 107x124 DPI). ocrmypdf supports these, but it seems one or more of the code paths is buggy or I introduced a regression at some point since they are somewhat rare. Might also be related to JPEG and ``--force-ocr``.

A short term fix is to use Ghostscript to rewrite them to square DPI and (``-r 150`` would do). That may not be a bad idea anyway, as many programs have poor support for non-square aspect ratio.

**Comment by jbarlow83** [comment]
Opening comment and links to files are here
https://github.com/jbarlow83/OCRmyPDF/issues/134#issuecomment-279955460

**Comment by AEgit** [comment]
@jbarlow83: Thank you for the quick reply! Yes, unfortunately I have no control over how those files are generated in the first place (when I do the scanning on my own, I don't run into such problems).

**Comment by jbarlow83** [comment]
fixed 4.5.1

**Comment by AEgit** [comment]
I can confirm that this issue has been solved in version 4.5.1.
Thank you very much for your help!
