### ISSUE TITLE
OCR not possible: "not a valid PDF, and could not repair it."

### ISSUE THREAD

**Issue by AEgit** [jbarlow83/OCRmyPDF#138]
This PDF file cannot be OCRed (even when using --force-ocr):
https://app.box.com/s/wtsht3h8atqi4e9p00wd93c9zty8oh3w

The error message "not a valid PDF, and could not repair it" appears. Despite the message, it is possible to open the original PDF and view it.

```
ocrmypdf -l eng --force-ocr Test.pdf Test_ocr.pdf
ERROR - /tmp/com.github.ocrmypdf.f7ilf7wc/origin.pdf: not a valid PDF, and could not repair it.
ERROR - Details: attempt to make a stream into a direct object   
```                                                     

As the PDF probably stems from the source that produced the distorted PDFs (see https://github.com/jbarlow83/OCRmyPDF/issues/137), this issue might be related to it (?).

**Comment by jbarlow83** [comment]
The file worked for me, although the output is unusable. The image and OCR text positioning is all wrong (like #137). Attached file for reference.

That error comes from the qpdf library. What is `qpdf --version`? Mine is 6.0.0.

[_test1.pdf](https://github.com/jbarlow83/OCRmyPDF/files/797498/_test1.pdf)

**Comment by AEgit** [comment]
Ah yes, my qpdf version is just 5.1.1

**Comment by jbarlow83** [comment]
It looks like this error was fixed in qpdf 5.1.2.
https://github.com/qpdf/qpdf/blob/master/ChangeLog

**Comment by AEgit** [comment]
Yes, I can confirm that the OCR is produced with an updated version of qpdf. As you mention, the pages are distorted like in https://github.com/jbarlow83/OCRmyPDF/issues/137). Furthermore, the order of the pages has also changed completely. Is this issue also related to https://github.com/jbarlow83/OCRmyPDF/issues/137 or do you think it might be something different?

Thank you for your quick help!

**Comment by AEgit** [comment]
Ah, no sorry - the PDF is just so distorted, that only half of the page is visible. I thought initially, that the order of the pages had flipped, but actually those pages are just not visible  - so everything behaves as described in https://github.com/jbarlow83/OCRmyPDF/issues/137.
