### ISSUE TITLE
Documentation: invalid choice 'tess4'

### ISSUE THREAD

**Issue by tuxflo** [jbarlow83/OCRmyPDF#141]
I'm experimenting with the tesseract version 4 using the ppa (https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr).
If I try to set the pdf-renderer to `tess4` as mentioned in the docs, the following error occurs:
`ocrmypdf: error: argument --pdf-renderer: invalid choice: 'tess4' (choose from 'auto', 'tesseract', 'hocr')`

I used the following parameters:
`ocrmypdf -c -d -f --pdf-renderer tess4 -l deu test.pdf tess4.pdf`

Are the parameters `--pdf-renderer tess4` and `--tesseract-oem` required if I have a tesseract4 only system?

**Comment by jbarlow83** [comment]
It sounds like you have an older version of ocrmypdf from before I added
tesseract 4 features. The version available from apt does not have this.

The new parameters are not required, unless you want to access new features
in tesseract 4.

**Comment by tuxflo** [comment]
Yes I installed ocrmypdf with apt:
`ocrmypdf --version
4.2.2`
I'll try it with a newer version built from the source.

Thanks for the quick reply!
