### ISSUE TITLE
Feature request: quieter output

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#143]
It would be great if I ocrmypdf had a quiet mode, which suppressed the `INFO` notifications.  Thanks.

**Comment by jbarlow83** [comment]
Fixed in 2a61902.

The same commit also fixes this issue reported in ocrmypdf Ubuntu:
https://bugs.launchpad.net/ubuntu/+source/ocrmypdf/+bug/1687308
