### ISSUE TITLE
--remove-background "damages" PDF when outputting to stdout

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#144]
I am using `qpdf --linearize` to shrink the filesize of a PDF after processing it with OCRmyPDF:

    % ocrmypdf -c -i -r --remove-background temp2.pdf - >temp.pdf
    % qpdf --linearize temp.pdf output.pdf

But I get this error:

    WARNING: temp.pdf: file is damaged
    WARNING: temp.pdf: can't find startxref
    WARNING: temp.pdf: Attempting to reconstruct cross-reference table
    temp.pdf: unable to find trailer dictionary while recovering damaged file

This problem does not occur if ocrmypdf outputs directly to temp.pdf, rather than stdout.  Nor does it occur if I drop `--remove-background`.

The attached file is hereby released under OCRmyPDF's current license.

[temp2.pdf](https://github.com/jbarlow83/OCRmyPDF/files/836984/temp2.pdf)

Thanks.

**Comment by jbarlow83** [comment]
I suspect that this actually due to not flushing stdout in v4.3.4 which corrupts some files depending on when the OS decides to flush the output buffer. I fixed this in v4.4. 

I suppose this is enough of a bug to warrant being patched into Debian. That is a one line fix:

```
diff --git a/ocrmypdf/__main__.py b/ocrmypdf/__main__.py
index 8c2f54e..a94e7a1 100755
--- a/ocrmypdf/__main__.py
+++ b/ocrmypdf/__main__.py
@@ -1350,6 +1350,7 @@ def copy_final(
         from shutil import copyfileobj
         with open(input_file, 'rb') as input_stream:
             copyfileobj(input_stream, sys.stdout.buffer)
+            sys.stdout.flush()
     else:
         shutil.copy(input_file, output_file)
``` 

The fix comes from 6cc5135 which is identical except that the code was moved to a new file.

**Comment by jbarlow83** [comment]
Correction: I see Debian is actually using v4.3.5. The patch should work against v4.3.5 as well.

**Comment by spwhitton** [comment]
Thank you for your reply.  Unfortunately, this bug would not be serious
enough to justify patching the version in Debian until after our current
pre-release freeze.

My apologies for not testing with the latest version of OCRmyPDF -- I
forgot my version is old.

-- 
Sean Whitton
