### ISSUE TITLE
how to visible ocr layer?

### ISSUE THREAD

**Issue by sickHamm** [jbarlow83/OCRmyPDF#146]

**Comment by jbarlow83** [comment]
You can use the debug rendering mode (I forget the switch, see --help) to
see what the OCR looks like approximately. Or use a program such as
poppler's pdftotext to produce the output without positioning information.

There is no way to make the text layer in an existing PDF visible.

**Comment by sickHamm** [comment]
thanks you explicit answer. and I will try some workaround [method](https://stackoverflow.com/questions/29331731/postscript-code-to-un-hide-hidden-text-in-pdf)
