### ISSUE TITLE
pdf/a entry

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#148]
Hi,
a bit off topic but does someone know how to remove the pdf/a-1b information from a pdf file?
Background: I have some pdfs that were edited after ocrmypdf and are no longer in pdf/a-1b format but show that they are. For consistency I would like to remove this entry. Can this be done with pdftk or with qpdf? How?
I recently found a java software [https://github.com/verapdf] which has obviously hard criteria to check for pdf/a conformity.
Thanks, Femi

**Comment by jbarlow83** [comment]
I believe pdftk will strip PDF/A when used as a pass through (pdftk in.pdf
cat output out.pdf). It has an option to dump metadata as well which could
work. The PDF/A marker is in the XMP metadata.
