### ISSUE TITLE
ĈĴĜĤŜŬ all turning into ■ (-l epo, Tesseract 4, UTF-8 problem?)

### ISSUE THREAD

**Issue by ctrlcctrlv** [jbarlow83/OCRmyPDF#150]
I used this program to make an OCR layer for a book in Esperanto, but all special characters are turning into ■ for some reason :(

My command line:

```ocrmypdf -j 5 -r -l epo ~/WINDOWS/Korano.pdf Korano.pdf```

![c to square](https://cloud.githubusercontent.com/assets/838783/24856450/6295f3b4-1e17-11e7-9421-b1325ed06951.png)

Although in the image you see me using Windows, I actually installed `ocrmypdf` in an Arch Linux VM. Software versions:

```
tesseract 4.00.00alpha
 leptonica-1.74
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.1) : libpng 1.6.28 : libtiff 4.0.7 : zlib 1.2.11 : libwebp 0.5.2

 Found AVX
 Found SSE

GPL Ghostscript 9.21 (2017-03-16)
Copyright (C) 2017 Artifex Software, Inc.  All rights reserved.

qpdf version 6.0.0
Copyright (c) 2005-2015 Jay Berkenbilt
This software may be distributed under the terms of version 2 of the
Artistic License which may be found in the source distribution.  It is
provided "as is" without express or implied warranty.
```

I really hope you can help me solve this as otherwise the output is excellent, comparable to something like ABBYY FineReader.

I also attempted -l epo+ara, but this did not work due to a bug in Tessearct. When using plain `-l epo` and the regular Tesseract plaintext output, the bug does not occur.

**Comment by ctrlcctrlv** [comment]
( By the way, file available from https://www.alislam.org/quran/Holy-Quran-Esperanto.pdf )

**Comment by jbarlow83** [comment]
Try `--pdf-renderer tess4`.  It has better support for international characters.

**Comment by ctrlcctrlv** [comment]
Thank you, that solved my problem. :-)
