### ISSUE TITLE
Ghostscript errors returned on stderr are not displayed (at least with Ghostscript 9.19)

### ISSUE THREAD

**Issue by mircea** [jbarlow83/OCRmyPDF#159]
The snippet below in exec/ghostscript.py does not process stderr for the ghostscript process.
~~~~~
        stdout, _ = p.communicate()
        if 'error' in stdout:
            log.error(stdout)  # Ghostscript puts errors in stdout
        else:
            log.debug(stdout)
~~~~~

Sample output debugging #158:
~~~~~
$ gs -dQUIET -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -dFirstPage=1 -dLastPage=1 -o /tmp/pdfs -r300x300 /tmp/000001.ocr.oriented.pdf 
GPL Ghostscript 9.19: Can't find initialization file gs_init.ps.

$ gs -dQUIET -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -dFirstPage=1 -dLastPage=1 -o /tmp/pdfs -r300x300 /tmp/000001.ocr.oriented.pdf 2>/dev/null
~~~~~
and without -dQUIET (same output)
~~~~~
$ gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -dFirstPage=1 -dLastPage=1 -o /tmp/pdfs -r300x300 /tmp/000001.ocr.oriented.pdf
GPL Ghostscript 9.19: Can't find initialization file gs_init.ps.
~~~~~

**Comment by mircea** [comment]
BTW, fixed the Ghostscript issue which wasn't showing before (GPL Ghostscript 9.19: Can't find initialization file gs_init.ps.) by relinking Ghoscript with Homebrew, as described here: https://rcmdnk.com/blog/2017/02/09/computer-mac-homebrew/
~~~
brew link --overwrite ghostscript
~~~

Apparently, MacTex/Ghostscript conflicts with Homebrew/Ghostscript, an issue also described here:
https://github.com/Homebrew/homebrew-core/issues/11368

Now ocrmypdf works great :)

**Comment by jbarlow83** [comment]
The `Popen` that creates the process redirects stderr to stdout, so the comment is inaccurate, but in any case only stdout needs to be checked.

**Comment by mircea** [comment]
Indeed, I missed the Popen parameter doing that.

My challenge there was that the "GPL Ghostscript 9.19: Can't find initialization file gs_init.ps." message wasn't actually treated as an error (didn't pass the "'error' in stdout" test) and didn't show up, even though it was written on stderr.

According to the latest change, it will still not show up since it doesn't contain the 'error' word (capitalized or not).

There are also other Ghostscript errors that don't match "error" - searching for "emprintf1" in [ghostscript/psi/main.c](http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=psi/imain.c) will reveal some (or see all emprintf1 occurences [here](http://git.ghostscript.com/?p=ghostpdl.git&a=search&h=HEAD&st=grep&s=emprintf1)).

A workaround would be to instruct the user to also display debug messages, since they would include the Ghostscript errors not caught with the filter - log.error('Ghostscript rasterizing failed. Use --verbose to get more details.').
