### ISSUE TITLE
Setting TESSDATA_PREFIX results in failure

### ISSUE THREAD

**Issue by Jmuccigr** [jbarlow83/OCRmyPDF#161]
I recently set my TESSDATA_PREFIX via .bash_profile and now ocrmypdf fails when I run it. If I don't set the variable, it works fine (but then it doesn't see my other languages). Here's the error:

```
ERROR -    1: [tesseract] read_params_file: Can't open hocr  
WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
  ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/pipeline.py", line 498, in ocr_tesseract_hocr
    log=log
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/exec/tesseract.py", line 268, in generate_hocr
    with open(badxml, mode='r', encoding='utf-8') as f_in, \
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/yl/xd3tsv2x1959s23ts4k1qt9m0000gr/T/com.github.ocrmypdf._43vvg9x/000001.badxml'
```

**Comment by jbarlow83** [comment]
That is Tesseract saying it [can't open some file](https://github.com/tesseract-ocr/tesseract/blob/1cc511188d980a33742d2699f9927ed1c84e81de/ccutil/params.cpp#L55), so it looks like TESSDATA_PREFIX isn't valid.

Somewhat confusingly, `TESSDATA_PREFIX` is not the location of the tessdata/ folder but the parent directory of tessdata/, e.g. you should a file named `$TESSDATA_PREFIX/tessdata/eng.traineddata`.

Is `TESSDATA_PREFIX` an absolute path? Does `env TESSDATA_PREFIX=location tesseract testimage.tif output hocr` work?

**Comment by Jmuccigr** [comment]
I didn't know that about the prefix, but interestingly tesseract doesn't seem to care. It found the languages in both cases.

ocrmypdf still fails in the same way.

tesseract with the hocr output still generates the output text file, but first reports a number of errors, mostly related to the image file, but with one about hocr:

```
read_params_file: Can't open hocr
Error: failed to load /Users/john_muccigrosso/Documents/github/local/tessdata/ita.special-words
Tesseract Open Source OCR Engine v3.05.00 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
Error in pixConvertRGBToGray: pixs not 32 bpp
Error in pixGetWidth: pix not defined
Error in pixGetHeight: pix not defined
Error in pixGetDepth: pix not defined
Error in pixCreateHeader: width must be > 0
Error in pixCreateNoInit: pixd not made
Error in pixCreate: pixd not made
Error in pixSetAllArbitrary: pix not defined
Error in pixConvertRGBToGray: pixs not 32 bpp
Detected 69 diacritics
```

**Comment by jbarlow83** [comment]
Something is wrong with your tesseract installation or the tessdata folder.

It's missing tessdata/configs/hocr and probably some other things. Tessdata
needs config files not just language data.

**Comment by Jmuccigr** [comment]
Hold on, I got it. I'm using my github clone of tessdata which only has languages in it. I guess I need to symlink them into the actual tessdata, unless there's a way to use both simultaneously.
