### ISSUE TITLE
Feature request - support the Tesseract user-words qualifier

### ISSUE THREAD

**Issue by scaddenp** [jbarlow83/OCRmyPDF#165]
Expect a lot of extra-language names, jargon, in the files to OCR and I can easily compile a list of what I expect. Tesseract performs better with this list and seems it should be easy to add.

**Comment by jbarlow83** [comment]
Agreed, not too hard to implement. I will see about adding it.

**Comment by jbarlow83** [comment]
added for next release

**Comment by scaddenp** [comment]
Thanks very much. Does this mean a new release imminent?

**Comment by jbarlow83** [comment]
Yes
