### ISSUE TITLE
The --image-dpi or --oversample-dpi does not have influence on image size

### ISSUE THREAD

**Issue by debaerd** [jbarlow83/OCRmyPDF#168]
ocrmypdf --verbose 8 --oversample 72 --image-dpi 72 moznc24.pdf moznc24-72.pdf  2> oc.log
[Uploading moznc24.pdf…]
[moznc24-72.pdf]
log:
  DEBUG - ocrmypdf 4.5.6.post7+gd077c03.d20170509
  DEBUG - tesseract 3.05.00
  DEBUG - os.symlink(moznc24.pdf, /tmp/com.github.ocrmypdf.cew7lxqf/origin)
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/origin, /tmp/com.github.ocrmypdf.cew7lxqf/origin.pdf)
  DEBUG - [{'xres': Decimal('214.648'), 'rotate': 0, 'has_text': False, 'pageno': 0, 'width_pixels': 1775, 'images': [{'dpi_h': Decimal('214.648'), 'dpi': Decimal('214.648'), 'height': 2336, 'color': 'rgb', 'name': '/x5', 'comp': 3, 'bpc': 8, 'type': 'image', 'width': 1653, 'enc': 'image', 'dpi_w': Decimal('214.648')}], 'width_inches': Decimal('8.267716541666666666666666667'), 'yres': Decimal('214.648'), 'height_pixels': 2510, 'height_inches': Decimal('11.69291338888888888888888889')}]
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/000001.page.pdf, /tmp/com.github.ocrmypdf.cew7lxqf/000001.ocr.page.pdf)
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/000001.ocr.page.pdf, /tmp/com.github.ocrmypdf.cew7lxqf/000001.ocr.oriented.pdf)
  DEBUG - Rasterize 000001.ocr.oriented.pdf with png16m
  DEBUG - 
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/000001.page.png, /tmp/com.github.ocrmypdf.cew7lxqf/000001.pp-background.png)
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/000001.pp-background.png, /tmp/com.github.ocrmypdf.cew7lxqf/000001.pp-deskew.png)
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/000001.pp-deskew.png, /tmp/com.github.ocrmypdf.cew7lxqf/000001.pp-clean.png)
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf(https://github.com/jbarlow83/OCRmyPDF/files/995662/moznc24-72.pdf)
/000001.pp-clean.png, /tmp/com.github.ocrmypdf.cew7lxqf/000001.ocr.png)
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/000001.page.png, /tmp/com.github.ocrmypdf.cew7lxqf/000001.image)
  DEBUG - ['tesseract', '-l', 'eng', '/tmp/com.github.ocrmypdf.cew7lxqf/000001.ocr.png', '/tmp/com.github.ocrmypdf.cew7lxqf/000001.badxml', 'hocr']
  DEBUG -    1: page eligible for lossless reconstruction
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.cew7lxqf/000001.ocr.oriented.pdf, /tmp/com.github.ocrmypdf.cew7lxqf/000001.image-layer.pdf)
  DEBUG - Final pages: /tmp/com.github.ocrmypdf.cew7lxqf/000001.rendered.pdf
/tmp/com.github.ocrmypdf.cew7lxqf/pdfa.ps
  DEBUG - Ghostscript had to remove PDF 'overprinting' from the input file to complete PDF/A conversion. 
   INFO - Output file is a PDF/A-2B (as expected)
  DEBUG - [{'has_text': False,
  'height_inches': Decimal('11.69291338888888888888888889'),
  'height_pixels': 2510,
  'images': [{'bpc': 8,
              'color': 'rgb',
              'comp': 3,
              'dpi': Decimal('214.648'),
              'dpi_h': Decimal('214.648'),
              'dpi_w': Decimal('214.648'),
              'enc': 'image',
              'height': 2336,
              'name': '/x5',
              'type': 'image',
              'width': 1653}],
  'pageno': 0,
  'rotate': 0,
  'width_inches': Decimal('8.267716541666666666666666667'),
  'width_pixels': 1775,
  'xres': Decimal('214.648'),
  'yres': Decimal('214.648')}]

________________________________________
Tasks which will be run:

Task enters queue = 'ocrmypdf.pipeline.triage' 
    Job  = [.../origin -> .../origin.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../origin.pdf] 
    Job  = [.../origin -> .../origin.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.triage' 
Task enters queue = 'ocrmypdf.pipeline.repair_pdf' 
    Job  = [.../origin.pdf -> .../origin.repaired.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../origin.repaired.pdf] 
    Job  = [.../origin.pdf -> .../origin.repaired.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.repair_pdf' 
Task enters queue = 'ocrmypdf.pipeline.split_pages' 
    Job  = [[.../origin.repaired.pdf] -> .../*.page.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] Missing output file 
Task enters queue = 'ocrmypdf.pipeline.generate_postscript_stub' 
    Job  = [.../origin.repaired.pdf -> .../pdfa.ps, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../pdfa.ps] 
    Job  = [[.../origin.repaired.pdf] -> .../*.page.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.split_pages' 
Inactive Task = 'ocrmypdf.pipeline.rasterize_preview'
Task enters queue = 'ocrmypdf.pipeline.orient_page' 
    Job  = [[.../000001.ocr.page.pdf] -> .../000001.ocr.oriented.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.ocr.oriented.pdf] 
    Job  = [.../origin.repaired.pdf -> .../pdfa.ps, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.generate_postscript_stub' 
    Job  = [[.../000001.ocr.page.pdf] -> .../000001.ocr.oriented.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.orient_page' 
Task enters queue = 'ocrmypdf.pipeline.rasterize_with_ghostscript' 
    Job  = [.../000001.ocr.oriented.pdf -> .../000001.page.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.page.png] 
Task enters queue = 'ocrmypdf.pipeline.skip_page' 
Uptodate Task = 'ocrmypdf.pipeline.skip_page'

WARNING:
        In Task 'ocrmypdf.pipeline.skip_page':
        No jobs were run because no file names matched.
        Please make sure that the regular expression is correctly specified.
        Job Warning: Input substitution failed:
          File '/tmp/com.github.ocrmypdf.cew7lxqf/000001.ocr.oriented.pdf' does not match suffix('.skip.oriented.pdf') and pattern '.done.pdf' 

    Job  = [.../000001.ocr.oriented.pdf -> .../000001.page.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.rasterize_with_ghostscript' 
Task enters queue = 'ocrmypdf.pipeline.preprocess_remove_background' 
    Job  = [.../000001.page.png -> .../000001.pp-background.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.pp-background.png] 
    Job  = [.../000001.page.png -> .../000001.pp-background.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.preprocess_remove_background' 
Task enters queue = 'ocrmypdf.pipeline.preprocess_deskew' 
    Job  = [.../000001.pp-background.png -> .../000001.pp-deskew.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.pp-deskew.png] 
    Job  = [.../000001.pp-background.png -> .../000001.pp-deskew.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.preprocess_deskew' 
Task enters queue = 'ocrmypdf.pipeline.preprocess_clean' 
    Job  = [.../000001.pp-deskew.png -> .../000001.pp-clean.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.pp-clean.png] 
    Job  = [.../000001.pp-deskew.png -> .../000001.pp-clean.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.preprocess_clean' 
Task enters queue = 'ocrmypdf.pipeline.select_ocr_image' 
    Select the image we send for OCR. May not be the same as the display image depending on preprocessing.
    Job  = [[.../000001.pp-clean.png] -> .../000001.ocr.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.ocr.png] 
Task enters queue = 'ocrmypdf.pipeline.select_visible_page_image' 
    Selects a whole page image that we can show the user (if necessary)
    Job  = [[.../000001.page.png, .../000001.pp-background.png, .../000001.pp-clean.png, .../000001.pp-deskew.png] -> .../000001.image, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.image] 
    Job  = [[.../000001.pp-clean.png] -> .../000001.ocr.png, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.select_ocr_image' 
Task enters queue = 'ocrmypdf.pipeline.ocr_tesseract_hocr' 
    Job  = [.../000001.ocr.png -> .../000001.hocr, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.hocr] 
Inactive Task = 'ocrmypdf.pipeline.ocr_tesseract_textonly_pdf'
    Job  = [[.../000001.page.png, .../000001.pp-background.png, .../000001.pp-clean.png, .../000001.pp-deskew.png] -> .../000001.image, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.select_visible_page_image' 
Task enters queue = 'ocrmypdf.pipeline.select_image_layer' 
    Selects the image layer for the output page. If possible this is the orientation-corrected input page, or an image of the whole page converted to PDF.
    Job  = [[.../000001.image, .../000001.ocr.oriented.pdf] -> .../000001.image-layer.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.image-layer.pdf] 
Inactive Task = 'ocrmypdf.pipeline.ocr_tesseract_and_render_pdf'
    Job  = [[.../000001.image, .../000001.ocr.oriented.pdf] -> .../000001.image-layer.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.select_image_layer' 
    Job  = [.../000001.ocr.png -> .../000001.hocr, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.ocr_tesseract_hocr' 
Task enters queue = 'ocrmypdf.pipeline.render_hocr_page' 
    Job  = [.../000001.hocr -> .../000001.text.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.text.pdf] 
Inactive Task = 'ocrmypdf.pipeline.render_hocr_debug_page'
    Job  = [.../000001.hocr -> .../000001.text.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.render_hocr_page' 
Task enters queue = 'ocrmypdf.pipeline.combine_layers' 
    Job  = [[.../000001.image-layer.pdf, .../000001.text.pdf] -> .../000001.rendered.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../000001.rendered.pdf] 
    Job  = [[.../000001.image-layer.pdf, .../000001.text.pdf] -> .../000001.rendered.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.combine_layers' 
Task enters queue = 'ocrmypdf.pipeline.merge_pages_ghostscript' 
    Job  = [[.../000001.rendered.pdf, .../pdfa.ps] -> .../merged.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] ...
        Missing file [.../merged.pdf] 
Inactive Task = 'ocrmypdf.pipeline.merge_pages_qpdf'
    Job  = [[.../000001.rendered.pdf, .../pdfa.ps] -> .../merged.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.merge_pages_ghostscript' 
Task enters queue = 'ocrmypdf.pipeline.copy_final' 
    Job  = [[.../merged.pdf] -> moznc24-72.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] Uncheckpointed file (left over from a failed run?):
        [moznc24-72.pdf] 
    Job  = [[.../merged.pdf] -> moznc24-72.pdf, <LoggingProxy>, <ocrmypdf.pipeline.JobContext>] completed
Completed Task = 'ocrmypdf.pipeline.copy_final'

**Comment by jbarlow83** [comment]
HEAD isn't passing the test suite right now. Please try with the tagged
version 4.5.6.

**Comment by jbarlow83** [comment]
Oh, never mind, I see what's going on. 

``--image-dpi`` sets the resolution for input *images* only. It does not override the resolution implied in a PDF.

``--oversample`` increases the resolution, but will not decrease it. The PDF already has 216 DPI, so ``--oversample 72`` will be ignored. Taken together, the two parameters have no effect.

There is no argument to downsample a PDF to lower resolution. You could use ghostscript to do that, preferably after running ocrmypdf (so that the loss in resolution will not affect OCR quality). See https://gist.github.com/firstdoit/6390547 for an example.

Note that 72 dots/inch or 28 dots/cm is extremely low; OCR does not usually work at all at that scale, and 10pt font would be barely readable by a person.

**Comment by jbarlow83** [comment]
Next release will warn when `--image-dpi` is going to be ignored
