### ISSUE TITLE
unpaper_6.1-1.deb

### ISSUE THREAD

**Issue by Shreeshrii** [jbarlow83/OCRmyPDF#171]
wget -q https://dl.dropboxusercontent.com/u/28971240/unpaper_6.1-1.deb -O unpaper_6.1-1.deb

I am trying to install ocrmypdf, however getting a 404 from dropbox on above file.

**Comment by jbarlow83** [comment]
I will look into that. On most Linux newer than Ubuntu trusty (14.04) you
should be able to install unpaper directly with the package manager. This
file is just to help my Travis tests go faster.

**Comment by Shreeshrii** [comment]
Thanks.

It is ubuntu trusty (WSL). I tried building unpaper 6.1.1 but getting errors because of libav, So, it will be useful if the deb package works.

**Comment by jbarlow83** [comment]
New link is https://www.dropbox.com/s/vaq0kbwi6e6au80/unpaper_6.1-1.deb?dl=0

**Comment by jbarlow83** [comment]
Actually use this: 
https://www.dropbox.com/s/vaq0kbwi6e6au80/unpaper_6.1-1.deb?raw=1 
to avoid the Dropbox signin page.

**Comment by Shreeshrii** [comment]
Thank you. Appreciate your prompt response.
