### ISSUE TITLE
Error: Document base stream is not seekable

### ISSUE THREAD

**Issue by laoyang360** [jbarlow83/OCRmyPDF#174]
When i use "ocrmypdf input.pdf - | tee output.pdf | pdftotext - output.txt"
The following bug appeared:
"Error: Document base stream is not seekable"

How to fix it ?

**Comment by jbarlow83** [comment]
What version of ocrmypdf?

To produce a text file containing the PDF contents it is better to use the
--sidecar argument.

But that should work anyway on ocrmypdf > 5.0. Send me the input file if
possible.

**Comment by laoyang360** [comment]
[root@f]# ocrmypdf --version
5.2.post0+g3a7c341.d20170710

[root@e1 f]# ocrmypdf 01.pdf - | tee 01.pdf | pdftotext - 01.txt
Error: Document base stream is not seekable
   INFO - Input file is not a PDF, checking if it is an image...
  ERROR - cannot identify image file '/df/01.pdf'

**Comment by jbarlow83** [comment]
Is the PDF larger than 2GB?

**Comment by laoyang360** [comment]
No, the max PDF is about 1GB.  Now I use the single command "pdftotext" solve this problem.

**Comment by jbarlow83** [comment]
As far as I can tell this is an issue in pdftotext, which also produces the error message. If the document is larger than a certain size it will attempt to seek and fail, so your approach is the correct workaround. Alternately use the `--sidecar` argument to get higher accuracy text output.

I've removed the recommendation to use pdftotext from my docs in favor of `--sidecar`
