### ISSUE TITLE
Batch Process - Wildcard *.PDF doesn´t work

### ISSUE THREAD

**Issue by mli1102** [jbarlow83/OCRmyPDF#182]
Hi,
i like to use the parallel command with the wildcard *.pdf liked showed in the Documentation. But it doesn´t work. There are files in the in folder, but it is looking for *.pdf, if it use a specific file name it is working. Can you help? 

Thanks Regards Martin

parallel --tag -j 2 ocrmypdf -l deu '/Volumes/scans/in/{}' '/Volumes/scans/out/{}' ::: *.pdf 
Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

*.pdf	  ERROR - File not found - /Volumes/scans/in/*.pdf

If possible, please use a test file that we can include in future test cases (no personal information, no copyrighted material).

**Comment by jbarlow83** [comment]
The [creator of GNU parallel demands](https://lists.gnu.org/archive/html/parallel/2013-11/msg00006.html) that you run `parallel --citation` prior to using that utility, promising that you cite his work in any of your publications or pay him for failing to do so. Running this command once will silence the message. Then you can repeat the command you attempted.
