### ISSUE TITLE
"E: Unable to locate package ocrmypdf" on ubuntu 16.04

### ISSUE THREAD

**Issue by yuriw** [jbarlow83/OCRmyPDF#183]
Running command on ubuntu 16.04

> sudo apt-get install ocrmypdf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ocrmypdf

pls fix

**Comment by jbarlow83** [comment]
Hello. ocrmypdf was not added to Ubuntu until 16.10.

You can follow the installation instructions for 16.04 in the
documentation, or use the Docker image.

**Comment by yuriw** [comment]
@jbarlow83 got it running , thank you!

**Comment by barrars** [comment]
@yuriw Did you get it running on 16.04?  How?

**Comment by jbarlow83** [comment]
See the installation instructions at ocrmypdf.readthedocs.io

**Comment by barrars** [comment]
Thank you, I installed with pip and have it running.  This tool is impressive.  Much kudos!

**Comment by yuriw** [comment]
@jbarlow83 Yes I did.
