### ISSUE TITLE
Test resources README updates needed: baiona_gray.png; poster.pdf; crom.png

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#186]
Hello,

The files baiona_gray.png, poster.pdf and crom.png aren't detailed in the test resources README.

The providence of baiona_gray.png and poster.pdf is obvious.  I don't think that crom.png is copyrightable, but to play it safe, could you confirm you made it yourself?

Thanks.

**Comment by jbarlow83** [comment]
Yes. 

Confirmed all in d04e43d.

**Comment by spwhitton** [comment]
Thanks!

-- 
Sean Whitton
