### ISSUE TITLE
test_textonly_pdf_on_older_tess3 test failure

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#188]
This is in a clean Debian unstable chroot:

    ============================= test session starts ==============================
    platform linux -- Python 3.5.4, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
    rootdir: /<<PKGBUILDDIR>>, inifile: setup.cfg
    plugins: xdist-1.18.2, helpers-namespace-2016.7.10, cov-2.5.1
    gw0 I / gw1 I / gw2 I / gw3 I
    gw0 [125] / gw1 [125] / gw2 [125] / gw3 [125]
    
    scheduling tests via LoadScheduling
    ..............................................................................................................sssss.F....s...
    =================================== FAILURES ===================================
    _______________________ test_textonly_pdf_on_older_tess3 _______________________
    [gw2] linux -- Python 3.5.4 /usr/bin/python3
    
    resources = PosixPath('/<<PKGBUILDDIR>>/tests/resources')
    no_outpdf = '/tmp/pytest-of-spwhitton/pytest-0/popen-gw2/test_textonly_pdf_on_older_tes0/no_output.pdf'
    
        @pytest.mark.skipif(tesseract.has_textonly_pdf(),
                            reason="check that missing dep is reported on old tess3")
        def test_textonly_pdf_on_older_tess3(resources, no_outpdf):
            p, _, _ = pytest.helpers.run_ocrmypdf(
                resources / 'linn.pdf',
                no_outpdf, '--pdf-renderer', 'sandwich')
        
    >       assert p.returncode == ExitCode.missing_dependency
    E       assert 0 == <ExitCode.missing_dependency: 3>
    E        +  where 0 = <subprocess.Popen object at 0x7f8199592c18>.returncode
    E        +  and   <ExitCode.missing_dependency: 3> = ExitCode.missing_dependency
    
    tests/test_tess3.py:21: AssertionError
    ============== 1 failed, 118 passed, 6 skipped in 303.30 seconds ===============

**Comment by spwhitton** [comment]
Looking further, we have tesseract 3.04 on Debian, and the `sandwich` renderer is the default for 3.05 or newer, so this test should probably be passing.

**Comment by jbarlow83** [comment]
Likely fixed in bafd083, but I wasn't able to replicate the problem in my Docker image of Debian sid since something in the vicinity of setuptools and cffi seemed to be broken in sid at the moment.

If this passes I will tag the release.

**Comment by spwhitton** [comment]
I can confirm that this fixes the failure.  Thanks!  (Whatever breakage you encountered doesn't affect my up-to-date sid chroot, just fyi.)
