### ISSUE TITLE
Dockerfile.tess4 won't work due to 16.10 no longer being supported by ppa:alex-p/tesseract-ocr

### ISSUE THREAD

**Issue by hernick-qc** [jbarlow83/OCRmyPDF#191]
The current version of `Dockerfile.tess4` is based on Ubuntu 16.10, but the `ppa:alex-p/tesseract-ocr` no longer offers tesseract-4 builds for 16.10. However, 17.04 is now supported by the PPA, and simply changing the Dockerfile `FROM    ubuntu:16.10` to `ubuntu:17.04` works great for me.

I'm using OCRmyPDF-tess4 to automatically OCR all documents scanned on our OSA Sharp MFP with PaperCut MF and it works great, the users love it, and the quality of the results are better than with tess3. Only downside, it takes nearly half an hour to OCR a 100 page document on a Xeon E3-1240 V2.

**Comment by jbarlow83** [comment]
I’ll make the change.

There’s not much I can do about the time to OCR. However you may want to
ensure that the Docker container runs with access to all CPUs since some
configurations only let it see one.

**Comment by jbarlow83** [comment]
My fix to this issue is blocked by https://github.com/tesseract-ocr/tesseract/issues/1167

**Comment by jbarlow83** [comment]
The issue above also describes the workaround, which is to replace the installed Tesseract 4's `tessdata/eng.traineddata` with the version from `tesseract-ocr/tessdata/eng.traineddata`, and for any other language of interest.

**Comment by jbarlow83** [comment]
Workaround added to v5.4.1
