### ISSUE TITLE
[Suggestion] A command thar produces only .txt without .pdf

### ISSUE THREAD

**Issue by Gugols** [jbarlow83/OCRmyPDF#195]
It would be nice to have a feature that when a specific argument is passed, the program would only output a .txt having just OCR text - without generating PDF itself. --sidecar argument still requires output pdf file to be specified.

In my case, I'm asked to OCR a PDF and put the text in Solr's index. Currently I just generate the .txt and need to delete the generated PDF which is redundant in my case.

**Comment by jbarlow83** [comment]
You can accomplish that by sending the output PDF to `/dev/null`. Use `-` in place of the output filename.

```
ocrmypdf --sidecar textfile.txt input.pdf - >/dev/null
```

The performance gain from not generating the PDF at all would be almost zero, so this should be fine.

I think this is sufficient so I'll close the issue. Feel free to reopen if this isn't satisfactory.
