### ISSUE TITLE
problem when libtiff changed, with suggestion for solution

### ISSUE THREAD

**Issue by autofax** [jbarlow83/OCRmyPDF#196]
In one of my installations, the call of orcmypdf gives the following error message:

> Traceback (most recent call last):
>   File "/usr/local/bin/ocrmypdf", line 7, in <module>
>     from ocrmypdf.__main__ import run_pipeline
>   File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/__main__.py", line 52, in <module>
>     if tesseract.version() < MINIMUM_TESS_VERSION:
>   File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/exec/tesseract.py", line 56, in version
>     tesseract_version = re.match(r'tesseract\s(.+)', versions).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

As the first link of a chain of reasons I found that in this system, the version of libtiff changed after the installation of leptonica. Therefore, 
`tesseract --version`
results in the following output:

> tesseract: /usr/local/lib/libtiff.so.5: no version information available (required by /usr/lib/liblept.so.5)
> tesseract 3.04.01
>  leptonica-1.73
>   libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.8 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

The first line is an informational message which does not affect the functionality, but it precludes the attempt to extract the version number of tesseract within the current version of the function **version()** in the file **tesseract.py**, which is implemented as follows:

>
> def version():
>     args_tess = [
>         get_program('tesseract'),
>         '--version'
>     ]
>     try:
>         versions = check_output(
>                 args_tess, close_fds=True, universal_newlines=True,
>                 stderr=STDOUT)
>     except CalledProcessError as e:
>         print("Could not find Tesseract executable on system PATH.",
>               file=sys.stderr)
>         raise MissingDependencyError from e
> 
>     tesseract_version = re.match(r'tesseract\s(.+)', versions).group(1)
>     return tesseract_version
> 

For this code I have two suggestions:
1) If "re.search" was used instead of "re.match", the result would be more rubust and cover my case.
2) If the regex-result would be first tested for not being "None" before trying to extract the group, Error messages would be less cryptic.
So, my proposal for this function is:

> def version():
>     args_tess = [
>         get_program('tesseract'),
>         '--version'
>     ]
>     try:
>         versions = check_output(
>                 args_tess, close_fds=True, universal_newlines=True,
>                 stderr=STDOUT)
>     except CalledProcessError:
>         print("Could not find Tesseract executable on system PATH.")
>         sys.exit(ExitCode.missing_dependency)
> 
>     vers=re.search(r'tesseract\s(.+)',versions);
>     if vers:
>         tesseract_version = vers.group(1)
>     else:
>         tesseract_version = 0
>     return tesseract_version
>

**Comment by jbarlow83** [comment]
I get that it's frustrating when a program sort of inadvertently suppress an error message like this – but your platform's linker thinks *something is wrong* with how libtiff and leptonica are built. I wouldn't trust that installation. I think aborting in that case is *useful* behavior.

I'd consider trapping the `None` and producing a different exception, complaining that `tesseract --version` failed to report its version as expected.

**Comment by jbarlow83** [comment]
Refactored version checking for next release, with a better error message when the output is unexpected.
