### ISSUE TITLE
PDF/A-3 Option

### ISSUE THREAD

**Issue by segro21** [jbarlow83/OCRmyPDF#197]
Hi,
not an issue, but a question:
is there any option to produce PDF/A-3 (version 3 of pdf/a) output documents?

https://www.pdf-tools.com/pdf20/de/know-how/pdf-iso-standards/pdfa-3-uebersicht/ 
«Document management – Electronic document file format for long-term preservation – Part 3: Use of ISO 32000-1 with support for embedded files ( PDF/A-3)»

**Comment by segro21** [comment]
Hi,
thanks for the quick answer and your hint to pikepdf! I'll try that.
regards,
Sebastian

**Comment by jbarlow83** [comment]
Ghostscript now supports PDF/A-3

**Comment by segro21** [comment]
Thank you very much for the information!

 
Von: jbarlow83 [mailto:notifications@github.com] 
Gesendet: Freitag, 20. April 2018 08:49
An: jbarlow83/OCRmyPDF <OCRmyPDF@noreply.github.com>
Cc: Sebastian <grosche@itsd.de>; Author <author@noreply.github.com>
Betreff: Re: [jbarlow83/OCRmyPDF] PDF/A-3 Option (#197)

 
Ghostscript now supports PDF/A-3

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jbarlow83/OCRmyPDF","title":"jbarlow83/OCRmyPDF","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jbarlow83/OCRmyPDF"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jbarlow83 in #197: Ghostscript now supports PDF/A-3"}],"action":{"name":"View Issue","url":"https://github.com/jbarlow83/OCRmyPDF/issues/197#issuecomment-382997957"}}}


----------------------------
Unser System ist mit einem Mailverschluesselungs-Gateway ausgestattet. Wenn Sie moechten, dass an Sie gerichtete E-Mails verschluesselt werden, senden Sie einfach eine S/MIME-signierte E-Mail oder Ihren PGP Public Key an sebastian.grosche@itsd.de.

Our system is equipped with an email encryption gateway. If you want email sent to you to be encrypted please send a S/MIME signed email or your PGP public key to sebastian.grosche@itsd.de.

**Comment by jbarlow83** [comment]
ocrmypdf 6.2.0 will support generating PDF/A-3, although without the ability to attach files.

@segro21 Your most recent message included some JSON that exposed your Github API key for some reason (!). You might want to change it. I removed edit the message to remove it.
