### ISSUE TITLE
Do you have the text layer to the PDF document on the API painting

### ISSUE THREAD

**Issue by MyCitron** [jbarlow83/OCRmyPDF#198]
Do you have the text layer to the PDF document on the API painting, I want to develop a XML file (XML file contains a text, and the text of the coordinate information) is converted to PDF documents, but when I a word painting after the generated PDF document, copied to the text will wrap, but they have been in a row. I'd like to refer to your text to PDF's API. Before I was using the reportlab.pdf Library in Python.thanks

**Comment by jbarlow83** [comment]
You can output to use tesseract to output to hocr or modify ocrmypdf to
output hocr files. You just need to change the format of the sidecar files
from text to hocr (by changing source). There is an open issue requesting
this feature.

Hocr is a HTML/XML-compatible file format that contains text positioning
information and other ocr markup.

**Comment by jbarlow83** [comment]
See issue #177
