### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by obstschale** [jbarlow83/OCRmyPDF#199]
I was looking for an open source OCR tool and just found OCRmyPDF. I installed it quickly with brew and violá it works like a charm! So much better than other (commercial) tools out there. Thank you so much! 💪

**Comment by femifrak** [comment]
I like ocrmypdf very very much! Many thanks for all the work you do and for making the software freely available.

However, I find it unfair that I pay money for commercial software and that developers of software, which I use much more often and provide much better services, get nothing.

Is there a way to donate? I would very much appreciate that!

In any case many thanks!

**Comment by sojusnik** [comment]
Yes, this software is marvelous, as is the developer! It would certainly help if a donation info was placed in the readme.md.

**Comment by SpencerRP** [comment]
You may want to close this.
