### ISSUE TITLE
fail if started from script 

### ISSUE THREAD

**Issue by donroesjen** [jbarlow83/OCRmyPDF#203]
Hi All,

first of all: Great Work. Thank you very much !!

I am running ocrmypdf on a Mac with OS 10.11.6. Running ocrmypdf from a terminal command line works brilliant. 

If I run it from a script (JavaScript) I get the following error message:

/usr/local//bin/ocrmypdf 170206174607.pdf 170206174607.pdf
/usr/local//bin/ocrmypdf: line 3: __requires__: command not found
/usr/local//bin/ocrmypdf: line 4: import: command not found
/usr/local//bin/ocrmypdf: line 5: import: command not found
from: can't read /var/mail/pkg_resources
/usr/local//bin/ocrmypdf: line 9: syntax error near unexpected token `('
/usr/local//bin/ocrmypdf: line 9: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'

Installed it via Homebrew.

Any Idea ?

Thank you very much

**Comment by jbarlow83** [comment]
That really looks as if the ocrmypdf script is missing it's #! shebang so
it is being run in bash. Have a look at that file and check if its first
line is the name of a Py3.6.interpreter that exists on the system.

**Comment by donroesjen** [comment]
Hi,
thank you for the fast response.
This is the script; it points to the correct 3.6 interpreter.

#!/usr/local/Cellar/ocrmypdf/5.4.3/libexec/bin/python3.6
# EASY-INSTALL-ENTRY-SCRIPT: 'ocrmypdf==5.4.3','console_scripts','ocrmypdf'
__requires__ = 'ocrmypdf==5.4.3'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ocrmypdf==5.4.3', 'console_scripts', 'ocrmypdf')()
    )

Thanks for the help.

**Comment by donroesjen** [comment]
the highlighted line "EASY ... " is not highlighted by me.  I think the first line is the interesting one ...

**Comment by jbarlow83** [comment]
You need to surround plain text with triple back quotes to avoid having Github interpret as markdown (I edited the comment).

Your Javascript is doing the equivalent of
`bash /usr/local/bin/ocrmypdf`...

which executes ocrmypdf as if it were a bash script

Instead you need it to do
`/usr/local/bin/ocrmypdf`

If NodeJS is running the command then you want `child_process.spawn(ocrmypdf, [...args...], {shell: 'false'})`

**Comment by jbarlow83** [comment]
I'll close the issue now because I think this has to do with the environment not anything about ocrmypdf. If you have further related questions feel free to reopen it.
