### ISSUE TITLE
add bbox info for spaces

### ISSUE THREAD

**Issue by xdsv** [jbarlow83/OCRmyPDF#205]
Spaces do not get a font and bbox entry. 
E.g.: 

Non spacing character: 
`<text font="MHKXGY+GlyphLessFont" bbox="119.430,390.600,122.760,398.600" size="8.000">t</text>
`

Spacing character:
`<text> </text>
`

Is there a way to add font and bbox info to spaces? Is this a change that has to be done to tesseract or ocrmypdf?

**Comment by jbarlow83** [comment]
It would be up to Tesseract to find this information and report it.

I don't think there's much use since the only useful information contained
in a space is the fact that it is a word boundary. No typesetting engine
needs to know where empty space is.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
