### ISSUE TITLE
idea: vectorize bitmaps

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#206]
Just an idea which could be interesting:
Once I improved ocr results by using potrace on a low resolution text scan before ocring.
potrace vecorizes bitmaps and removes aliasing to some degree.
[http://potrace.sourceforge.net](url)

**Comment by jbarlow83** [comment]
Tesseract also vectorizes bitmaps internally. It's likely the reason this works for you is that potrace would have the side effect of reducing noise (by eliminating pixels that aren't easily accounted for) and oversampling the input image (bitmap -> vector -> higher resolution bitmap). On some images this will improve things, but on others (particularly text with damaged characters) Tesseract is likely to do worse after this. 

You'd probably see similar benefits from using ocrmypdf's ``--clean`` and ``--oversample``, which remove noise from the input image (emphasis on margins) and oversample the input, respectively.

**Comment by femifrak** [comment]
ah okay. 
The improvements I realized were not ocred by ocrmypdf but long time ago by Abbyy. And I would not generalize that potrace always would improve result quality.
