### ISSUE TITLE
  ERROR: [tesseract] read_params_file: Can't open txt

### ISSUE THREAD

**Issue by Gugols** [jbarlow83/OCRmyPDF#209]
Hi, when OCRying a PDF I always get the following error for nearly every page:

>   ERROR -   56: [tesseract] read_params_file: Can't open txt

I tried to google it, but nothing comes up (txt part especially). Maybe someone has faced with something similar. What does _txt_ stand for? Some text format?

Command called:

> nice -19 env LANG=lv_LV.utf8 ocrmypdf -l lav+rus --rotate-pages --force-ocr --pdf-renderer tesseract --output-type pdf --sidecar - /tmp/input.pdf /tmp/output556.pdf

Thanks.

**Comment by jbarlow83** [comment]
I suspect you have an old/unsupported version of Tesseract. What is `tesseract --version`?

Your installation could also be missing the file `$tessroot/share/tessdata/configs/txt` where `$tessroot` varies from platform to platfom.

**Comment by pankajkumar2433** [comment]
I am running on CentOS 8.

Version is tesseract 5.0.0-beta-20210815.
Earlier it was tesseract 4.1.1

In both the versions this issue is coming.

What to do ?

**Comment by jbarlow83** [comment]
Does `tessdata/configs/txt` exist as mentioned above?

**Comment by pankajkumar2433** [comment]
No it doesn't exist.
From where to get it ?

I have installed tesseract from the source (tar.gz).

**Comment by jbarlow83** [comment]
I recommend using a version of tesseract provided by your Linux distribution or some third party packager that has solved these issues, rather than installing one from source. A source build is a special case.

**Comment by pankajkumar2433** [comment]
I installed as below->

```
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:/Alexander_Pozdnyakov/CentOS_8/
rpm --import https://build.opensuse.org/projects/home:Alexander_Pozdnyakov/public_key
sudo dnf install tesseract
```

`tessdata/configs/txt` is present in "/usr/share/tesseract/4/tessdata/configs"

Issue is still coming.

**Comment by jbarlow83** [comment]
You may need to set the environment variable `TESSDATA_PREFIX=/usr/share/tesseract/4` and ensure that your `PATH` env var gives priority to the new tesseract.

**Comment by pankajkumar2433** [comment]
Awesome!!
It's working.
