### ISSUE TITLE
OCRmyPDF does not realise if an input file is not present

### ISSUE THREAD

**Issue by Wikinaut** [jbarlow83/OCRmyPDF#21]
it looks, as if a basic test for "input file exists" is missing, or not working.

Assume, a file x.pdf exists.

Then
```
ocrmypdf x.pdf x.ocr.pdf
```
works, however
```
ocrmypdf x-no-such-file.pdf x.ocr.pdf
```
silently fails.

**Comment by jbarlow83** [comment]
Fixed v3.1
