### ISSUE TITLE
OCRmyPDF test suite failing against recent PIL

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#210]
Errors look like this:

    PIL.Image.DecompressionBombError: Image size (306250000 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

Full logs are [here](https://ci.debian.net/packages/o/ocrmypdf/unstable/amd64/).

**Comment by jbarlow83** [comment]
v5.5 should fix it - released a few hours ago

**Comment by spwhitton** [comment]
Thanks for this.  Now uploaded.
