### ISSUE TITLE
Encryption problem - Only algorithms "R = 1" and "R = 2" are supported

### ISSUE THREAD

**Issue by Gugols** [jbarlow83/OCRmyPDF#211]
Hi,

While testing the newly build project (a PHP application which OCRs PDF in a intranet project), I faced with a grieve problem. It seems that a great portion of files are encrypted.

> For information about this PDF's security use
>     qpdf --show-encryption [...input PDF...]
> 
> (Only algorithms "R = 1" and "R = 2" are supported.)

It turns out that indeed - there is an encryption.

> R = 4
> P = -3376
> User password =
> extract for accessibility: allowed
> extract for any purpose: allowed
> print low resolution: not allowed
> print high resolution: not allowed
> modify document assembly: not allowed
> modify forms: not allowed
> modify annotations: not allowed
> modify other: not allowed
> modify anything: not allowed
> stream encryption method: AESv2
> string encryption method: AESv2
> file encryption method: AESv2
> 

There's no way to bypass this? Because at first, it seems that PDF itself is high quality and resolution is sufficient for OCR. No password is asked.

EDIT: it seems that there is a password indeed (tried to re-export). I suppose if I get the password, I could decrypt by passing --decrypt parameter to qpdf somehow?

**Comment by jbarlow83** [comment]
I don't support encrypted PDFs, other than returning a clean error.

A PDF can be encrypted in a way that allows access but prevents
modification. Sounds like the case with your file but I need an example to
confirm.

Use qpdf or another tool to remove encryption or add encryption to output.
