### ISSUE TITLE
Preserve original PDF (vector file) after OCR

### ISSUE THREAD

**Issue by Catscratch** [jbarlow83/OCRmyPDF#216]
Hello.

Is it possible to preserve to input PDF file even after OCR process? I know you have to rasterize vector PDF to images for tesseract. But then, instead putting the text layer in a new PDF with a rasterized image would it be possible to include the text layer into the input PDF to keep vectors? Rastering always results in quality loss and also increases file size significant.

PDF/A allows the usage of vector content. So it would be nice to keep it.

**Comment by jbarlow83** [comment]
When possible already ocrmypdf does preserve the original content and does not rasterize vectors. 

In PDF/A mode (default) images will be transcoded which can change the file size and quality, but usually not dramatically. In PDF output mode (`--output-pdf pdf`) images are not transcoded. (Note:  you request image preprocessing or use `-f` to force rasterizing then naturally the input is not preserved).

So you shouldn't be seeing a size or quality change. Please attach your input file, output file and command line.

**Comment by Catscratch** [comment]
Hi.

Thanks for your reply.

The source PDF has no image because is only contains vectors. This means it has to be rasterized for Tesseract. But after OCR I want to preserve the vector content.

Right now I got two options. Take the file as it is which results in "page has no images" message and therefore not OCR is done. The other option is to use -f which will rasterize my PDF and remove the vector content.

Here is an example:
[vector_pdf.pdf](https://github.com/jbarlow83/OCRmyPDF/files/1702323/vector_pdf.pdf)
[vector_out.pdf](https://github.com/jbarlow83/OCRmyPDF/files/1702326/vector_out.pdf)

I'm using the docker image like this:
`docker run -v //c/temp/ocr:/ocr jbarlow83/ocrmypdf-tess4 --output-type pdfa /ocr/vector_pdf.pdf /ocr/vector_out.pdf`

This is the output:
`   INFO - Tesseract v4.x.alpha found.
You are using qpdf version 6.0.0 which has known issues including security vulnerabilities with certain malformed PDFs. Consider upgrading to version 7.0.0 or newer.
   INFO -    1: page has no images - skipping all processing on this page
   INFO - Output file is a PDF/A-2B (as expected)`

What I want is the vector_out.pdf with OCR information (text layer?) AND vector content.

Thanks for hints!

**Comment by jbarlow83** [comment]
That's the "text as curves" case. It was not possible without rasterizing in the past, but it is possible now. I never updated the checking logic so the fix is straightforward.

There is no need to use `--output-type pdf`. PDF/A conversion will retain the vector content without rasterizing. Strictly speaking, Ghostscript might rewrite the vector content but the rewrite will be equivalent. (Reason being, Ghostscript first interprets the PDF to build an internal representation, and then it "compiles" that into a new PDF/A.)

Can I add your test file to the test suite? Did you create it or did you get it from a free source?

**Comment by Catscratch** [comment]
The files were from clker.com with modifications.

Anyway, here you got a file fully created by myself. You can use it as you want.

Target would be, that this file got OCR in the output and also vector graphics.

[vector_in.pdf](https://github.com/jbarlow83/OCRmyPDF/files/1706156/vector_in.pdf)

**Comment by jbarlow83** [comment]
Fix pushed, should be deployed in about 30 minutes.

**Comment by Catscratch** [comment]
Thanks a lot. 

I don't really understand the fix. But at least the output file looks good! It got vectors and OCR.

I tried with newest build from dockerhub tess4.

**Comment by jbarlow83** [comment]
Re Fix: The CLI argument checking logic didn't handle vector only PDFs
properly but the PDF renderer already did, so no renderer changes needed.
