### ISSUE TITLE
OpenCL support for CUDA - increase OCR speed

### ISSUE THREAD

**Issue by Catscratch** [jbarlow83/OCRmyPDF#221]
Hey,

I want to speed up the OCR process by using GPU instead of CPU. 

There is a documentation for tesseract on how to use CUDA. 
https://github.com/tesseract-ocr/tesseract/wiki/TesseractOpenCL

Now my guess was to modify the Dockerfile.tess4 (attached) to extend an Nvidia cuda docker container.
[Dockerfile.tess4cuda.txt](https://github.com/jbarlow83/OCRmyPDF/files/1748244/Dockerfile.tess4cuda.txt)

I hoped tesseract 4 would recognize opencl drivers by its own. But first tests show that performance seems to be the same with and without cuda container. 

Now my question is, how my I force tesseract to use opencl? Or can you create a docker container with a working tesseract 4 opencl?

Thanks!

**Comment by stweil** [comment]
Don't try it unless you are willing to spend a lot of time with improving the current OpenCL support. See the [known problems](https://github.com/tesseract-ocr/tesseract/wiki/TesseractOpenCL#known-problems) remark in the Wiki.

**Comment by Catscratch** [comment]
Hm ok. Any other change to increase performance? I mean, other solutions than increasing the number of CPUs?

**Comment by stweil** [comment]
I assume that you are already using [tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast). Then you can use a faster CPU, add more cores or try patches like [this one](https://github.com/tesseract-ocr/tesseract/pull/954). Or you work on the Tesseract code yourself.

**Comment by Catscratch** [comment]
I wasn't aware of tessdata_fast but I'll give it a try. Thanks for the hint!

**Comment by jbarlow83** [comment]
I'm not going to do anything to make Tesseract with OpenCL easier to use with ocrmypdf given the many known issues.

**Comment by amitdo** [comment]
OpenCL !=r CUDA.

Tesseract never had CUDA code.

**Comment by PratapMehra** [comment]
I have found a [document](https://tesseract-dirac.readthedocs.io/en/latest/user-guide/gpu.html) from tesseract 5.0 alpha.

**Comment by stweil** [comment]
> I have found a document from tesseract 5.0 alpha.

That's one of many things which are also called Tesseract but which are completely unrelated to Tesseract OCR.
