### ISSUE TITLE
Can you overwrite existing PDF but only add OCR layer if none exists already?

### ISSUE THREAD

**Issue by sunk818** [jbarlow83/OCRmyPDF#229]
Is there a way to overwrite the PDF only if there is no OCR layer and this program adds the OCR layer?

**Comment by jbarlow83** [comment]
The option --skip-text will do that, mostly.

It adds an OCR layer if there is no text on the page. No distinction is
made between OCR text and visible text since the PDF specification
unfortunately makes no such distinction.

**Comment by sunk818** [comment]
I see. OCR layer applies to text layer. Text layer may already exist. 

What about the overwriting part? 

Should we create another directory the PDF outputs to, make file comparisons, and overwrite manually if we are satisfied with the results?

**Comment by jbarlow83** [comment]
First, ocrmypdf only overwrites output files on success, even if the input and output file are the same.

In its default mode (without skip-text) `ocrmypdf --output-type pdf` will exit with an error if text is found on any page. That means you could use on a folder of PDFs, mixed scanned and "born digital" files, and it will only change those that were scanned.

In the mode `ocrmypdf --skip-text --output-type pdf`, it will only perform OCR on pages that had no text. The overall PDF will be also have any syntax errors fixed and better compression used. 

You should use `--output-type pdf` if you are concerned about changing PDFs as little as possible, and the default (PDF/A) if you are concerned about making PDFs as future proof as possible.

That said, always keep backups.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by sunk818** [comment]
Thanks for the great information. I was worried about PDF with a password, but I see overwrite is only upon success so I don't have to worry about any scenarios where errors are involved. I like this great product!
