### ISSUE TITLE
Not skipping pages that contain text

### ISSUE THREAD

**Issue by enigma969** [jbarlow83/OCRmyPDF#232]
Hi, 

when running OCRmyPDF on PDFs born "digital" that already contain text, documentation says it should skip those pages: [https://github.com/jbarlow83/OCRmyPDF/blob/master/docs/advanced.rst](url)

In my case, it does not skip OCR when pages contain text. OCR is applied and the final document contains 2 layers of text. I tried it with multiple documents. 

According to documentation it should skip these pages by default, no additional flags are needed, right? 

I run OCRmyPDF like this: 

`~/.local/bin/ocrmypdf /home/me/ocrmypdf/demo-email.pdf /home/me/ocrmypdf/OCR-demo-email.pdf
`

Please find attached a sample document that gets OCR applied but shouldn't: 

[demo-email.pdf](https://github.com/jbarlow83/OCRmyPDF/files/1814897/demo-email.pdf)

**Comment by jbarlow83** [comment]
The test OCRmyPDF uses to determine if there is text on pages is not robust enough to handle this case.

**Comment by jbarlow83** [comment]
Fixed for v6 - text detection improved
