### ISSUE TITLE
OCRmyPDF with docker on CentOS7 not working

### ISSUE THREAD

**Issue by Roxy78** [jbarlow83/OCRmyPDF#24]
Hi,
I followed the docs for installing the docker container.
Running "docker run ocrmypdf --help" works fine.
But if I try to execute ocrmypdf on a local file, I get an error:

[root@CentOS7 test]# docker run -v "/srv/test/:/home/docker/" ocrmypdf ocrmypdf -v 1 x.pdf 1.pdf
usage: ocrmypdf [-h] [--verbose [VERBOSE]] [--version] [-L FILE] [-j N]
                [--use_threads] [-n] [--flowchart FILE] [-l LANGUAGE]
                [--title TITLE] [--author AUTHOR] [--subject SUBJECT]
                [--keywords KEYWORDS] [-d] [-c] [-i] [--oversample DPI] [-f]
                [-s] [--skip-big MPixels]
                [--tesseract-config TESSERACT_CONFIG]
                [--pdf-renderer {tesseract,hocr}]
                [--tesseract-timeout TESSERACT_TIMEOUT] [-k] [-g]
                input_file output_file
**ocrmypdf: error: unrecognized arguments: 1.pdf**

Any help would be nice.

Thank you!
Kind regards,
Nicole

**Comment by jbarlow83** [comment]
I think you have a duplicate "ocrmypdf" in your test command.
Try: docker run -v ".." ocrmypdf -v 1 x.pdf 1.pdf

**Comment by Roxy78** [comment]
Hi,

sorry for the very late response...

You're right. One ocrmypdf was obsolete.

Thanks!

Kind regars,
Nicole


Am 05.11.2015 um 08:02 schrieb jbarlow83:
> I think you have a duplicate "ocrmypdf" in your test command.
> Try: docker run -v ".." ocrmypdf -v 1 x.pdf 1.pdf
>
