### ISSUE TITLE
Upcoming changes to img2pdf

### ISSUE THREAD

**Issue by josch** [jbarlow83/OCRmyPDF#243]
Hi,

I wanted to inform you of a change that will appear in the next img2pdf release. I'm not sure whether it affects you, so just close this bug report in case it doesn't.

img2pdf will refuse to work with images that include transparency. This is because the main purpose of img2pdf is to do *lossless* conversion of raster images into a pdf container. Lossy conversion is already covered by other tools (like imagemagick). So if you want to put an image with transparency into a PDF, then you have to do the conversion yourself manually beforehand (img2pdf will give you a working imagemagick call to execute). Then you can also specify other things like which color you want the transparent background to in. This is to make the user conciously decide "Yes, I *really* want to destroy some of the data of my original input, I know what I'm doing." If you are using img2pdf as a Python library, then just use PIL to convert your image into RGB before giving it to img2pdf. Yes, I could add yet another command line switch to do the conversion on the fly but I think rather than making the user learn another program-specific behaviour, they should rather use the right tool for the job. And img2pdf should do one thing only and it should do that thing well (unix philosophy).

Thanks!

cheers, josch

**Comment by jbarlow83** [comment]
Thanks for the heads up.

I rasterize content from the PDF, and optionally apply some processing. When the user applies processing, I use img2pdf to convert the processed image back to a single page PDF, and then merge all the single page PDFs. So I'm flattening transparency before it gets there.

If you did want to support transparency I think all you need to do is create a separate Image XObject for the alpha channel, and set /SMask on the primary image as a pointer to the alpha channel.

**Comment by josch** [comment]
The problem then becomes: how do I verify that the output is indeed pixel perfect compared to the input? Or how do I then extract the image from the pdf and assemble the original? If I cannot verify that the resulting pdf is pixel perfect compared to the input and if I cannot extract something that is pixel perfect compared to the input from the pdf, then it would not be a lossless operation. You could also close this issue and write me an email if you would like to stop abusing your bugtracker for this exchange. Thanks! :)

**Comment by jbarlow83** [comment]
:)
