### ISSUE TITLE
Errors in tests/resources/README.rst

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#245]
Hello,

IANAL, but I am pretty sure that the license for epson.pdf has to be the license of the Wikipedia article.  I don't think that @lowesjam can claim copyright and licence it under MIT just for printing and scanning the page.  So I suggest listing the license as CC-BY-SA-3.0.  This is what I will write in the Debian copyright file.  Of course, it is fine to retain the credit to @lowesjam for his contribution of the PDF file.

Similarly for @supergrobi and masks.pdf.

Thanks.

**Comment by jbarlow83** [comment]
Fixed in 4f6bffb
