### ISSUE TITLE
Option to retain CreationDate (from Meta Data) from Input file

### ISSUE THREAD

**Issue by MarinRowingClub** [jbarlow83/OCRmyPDF#247]
1) Does CreationDate not refer to the the 1st day-time the doc was created and that should be retained by default.
2) I have a use case - when I must display the sorted files by date.

Or would you have another workaround that I could use to help me retain the creationDate.
Thanks!

**Comment by jbarlow83** [comment]
Do you mean the CreationDate XMP metadata, the DocumentInfo metadata, or the creation time as reported by the file system?

**Comment by MarinRowingClub** [comment]
"CreationDate" XMP metadata - the DocumentInfo Metadata - the metadata that you get along with author, title.
