### ISSUE TITLE
White glyphs when selecting ocr-text in Evince

### ISSUE THREAD

**Issue by geniusupgrader** [jbarlow83/OCRmyPDF#249]
Problem in evince pdf reader:

![screenshot_20180405_101240](https://user-images.githubusercontent.com/6190906/38354470-091542d6-38ba-11e8-8d06-68f25969f7eb.png)

It only happens when selecting. Is this a display failure? missing fonts? otherwise ocr text is correct.
Similar to #178?

**Comment by geniusupgrader** [comment]
Found this: https://unix.stackexchange.com/questions/306051/tesseract-is-it-possible-to-change-font-output-in-ocred-pdf

Do I really need to rebuild tesseract for this? Is there no other way around with OCRmyPDF?

**Comment by geniusupgrader** [comment]
This does only happen with scanned pages?

**Comment by jbarlow83** [comment]
At a glance it looks like that version of evince can't display the Tesseract glyphless font correctly, although that would be surprising since it's been checked.

Are you using Tesseract 4? What command line?

Try changing the PDF renderer
https://ocrmypdf.readthedocs.io/en/latest/advanced.html#changing-the-pdf-renderer

Try building a regular PDF instead of PDF/A
``--output-type pdf``

Can you use Tesseract on an image to create a PDF and view that PDF?

**Comment by geniusupgrader** [comment]
Thanks for your help:
tesseract --version
tesseract 3.05.01
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1

`--output-type pdf` does not work.
Haven't try to use tesseract on an image directly, because I don't use images only pdfs as input formats.
But when using the `hocr` renderer it works.
Then I will wait till the arch repos upgrade tesseract to version 4, in hope that other renderers will work, too.
Thanks for you help. I will close this. But if someone has other opinions please go ahead.

**Comment by jbarlow83** [comment]
What Linux and version of evince? This might be something that the maintainers of Tesseract or evince need to take up.

**Comment by geniusupgrader** [comment]
Evince Version: 3.26.0+14+g2a499547-1
Linux Kernel version: 4.14.31-1

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/182#issuecomment-170098851

**Comment by jbarlow83** [comment]
@bitwave The Ghostscript issue is fixed now.

I believe the issue is with Evince itself, so I reported it there.
https://gitlab.gnome.org/GNOME/evince/issues/953

**Comment by amitdo** [comment]
https://gitlab.freedesktop.org/poppler/poppler/issues/157

**Comment by PLChevalier** [comment]
![screenshot_27](https://user-images.githubusercontent.com/35298343/45626798-aa4c8a80-ba90-11e8-9f9a-a194b8dfaa6d.png)
Opening the pdf with a web browser allows to see the text while selecting it

**Comment by titaniumbones** [comment]
I'm still seeing this issue in poppler-based viewers. Is there any workaround available?

**Comment by grossherr** [comment]
@titaniumbones as mentioned above, change the renderer to `hocr`, so use `--pdf-renderer hocr`. Works for me in evince.

**Comment by titaniumbones** [comment]
where do I add this switch (`--pdf-renderer hocr`)? In tesseract? evince? just in poppler somehow?  I'm not seeing that switch in any docs....  

THanks for the help!

**Comment by hebdon** [comment]
Thank you all, this helped me fix what I thought was a deficiency in OCRmyPDF. For me the boxes were black not white, and manifested in all viewers whether Evince, Okular, or PDF-Tools in Emacs. 

Adding --pdf-renderer hocr makes highlighted text visible again. Beautiful!

**Comment by julian-klode** [comment]
I'd love too but I broke my wrist and the other side elbow, so I'm a bit incapacitated

**Comment by amitdo** [comment]
Hope you will feel better soon :-1

**Comment by amitdo** [comment]
https://gitlab.freedesktop.org/poppler/poppler/-/commit/375809c897a66f
