### ISSUE TITLE
ocrmypdf suddenly stopped working on osx 10.12 / latest homebrew

### ISSUE THREAD

**Issue by benjo2000** [jbarlow83/OCRmyPDF#250]
ocrmypdf -r -i -l deu input.pdf output.pdf results in the following error: 
Could not find program 'unpaper' on the PATH

the verbose mode postulates:
DEBUG - ocrmypdf 6.1.3
 DEBUG - tesseract 3.05.01
 DEBUG - qpdf 8.0.2
 DEBUG - PyMuPDF not installed
ERROR - Could not find program 'unpaper' on the PATH

I tried reinstalling unpaper via homebrew, that didn't help.

Thanks for your help

**Comment by benjo2000** [comment]
Ok, it works again. I tried to run unpaper with different commands and files. That failed everytime because a missing x265 lib in ffmpeg prevented it from running: `Library not loaded: /usr/local/opt/x265/lib/libx265.146.dylib`
After reinstalling ffmpeg via brew, everything is working now. Seems that ffmpeg didnt upgrade correctly at one time on my system.

**Comment by jbarlow83** [comment]
Mostly a brew issue. Changed error message to repeat system error in that case.
