### ISSUE TITLE
Installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by Shreeshrii** [jbarlow83/OCRmyPDF#252]
I was able to install and run ocrmypdf on WSL - Ubuntu 14.03. However, some extra steps were required to get pip to install.

Here are the additional/changed commands that were required:

```
sudo apt-get install python3.6-dev
curl https://bootstrap.pypa.io/ez_setup.py -o - | python3.6 && python3.6 -m easy_install pip
pip3.6 install ocrmypdf[fitz]
```

**Comment by jbarlow83** [comment]
Thanks - updated
