### ISSUE TITLE
Test file license clarification

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#254]
I want to clarify the license of a few test files and put them under CC-BY-SA 4.0, which I think is a more appropriate license for test resources. Previously I did not pay much attention to how test files were licensed.

@maxandersen - You contributed tests/resources/overlay.pdf. Can I set this file to the CC-BY-SA 4.0 license?

@Catscratch - You contributed tests/resources/vector.pdf. Did you create this file or do you know who holds the copyright? If you created it, can I license it as CC-BY-SA 4.0?

Thanks.

**Comment by Catscratch** [comment]
I created it and yes, you may license it.

**Comment by maxandersen** [comment]
> @maxandersen - You contributed tests/resources/overlay.pdf. Can I set this file to the CC-BY-SA 4.0 license?

go ahead. All good with me. Thanks for asking.

**Comment by jbarlow83** [comment]
Thank you both.
