### ISSUE TITLE
PDF Compression

### ISSUE THREAD

**Issue by jmrichardson** [jbarlow83/OCRmyPDF#255]
Hi, This is more of a question than an issue...  Is it possible to compress the PDF as part of the OCRmyPDF pipeline?  I don't see any references to this capability in the documentation.  

Thanks in advance

**Comment by tuxflo** [comment]
Why not just put an && `gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=output.pdf input.pdf` or a similar pdf compression tool at the end of your ORCmyPDF command?

**Comment by jbarlow83** [comment]
Currently the PDF will be compressed without loss when possible, by default. That is, a lossless data gets compressed to lossless, and data that was lossy remains as lossy as the input.

You can current use ``--pdfa-image-compression`` to request OCRmyPDF to use JPEG more often. This helps a lot of files.

I am actively working changes that will introduce better compression algorithms, downsampling, and color reduction. There should be improvements for all files generally, and options to sacrifice quality and further reduce file size.

@tuxflo That command asks Ghostscript to distill a PDF for display on a screen and will reduce color and grayscale images to 72 DPI. It also throws aways PDF/A. That's unacceptable quality loss in many use cases. See docs. https://www.ghostscript.com/doc/9.23/VectorDevices.htm#COMMON

**Comment by tuxflo** [comment]
Yes, it was just meant to be an example of a different compression strategy, but thanks for clearing this up. I just thought it might be better to use OCRmyPDF for creating OCR'd pdfs and use other tools for compression close to the Unix philosophy "do one thing and do it well".

**Comment by jbarlow83** [comment]
I do support the Unix philosophy of composition and spinning off the PDF optimizer as a separate component is a possibility. For the moment it's easier to bake it in than turn one project into 3 (common code, ocrmypdf, pdf optimizer).

The reason I'm working on this is that PDF optimizers I've found tend to be overly aggressive and usually produce PDFs that don't pass validation. I'm also narrowly focused on the types of PDFs that appear on in scan and OCR workflows, as opposed to say, optimizing prepress PDFs or producing linearized PDFs.

**Comment by jmrichardson** [comment]
Thank you and appreciate this tool!
