### ISSUE TITLE
overlay two pdfs

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#267]
I have 2 pdf files, one graphic-only pdf (from a scan) and one containing the corresponding text (but with the wrong font). Both files contain many but the same number and format of pages.

Now I want to superimpose these two pdfs so that the graphic is on top and the text is invisible. I want to use the existing text instead of ocr, so that the graphic looks correct and at the same time no ocr errors can play a role.

Can this be done with ocrmypdf?

(I tried with pdftk and the background option but this uses only the first page of the text pdf over and over again instead of all text pdf pages.)

**Comment by femifrak** [comment]
Now I have an idea. Can't use this method well to implement the sometimes requested function of editing the ocr text? ocrmypdf could create a text PDF that can be corrected with an external pdf editor. Afterwards you could put graphic and text together again.

**Comment by jbarlow83** [comment]
multibackground is probably your best bet, but if you need more control of it.

ocrmypdf does this internally but doesn't expose the machinery. Have a look at [combine_layers](https://github.com/jbarlow83/OCRmyPDF/blob/master/src/ocrmypdf/pipeline.py#L728) if you want to see how ocrmypdf does it; this function would work almost verbatim on single page PDFs.

**Comment by jbarlow83** [comment]
I'd lean towards using a .hocr file with an external editor and feeding that back in somehow. PDFs are almost maximally unsuitable for text editing. A hocr editor could be implemented in a browser since hocr is mostly HTML.

**Comment by femifrak** [comment]
Thanks!
(There is a comfortable pdf editor, infix)
