### ISSUE TITLE
Question: Support for Python2.7?

### ISSUE THREAD

**Issue by guettli** [jbarlow83/OCRmyPDF#268]
Unfortunately I need to support Python2.7.

Do you have a clue how hard it would be to get ocrmypdf running on Python2.7?

**Comment by jbarlow83** [comment]
It would be difficult, and the next release will only make it more so. But
more to the point I can't think of a reason it would be necessary.

ocrmypdf is an application not a library. Not many parts of the application
code that would be useful to another application. If you want to use
ocrmypdf from a Py2 project you should install Py3 and ocrmypdf and call it
through a subprocess.

You could also extract parts of ocrmypdf code and run 3to2 for selective
porting. Ocrmypdf is GPLv3.

You could also use the Docker container if Python 3 cannot be installed on
the host for some reason.

What are you trying accomplish?

**Comment by guettli** [comment]
Thank you for your answer.

I try to accomplish to annotate PDFs from a document scanner with text. 
And I need to install the software somehow.

Unfortunately we still use Python 2.7.

At the moment we use install_requires in setup.py for dependency management (if possible).
Only in few cases I need to create a RPM.

I could use Python3 and install it via RPM and use subprocess.

Your answer solved my issue. I personally like it, that you support only Python3. This gives me arguments to do the upgrade from 2.7 to 3.x  in our company :-)
