### ISSUE TITLE
OCR timeout - exception occurs

### ISSUE THREAD

**Issue by Gugols** [jbarlow83/OCRmyPDF#270]
Hi, while doing the OCR processes, I'm facing a problem where the timeout occurs however it causes an ugly exception - is it usual or something may be wrong with setup/installation I have? https://gist.github.com/Gugols/dc960bfeabadf6981174d693aea77f27

Also - Can I somehow debug why does Tesseract stuck in OCR process? Since even when I set the timeout to 30 minutes, it's still stuck and I can't figure out a way to see the cause of such unexpected stalemate.

**Comment by Gugols** [comment]
@jbarlow83 

Ok, after hours of struggling I managed to install _Tesseract_ 4. Actually the struggle was the _Leptonica_ installation since it wasn't detected by _Tesseract_ at first:

>configure: error: Leptonica 1.74 or higher is required." Try to install libleptonica-dev package.
I compiled it from source since there was no repo for RedHat. Then I managed to create a symlink:

> ln -s /usr/local/lib/pkgconfig/lept.pc /usr/share/pkgconfig/lept.pc

So, the installation was successful. However, when I try to run:

> tesseract -l eng 000001.image 000001.rendered pdf txt

I get:

>Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
>Error in pixReadStreamPng: function not present
>Error in pixReadStream: png: no pix returned
>Error in pixRead: pix not read
>Error during processing.

Then when I take a look at: tesseract -v I get the following output:

>tesseract 4.0.0-beta.1
> leptonica-1.76.0
>  libjpeg 6b (libjpeg-turbo 1.2.90) : libtiff 4.0.3 : zlib 1.2.7 : libwebp 0.3.0
> Found SSE

So, at first it seemed that I'm missing some kind of png library. So I installed it:

> yum install libpng-devel

But tesseract -v still doesn't list it (even after the re-install of Leptonica). This is likely not a OCRMyPDF issue, but yeah - kind of struggling with this new setup.

**Comment by jbarlow83** [comment]
Your 3.0 and 4.0 issues were likely the same then. Which RedHat is this?

Ubuntu 18.04 is a lot smoother....

This might help too.
https://github.com/EisenVault/install-tesseract-redhat-centos/blob/master/install-tesseract.sh

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by divyangashah** [comment]
hi @jbarlow83 , I am using tesseract v4.0.0.0-beta3 ver.
I am still facing timeout gets failed with application crash.

**Comment by jbarlow83** [comment]
@divyangashah Please open a new issue with more details about your problem, such as your operating system, and a test file. You might get the same error, but it doesn't mean it's the same issue as this old one.

**Comment by divyangashah** [comment]
@jbarlow83 please refer below issue:
https://github.com/tesseract-ocr/tesseract/issues/2910

Thanks!
