### ISSUE TITLE
Python 3.7 incompatibility

### ISSUE THREAD

**Issue by ilovezfs** [jbarlow83/OCRmyPDF#274]
Due to the ruffus dependency, OCRmyPDF is incompatible with Python 3.7.

See https://github.com/cgat-developers/ruffus/pull/92

Given there has been no release of ruffus since 2015, it may be worth looking into dropping the dependency. There does seem to be some recent commits on the GitHub repo but it's not clear whether that's going to translate into an actual release to PyPI.

For now we are hacking around this in the Homebrew formula by patching ruffus.

**Comment by jbarlow83** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/29920
