### ISSUE TITLE
Homebrew upgrade failed

### ISSUE THREAD

**Issue by mutex1980** [jbarlow83/OCRmyPDF#277]
Todays homebrew upgrade produced this error, it says I should report it here so here it is :-)  : 

> ==> Upgrading 1 outdated package, with result:
jbarlow83/ocrmypdf/ocrmypdf 6.2.1 -> 7.0.0
==> Upgrading jbarlow83/ocrmypdf/ocrmypdf 
==> Downloading https://files.pythonhosted.org/packages/ef/b2/b9d4d796d485852f583c34d16d20f20be3f5926049e859e1dd1d991205d9/ocrmypdf-7.0.0.tar.gz
Already downloaded: /Users/mmae/Library/Caches/Homebrew/ocrmypdf-7.0.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Already downloaded: /Users/mmae/Library/Caches/Homebrew/ocrmypdf--homebrew-virtualenv-16.0.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/ocrmypdf--homebrew-virtualenv-20180711-4925-1lvs0ce/target --single-version-exte
==> python3 -s /private/tmp/ocrmypdf--homebrew-virtualenv-20180711-4925-1lvs0ce/target/bin/virtualenv -p python3 /usr/local/Cellar/ocrmypdf/7.0.0/libexec
==> Downloading https://files.pythonhosted.org/packages/d3/c4/b45b9c0d549f482dd072055e2d3ced88f3b977f7b87c7a990228b20e7da1/Pillow-5.2.0.tar.gz
Already downloaded: /Users/mmae/Library/Caches/Homebrew/ocrmypdf--Pillow-5.2.0.tar.gz
==> /usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ocrmypdf--Pillow-20180711-4925-10zjf
==> Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz
Already downloaded: /Users/mmae/Library/Caches/Homebrew/ocrmypdf--cffi-1.11.5.tar.gz
==> /usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ocrmypdf--cffi-20180711-4925-llfcvb/
==> Downloading https://files.pythonhosted.org/packages/7e/a2/4f06081f674920be757d894b4bab874e6a3b5227e730cb7618430b366e69/img2pdf-0.2.4.tar.gz
Already downloaded: /Users/mmae/Library/Caches/Homebrew/ocrmypdf--img2pdf-0.2.4.tar.gz
==> /usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ocrmypdf--img2pdf-20180711-4925-1mac
==> Downloading https://files.pythonhosted.org/packages/50/03/f5af2251b8c206a7768a315c0487572a25e8225b6c9549d0b142862626c0/pikepdf-0.2.2.tar.gz
Already downloaded: /Users/mmae/Library/Caches/Homebrew/ocrmypdf--pikepdf-0.2.2.tar.gz
==> /usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ocrmypdf--pikepdf-20180711-4925-1kod
Last 15 lines from /Users/mmae/Library/Logs/Homebrew/ocrmypdf/06.pip:
  Removing source in /private/tmp/pip-req-build-xocx1n4g
Command "/usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-xocx1n4g/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record 
Todays homebrew 

> /private/tmp/pip-record-ncmi_rjn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/../include/site/python3.7/pikepdf" failed with error code 1 in /private/tmp/pip-req-build-xocx1n4g/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/7.0.0/libexec/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/ocrmypdf/7.0.0/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/ocrmypdf/7.0.0/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/ocrmypdf/7.0.0/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/Cellar/ocrmypdf/7.0.0/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-xocx1n4g/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-ncmi_rjn/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/7.0.0/libexec/bin/../include/site/python3.7/pikepdf" failed with error code 1 in /private/tmp/pip-req-build-xocx1n4g/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jbarlow83/homebrew-ocrmypdf/issues

**Comment by jbarlow83** [comment]
That appears to be based on my old homebrew tap from before ocrmypdf got added to homebrew core. Follow the instructions here to remove the tap and upgrade to the official version:

https://github.com/jbarlow83/homebrew-ocrmypdf/
