### ISSUE TITLE
No module named 'ocrmypdf.main'

### ISSUE THREAD

**Issue by kagithd** [jbarlow83/OCRmyPDF#282]
when calling ocrmypdf  on ubuntu 18.04 i got following failure
# ocrmypdf --help
Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.main import run_pipeline
ModuleNotFoundError: No module named 'ocrmypdf.main'

**Comment by jbarlow83** [comment]
You seem to have an incomplete/failed installation. I have no suggestions as to how to remove it, as you haven't indicated how you got to this state originally.

Try ``apt-get install ocrmypdf`` to install ocrmypdf 6.x which ships with Ubuntu 18.04, and then checking that `/usr/bin/ocrmypdf --help` works. 

Then follow the procedure here to get the latest version.
https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-the-latest-version-on-ubuntu-18-04-lts

**Comment by jbarlow83** [comment]
I'll close the issue now because it is likely a local configuration issue. If you have further related questions feel free to reopen it.
