### ISSUE TITLE
change TMPDIR did not work

### ISSUE THREAD

**Issue by ka223** [jbarlow83/OCRmyPDF#287]
I changed the TMPDIR variable in terminal, but OCRmyPDF is using my /tmp folder.
`TMPDIR="/media/HDD/tmp"`
https://github.com/jbarlow83/OCRmyPDF/blob/master/docs/security.rst

Version 5.6.2

Not sure why?

Best wishes

**Comment by jbarlow83** [comment]
Did you export the variable? Does running `tempfile.gettempdir()` in a Python shell report the modified value?

As the release notes indicate, v5.6.2 was a development branch accidentally tagged for release and it should not be used at all.

**Comment by ka223** [comment]
Sorry, but this Version was provided by pip.
export TMPDIR=...
works, but I can only use the version from bionic repository 6.1.2.
Have some problems with pip, pip3 -V shows python 2.7, even when I remove python-pip and python3-pip package or reinstall ...

**Comment by jbarlow83** [comment]
Run 

```
env TMPDIR=/tmp python3 -c 'import tempfile; print(tempfile.gettempdir())'
```

to ask Python where it thinks TMPDIR is.

Whatever issues you're having seem to be related to your local configuration, not ocrmypdf, so I can't help any further.
