### ISSUE TITLE
USAGE

### ISSUE THREAD

**Issue by jigyasa06** [jbarlow83/OCRmyPDF#295]
Hey,
Actually I wanted to know how to use this OCRmy PDF. Can you please tell me the command line usage commands.

Thank you so much.

**Comment by femifrak** [comment]
You want to have a look at:
https://ocrmypdf.readthedocs.io/en/latest/cookbook.html

The simplest way is:
ocrmypdf in.pdf out.pdf

**Comment by jigyasa06** [comment]
Thank you so much for your reply. 
I am doing ocrmypdf in.pdf and out.pdf but I am getting this error.
<img width="569" alt="screen shot 2018-09-13 at 15 08 48" src="https://user-images.githubusercontent.com/37703929/45490349-21b7ac80-b767-11e8-97c8-f1a1a1ca7017.png">

**Comment by femifrak** [comment]
Did you have a look at "Installation"? 'gs' (i.e. ghostscript) does not seem to be installed but is a dependency.

**Comment by jigyasa06** [comment]
Hey,

Thank you so much for your reply.

Actually, when I am parsing through the pdfs I am not able to get any results but when I am converting those PDFs into text using "CONVERTIO" online OCR Tool and then copying this text and pasting it on another file and saving it as a PDF and then the program (OCRmyPDF) is giving me results for those PDFs which I am creating on my own. I am not getting why is it so? Can you please suggest me what is the problem as I am not getting it.

Thank you so much in advance.

**Comment by femifrak** [comment]
I am not sure I understood you. However, when you have already text (as output from some online tool), you do not need ocrmypdf anymore (generally speaking). ocr tools convert graphics (which look like letters, a,b c, é, ß, 1, 2, ~, &, etc., etc., ...) to letters which also look like letters but additionally can be interpreted by you PC. When you are able to paste text, then you PC can handle it and ocr is no longer needed.
Maybe when you input real text (not only graphics) ocrmypdf does not require gs. But in this case I don't know the effect ocrmypdf could have. For a graphics to text conversion with ocrmypdf you need gs.

**Comment by jigyasa06** [comment]
Hey,
Thank you so much for your reply. I have already downloaded the ghostscript. But when I am running OCRmyPDF on a pdf file in German language I am getting the output as follows:

I used " ocrmypdf DataKeyTermExtraction/115_Hausreinigung_Standardvertrag.pdf kj.txt "this command to convert a pdf into text.

<img width="632" alt="screen shot 2018-09-14 at 18 02 41" src="https://user-images.githubusercontent.com/37703929/45561674-9a426a00-b848-11e8-821e-dd4b2111e85c.png">

Can You please explain me why is this coming like this?

**Comment by jbarlow83** [comment]
You're looking at the PDF file in a text file viewer.

The command should be
```
ocrmypdf --sidecar kj.txt DataKeyTermExtraction/115_Hausreinigung_Standardvertrag.pdf kj.pdf
```

to create a text file that contains extracted text (in kj.txt) and a searchable PDF (in kj.pdf, for use with a PDF viewer).

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by jigyasa06** [comment]
My issue is solved. Thank you so much :)
