### ISSUE TITLE
Rotation of pages doesn't work with --rotate-pages option

### ISSUE THREAD

**Issue by DEEPAK-KESWANI** [jbarlow83/OCRmyPDF#307]
Hi,

I'm using OCRMyPDF version 7.0.0 on Ubuntu 16.04.5 LTS and using below command to rotate PDF files but it's not working. 

Can you please help on this?

ocrmypdf --verbose 1 --force-ocr -l eng --output-type pdf --rotate-pages --deskew input.pdf output.pdf

Thanks.

**Comment by jbarlow83** [comment]
Rotation tries to guess the orientation, and if nothing changed the algorithm may have guessed that the current orientation was best. As with everything it will depend on a lot on the quality of the input files.

Use `--rotate-pages-threshold` to rotate more aggressively (and get more false positives).

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by DEEPAK-KESWANI** [comment]
Thanks for your quick response.

What should be the CONFIDENCE value in --rotate-pages-threshold to rotate the pages?

If I add 50 or 100 it doesn't rotate the pages. Can you provide the full command options to rotate the pages?

Thanks

**Comment by jbarlow83** [comment]
The threshold value should be lower if you want more rotation to occur. The default is 15.0. Try `1`.

The units are arbitrary.

**Comment by DEEPAK-KESWANI** [comment]
Thanks a lot.

The below command worked for me. 
ocrmypdf --verbose 1 --force-ocr -l eng --output-type pdf --rotate-pages --rotate-pages-threshold 1 input.pdf output.pdf

Again thanks for your quick help and support.
