### ISSUE TITLE
OCRmyPDF v6.x series: test suite fails with new tesseract

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#308]
[OCRmyPDF 6.2.4 is failing its tests](https://bugs.debian.org/912001) against tesseract `4.00~git3241-1066f696`, whereas they passed against tesseract `4.00~git2904-07acc2b2`.  To be clear about these version numbers, they are both git snapshots made prior to the 4.00 release of tesseract (the `~` means "subtract").

OCRmyPDF 7.2.1 is fine, which probably means there is a fix that can be backported?

Thanks.

**Comment by jbarlow83** [comment]
Suppressed in v6.2.5 by disabling the failing test. Fix is spread across a few commits and doesn't backport cleanly.

The test was for whether we cleanly handle an error message from Tesseract, and the user supplies a custom Tesseract configuration file (or somehow corrupted a main file). So it's advanced usage and obscure.

**Comment by spwhitton** [comment]
Hello,

On Mon 29 Oct 2018 at 05:33AM GMT, jbarlow83 wrote:

> Suppressed in v6.2.5 by disabling the failing test. Fix is spread
> across a few commits and doesn't backport cleanly.
> The test was for whether we cleanly handle an error message from
> Tesseract, and the user supplies a custom Tesseract configuration file
> (or somehow corrupted a main file). So it's advanced usage and
> obscure.

Thank you!

-- 
Sean Whitton
