### ISSUE TITLE
Command does nothing

### ISSUE THREAD

**Issue by pwannh** [jbarlow83/OCRmyPDF#310]
I used this command:
ocrmypdf ~/Scratch/Scan-181102-0002.pdf ~/Scratch/x.pdf
The command completed with no messages, but no output file was created.
"ocrmypdf --version" shows 7.2.1. I am on a MacBook with Mac OS 10.12.6.
What's wrong?
The input file is attached.

![image](https://user-images.githubusercontent.com/44687053/47886599-4cef7b80-de3b-11e8-99a6-928c268b1663.png)

**Comment by jbarlow83** [comment]
You attached an image of the file rather than the PDF. I'll need the PDF to investigate further.

**Comment by jbarlow83** [comment]
The file displays the error message:
```
 ERROR -    1: page already has text! – aborting (use --force-ocr to force OCR)
```

Perhaps you're running from a script or other program that does not read stderr?

I see the file is in Sweden but was OCR'd to use the English alphabet. You probably want to redo the OCR. You could use ``ocrmypdf --deskew --force-ocr -l swe in.pdf out.pdf`` to redo it in Swedish and straighten the file.

**Comment by pwannh** [comment]
Hi,

Thanks for your reply, I really appreciate it. I tried the command you gave me with this result:

ERROR - The installed version of tesseract does not have language data for the following requested languages: 
swe

I don’t know how to add language support to tesseract but will look into that. I then tried the same command leaving "-l swe” out. Result: no message of any kind, neither success nor error, no output produced. I then tried again with the option “-l eng” - same result.

Any more ideas?

Regards
Peter

**Comment by pwannh** [comment]
Hi again,

I have to add the following to my previous message: I believe the file was scanned with an OCR option turned on. That may explain my problems, but perhaps a message of some kind from ocrmypdf would be appropriate.

However, the reason I raised this is that I had another file that was scanned without OCR-ing, which I tried to process with ocrmypdf without success. It is quite large (54 pages, 1.3 MB) and contains some private information so I did not want to submit it, but just scanned some other random one-page document. I forgot that the scanner does OCR. Now, I have extracted a single page out of that big file (attached) and tried ocrmypdf on it. Same result as before: no message, no output.

Regards
Peter

**Comment by jbarlow83** [comment]
It seems like something is missing from your installation.

Try running with something `-v 1` which shows debug messages.

**Comment by pwannh** [comment]
Sorry, I should have thought of that myself. Here it is. Again, I appreciate your attention to this!

**Comment by jbarlow83** [comment]
Were you going to attach a log file? (I'm not sure if email attachments to GitHub get added to the issue.)

**Comment by pwannh** [comment]
Not sure I understad what you are saying here. In my last message, I attached the complete output on stdout from running the command with -v 1, as you suggested. What else do you want me to do?

**Comment by jbarlow83** [comment]
You put the output in as an attachment to your email, and GitHub deletes email attachments, so I can't see it. There is nothing for me to look at:

https://github.com/jbarlow83/OCRmyPDF/issues/310#issuecomment-435626561

**Comment by pwannh** [comment]
Sorry, I am not familiar with how to use this forum. I thought we had a private email conversation. Here's the log file I sent before through regular email.

[ocrmypdf_output.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2545425/ocrmypdf_output.pdf)

**Comment by jbarlow83** [comment]
You're using a very old version of Ghostscript, version 8.61.

If you install ocrmypdf from homebrew it should automatically install a good version of Ghostscript for you. The minimum supported version is in the documentation (probably about 9.15 but I can't remember).

**Comment by jbarlow83** [comment]
This is a public conversation. If there is information in the PDF you didn't want seen publicly I can remove it.

**Comment by jbarlow83** [comment]
And `gs --version` says?

**Comment by pwannh** [comment]
Says 8.61. Something is fishy. I have tried the whole thing on another
MacBook (MB2) running MacOS 10.13.6. It was initially pretty much identical
to the one where I had the problem (MB1) , except that MB1 runs MacOS
10.12.6. Also, MB1 is using pyenv and has both python 2 and 3, MB2 has only
python 3 (after my actions). I essentially did this:

brew uninstall ghostscript
brew uninstall python
brew install ghostscript
brew install python
brew install ocrmypdf

Now gs --version says 9.25, and the ocrmypdf operations seem OK. I don't
understand exactly what the difference is, but I will try to bring MB1 to
the same state.

Yes, please do remove  the PDF's I sent from the forum, at least the first
one that I accidentally dragged in rather than select.

Thanks, Peter
