### ISSUE TITLE
--force-ocr should consider applying CropBox or other trimming boxes

### ISSUE THREAD

**Issue by wanghaisheng** [jbarlow83/OCRmyPDF#311]
```
docker run --rm -v "$(pwd):/home/docker"   ocrmypdf --max-image-mpixels 12800 --force-ocr all/should_detect_rulings.pdf out/should.pdf
WARNING -    1: page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
   INFO -    1: [tesseract] Image too large: (36800, 36800)
  ERROR -    1: [tesseract] Error during processing.
   INFO - Optimize ratio: 7.09 savings: 85.9%
   INFO - Output file is a PDF/A-2B (as expected)
```
[should_detect_rulings.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2556796/should_detect_rulings.pdf)

**Comment by jbarlow83** [comment]
The PDF says, internally
```
/CropBox [ 31.697 5409.59 704.89 6570.3 ] /MediaBox [ 0 0 6624 6624 ]
```

meaning that the target media is a very large 233x233 cm, but you have cropped to about the size of a A3 sheet. ocrmypdf is trying to preserve the very large original media, which results in an extremely large image.

As a workaround, you can rewrite the PDF with

```
gs -dUseCropBox -dNOPAUSE -sDEVICE=pdfwrite -o output.pdf input.pdf
```

That will reduce the size of the mediabox to match the cropbox.

**Comment by jbarlow83** [comment]
Also note that this PDF does not need OCR.
