### ISSUE TITLE
conversion of ocr'ed docs to pdf/a possible?

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#319]
Sometimes I have pdf/a documents (scanned + text layer), which lose their pdf/a qualification through editing (pdftk, qpdf, third party software).
Is it possible with ocrmypdf (in the current or a future version ;) ) to raise these documents back to the pdf/a standard? However, the existing text should be retained.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by femifrak** [comment]
I'm sorry, but I didn't get your answer. What do you mean by "converting to OCR"? Do you mean "converting to pdf/a"?
I tried to convert such a document with ocrmypdf --skip-text. According to metadata it is pdf/a compliant afterwards, but a test with verapdf shows that it doesn't really meet this standard.
Now I don't know how long the converted pdfs will be readable, but maybe we don't need to be so worried.

**Comment by jbarlow83** [comment]
>What do you mean by "converting to OCR"? Do you mean "converting to pdf/a"?

Yes, that's what I meant.

If there's a way you can send me a file I could take a look and see if there's a reason it loses pdf/a compliance after this procedure.

**Comment by femifrak** [comment]
While generating an example file I used your [hint](https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#don-t-actually-ocr-my-pdf) to create a pdf/a document with:

`ocrmypdf --tesseract-timeout=0 --remove-background graphicsonly.pdf  \ graphicsonly_pretendstobepdfa.pdf`



The terminal output assures:

>     INFO - Output file is a PDF/A-2B (as expected)

However, according to verapdf, graphicsonly_pretendstobepdfa.pdf is unfortunately **not** pdf/a compliant.

(This is not my original problem description but seems to be the same problem.)

[graphicsonly.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2690072/graphicsonly.pdf)
[graphicsonly_pretendstobepdfa.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2690073/graphicsonly_pretendstobepdfa.pdf)

**Comment by femifrak** [comment]
I don't understand the meaning of the verapdf messages, why the pdf is not pdf/a conform but I hope they are not so important with respect to permanent readability. Could you please confirm this?

I combined graphics and pdf/a text layer with
`pdftk graphicsonly_pretendstobepdfa.pdf multibackground textonly_pdfacompliant.pdf output \ graphics_plus_text.pdf`

As expected graphics_plus_text.pdf is also not pdf/a conform. Curiously, 

`ocrmypdf --skip-text graphics_plus_text.pdf gpt_pdfa.pdf`

results in some errors.

[graphics_plus_text.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2697822/graphics_plus_text.pdf)
 
Could you please give me some comments on that? Thanks a lot!

**Comment by jbarlow83** [comment]
veraPDF is correct. I made a change to metadata handling (in pikepdf, actually) that broke PDF/A conformance in a few situations. I took a look and have it mostly fixed; should have an update in the next day or so.

Anything pdftk touches loses PDF/A conformance. I've never looked into why.

**Comment by femifrak** [comment]
since ver. 8.0 everythink is working. Thanks!!!
