### ISSUE TITLE
Fedora 29 misses the tesseract-osd installation by default

### ISSUE THREAD

**Issue by toliwa** [jbarlow83/OCRmyPDF#323]
After installing ocrmypdf under Fedora 29 with

```
dnf install ocrmypdf
```

the program will produce the following output when trying to run it on a pdf:

```
  ERROR -    1: [tesseract] Error opening data file /usr/share/tesseract/tessdata/osd.traineddata
   INFO -    1: [tesseract] Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
   INFO -    1: [tesseract] Failed loading language 'osd'
   INFO -    1: [tesseract] Tesseract couldn't load any languages!
WARNING -    1: [tesseract] Warning: Auto orientation and script detection requested, but osd language failed to load
```

To remedy this, it seems that tesseract-osd should be installed. After running:

```
dnf install tesseract-osd
```

The above error is no longer shown. I would recommend to update this for Fedora. Hope this helps.

**Comment by jbarlow83** [comment]
This has to do with how Fedora has packaged ocrmypdf, which is not done by me. Please report it as a bug against the package in Fedora.

**Comment by fangzhou-xie** [comment]
@toliwa Thanks for your solution!

This is the error I had on Fedora 33 as well and your method fixed it for me!

**Comment by engineervix** [comment]
Thanks @toliwa! This also worked on Fedora 32.
