### ISSUE TITLE
A set of failing PDFs

### ISSUE THREAD

**Issue by gwern** [jbarlow83/OCRmyPDF#325]
I recently used `ocrmypdf` to mass-OCR my PDFs and a bunch of DjVu files I converted to PDF (which strips the original Tesseract OCR so I needed some way to restore it). Worked very nicely, and I like the better compression over the default `ddjvu` output.

Some files failed. I noticed the mention of a test corpus, so I thought you might like a list of failing files (these failed multiple times, so should be reliable test cases) and the errors.

The errors:

[myocr-gwernnet-errors.txt](https://github.com/jbarlow83/OCRmyPDF/files/2682362/myocr-gwernnet-errors.txt)

The files:

- https://www.gwern.net/docs/cs/1988-borenstein.pdf
- https://www.gwern.net/docs/eva/1999-japanedge-childrenmiyazakicocacola.pdf
- https://www.gwern.net/docs/statistics/decision/2006-drescher-goodandreal.pdf
- https://www.gwern.net/docs/statistics/decision/1962-blackett-studiesofwarnuclearandconventional.pdf
- https://www.gwern.net/docs/statistics/decision/1987-jonker.pdf
- https://www.gwern.net/docs/statistics/causality/2006-papanikolaou.pdf
- https://www.gwern.net/docs/nicotine/1996-foulds.pdf
- https://www.gwern.net/docs/history/1989-stern.pdf
- https://www.gwern.net/docs/sunkcosts/1990-wiklund-a.pdf
- https://www.gwern.net/docs/sunkcosts/1980-dawkins.pdf
- https://www.gwern.net/docs/genetics/correlation/1996-billig.pdf
- https://www.gwern.net/docs/genetics/correlation/1995-wadsworth.pdf
- https://www.gwern.net/docs/genetics/correlation/1989-tambs.pdf
- https://www.gwern.net/docs/genetics/correlation/1988-hewitt.pdf
- https://www.gwern.net/docs/genetics/correlation/1993-petrill.pdf
- https://www.gwern.net/docs/genetics/selection/2014-blasco.pdf
- https://www.gwern.net/docs/genetics/selection/2014-yao.pdf
- https://www.gwern.net/docs/genetics/selection/1980-yoo-3.pdf
- https://www.gwern.net/docs/genetics/selection/2014-montague.pdf
- https://www.gwern.net/docs/genetics/selection/2010-stearns.pdf
- https://www.gwern.net/docs/genetics/selection/1957-clayton.pdf
- https://www.gwern.net/docs/genetics/selection/2004-dekkers.pdf
- https://www.gwern.net/docs/genetics/heritable/1995-serpell-thedomesticdog.pdf
- https://www.gwern.net/docs/genetics/heritable/1989-coon.pdf
- https://www.gwern.net/docs/genetics/heritable/1979-jensen.pdf
- https://www.gwern.net/docs/genetics/heritable/1987-behavioralgeneticsabstracts.pdf
- https://www.gwern.net/docs/genetics/heritable/1989-reed.pdf
- https://www.gwern.net/docs/genetics/heritable/1986-davis-stormoverbiology.pdf
- https://www.gwern.net/docs/genetics/heritable/1995-willis.pdf
- https://www.gwern.net/docs/genetics/heritable/2014-cronqvist.pdf
- https://www.gwern.net/docs/genetics/heritable/1985-defries.pdf
- https://www.gwern.net/docs/music-distraction/2013-pacheco-unguetti.pdf
- https://www.gwern.net/docs/iodine/2005-caldwell.pdf
- https://www.gwern.net/docs/iq/smpy/1986-brody.pdf
- https://www.gwern.net/docs/iq/2014-beaver.pdf
- https://www.gwern.net/docs/iq/2015-daniele.pdf
- https://www.gwern.net/docs/iq/2013-barnes.pdf
- https://www.gwern.net/docs/iq/2010-lynn.pdf
- https://www.gwern.net/docs/iq/2004-van-hiel.pdf
- https://www.gwern.net/docs/rl/2002-schmidhuber.pdf
- https://www.gwern.net/docs/catnip/1976-preti.pdf
- https://www.gwern.net/docs/catnip/1987-tucker.pdf
- https://www.gwern.net/docs/catnip/1976-hill.pdf
- https://www.gwern.net/docs/catnip/1979-bland.pdf
- https://www.gwern.net/docs/catnip/1998-vandenbos.pdf
- https://www.gwern.net/docs/psychology/writing/1989-hartley.pdf
- https://www.gwern.net/docs/psychology/1957-clark.pdf
- https://www.gwern.net/docs/lithium/1990-schrauzer.pdf
- https://www.gwern.net/docs/vitamind/2013-li.pdf
- https://www.gwern.net/docs/japanese/1999-keene-seedsintheheart-teika.pdf
- https://www.gwern.net/docs/japanese/1999-keene-seedsintheheart-shotetsu.pdf
- https://www.gwern.net/docs/biology/1975-southern.pdf
- https://www.gwern.net/docs/culture/2007-cohen.pdf
- https://www.gwern.net/docs/nootropics/1992-heikinheimo.pdf
- https://www.gwern.net/docs/nootropics/2010-giesbrecht.pdf
- https://www.gwern.net/docs/nootropics/2004-juliano.pdf
- https://www.gwern.net/docs/nootropics/2012-pase.pdf
- https://www.gwern.net/docs/modafinil/2004-turner.pdf

**Comment by jbarlow83** [comment]
I will take a look.

Do you know what version of ocrmypdf version you used? The stack traces appear to be from an older version.

**Comment by gwern** [comment]
Whatever Ubuntu 18.0.4.1 ships, which appears to be '6.1.2-1ubuntu1.1' or '6.1.2' from `--version`.

**Comment by jbarlow83** [comment]
Please try the latest released version. There is an installation procedure in the documentation specifically for Ubuntu 18.04. I suspect that will fix many of these errors.

**Comment by gwern** [comment]
Upgrading to 7.3.1 does fix many of the errors. What's still left:

- https://www.gwern.net/docs/cs/1988-borenstein.pdf
- https://www.gwern.net/docs/statistics/causality/2006-papanikolaou.pdf
- https://www.gwern.net/docs/genetics/selection/2014-blasco.pdf
- https://www.gwern.net/docs/genetics/selection/2014-yao.pdf
- https://www.gwern.net/docs/genetics/selection/2014-montague.pdf
- https://www.gwern.net/docs/genetics/selection/2010-stearns.pdf
- https://www.gwern.net/docs/genetics/heritable/2014-cronqvist.pdf
- https://www.gwern.net/docs/music-distraction/2013-pacheco-unguetti.pdf
- https://www.gwern.net/docs/iodine/2005-caldwell.pdf
- https://www.gwern.net/docs/iq/2014-beaver.pdf
- https://www.gwern.net/docs/iq/2015-daniele.pdf
- https://www.gwern.net/docs/iq/2013-barnes.pdf
- https://www.gwern.net/docs/iq/2010-lynn.pdf
- https://www.gwern.net/docs/iq/2004-van-hiel.pdf
- https://www.gwern.net/docs/vitamind/2013-li.pdf
- https://www.gwern.net/docs/culture/2007-cohen.pdf
- https://www.gwern.net/docs/nootropics/2010-giesbrecht.pdf
- https://www.gwern.net/docs/nootropics/2004-juliano.pdf
- https://www.gwern.net/docs/nootropics/2012-pase.pdf
- https://www.gwern.net/docs/modafinil/2004-turner.pdf

[ocrmypdf-gwernnet-errors2.log](https://github.com/jbarlow83/OCRmyPDF/files/2682382/ocrmypdf-gwernnet-errors2.log)

**Comment by jbarlow83** [comment]
The problem is quite definitely how these files are formatted. In any case, the next release should be more tolerant of PDFs with these types of errors - it will issue warnings instead.

I went by the logs and concluded the errors are for the same for the most part.

**Comment by gwern** [comment]
That's good to hear. I hope they'll be good test cases for the next release, then.

**Comment by ivsanro1** [comment]
I found another error. Unfortunately, I cannot upload the pdf file, because it has personal data, and I do not know how to reproduce the error by creating a handcrafted pdf file. It seems to be a problem of the internal structure of the pdf file. This is the stacktrace of the error:


```  ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/lib/python3.5/dist-packages/ruffus/task.py", line 544, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/_pipeline.py", line 170, in repair_and_parse_pdf
    pdfinfo = PdfInfo(output_file, detailed_page_analysis=detailed_page_analysis, log=log)
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 722, in __init__
    infile, detailed_page_analysis, log=log)
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 604, in _pdf_get_all_pageinfo
    page = PageInfo(pdf, n, infile, page_xml, detailed_analysis)
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 614, in __init__
    self._pageinfo = _pdf_get_pageinfo(pdf, pageno, infile, xmltext)
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 571, in _pdf_get_pageinfo
    shorthand=userunit_shorthand)]
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 569, in <listcomp>
    contentsinfo = [ci for ci in
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 485, in _process_content_streams
    yield from _find_regular_images(container, contentsinfo)
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 390, in _find_regular_images
    for pdfimage, xobj in _image_xobjects(container):
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/pdfinfo/__init__.py", line 376, in _image_xobjects
    if candidate['/Subtype'] == '/Image':
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jbarlow83** [comment]
The wiki has instructions for encrypting a file for me only if you are comfortable with that.
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by ivsanro1** [comment]
> The wiki has instructions for encrypting a file for me only if you are comfortable with that.
> https://github.com/jbarlow83/OCRmyPDF/wiki

I am afraid I cannot do that, sorry. The document itself pertains to a third-party organization, and the personal info is not mine. I can check why it fails with pdb if it helps.

Thanks

**Comment by jbarlow83** [comment]
Probably fixed this, or at least suppressed the immediate cause of stack trace, in next release
