### ISSUE TITLE
brew or pip?

### ISSUE THREAD

**Issue by warmup72** [jbarlow83/OCRmyPDF#328]
Hi,
I´m not realy deep in using terminal-commands, so maybe a stupied question.
I want to use OCRmyPDF 7.4., because I need "--mask-barcodes" an hope, that die XMP-Trap "Creation Date" will be set, because 7.2.1 will set it to "null", which is not a valide PDF/A-XMP-Trap!

I have installed ocrmypdf via brew. In brew there is only version 7.2.1.
Is it planed to make 7.4.0 also install over brew or can ja user pip instead?

When should I user brew, when pip?!?

Thx

**Comment by jbarlow83** [comment]
Use pip if you need the latest version. 

Normally homebrew follows pip closely, but the update to homebrew
 https://github.com/Homebrew/homebrew-core/pull/35138 
is blocked until someone can resolve
 https://github.com/pdfminer/pdfminer.six/issues/208

That said, 7.4 improves metadata handling in several ways but there is still an open issue to resolve.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
