### ISSUE TITLE
ffi.error: symbol 'setMsgSeverity' not found in library '<None>': /usr/bin/python3: undefined symbol: setMsgSeverity

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#332]
When trying to build 7.4.0 against Debian experimental, I got this error:

    Running Sphinx v1.7.9
    
    Configuration error:
    There is a programable error in your configuration file:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/sphinx/config.py", line 161, in __init__
        execfile_(filename, config)
      File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
        exec_(code, _globals)
      File "conf.py", line 81, in <module>
        from ocrmypdf import __version__ as OCRMYPDF_VERSION
      File "/<<PKGBUILDDIR>>/debian/.debhelper/ocrmypdf/__init__.py", line 36, in <module>
        from . import leptonica
      File "/<<PKGBUILDDIR>>/debian/.debhelper/ocrmypdf/leptonica.py", line 43, in <module>
        lept.setMsgSeverity(lept.L_SEVERITY_WARNING)
    ffi.error: symbol 'setMsgSeverity' not found in library '<None>': /usr/bin/python3: undefined symbol: setMsgSeverity

The call to `lept.setMsgSeverity` is new.  I tried patching that line into OCRmyPDF 7.2.1, which is the version currently in Debian experimental, and I get a slightly different error:

    Running Sphinx v1.7.9
    
    Configuration error:
    There is a programable error in your configuration file:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/sphinx/config.py", line 161, in __init__
        execfile_(filename, config)
      File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
        exec_(code, _globals)
      File "conf.py", line 81, in <module>
        from ocrmypdf import __version__ as OCRMYPDF_VERSION
      File "/<<PKGBUILDDIR>>/debian/.debhelper/ocrmypdf/__init__.py", line 36, in <module>
        from . import leptonica
      File "/<<PKGBUILDDIR>>/debian/.debhelper/ocrmypdf/leptonica.py", line 38, in <module>
        lept.setMsgSeverity(lept.L_SEVERITY_WARNING)
    AttributeError: cffi library '<None>' has no function, constant or global variable named 'setMsgSeverity'

It would seem that the version of liblept5 in Debian does not export the setMsgSeverity function.  So I was thinking of just patching it out.  But I am worried about the `<None>`.  It suggests that the `ffi.dlopen` call is not succeeding.  What do you think?

**Comment by jbarlow83** [comment]
The error message normally names the library, e.g. `AttributeError: cffi library 'liblept.so.5' has no function...` when the library is loaded and an unrecognized symbol is accessed so something is definitely abnormal there. Does `ctypes.util.find_library("lept")` give the full path to liblept5.so?

I confirmed that `setMsgSeverity` is in Leptonica and probably has been for a few years. I also checked that we can call setMsgSeverity through CFFI on debian experimental... just in case some part of that process was broken at the moment.

```
>>> from cffi import FFI
>>> ffibuilder = FFI()
>>> ffibuilder.set_source('_test', None)
>>> ffibuilder.cdef(""" int32_t setMsgSeverity ( int32_t newsev ); """)
>>> ffibuilder.compile(verbose=True)
generating ./_test.py
>>> from _test import ffi
>>> from ctypes.util import find_library
>>> liblept = find_library('lept')
>>> liblept
'liblept.so.5'
>>> lib = ffi.dlopen(liblept)
>>> lib
<Lib object for 'liblept.so.5'>
>>> lib.setMsgSeverity(0)
3
```

Is ocrmypdf/_lib/leptonica.py being regenerated as part of setup.py? setup.py (on its own) should be calling src/ocrmypdf/compile_leptonica.py which recreates that file. You can call it explicitly too.

Incidentally I am planning to spin off my Leptonica bindings as another package, although not before the freeze.

**Comment by spwhitton** [comment]
Thank you for the hints.  I dug a bit deeper and have solved this.

OCRmyPDF's doc build requires OCRmyPDF to already be installed, so for the Debian package build there is a hack.  We make a copy of src/ocrmypdf, patch the version number into that, and point sphinx-build at the copy.

The problem is that in the copy, the dlopen call fails.  That dlopen call does not actually have to be made, though, since the copy is only there for sphinx-build to find the version number.  So I fixed it by patching `from . import leptonica` out of __init__.py in the copy.

**Comment by sangramz** [comment]
Hey @spwhitton  & @jbarlow83 , I'm getting the same Error however I'm not able to fix it. I'll be glad if you can explain it bit in details. when you say " _So I fixed it by patching from . import leptonica out of __init__.py in the copy._"

**Comment by TensorTom** [comment]
I could only get ocrmypdf installed on Arch by using pip. Upon running, I encounter this error. How exactly to apply the patch?

**Comment by jbarlow83** [comment]
The problem here came up while trying to build the ocrmypdf documentation for Debian. If you're not trying to build the documentation, could you open a new issue with more details? (The workaround devised here only works because the documentation doesn't need to run ocrmypdf for real, and implementing it will break the program.)

**Comment by oxplot** [comment]
I get this error when simply running `ocrmypdf` command line program. I did the vanilla `pip install ocrmypdf`.

**Comment by jbarlow83** [comment]
@TensorTom @oxplot 

What is the output of `python3 -c 'ctypes.util.find_library("lept")'` and what version of Leptonica is installed on your systems?

**Comment by oxplot** [comment]
Ah, missed the leptonica dependency. My bad. It's all good now.

**Comment by Gwiazda01** [comment]
Hi,
I have exactly the same issue when trying to import ocrmypdf lib in my project on azure functions.
When i run tesseract -v command azure function's terminal i receive following reluts:
**tesseract 3.04.01
 leptonica-1.78.0
  libjpeg 6b (libjpeg-turbo 1.5.1) : libpng 1.2.50 : libtiff 4.0.8 : zlib 1.2.8**

I tried reinstalling tesseract, explicitly call compile_leptonica.py. None of it worked.
I'm new to linux and python so any suggestions would be appriciated :)

Error message is as below:

`Result: Failure
Exception: error: symbol 'setMsgSeverity' not found in library '<None>': python: undefined symbol: setMsgSeverity
Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 240, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/BlobTrigger/__init__.py", line 9, in <module>
    from ocrmypdf import leptonica
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/ocrmypdf/__init__.py", line 18, in <module>
    from . import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/ocrmypdf/leptonica.py", line 43, in <module>
    lept.setMsgSeverity(lept.L_SEVERITY_WARNING)`

**Comment by jbarlow83** [comment]
What is the output of `python3 -c 'ctypes.util.find_library("lept")'`?

Also please note that if you deploy ocrmypdf in an online environment you will have to use the AGPL license because Ghostscript is AGPL.

**Comment by Gwiazda01** [comment]
I did it as below. Final output is **'liblept.so.5'**

 root@f1328a3a10df:# python3 -c 'ctypes.util.find_library("lept")'
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
 NameError: name 'ctypes' is not defined
 root@f1328a3a10df:# python
 Python 3.6.9 (default, Sep 12 2019, 16:51:25)
 [GCC 6.3.0 20170516] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> import ctypes
 >>> ctypes.util.find_library("lept")
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 AttributeError: module 'ctypes' has no attribute 'util'
 >>> from ctypes import util
 >>> ctypes.util.find_library("lept")
 **'liblept.so.5'**

**Comment by bhavankris** [comment]
> I did it as below. Final output is **'liblept.so.5'**
> 
> root@f1328a3a10df:# python3 -c 'ctypes.util.find_library("lept")'
> Traceback (most recent call last):
> File "", line 1, in
> NameError: name 'ctypes' is not defined
> root@f1328a3a10df:# python
> Python 3.6.9 (default, Sep 12 2019, 16:51:25)
> [GCC 6.3.0 20170516] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import ctypes
> > > > ctypes.util.find_library("lept")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > AttributeError: module 'ctypes' has no attribute 'util'
> > > > from ctypes import util
> > > > ctypes.util.find_library("lept")
> > > > **'liblept.so.5'**

I was getting same error. What I did wrong was; I installed ocrmypdf without installing tesseract. After installing tesseract first, issues got resolved

**Comment by AmirthaKrishnan** [comment]
>> python3 -c 'ctypes.util.find_library("lept")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ctypes' is not defined

How to fix this issue @jbarlow83
