### ISSUE TITLE
Errors on 7.4.0 and last commit

### ISSUE THREAD

**Issue by freestyle68** [jbarlow83/OCRmyPDF#334]
Hi,

**Describe the issue**
With version 7.4.0 (an also last commit) ocrmypdf fail with some PDFs.
No errors on 7.3.1

Various error, logs attached, for version 7.3.1 and last commit  (https://github.com/jbarlow83/OCRmyPDF/tree/089ece2715496b71dcb8f9f59e85cd46915bcd34 )

The command is:
```bash
parallel --tag -j 2 ocrmypdf -l=ita+eng --rotate-pages --deskew '{}' 'output/{}' ::: *.pdf
```

**Example file**
I attacked some failed PDFs. Apart from a personal file, they are from public Enron archive  https://enrondata.readthedocs.io/en/latest/

Please check any or all that apply about the test file:

- [ x] This is the input file
- [x ] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [x ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ x] I am not the copyright holder, but this file is available under a free software license

**System:**

- OS: Ubuntu 18.10
- OCRmyPDF Version: 7.3.1, 7.4.0 and last commit.
-tesseract 4.0.0-115-ge3a3
 leptonica-1.77.0 compiled from source
libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 libopenjp2 2.3.0
Python 3.7.1
ghostscript 9.26
libexempi3 2.4.5
qpdf 8.2.1
jbig2enc 0.29 compiled from source
pngquant 2.5
unpaper 6.1

Thank you

[files.zip](https://github.com/jbarlow83/OCRmyPDF/files/2725620/files.zip)

[log last commit.txt](https://github.com/jbarlow83/OCRmyPDF/files/2725621/log.last.commit.txt)

[log 7.3.1.txt](https://github.com/jbarlow83/OCRmyPDF/files/2725623/log.7.3.1.txt)

**Comment by jbarlow83** [comment]
Thanks for the detailed issue report.

Should be fixed in the next ocrmypdf release. If you force an upgrade to pikepdf 1.0.2 it should work as well.

**Comment by jbarlow83** [comment]
Fixed in v8
