### ISSUE TITLE
Rasterization prevents correct ocr'ing

### ISSUE THREAD

**Issue by MarinaHa** [jbarlow83/OCRmyPDF#336]
**Describe the issue**
When ocr'ing the input file, small bounding boxes are fit to each letter in the gray header 'SAMPLE CONTRACT' (see bboxes_example.png). The cause for this seems to be that OCRMYPDF rasterizes the gray header (see rasterization.png). In our case, this issue could be solved by changing the value of the variable device_idx from 0 to 1 in the _pipeline.py file. 

**To Reproduce**

```bash
ocrmypdf --l eng  --clean --remove-background --force-ocr -k --oversample 300 --pdf-renderer hocr Input_file.pdf output.hocr
```

**Example file**
- [x] This is the input file
- [x] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

**System:**

- OS: Linux
- OCRmyPDF Version: 7.2.1

[Input_file.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2736269/Input_file.pdf)
[bboxes_example](https://user-images.githubusercontent.com/12018380/50824800-d178e180-1337-11e9-98ea-d24ceb5d22aa.png)
[rasterization](https://user-images.githubusercontent.com/12018380/50824846-ec4b5600-1337-11e9-89db-75a67a57b261.png)

**Comment by jbarlow83** [comment]
This is the black and white/grayscale equivalent of issue #305.

However, the file in question does not need OCR. If the goal is to have ocrmypdf run on all input files so that those need OCR can have it applied, `--redo-ocr` is more suitable for that. Is the issue that printed and scanned versions of this document have the same problem when the form is filled out?

**Comment by SpencerRP** [comment]
I'd close this as a duplicate.
