### ISSUE TITLE
Poll for users who work in languages other than English

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#337]
OCRmyPDF currently assumes all documents are English unless told otherwise with the `-l` argument.

For users who work in another language, would you generally prefer OCRmyPDF to assume that the locale set by the operating system is the one you usually work in? Is this how you assumed it would work?

**Comment by femifrak** [comment]
I would not assume ocrmypdf to use the OS language. I am from Germany and pdfs that were scanned are often old (later pdfs are mostly digitally born and don't need ocrmypdf), that means they are often written according to the old orthography which is somehow different from the current OS language orthography.
However, an output or warning message that the used language is different from the OS one could probably avoid disappointments.

**Comment by sojusnik** [comment]
Same here. My locale is German, but my texts are mostly in English. A message that English is being used as default language is sufficient.

**Comment by sniner** [comment]
My language is German and the great majority of the documents I ocr is also German. For this reason I would appreciate if the default langage for OCRmyPDF would be derived from the locale setting.

**Comment by Lin-Buo-Ren** [comment]
Locale: Chinese(Traditional)
Documents: 50% English only 40% chi_tra+eng 10% other combinations
Preference: Current behavior is fine

**Comment by stweil** [comment]
Ideally all compiled default values could be overridden by optional system and user default values – not only the default language. That's a feature which is still missing in Tesseract.

**Comment by willaaam** [comment]
I always give the language anyway, I would find it kind of annoying for it to default to the locale, now behavior is more consistent should someone be running this in containers or something and forgetting to set the language param.
