### ISSUE TITLE
Test failures with v8.0.0

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#339]
I'm seeing some failures in test_main.py with OCRmyPDF v8.0.0 again Debian unstable.  I'd be grateful for any guidance.  Thanks.

    ============================= test session starts ==============================
    platform linux -- Python 3.7.2, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
    rootdir: /tmp/autopkgtest.4xz5Rb/build.7Cj/src, inifile: setup.cfg
    plugins: helpers-namespace-2017.11.11, cov-2.6.0
    collected 193 items
    
    tests/test_hocrtransform.py .                                            [  0%]
    tests/test_lept.py ........                                              [  4%]
    tests/test_main.py ..................................................... [ 32%]
    ...FFFF....s..........sss.............F.....s.........                   [ 60%]
    tests/test_metadata.py .....ssss....ss...                                [ 69%]
    tests/test_multiprocessing.py .                                          [ 69%]
    tests/test_optimize.py ....sss                                           [ 73%]
    tests/test_pdfinfo.py ..............                                     [ 80%]
    tests/test_qpdf.py .                                                     [ 81%]
    tests/test_rotation.py .ss....ssssssssssssssss.                          [ 93%]
    tests/test_tess4.py ......                                               [ 96%]
    tests/test_unpaper.py s..                                                [ 98%]
    tests/test_userunit.py ...                                               [100%]
    
    =================================== FAILURES ===================================
    _______________________ test_non_square_resolution[hocr] _______________________
    
    renderer = 'hocr'
    spoof_tesseract_cache = {'ADTTMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', 'ADT_ARTIFACTS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts',...TS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts', 'AUTOPKGTEST_TMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', ...}
    resources = PosixPath('/tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/resources')
    outpdf = '/tmp/pytest-of-spwhitton/pytest-0/test_non_square_resolution_hoc0/out.pdf'
    
        @pytest.mark.parametrize('renderer', RENDERERS)
        def test_non_square_resolution(renderer, spoof_tesseract_cache, resources, outpdf):
            # Confirm input image is non-square resolution
            in_pageinfo = PdfInfo(resources / 'aspect.pdf')
            assert in_pageinfo[0].xres != in_pageinfo[0].yres
        
            check_ocrmypdf(
                resources / 'aspect.pdf',
                outpdf,
                '--pdf-renderer',
                renderer,
                env=spoof_tesseract_cache,
            )
        
            out_pageinfo = PdfInfo(outpdf)
        
            # Confirm resolution was kept the same
    >       assert in_pageinfo[0].xres == out_pageinfo[0].xres
    E       assert Decimal('200') == None
    E        +  where Decimal('200') = <PageInfo pageno=0 5"x4" rotation=0 res=200x100 has_text=False>.xres
    E        +  and   None = <PageInfo pageno=0 5"x4" rotation=0 res=NonexNone has_text=False>.xres
    
    tests/test_main.py:487: AssertionError
    ----------------------------- Captured stderr call -----------------------------
       INFO -    1: [tesseract] Tesseract cache folder /tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/cache/aspect/__-l__eng__000001.ocr.png__000001__hocr__txt - HIT
       INFO - Optimize ratio: 1.00 savings: 0.0%
       INFO - Output file is a PDF/A-2B (as expected)
    
    _____________________ test_non_square_resolution[sandwich] _____________________
    
    renderer = 'sandwich'
    spoof_tesseract_cache = {'ADTTMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', 'ADT_ARTIFACTS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts',...TS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts', 'AUTOPKGTEST_TMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', ...}
    resources = PosixPath('/tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/resources')
    outpdf = '/tmp/pytest-of-spwhitton/pytest-0/test_non_square_resolution_san0/out.pdf'
    
        @pytest.mark.parametrize('renderer', RENDERERS)
        def test_non_square_resolution(renderer, spoof_tesseract_cache, resources, outpdf):
            # Confirm input image is non-square resolution
            in_pageinfo = PdfInfo(resources / 'aspect.pdf')
            assert in_pageinfo[0].xres != in_pageinfo[0].yres
        
            check_ocrmypdf(
                resources / 'aspect.pdf',
                outpdf,
                '--pdf-renderer',
                renderer,
                env=spoof_tesseract_cache,
            )
        
            out_pageinfo = PdfInfo(outpdf)
        
            # Confirm resolution was kept the same
    >       assert in_pageinfo[0].xres == out_pageinfo[0].xres
    E       assert Decimal('200') == None
    E        +  where Decimal('200') = <PageInfo pageno=0 5"x4" rotation=0 res=200x100 has_text=False>.xres
    E        +  and   None = <PageInfo pageno=0 5"x4" rotation=0 res=NonexNone has_text=False>.xres
    
    tests/test_main.py:487: AssertionError
    ----------------------------- Captured stderr call -----------------------------
       INFO -    1: [tesseract] Tesseract cache folder /tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/cache/aspect/__-l__eng__000001.ocr.png__000001.text__pdf__txt - HIT
       INFO - Optimize ratio: 1.00 savings: 0.0%
       INFO - Output file is a PDF/A-2B (as expected)
    
    ___________________ test_convert_to_square_resolution[hocr] ____________________
    
    renderer = 'hocr'
    spoof_tesseract_cache = {'ADTTMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', 'ADT_ARTIFACTS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts',...TS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts', 'AUTOPKGTEST_TMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', ...}
    resources = PosixPath('/tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/resources')
    outpdf = '/tmp/pytest-of-spwhitton/pytest-0/test_convert_to_square_resolut0/out.pdf'
    
        @pytest.mark.parametrize('renderer', RENDERERS)
        def test_convert_to_square_resolution(
            renderer, spoof_tesseract_cache, resources, outpdf
        ):
            # Confirm input image is non-square resolution
            in_pageinfo = PdfInfo(resources / 'aspect.pdf')
            assert in_pageinfo[0].xres != in_pageinfo[0].yres
        
            # --force-ocr requires means forced conversion to square resolution
            check_ocrmypdf(
                resources / 'aspect.pdf',
                outpdf,
                '--force-ocr',
                '--pdf-renderer',
                renderer,
                env=spoof_tesseract_cache,
            )
        
            out_pageinfo = PdfInfo(outpdf)
        
            in_p0, out_p0 = in_pageinfo[0], out_pageinfo[0]
        
            # Resolution show now be equal
            assert out_p0.xres == out_p0.yres
        
            # Page size should match input page size
            assert isclose(in_p0.width_inches, out_p0.width_inches)
            assert isclose(in_p0.height_inches, out_p0.height_inches)
        
            # Because we rasterized the page to produce a new image, it should occupy
            # the entire page
    >       out_im_w = out_p0.images[0].width / out_p0.images[0].xres
    E       IndexError: list index out of range
    
    tests/test_main.py:522: IndexError
    ----------------------------- Captured stderr call -----------------------------
       INFO -    1: [tesseract] Tesseract cache folder /tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/cache/aspect/__-l__eng__000001.ocr.png__000001__hocr__txt - HIT
       INFO - Optimize ratio: 1.00 savings: 0.0%
       INFO - Output file is a PDF/A-2B (as expected)
    
    _________________ test_convert_to_square_resolution[sandwich] __________________
    
    renderer = 'sandwich'
    spoof_tesseract_cache = {'ADTTMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', 'ADT_ARTIFACTS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts',...TS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts', 'AUTOPKGTEST_TMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', ...}
    resources = PosixPath('/tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/resources')
    outpdf = '/tmp/pytest-of-spwhitton/pytest-0/test_convert_to_square_resolut1/out.pdf'
    
        @pytest.mark.parametrize('renderer', RENDERERS)
        def test_convert_to_square_resolution(
            renderer, spoof_tesseract_cache, resources, outpdf
        ):
            # Confirm input image is non-square resolution
            in_pageinfo = PdfInfo(resources / 'aspect.pdf')
            assert in_pageinfo[0].xres != in_pageinfo[0].yres
        
            # --force-ocr requires means forced conversion to square resolution
            check_ocrmypdf(
                resources / 'aspect.pdf',
                outpdf,
                '--force-ocr',
                '--pdf-renderer',
                renderer,
                env=spoof_tesseract_cache,
            )
        
            out_pageinfo = PdfInfo(outpdf)
        
            in_p0, out_p0 = in_pageinfo[0], out_pageinfo[0]
        
            # Resolution show now be equal
            assert out_p0.xres == out_p0.yres
        
            # Page size should match input page size
            assert isclose(in_p0.width_inches, out_p0.width_inches)
            assert isclose(in_p0.height_inches, out_p0.height_inches)
        
            # Because we rasterized the page to produce a new image, it should occupy
            # the entire page
    >       out_im_w = out_p0.images[0].width / out_p0.images[0].xres
    E       IndexError: list index out of range
    
    tests/test_main.py:522: IndexError
    ----------------------------- Captured stderr call -----------------------------
       INFO -    1: [tesseract] Tesseract cache folder /tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/cache/aspect/__-l__eng__000001.ocr.png__000001.text__pdf__txt - HIT
       INFO - Optimize ratio: 1.00 savings: 0.0%
       INFO - Output file is a PDF/A-2B (as expected)
    
    _______________ test_compression_changed[congress.jpg-lossless] ________________
    
    spoof_tesseract_noop = {'ADTTMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', 'ADT_ARTIFACTS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts',...TS': '/tmp/autopkgtest.4xz5Rb/test-suite-artifacts', 'AUTOPKGTEST_TMP': '/tmp/autopkgtest.4xz5Rb/autopkgtest_tmp', ...}
    ocrmypdf_exec = ['/usr/bin/python3', '-m', 'ocrmypdf']
    resources = PosixPath('/tmp/autopkgtest.4xz5Rb/build.7Cj/src/tests/resources')
    image = 'congress.jpg', compression = 'lossless'
    outpdf = '/tmp/pytest-of-spwhitton/pytest-0/test_compression_changed_congr0/out.pdf'
    
        @pytest.mark.parametrize(
            'image,compression',
            [
                ('baiona.png', 'jpeg'),
                ('baiona_gray.png', 'lossless'),
                ('congress.jpg', 'lossless'),
            ],
        )
        def test_compression_changed(
            spoof_tesseract_noop, ocrmypdf_exec, resources, image, compression, outpdf
        ):
            input_file = str(resources / image)
            output_file = str(outpdf)
        
            im = Image.open(input_file)
        
            # Runs: ocrmypdf - output.pdf < testfile
            with open(input_file, 'rb') as input_stream:
                p_args = ocrmypdf_exec + [
                    '--image-dpi',
                    '150',
                    '--output-type',
                    'pdfa',
                    '--optimize',
                    '0',
                    '--pdfa-image-compression',
                    compression,
                    '-',
                    output_file,
                ]
                p = Popen(
                    p_args,
                    close_fds=True,
                    stdout=PIPE,
                    stderr=PIPE,
                    stdin=input_stream,
                    env=spoof_tesseract_noop,
                )
                out, err = p.communicate()
        
                assert p.returncode == ExitCode.ok, err
        
            pdfinfo = PdfInfo(output_file)
        
            pdfimage = pdfinfo[0].images[0]
        
            if compression == "jpeg":
                assert pdfimage.enc == Encoding.jpeg
            else:
    >           assert pdfimage.enc not in (Encoding.jpeg, Encoding.jpeg2000)
    E           AssertionError: assert <Encoding.jpeg: 2> not in (<Encoding.jpeg: 2>, <Encoding.jpeg2000: 3>)
    E            +  where <Encoding.jpeg: 2> = <ImageInfo '/R8' image 1000x1520 Colorspace.rgb 3 8 Encoding.jpeg 150.0x150.0>.enc
    
    tests/test_main.py:937: AssertionError
    =============================== warnings summary ===============================
    tests/test_main.py::test_redo_ocr
      /usr/lib/python3/dist-packages/sortedcontainers/sortedlist.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
        from collections import Sequence, MutableSequence
      /usr/lib/python3/dist-packages/sortedcontainers/sortedlist.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
        from collections import Sequence, MutableSequence
      /usr/lib/python3/dist-packages/sortedcontainers/sortedset.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
        from collections import MutableSet, Sequence, Set
      /usr/lib/python3/dist-packages/sortedcontainers/sortedset.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
        from collections import MutableSet, Sequence, Set
      /usr/lib/python3/dist-packages/sortedcontainers/sorteddict.py:21: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
        from collections import ItemsView, KeysView, ValuesView, Sequence
      /usr/lib/python3/dist-packages/sortedcontainers/sorteddict.py:21: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
        from collections import ItemsView, KeysView, ValuesView, Sequence
      /usr/lib/python3/dist-packages/sortedcontainers/sorteddict.py:21: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
        from collections import ItemsView, KeysView, ValuesView, Sequence
    
    -- Docs: https://docs.pytest.org/en/latest/warnings.html
    ======== 5 failed, 155 passed, 33 skipped, 7 warnings in 847.31 seconds ========

**Comment by jbarlow83** [comment]
Is pdfminer.six installed?

**Comment by spwhitton** [comment]
Yes.  I think, however, that something is going wrong with loading pdfminer:

    spwhitton@develacc:~>ocrmypdf --version
    Traceback (most recent call last):
      File "/usr/bin/ocrmypdf", line 6, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3126, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3110, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 581, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 898, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 784, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pycryptodome' distribution was not found and is required by pdfminer.six

I note that this problem does *not* occur with OCRmyPDF v7.4.0, so I think the problem is in OCRmyPDF, not in the pdfminer packaging.

**Comment by jbarlow83** [comment]
python3-pdfminer recommends rather than requires python3-crypto...

https://sources.debian.org/src/pdfminer/20181108+dfsg-2/debian/control/#L59

But it's marked as required in pdfminer's setup.py.

**Comment by spwhitton** [comment]
Good catch, but that does not seem to be the root of the problem: I forced installation of python3-crypto and the problems occur in the same way.

**Comment by jbarlow83** [comment]
Digging further it looks like
 https://pypi.org/project/pycryptodome/
is a fork of
 https://pypi.org/project/pycrypto/

Fortunately there is a Debian port of each
 https://packages.debian.org/sid/python3-pycryptodome

So it's actually python3-pycryptodome that pdfminer.six needs.

**Comment by spwhitton** [comment]
Ah, nice find.  It turns out that the Debian package `python3-pycryptodome` [is broken](https://bugs.debian.org/886291).  I don't think that's going to be fixed before our transitions freeze.  So it looks like we'll see OCRmyPDF 7.4.0 in the next release of Debian, and I'll have to get back to you on this bug (please feel free to close it if you're sufficiently convinced this is a Debian-specific problem).

**Comment by jbarlow83** [comment]
If possible I'd prefer if we go with 8.0 and drop pdfminer.six.

I dropped support for Python 3.5 and Tesseract 3 in 8.0, which cleaned up a lot of cruft. The downside is backporting from 8.0 to 7.4 will not be that smooth if it becomes necessary. Other than that the two versions are functionally quite similar.

Apart from #340, the errors in 8.0 seem to be related to pdfminer. 

If pdfminer is dropped, `--redo-ocr` is disabled but everything else works. I set this up for Homebrew because they require a sdist and pdfminer.six doesn't have one. You can patch out pdfminer.six from the dependencies in setup.py.

**Comment by spwhitton** [comment]
The backporting reason is a strong reason to get 8.0 into the next Debian stable, indeed.

I tried dropping pdfminer from setup.py, but left it in the .deb's Depends: field, and then ran the test suite.  All but the #340 test passed, so it seems that OCRmyPDF is not trying to use pdfminer even though the package is installed.  So pending the resolution of #340, we should be good to go.
