### ISSUE TITLE
test_compression_changed failure with v7.4.0 and v8.0.0

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#340]
Hello,

I am seeing `test_compression_changed` in `test_main.py` fail in both v7.4.0 and v8.0.0, when running the tests against Debian unstable.  I've actually already reported this failure in [another issue](https://github.com/jbarlow83/OCRmyPDF/issues/339), but I believe that the underlying cause is independent from the problem discussed in that bug report, because in v7.4.0 this is the only test failure that I see.

    =================================== FAILURES ===================================
    _______________ test_compression_changed[congress.jpg-lossless] ________________
    
    spoof_tesseract_noop = {'ADTTMP': '/tmp/autopkgtest-lxc.xqi13m13/downtmp/autopkgtest_tmp', 'ADT_ARTIFACTS': '/tmp/autopkgtest-lxc.xqi13m13/do...qi13m13/downtmp/test-suite-artifacts', 'AUTOPKGTEST_TMP': '/tmp/autopkgtest-lxc.xqi13m13/downtmp/autopkgtest_tmp', ...}
    ocrmypdf_exec = ['/usr/bin/python3', '-m', 'ocrmypdf']
    resources = PosixPath('/tmp/autopkgtest-lxc.xqi13m13/downtmp/build.wnG/src/tests/resources')
    image = 'congress.jpg', compression = 'lossless'
    outpdf = '/tmp/pytest-of-debci/pytest-0/test_compression_changed_congr0/out.pdf'
    
        @pytest.mark.parametrize('image,compression', [
            ('baiona.png', 'jpeg'),
            ('baiona_gray.png', 'lossless'),
            ('congress.jpg', 'lossless')
            ])
        def test_compression_changed(spoof_tesseract_noop, ocrmypdf_exec,
                                     resources, image, compression, outpdf):
            input_file = str(resources / image)
            output_file = str(outpdf)
        
            im = Image.open(input_file)
        
            # Runs: ocrmypdf - output.pdf < testfile
            with open(input_file, 'rb') as input_stream:
                p_args = ocrmypdf_exec + [
                    '--image-dpi', '150', '--output-type', 'pdfa',
                    '--optimize', '0',
                    '--pdfa-image-compression', compression,
                    '-', output_file]
                p = Popen(
                    p_args, close_fds=True, stdout=PIPE, stderr=PIPE,
                    stdin=input_stream, env=spoof_tesseract_noop)
                out, err = p.communicate()
        
                assert p.returncode == ExitCode.ok, err
        
            pdfinfo = PdfInfo(output_file)
        
            pdfimage = pdfinfo[0].images[0]
        
            if compression == "jpeg":
                assert pdfimage.enc == Encoding.jpeg
            else:
    >           assert pdfimage.enc not in (Encoding.jpeg, Encoding.jpeg2000)
    E           AssertionError: assert <Encoding.jpeg: 2> not in (<Encoding.jpeg: 2>, <Encoding.jpeg2000: 3>)
    E            +  where <Encoding.jpeg: 2> = <ImageInfo '/R8' image 1000x1520 Colorspace.rgb 3 8 Encoding.jpeg 150.0x150.0>.enc
    
    tests/test_main.py:785: AssertionError

I know that v7.4.0 is not the latest upstream release, but based on [discussion in the other bug](https://github.com/jbarlow83/OCRmyPDF/issues/339) it will be the version shipped in the upcoming Debian stable release.  Right now, this test failure is blocking inclusion of OCRmyPDF v7 in that release, so I would be very grateful for any help in resolving it.  Thank you!

**Comment by jbarlow83** [comment]
I can't replicate this although I see it did show up on autopkgtest too. I set up a Docker image of debian:sid, and installed ocrmypdf 7.4 via apt. I download the tests and ran them externally, and these tests passed. I also installed 8.0 in a virtual environment (with pip) over top of this, and these tests pass. Is this valid?

This is not something I'd feel too bad about disabling the failing test. The test supplies a JPEG, asks for lossless PDF/A conversion, and gets a JPEG output. This is surprising because it deviates from past behavior, and I want to understand it for that reason. But it's not necessarily undesirable behavior since preserving an existing JPEG is a lossless operation.

**Comment by jbarlow83** [comment]
Do you think you could extract the output file from that failing test?

Just add:
```diff
diff --git a/tests/test_main.py b/tests/test_main.py
index 79c5074..288b114 100644
--- a/tests/test_main.py
+++ b/tests/test_main.py
@@ -924,6 +924,9 @@ def test_compression_changed(

         assert p.returncode == ExitCode.ok, err

+    from shutil import copyfile
+    copyfile(output_file, '/some/tmp/location.pdf')
+
     pdfinfo = PdfInfo(output_file)

     pdfimage = pdfinfo[0].images[0]
```

**Comment by spwhitton** [comment]
What you describe should be expected to reproduce the failure, indeed.

The actual script that runs the tests on our infra is:

    #!/bin/bash
    
    # ensure that a test suite failure is registered
    set -e
    
    # ensure we test installed version
    mv src/ocrmypdf src/disabled
    
    py.test-3
    
    # comply with rw-build-tree
    mv src/disabled src/ocrmypdf

Perhaps you could try doing this inside your container?  After installing ocrmypdf with apt, you would use `apt-get source ocrmypdf && cd ocrmypdf` and then run the commands in the script above.

Here is the extracted output:  [output.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2751450/output.pdf)  Let me know whether your opinion about disabling the test changes after looking at this.

**Comment by jbarlow83** [comment]
Thanks, I can reproduce it now. 

The issue seems to be introduced by the patch in debian/patches/debian-changes

```diff
+--- ocrmypdf-7.4.0.orig/tests/test_main.py
++++ ocrmypdf-7.4.0/tests/test_main.py
+@@ -595,6 +595,9 @@ def test_tesseract_config_notfound(rende
+ 
+ 
+ @pytest.mark.parametrize('renderer', RENDERERS)
++@pytest.mark.skipif(
++    tesseract.v4(),
++    reason='not valid due to behavior change in Tesseract >= 4.0-rc1')
+ def test_tesseract_config_invalid(renderer, resources, outdir):
+     cfg_file = outdir / 'test.cfg'
+     with cfg_file.open('w') as f:
+@@ -779,13 +782,7 @@ def test_compression_changed(spoof_tesse
+     if compression == "jpeg":
+         assert pdfimage.enc == Encoding.jpeg
+     else:
+-        if ghostscript.jpeg_passthrough_available():
+-            # Ghostscript 9.23 adds JPEG passthrough, which allows a JPEG to be
+-            # copied without transcoding - so report
+-            if image.endswith('jpg'):
+-                assert pdfimage.enc == Encoding.jpeg
+-        else:
+-            assert pdfimage.enc not in (Encoding.jpeg, Encoding.jpeg2000)
++        assert pdfimage.enc not in (Encoding.jpeg, Encoding.jpeg2000)
+ 
+     if im.mode.startswith('RGB') or im.mode.startswith('BGR'):
+         assert pdfimage.color == Colorspace.rgb, \
```

I think this patch can be dropped now - I believe both these changes were added to deal with 6.x issues. For the first change, the test was revised to account for the behavior change in Tesseract 4, and the second patch makes JPEG->JPEG acceptable provided Ghostscript was using JPEG passthrough.

**Comment by spwhitton** [comment]
My apologies for reporting a bug introduced by a Debian-specific change :\

I investigated the git history and determined that this patch was not dropped automatically because I botched the `git merge` of 7.4.0 into my packaging branch.  Thank you for the help.
