### ISSUE TITLE
tag docker images for jbarlow83/ocrmypdf-webservice

### ISSUE THREAD

**Issue by fhoeben** [jbarlow83/OCRmyPDF#349]
At the moment only the `latest` tag is available for jbarlow83/ocrmypdf-webservice on docker hub.

Please tag the versions on release, so they are available for this image just like they are for jbarlow83/ocrmypdf

**Comment by jbarlow83** [comment]
Done - future releases will be tagged. I'm not sure there's an easy way to tag past images....
