### ISSUE TITLE
Using BREW: pdfminer is required for this feature. Your distribution may not have installed it.

### ISSUE THREAD

**Issue by yankun** [jbarlow83/OCRmyPDF#350]
**Describe the issue**
Hi, I freshly installed ocrmypdf via Brew for mac, after running following command:
```bash
ocrmypdf -l deu --sidecar test.txt --clean --redo-ocr input.pdf output.pdf
```
I get following error:

pdfminer is required for this feature. Your distribution may not have installed it.

This seems to be caused by the --redo-ocr command. If I remove this, I will get a different error (that the pdf already contains ocr'ed text).

I tried to install pdfminer and pdfminer.six manually, but the problem remains.

**System:**

- OS: [macOS]
- OCRmyPDF Version: [e.g. v8.1.0]

**Comment by jbarlow83** [comment]
Try `pip3 install --user ocrmypdf pdfminer.six` and putting `$HOME/.local/bin` on your `PATH`. That will install another copy of ocrmypdf, while using Homebrew to provide the dependencies. At least I think that will work.

Homebrew creates a Python virtual environment for Python packages. You could also locate the virtual environment in the Homebrew Cellar and manually install pdfminer.six into that. Of course changing files that Homebrew installs is not supported by homebrew and you will have to redo this.

The fundamental issue is a problem with how the release for pdfminer.six is packaged so I cannot fix it.
