### ISSUE TITLE
Ocrmypdf does not run in MacOS Automator

### ISSUE THREAD

**Issue by MarjaE2** [jbarlow83/OCRmyPDF#353]
**Describe the issue**

When installed using brew.sh, and called using MacOS Automator, OCRmypdf returns a very long error including:

FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'

**To Reproduce**

It fails when running via MacOS Automator using the following instructions:

Application recieves files and folders as input

Run shell script

Shell: /bin/bash

Pass input: as arguments

for f in "$@"
do
	suffix="-OCRA1.pdf"
	base=`basename "$f" .pdf`
	outputfile=$base$suffix
	/usr/local/bin/ocrmypdf --force-ocr --output-type pdfa-1 $f "$outputfile"
done

It runs normally with ocrmypdf -f --output-type pdfa-1 input.pdf output.pdf

... but that is a pain to type every single time with repetitive strain injuries.

**Example file**
Please include an example *input* PDF (or image). The input file is more helpful.

[Notes on Dacian Towns_k2opt.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2886297/Notes.on.Dacian.Towns_k2opt.pdf)

Note that this already contains text-- but it still shows the error.

Please check any or all that apply about the test file:

- [x] This is the input file
- [ ] The file contains no personal or confidential information
- [x] I am the copyright holder for this file
- [x] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

Files that are not free for inclusion in this project are quite welcome, but we like to collect free files for our test suite when possible. Please do *not* submit files with confidential information. At your option you may encrypt files for OCRmyPDF's author only.

**Expected behavior**
A clear and concise description of what you expected to happen. Include screenshots if applicable.

**System:**

- OS: MacOS 10.14.3
- OCRmyPDF Version: can't find this

**Additional context**

**Comment by jbarlow83** [comment]
You probably just need `export PATH=/usr/local/bin:$PATH` in your script. The environment in which Automator runs is not the same as your terminal.

**Comment by MarjaE2** [comment]
Still doesn't work. But it now gives "ERROR: File not found - " instead of naming Tesseract as not found.

**Comment by jbarlow83** [comment]
I'll need all of the output to see what is going on.

**Comment by MarjaE2** [comment]
I now have it working with:

for f in "$@"
do
	suffix="-OCRA1.pdf"
	base=`basename "$f" .pdf`
	outputfile=$base$suffix
	export PATH=/usr/local/bin:$PATH
	/usr/local/bin/ocrmypdf --force-ocr --output-type pdfa-1 $f "$outputfile"
done

I had the error with a more complicated script my brother had suggested:

Javascript

function run(input, parameters) {
	
	var app = Application.currentApplication()
app.includeStandardAdditions = true
var file = app.chooseFile({
   ofType: "pdf",
   withPrompt: "Please select a pdf file:"
})

var inputfilename=file.toString();
var prefix= (inputfilename.split('.'))[0];


var outputfilename=prefix+"-OCRA1.pdf"

return [inputfilename, outputfilename]
}

bash

inputfilename=$0
outputfilename=$1
export PATH=/usr/local/bin:$PATH
export TESSDATA_PREFIX=/usr/local/share/tessdata
/usr/local/bin/ocrmypdf --force-ocr --output-type pdfa-1 "${1}" "${2}"

That one immediately fails with "ERROR: file not found - "

**Comment by MarjaE2** [comment]
P.S. So yes, this seems to be solved after all.
