### ISSUE TITLE
Super new with docker, not sure how to use the image.. 

### ISSUE THREAD

**Issue by abclution** [jbarlow83/OCRmyPDF#355]
**Describe the issue**
I'm new to docker, but I have successfully deployed several other "apps", but I just need a clue on how to use this one.

I have downloaded and have the docker image for OCRmyPDF, but I really don't understand how to use it. I'm super new to docker (Very competent in other virtualization stuff)
Every other docker program I have used is like a whole container, I just don't understand how I can call the dockerized OCRmyPDF from my host machine?

It may be a stupid question but, how should/can I use the most recent OCRmyPDF when its in a docker image? Do I need to attach it to for example another Ubuntu/Debian docker image? I'm just very new to docker.

Oh, and the reason I'm trying to use it in docker is the debian packages are very old, comparatively.

**Comment by jbarlow83** [comment]
Did you read?
https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-the-docker-image

Part of the confusion may be that most of the time, you set up a container as a sort of persistent daemon or lightweight VM. ocrmypdf's Docker is intended to be used as a disposal one-shot command; the container should be removed after use. We're using it as an application packaging format. (You do attach the current directory as a local volume to the Docker image.)

**Comment by abclution** [comment]
Ok, great. Now I get it.
For some reason, I never got that far down on the page. Literally has examples and show exactly what you are saying.
That explains everything! Thank you!

**Comment by Cantello** [comment]
The link on the installation page refers to https://ocrmypdf.readthedocs.io/en/latest/docker, which is not available. Any chance the docker documentation is online somewhere?
