### ISSUE TITLE
Timeout of larger files ( >10Mb) when using Web requests for OCR

### ISSUE THREAD

**Issue by jlazenby99** [jbarlow83/OCRmyPDF#365]
When posting PDF files that are typically > 10 Mb to the Web request route, I am consistently getting a timeout response, as follows;

504 Gateway Time-out
The server didn't respond in time. 

args used on requests;

(none - just default behavior)

I've tried extending the tesseract timeout value - but that's page level - so I guess not the issue.

I suspect it relates to a default HTTP server timeout - is this settable in the docker image?

**To Reproduce**

post a HTTP request with a large PDF file (image only) - example 400+ pages -this is extreme - have had the issue with many documents with > 20 pages...

[many-page-vector.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2961485/many-page-vector.pdf)

**Example file**
Please include an example *input* PDF (or image). The input file is more helpful.

Please check any or all that apply about the test file:

I printed the attached vector file to image (adobe print to PDF) to make it scalar for testing - re-ocring the vector version should show same issue

- [X ] This is the input file
- [ X] The file contains no personal or confidential information
- [ X ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ X] I am not the copyright holder, but this file is available under a free software license

**Expected behavior**
Expect response to be an Image over Text PDF

**System:**

- OS: OCRMYPDF docker - latest version.
- OCRmyPDF Version: most current.

**Additional context**
Works fine for smaller files.

**Comment by jbarlow83** [comment]
You'll have to set the timeout= argument on requests.

**Comment by jbarlow83** [comment]
To clarify my vague comment above: 

Your HTTP POST request will need to have a timeout long enough for the job to complete, for example if you were using requests, `requests.post(...timeout=3600)` to allow an hour.

Alternately, implement some sort of token mechanism were HTTP POST returns a token that can be used in a subsequent HTTP GET. But that is considerably more complex. The webservice as currently implemented is just a toy/demonstration and not suitable for production for many other reasons (e.g. being completely single threaded and using Flask's development mode WSGI server).

**Comment by jlazenby99** [comment]
Thanks very much – I traced it to default HA Proxy timeout – quick solution…
