### ISSUE TITLE
Words are getting clubbed in OCRed PDF

### ISSUE THREAD

**Issue by prabhu92m** [jbarlow83/OCRmyPDF#366]
**Issue Description**

When I used to do OCR a pdf using the OCRmyPDF some of the words are getting clubbed.

**Use this command to reproduce**

```
ocrmypdf --deskew --rotate-pages --rotate-pages-threshold 0.05 --output-type pdf input.pdf output.pdf
```

**Example file**

[input.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2964753/input.pdf)

**Expected behavior**

Check the last paragraph for testing this issue.

**Example words that are clubbed in last paragraph**

- Rentapplicable
- Rentshall
- concessionsorlost
- Tenantfail

**System**

- OS: Ubuntu 18
- OCRmyPDF Version: 6.2.4

**Additional information**

The same pdf is working fine in the pypdfocr but this issue is only raised in the  OCRmyPDF. I also increase the oversample to 300 and 600 dpi, and I also in try the HOCR rendering. But still this issue is exists. I think there may some fine tuning needed in the image conversion using ghost script.

**Additional request**

I can't install the Jbig2 in the ubuntu 18. It returns the below error.

```
Running aclocal
./autogen.sh: 45: ./autogen.sh: aclocal: not found

  Something went wrong, bailing out!
```
I know this is not your part, But have u seen any thing like this and do have any idea to rectify this issue??

Thanks in advance, 
Your doing good.👍

**Comment by jbarlow83** [comment]
PDF has no concept of a "space" or "word" internally. The graphic drawing commands just say "draw these characters at this point". A space is just the absence of drawing. So word segmentation is done by a heuristic algorithm, and every viewer does it differently. Some do it badly, like macOS Preview. There's nothing we can do to help out the PDF viewer in some cases.

Using `--pdf-renderer hocr` and ocrmypdf 8.2.2 got me better results in that your example words seem to work. I attached the output. That option is usually better for English but doesn't work well for all languages. I recommend trying the latest version - the documentation has an update procedure for Ubuntu 18 and CI runs there.

[output.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2965433/output.pdf)

--

For jbig2, you need to install autotools.
https://askubuntu.com/questions/45480/how-do-i-install-aclocal

**Comment by SpencerRP** [comment]
This can maybe be closed
