### ISSUE TITLE
Linux Install Error

### ISSUE THREAD

**Issue by shaunc869** [jbarlow83/OCRmyPDF#37]
When installing on Debian Wheezy I am getting:

$ sudo pip-3.2 install ocrmypdf
Downloading/unpacking ocrmypdf
  Downloading ocrmypdf-3.1.tar.gz
  Running setup.py egg_info for package ocrmypdf
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/shaun/build/ocrmypdf/setup.py", line 7, in <module>
        from collections.abc import Mapping
    ImportError: No module named abc
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/shaun/build/ocrmypdf/setup.py", line 7, in <module>
    from collections.abc import Mapping
ImportError: No module named abc
----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/shaun/build/ocrmypdf
Storing complete log in /root/.pip/pip.log

Any idea how to fix this? Thanks!

**Comment by shaunc869** [comment]
Just in case I used the wrong command I also tried pip and got:

sudo pip install ocrmypdf
Collecting ocrmypdf
  Using cached ocrmypdf-3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-zA6kVz/ocrmypdf/setup.py", line 66
        print(okay_its_optional.format(**locals()), file=sys.stderr)
                                                        ^
    SyntaxError: invalid syntax

**Comment by jbarlow83** [comment]
pip-32 looks like Python 3.2 which is not supported.
The second error was running python 2.7, hence it finds a syntax error on
print as a function.

There's probably a backport for Python 3.4 or 3.5 to wheezy.

**Comment by jbarlow83** [comment]
Added an explicit test for python 3.4 + in setup.py and made setup.py somewhat py2.7 friendly.
