### ISSUE TITLE
feature request: add progress for long-running stuff

### ISSUE THREAD

**Issue by icegood** [jbarlow83/OCRmyPDF#370]
Please, consider adding progress for long-running stuff.

**Comment by jbarlow83** [comment]
I'd very much like to do this but the execution state is locked up inside the library (ruffus) for I use for multiprocessing. At some point I will overhaul it, probably changing to a new library in the process.

**Comment by jbarlow83** [comment]
This is now being worked on

**Comment by jbarlow83** [comment]
In next release

**Comment by jbarlow83** [comment]
Added in v9
