### ISSUE TITLE
Improve OCR of highlighted text

### ISSUE THREAD

**Issue by 545ch4** [jbarlow83/OCRmyPDF#371]
I tried to understand the ```ocrmypdf``` pipeline, but didn't find a correct place to put my suggestion... So, this more of a feature request then. I think it is related to #289.

I have to OCR dozens of manually highlighted PDFs (e.g. using a color highlighter, see attachments) and came across an issue when the corresponding highlighting color is slightly darker than usual. ```ocrmypdf```will not correctly OCR text of those highlighted parts.

As there is no way to intervene or modify the way ```ocrmypdf``` is preprocessing the PDF for OCR, I did a dirty work-around, just to check if things my could be improved:

0. Wrote an document ([highlightedtext.txt](https://github.com/jbarlow83/OCRmyPDF/files/2992972/highlightedtext.txt)) and scanned it [highlightedtext.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2992975/highlightedtext.pdf)
1. To preprocess the file with ```ocrmypdf``` (just to unskew etc.) using:
`ocrmypdf -l eng --force-ocr --optimize 0 --clean-final --tesseract-timeout=0 --deskew --rotate-pages --output-type pdf highlightedtext.pdf highlightedtext_deskew.pdf`
2. To convert the PDF to actual images for tesseract and in my case remove all color information as all text relevant for OCR is black (printed copies):
`convert -density 300 highlightedtext_deskew.pdf -density 300 -fuzz 50% +opaque black -fill white -threshold 99% highlightedtext_deskew.png`
3. Collect all images and do tesseract:
`ls -1 highlightedtext_deskew*.png > highlightedtext_deskew.txt`
`tesseract -l eng --dpi 300 highlightedtext_deskew.txt highlightedtext_deskew_OCR pdf`
4. Join OCR-ed PDFs and the original PDF
`pdftk highlightedtext_deskew.pdf multibackground highlightedtext_deskew_OCR.pdf output highlightedtext_OCR_better.pdf` ([highlightedtext_OCR_better.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2992973/highlightedtext_OCR_better.pdf))

For comparison I did use the ```ocrmypdf``` tool as intended:
`ocrmypdf -l eng --force-ocr --optimize 1 --mask-barcodes --remove-background --clean --clean-final --deskew --rotate-pages --output-type pdfa highlightedtext.pdf highlightedtext_OCR_ocrmypdf.pdf` ([highlightedtext_OCR_ocrmypdf.pdf](https://github.com/jbarlow83/OCRmyPDF/files/2992974/highlightedtext_OCR_ocrmypdf.pdf))

When comparing the two OCR-ed PDFs (removing spaces etc.) ... well it's obvious.
`diff <(pdftotext -q highlightedtext_OCR_better.pdf - | tr -d ' \n\r\t\f') <(cat highlightedtext.txt | tr -d ' \n\r\t\f')`
vs.
`diff <(pdftotext -q highlightedtext_OCR_ocrmypdf.pdf - | tr -d ' \n\r\t\f') <(cat highlightedtext.txt | tr -d ' \n\r\t\f')`

**Could you please extend ```ocrmypdf``` in a way that it is possible to inject some preprocessing cmds before everything gets OCR-ed?**

**Comment by jbarlow83** [comment]
`ocrmypdf --threshold` should improve thresholding on highlighted text, although it won't necessarily do better than a pipeline you've tuned for your particular files.

I do want to open up the pipeline for customization, but that's not so simple. The current pipeline package (ruffus) is not re-entrant and not that well maintained so I'll need to change pipe providers or fork and fix it; either way it's a fairly major overhaul.
