### ISSUE TITLE
 unable to find /Root dictionary

### ISSUE THREAD

**Issue by AnotherSuggestion88** [jbarlow83/OCRmyPDF#376]
Just tried to use it on two different MacOS' and it returned the same error message. Tried updating, uninstall & reinstalling, running in sudo mode and all returned the same error:
  ERROR - /tmp/com.github.ocrmypdf.vpnzmltu/origin.repaired.pdf (offset 10104933): unable to find /Root dictionary

Any idea would be beneficial

**Comment by jbarlow83** [comment]
Most likely the input file is not a PDF or corrupt.

**Comment by AnotherSuggestion88** [comment]
Turns out that it was actually corrupted! cheers.
