### ISSUE TITLE
Ubuntu 18.04 no rescent version available

### ISSUE THREAD

**Issue by zbgns** [jbarlow83/OCRmyPDF#377]
I installed ocrmypdf 6.1.2 version from standard repository:
```bash
sudo apt-get install ocrmypdf
```
however I'm not able to install the latest version.

I followed the installation instruction, but after:
```bash
pip3 install --user ocrmypdf
```
I have following message:
```bash
Requirement already satisfied: pikepdf in /usr/local/lib/python3.6/dist-packages (1.1.0)
Requirement already satisfied: defusedxml>=0.5.0 in /usr/lib/python3/dist-packages (from pikepdf) (0.5.0)
Requirement already satisfied: lxml>=4.0 in /usr/local/lib/python3.6/dist-packages (from pikepdf) (4.3.3)
```
There is still 6.1.2 version.

```bash
zbgns@zbgns:~$ ocrmypdf --version
6.1.2
```
I installed more resent qpdf version 8.4.0

Any suggestions, how to solve this issue would be highly appreciated.

**System:**

- OS: [Ubuntu 18.04]
- OCRmyPDF Version: [6.1.2]

**Comment by jbarlow83** [comment]
See here
https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-the-latest-version-on-ubuntu-18-04-lts

in particular, you may have not set the PATH environment variable.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by zbgns** [comment]
The PATH variable has been set like in the installation instruction, but it doesn't help.
there is still:

```zbgns@zbgns:~$ pip3 install --user ocrmypdf
Requirement already satisfied: ocrmypdf in /usr/lib/python3/dist-packages (6.1.2)
```
Is there any alternative way to install some newer version?

**Comment by jbarlow83** [comment]
There are detailed installation instructions for multiple platforms.

It is not possible to change the version Ubuntu provides. They only update old releases like 18.04 at their discretion.

If ocrmypdf was successfully installed with `pip install --user` then 

```
$HOME/.local/bin/ocrmypdf --version
```

should report the latest version.

**Comment by zbgns** [comment]
Unfortunately, after:
 `$HOME/.local/bin/ocrmypdf --version`
There is message that there is no such file or folder.

**Comment by zbgns** [comment]
OK, I managed to install actualization by following [instruction on installation of HEAD revision from sources](
https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-head-revision-from-sources)
Thank you for your time and for the great program
