### ISSUE TITLE
Skip text removes text from output file

### ISSUE THREAD

**Issue by shaunc869** [jbarlow83/OCRmyPDF#38]
I might be reading this wrong, but when I run skip-text on this PDF:

https://www.dropbox.com/s/dt0d3wpwb6ovngi/OTII_PressRelease-200110301.pdf?dl=0

Which has text in it the output file looks the same except the searchable text is now gone, what am I doing wrong? Thanks!

**Comment by jbarlow83** [comment]
Try pulling the latest version in the master branch to see if a recent fix
helps that case.

**Comment by jbarlow83** [comment]
Should be officially fixed in v3.1.1
