### ISSUE TITLE
[Feature request] add "cut pages vertically

### ISSUE THREAD

**Issue by Nokia808** [jbarlow83/OCRmyPDF#380]
Hi.

There are certain PDF (especially scanned PDF) prepared so that each faced 2 pages of paper book appeared per single PDF page. For example PDF page 1 contained paper page 1 & 2 (twin pages being side to side).

Can you kindly add option allow user to cut such PDF pages vertically at middle so that the output is single (not multiple) PDF that each of it's page contain single paper page of original book as if it scanned each single paper page individually ?

If you accept to add this option please make for it a sub-option to make arrangement "right to left" so that Arabic & Hebrew peoples make benefit from this new option. Let make default arrangement "left to right" & add sub-option if used will make arrangement right to left. For Arabic & Hebrew if we use default left to right arrangement, then resulted PDF will be as if original paper book scanned as follow: page 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, ......... & this will be useless & in this case we need right to left sub-option.

I'm already asked for this feature Scan2PDF developer & he added it since long time & his application used same backend that your application used "unpaper". However, I remove scan2pdf because it is not working well unless with PDF generated by it not by other application & it freeze with multi-pages PDF of huge number of pages ...... Your application seem to be not suffering from such limitations ......

**Comment by DesWurstes** [comment]
Dupe #330 ?

**Comment by SpencerRP** [comment]
Definitely a duplicate, close it.
