### ISSUE TITLE
[Feature request] Add "centralize contents" option

### ISSUE THREAD

**Issue by Nokia808** [jbarlow83/OCRmyPDF#381]
Hi.
There are many scanned PDF books scanned in such a way that contents of a page (say page X) is not in center of that page so that white margins on left & right not equal (let we say white margin area on left double or triple that on right of that page X). While next page (let we call it page Z) has same OR the white margin area on right is the largest one being double or triple that of right side of page Z.
It will be useful in the above case to have an option to "centralized" the contents of page(s) so that white empty margin area on left sector of page(s) being = to that on right sector of that page(s)
Best.

**Comment by jbarlow83** [comment]
Apologies for slow response.

You can do this using the `--unpaper-args` ocrmypdf.
See here:
https://ocrmypdf.readthedocs.io/en/latest/advanced.html#control-of-unpaper
You may need to look at unpaper's documentation to decide what you want.
It's unpaper's "mask centering" features that deal with centering content.

ScanTailor can also do this but it is fairly manual and takes about 30s/page.
