### ISSUE TITLE
Feature request: linearize pdf (fast web view)

### ISSUE THREAD

**Issue by j3ssass** [jbarlow83/OCRmyPDF#385]
First things first: GREAT work. 

Just a tiny feature request: current output does not linearize the pdf.

I did hardcode linearize=True in optimize.py for my use case. Not sure if there is any reason not to linearize (in that case maybe add a command line parameter)

Thanks again for the outstanding job!

Sven

**Comment by jbarlow83** [comment]
Linearizing can increase file size slightly, and is not compatible with PDF/A (or more specifically a conforming reader is supposed to ignore linearization in PDF/A mode, and Ghostscript erases it).

It could be implemented for `--output-type pdf`.

**Comment by j3ssass** [comment]
I was not aware of this fact. So it is not forbidden, but the reader shall ignore it is what I understood. Furthermore Google tells me some readers (Acrobat) actually use it for PDF/A aswell.

a.) So for pdf it makes sense I guess. 
b.) For the other formats it **could** be an option `--force-linearize` (but should not be default) 

I'm not sure why linear pdfs should not be used - I can only assume, that it is not safe to display page 1 while the complete pdf has not yet been loaded (because.. well somehting later changes the content/layout/whatever on the first page). 

I guess you'll make the right call as you are the guru!

Thanks again so much for your really cool work.

**Comment by jbarlow83** [comment]
Added for v9
