### ISSUE TITLE
ERROR - Ghostscript text extraction failed

### ISSUE THREAD

**Issue by nemobis** [jbarlow83/OCRmyPDF#386]
OCR of the attached PDF fails with ERROR - Ghostscript text extraction failed:
```
ocrmypdf 10.1086%2Fahr%2F28.2.293.pdf /tmp/out.pdf
  ERROR - (Ghostscript text extraction failed
/tmp/com.github.ocrmypdf.v0br8ycq/origin.repaired.pdf
   **** Error reading a content stream. The page may be incomplete.
               Output may be incorrect.
   **** Error reading a content stream. The page may be incomplete.
               Output may be incorrect.
   **** Error: File did not complete the page properly and may be damaged.
               Output may be incorrect.
Error: /rangecheck in /--pdfshowpage_finish--
Operand stack:
   --dict:9/17(L)--   --nostringval--   -1   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   pdfshowpage_finish   --nostringval--   2   %stopped_push   --nostringval--   pdfshowpage_finish   pdfshowpage_finish   false   1   %stopped_push   2046   1   3   %oparray_pop   2045   1   3   %oparray_pop   2025   1   3   %oparray_pop   2026   1   3   %oparray_pop   pdfshowpage_finish   pdfshowpage_finish   2   1   2   pdfshowpage_finish   %for_pos_int_continue   2029   1   7   %oparray_pop   pdfshowpage_finish   pdfshowpage_finish
Dictionary stack:
   --dict:960/1684(ro)(G)--   --dict:1/20(G)--   --dict:84/200(L)--   --dict:84/200(L)--   --dict:133/256(ro)(G)--   --dict:310/450(ro)(G)--   --dict:32/32(L)--   --dict:6/9(L)--   --dict:8/20(L)--
Current allocation mode is local

GPL Ghostscript 9.26: Unrecoverable error, exit code 1
)
```
(The PDF is public domain in USA because it was published before 1924.)

**Expected behavior**
I'm not sure. Maybe it's safer to just give up, as currently happens. However, okular seems to have no problem in reading this PDF, so maybe an alternative route is possible. pdf2djvu also manages to read and convert this PDF correctly (pdf2djvu 0.9.11 + DjVuLibre 3.5.27 + Poppler 0.67.0).

**System:**

- OS: Linux Fedora 29
- OCRmyPDF Version: 7.4.0

[10.1086%2Fahr%2F28.2.293.pdf](https://github.com/jbarlow83/OCRmyPDF/files/3176268/10.1086.2Fahr.2F28.2.293.pdf)

**Comment by jbarlow83** [comment]
Interesting. I think this is a combination of the PDF content stream being not quite right and Ghostscript's text extraction driver tripping over it.

It so happens that if you rewrite the file with Ghostscript it work will. 
```
gs -q -sDEVICE=txtwrite -dTextFormat=0 -o out.txt out.pdf # <-- fails
gs -q -sDEVICE=pdfwrite -o out.pdf 10.1086.pdf # <-- works
gs -q -sDEVICE=txtwrite -dTextFormat=0 -o out.txt out.pdf # works
```

ocrmypdf works after rewriting too.

I suggest reporting this issue to bugs.ghostscript.com (it's independent of ocrmypdf).

**Comment by jbarlow83** [comment]
The fact that other viewers handle it well - I can add Acrobat DC to the list - seems to suggest it's their issue. If you don't mind I'll close this because I can't do much about it. I'm planning to eventually drop the use of Ghostscript for text extraction in ocrmypdf, since it's currently duplicated alongside with pdfminer; because of that I don't think I'll try to find any short term workarounds. Good find though.
