### ISSUE TITLE
webservice.dockerfile uses ocrmypdf from apt-get, not pip

### ISSUE THREAD

**Issue by ilexius** [jbarlow83/OCRmyPDF#388]
**Describe the issue**
When using the webservice dockerfile, the system-installed ocrmypdf version is used, not the upgraded one from pip (that is installed in the venv)

**To Reproduce**
Run
`docker run -p 5000:5000 jbarlow83/ocrmypdf-webservice`
in one terminal. In another terminal run
`curl -F "params=-version" -F "file=@any-pdf-file.pdf" http://localhost:5000`

Output is:
```
  DEBUG - ocrmypdf 6.1.2
  DEBUG - tesseract 4.0.0-beta.1
  DEBUG - qpdf 8.0.2
  DEBUG - PyMuPDF not installed

```
**Example file**
Not applicable, you can use any file to test this.

**Expected behavior**
Should use ocrmypdf 7.4.0 (the version from pip)

**System:**
Docker for Windows

**Additional context**
This can be fixed by changing the last line in webservice.dockerfile to:
`ENTRYPOINT ["/bin/bash", "-c", ". /appenv/bin/activate && python3 /application/webservice.py"]`

**Comment by jbarlow83** [comment]
Thanks for reporting, that is... not how it should be.

I suggest using the new and improved `ocrmypdf-alpine` package instead. The `ocrmypdf-polyglot` and `ocrmypdf-webservice` images are deprecated.

**Comment by ilexius** [comment]
Thanks, I did not know this. And keep up the amazing work, this is one of the most useful Open Source projects we use! Thank you very much for this amazing piece of software!

**Comment by jbarlow83** [comment]
ocrmypdf-webservice is now marked as deprecated to the extent that Docker Hub allows that.
