### ISSUE TITLE
automatic language detection

### ISSUE THREAD

**Issue by enefem** [jbarlow83/OCRmyPDF#39]
woukd be great if ocrmypdf would automatically recognize the language used in a pdf and used it

**Comment by enefem** [comment]
langdetect python project may help for this

**Comment by jbarlow83** [comment]
This can't be done in advance, unfortunately. langdetect needs a sample of text after OCR has been performed – it cannot look at an arbitrary image and guess the language.

Tesseract also doesn't have that capability either. It assumes English unless told otherwise.

If you know your documents contain multiple languages you can issue specify all languages that may appear, e.g. `ocrmypdf -l eng -l deu ...` for a document that contains English and German.

**Comment by enefem** [comment]
Is it not possible to Ocr part of the pdf using english for getting an input to langdetect and then do the full scan afterwards. I know this is slower, but if I want to plug the tool to automatically process all my documents (each with different languages), I won't mind sacrificing performance for automation.

I was afraid using multiple languages will reduce the precision of the scan. Is this not the case?

**Comment by jbarlow83** [comment]
I think what you describe is not that different from just giving Tesseract the list of possible languages. Tesseract only uses language to help when the scan quality is poor and letters are ambiguous – then it will use the dictionary to pick the most likely word. If you give it a good scan and tell it the wrong language (but right alphabet) it will get most things right. For example, telling it to look for French in a good quality English document will get you English. (I don't exactly what Tesseract does internally, but that is my observation of how it behaves.)

It's possible that this would get an improvement for *some* documents:
* Tell ocrmypdf/tesseract to do OCR on all languages that might be present ( -l eng -l deu -l fra ...)
* Run langdetect to find the best language
* Tell ocrmypdf/tesseract to redo OCR with only the language found by langdetect

However, that will not work for multilingual documents unless langdetect can reliably handle multilingual text.

**Comment by jbarlow83** [comment]
Depending on your situation you might be get better results by training Tesseract on the specific fonts in use. You can even create a virtual language to deal with your specific documents. However, this process is very tedious.

**Comment by nemobis** [comment]
I found that the CPU time taken by ocrmypdf (7.0.3, with tesseract 3.04.01 and qpdf 6.0.0) is directly proportional to the number of languages I specify, so I cannot afford listing even a small number of languages. This might be different with tesseract 4 based on stweil's comment in the issue above.

I don't necessarily need tesseract to be run with the "best" language, but I'd like to avoid spectacular failures (like it presumably is to run English on Japanese text). Then I can try other languages on the remaining PDFs.

From MeanTextConf() in TessBaseAPI and https://github.com/tesseract-ocr/tesseract/wiki/APIExample#result-iterator-example I understand it's possible to get the average confidence level of the OCR, which could be enough in many cases. I also see warnings like
> WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR

which might be enough or not to identify some cases.

**Comment by stweil** [comment]
You could also try `tesseract -l osd --psm 0 IMAGE -`. Does it correctly detect Latin or Japanese script for your images?

**Comment by Juanfree** [comment]
Hi,

Exist some way for detect the language before to run Tesseract, or other tool in order to perform this kind of detection?

Thanks.

**Comment by jbarlow83** [comment]
@Juanfree You can use the command someone mentioned above to detect the type of script 
```
tesseract -l osd --psm 0 IMAGE -
```

If you know that the document will be one of several languages you can specify multiple ones: `-l eng+fra` for English and French.

**Comment by Juanfree** [comment]
Hi, If I do not know the language previously then how could do it for now the language?

This kind of process should works?

* Tell ocrmypdf/tesseract to do OCR on all languages that might be present ( -l eng -l deu -l fra ...)
* Run langdetect to find the best language
* Tell ocrmypdf/tesseract to redo OCR with only the language found by langdetect

Thanks in advance

**Comment by jbarlow83** [comment]
If you use that command line Tesseract will attempt to identify the script.

```
tesseract -l osd --psm 0 tests/resources/typewriter.png -
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 753
Warning. Invalid resolution 0 dpi. Using 70 instead.
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 10.45
Script: Latin
Script confidence: 75.33
```

From the script you can at least narrow the set of languages. Do not try to run OCR on all possible languages. It takes about N times as long for N languages and quality will drop.
