### ISSUE TITLE
Allow to only specify the input.pdf

### ISSUE THREAD

**Issue by sojusnik** [jbarlow83/OCRmyPDF#390]
It would be useful, if an appendix like "_ocr" would be attached to the ocred file automatically, if only the input.pdf was specified. So `ocrmypdf input.pdf` would then produce an `input_ocr.pdf` in the same directory.

**Comment by jbarlow83** [comment]
You can do a tiny bit of shell scripting for that:

```bash
file=input ; ocrmypdf ${file}.pdf ${file}_ocr.pdf
```

There's examples in the documentation of using e.g. GNU parallel if you want this for a lot of files at once. https://ocrmypdf.readthedocs.io/en/latest/batch.html#batch-jobs

**Comment by sojusnik** [comment]
@jbarlow83 Thanks for the hint! Thought that it would be also useful to have it without scripting, like f.i. [pdfsandwich](http://www.tobias-elze.de/pdfsandwich/) does.
