### ISSUE TITLE
Option to skip certain pages

### ISSUE THREAD

**Issue by sojusnik** [jbarlow83/OCRmyPDF#391]
From time to time I have pdfs with a cover (normally at the beginning and sometimes at the end too), that shouldn't be ocred and processed (by `unpaper`). A corresponding option would come in handy and would also serve as a workaround for pdfs not being ocred due to a troublesome page.

The `unpaper` options, like `-n sheet-range` or `-start sheet`, don't have any effect.

**Comment by jbarlow83** [comment]
`unpaper` gets shown each page one at a time, so options that are based on the page number won't have any effect. (If that's what those do.)

Will `--redo-ocr` help? That should prevent existing OCR, if the issue is that those pages have OCR already. Or is it just non-OCRable graphics?

**Comment by sojusnik** [comment]
It's the latter.

Seems that [your suggestion](https://github.com/jbarlow83/OCRmyPDF/issues/392#issuecomment-496831540) could solve this?

**Comment by jbarlow83** [comment]
Added in v9 (`--pages`)
