### ISSUE TITLE
--user-words - don't warn in Tesseract >= 4.1

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#404]
As far as I understand the release notes of tesseract 4.1, whitelists and blacklists are now supported again. Could you therefore enable --user-words again, please?
Thanks, Femi

**Comment by jbarlow83** [comment]
`--user-words` is always forwarded to Tesseract so it will work fine right now, you'll just see a warning.

I'll change it so the warning is only shown for tesseract 4.0.

**Comment by femifrak** [comment]
ah, okay. Thanks!
