### ISSUE TITLE
How can I read the PDF from ocrmypdf with identity H encoding?

### ISSUE THREAD

**Issue by charu0101** [jbarlow83/OCRmyPDF#405]
I am not able to read the pdf generated from OCRMYPDF .
I had run the ocrmypdf and it has successfully ocred the scanned pdf(non-searchable).
but i am not able to read it through PyPDF2.
It gives some encoding error.
" UnicodeEncodeError: 'charmap' codec can't encode character '\\u02dd' in position 1779: " 
Then I checked the properties of the converted PDF, it is "Identity-H"

**Comment by jbarlow83** [comment]
PyPDF2 is incomplete, unmaintained and generally very fragile. If you're trying to use its text extraction feature, that is broken by design and only works on a narrow set of text encodings.

pdfminer.six is more likely to succeed at text extraction. My pikepdf library is more likely to succeed anything else you might use PyPDF2 for.

You could also use the `ocrmypdf --sidecar` feature to generate a companion text file of OCR text.

**Comment by charu0101** [comment]
Thankyou for your reply.
I want to run text extraction on the pdf file generated from ocrmypdf.
How can I read that in python? as its encoding is Identity-H?
Will pdfminer do that?

**Comment by jbarlow83** [comment]
pdfminer.six should do it.

Or poppler's `pdftotext`.

**Comment by charu0101** [comment]
I have tried the following code. This is reading the text but of 1st page only. I am using Python 3.6

# Extract Text from PDF with Python 3.7 and PDFMiner
from pdfminer.pdfinterp import PDFResourceManager,PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from io import BytesIO
def pdf_to_text(path):
    manager = PDFResourceManager()
    retstr = BytesIO()
    layout = LAParams(all_texts=True)
    device = TextConverter(manager, retstr, laparams=layout)
    filepath = open(path, 'rb')
    interpreter = PDFPageInterpreter(manager, device)
    for page in PDFPage.get_pages(filepath, check_extractable=True):
        interpreter.process_page(page)
        text = retstr.getvalue()
        filepath.close()
        device.close()
        retstr.close()
        return text

if __name__ == "__main__":
    text = pdf_to_text("PATH TO PDF TO BE READ")
    print(text)

**Comment by jbarlow83** [comment]
pdfminer installs a script called that `pdf2txt.py` that should do what you need.
