### ISSUE TITLE
   What do I need to do if I want to get an editable PDF file, is this project supported

### ISSUE THREAD

**Issue by Crescentz** [jbarlow83/OCRmyPDF#406]
What do I need to do if I want to get an editable PDF file, is this project supported

**Comment by jbarlow83** [comment]
In what way do you want to edit the PDF? The PDF format is not really amenable to editing overall but it is possible.

**Comment by jbarlow83** [comment]
Please open a new issue, and include all of the information requested in the issue template. I can't make sense of what you're asking without this information.
