### ISSUE TITLE
Ghostscript error at the final step

### ISSUE THREAD

**Issue by Fifis** [jbarlow83/OCRmyPDF#407]
I am trying to use ocrmypdf 8.3.0 on Arch Linux to OCR the PDF I got by converting ScanTailor PNG’s or TIFF’s into a PDF using ImageMagick. The file properties are:
```
Title:          Newey
Producer:       C:\Program Files\ImageMagick-7.0.5-Q16\\index.html
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          36
Encrypted:      no
Page size:      378.72 x 612.54 pts
Page rot:       0
File size:      5375775 bytes
Optimized:      no
PDF version:    1.3
```
The command I am running is a simple

```bash
ocrmypdf -j3 -v1 Efficient_Estimation_of_Models_with_Conditional_Moment_Restrictions.pdf Newey.pdf
```

**Example file:**
https://www.dropbox.com/s/4z3cq62yduc2uhu/Newey-1993-Efficient_Estimation_of_Models_with_Conditional_Moment_Restrictions.pdf?dl=0

The errors I am getting are
```
  ERROR - GPL Ghostscript 9.27: UTF16BE text string detected in DOCINFO cannot be represented in XMP for PDF/A1, discarding DOCINFO
**** Error: The Page /Contents array contains an element which is not a stream
            This page will not display correctly

GPL Ghostscript 9.27: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

**** Error: The Page /Contents array contains an element which is not a stream
            This page will not display correctly
(same error many times)
```

The full verbose output is here:
https://pastebin.com/xaUxvXsz

I can’t even find a single mentioning of this error message on Google. What could be wrong?

**Comment by jbarlow83** [comment]
`img2pdf` generally does a better job of image to PDF than ImageMagick. You could try use it to generate your PDF.

Also see if ocrmypdf 8.3.2 makes a difference. I can't reproduce this in ocrmypdf 8.3.2.

The error message about dropping DOCINFO is innocuous.

Page /Contents is concerning, but I can't reproduce that. What platform is this?

**Comment by Fifis** [comment]
Thank you, the version 8.3.2 works flawlessly. It is just the maintainer of Arch Linux who has not updated the AUR from 8.3.0.
