### ISSUE TITLE
pdf with only text layer

### ISSUE THREAD

**Issue by Crescentz** [jbarlow83/OCRmyPDF#408]
`ocrmypdf -l chi_sim --sidecar text.txt testchi.pdf o.pdf`

With this command, I can  get the text of the ocr, and the double layer of pdf, a picture layer, a transparent text layer. But all I wanted was pdf with a text layer, and it wasn't transparent. What should I do？

now i get o.pdf like this
![image](https://user-images.githubusercontent.com/35165563/61862621-c61a8b80-af00-11e9-90bd-7a4b8ce9a163.png)
 All I wanted was text in original position，like this，but the font was transparent when I deleted the picture layer
![image](https://user-images.githubusercontent.com/35165563/61862801-0b3ebd80-af01-11e9-99bb-bb0c982e8b5b.png)
`--sidecar text.txt `
I know you can get the text.txt through the above, but I'm trying to get the pdf in the original position

**Comment by jbarlow83** [comment]
This is the way Tesseract (the OCR engine) is designed to work. It does not have the ability to determine what font was used and map characters back to that. Since this is Tesseract's behavior I cannot change it.

As long as you can select the text, and copy and paste it, it is working correctly.

**Comment by Crescentz** [comment]
Yes, the text was available and copied. I mean, in ‘ocrmypdf’ , whether it displays text, such as red or black, can be seen in pdf.

**Comment by jbarlow83** [comment]
If you're looking for information about the exact position of text within the PDF, 

You could also use `ocrmypdf --pdf-renderer hocr -k` and check the temporary folder whose location will be printed when the program exits. In this folder there will be files with the extension `.hocr`. These HTML-like files contain the position of all OCR text.

You could use pdfminer.six. This will find original text and OCR text.

**Comment by maralamir** [comment]
Hi, 
Thank you so much for a great tool.
Is there a way to have the OCRed text or the drawn bbox visible in the rendered layer? I can see the bbox or the visible text in the *.text.pdf file. But once the image is grafted and the final rendered layer is generated, the visible OCRed text or the drawn bbox is not shown.

**Comment by jbarlow83** [comment]
You can modify hocrtransform.py and use `--pdf-renderer hocr` to generate visible text. It will be done in Arial and can be weirdly distorted. This only works for the Latin alphabet however.

**Comment by maralamir** [comment]
Thank you for your prompt reply. 
I have already modified the hocrtransform.py file and I can generate the ocr_hocr.pdf with visible OCRed text and bbox drawn. However, this file does not include the original image on top. I want to see the original image (scanned pdf) and the OCRed text both in the same pdf file. As far as I have studied the source code , the next step happens at the "_graft.py" file. The "ocr_hocr.pdf" layer is used as the "pdf_text_contents" and the original "input.pdf" file is used as the "pdf_base". How can I make the final output "graft_layers.pdf" to include both OCRed text(visible) and the original image? Thanks.

**Comment by jbarlow83** [comment]
The image is drawn on top of the text, hiding the text. You could reverse the order in _graft.py around line 147 line so:

```diff
-    base_page.page_contents_add(new_text_layer, prepend=True)
+    base_page.page_contents_add(new_text_layer, prepend=False)
```

**Comment by maralamir** [comment]
That worked! Thank you so much!!
