### ISSUE TITLE
pagesize is altered by ocrmypdf

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#41]
Hi,

thank you very much for this really decent software!

When i run ocrmypdf 3.1 on an pdf which contains pages in A5 size (148 x 210 mm), the output page size is not the same (125 x 210 mm).

Regards,

Femi

**Comment by jbarlow83** [comment]
You're welcome.

There's an open issue with how v3.1 calculates the effective DPI of an image if the page contains any cropped images or if the image is rendered within the PDF in an unusual way (anything other than a full page image causes trouble). You can override it by setting it to oversample the image (`--oversample 400`). 

The HEAD revision contains a fix for a related issue if a document contains mixed page sizes.

**Comment by femifrak** [comment]
ver. 3.1.1 alone does not help. Oversampling helps. Thanks.

**Comment by jbarlow83** [comment]
I implemented a proper effective DPI calculation, so the --oversample workaround is no longer necessary.
