### ISSUE TITLE
Error: unable to find trailer dictionary while recovering damaged file

### ISSUE THREAD

**Issue by fuzihaofzh** [jbarlow83/OCRmyPDF#410]
Hi, I meet with the following problems. Can anyone help to solve?

ocrmypdf 1.pdf 2.pdf -l chi_sim+eng --force-ocr
   INFO -  186: page already has text! - rasterizing text and running OCR anyway
WARNING -    2: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   16: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   22: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   25: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   26: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   29: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   31: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   34: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   35: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   36: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   37: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   38: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   40: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   44: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   48: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   52: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   56: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   58: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   65: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   69: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   68: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   71: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   72: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   73: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   74: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   75: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   79: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   81: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   82: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   83: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   85: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   87: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   92: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   94: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   93: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   96: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   95: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   99: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  102: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  104: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  105: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  106: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  108: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  107: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  109: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  110: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  112: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  113: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  114: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  115: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  118: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  119: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  120: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  122: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  124: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  126: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  130: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  131: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  133: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  134: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  135: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  136: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  137: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  138: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  140: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  139: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  141: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  142: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  145: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  149: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  150: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  156: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  158: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  161: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  160: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  165: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  166: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  167: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  171: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  172: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  170: [tesseract] lots of diacritics - possibly poor OCR
  ERROR - GPL Ghostscript 9.21: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

GPL Ghostscript 9.21: ERROR: rangecheck (-15) on closing pdfwrite device.

  ERROR - Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/8.3.2/libexec/lib/python3.7/site-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/usr/local/Cellar/ocrmypdf/8.3.2/libexec/lib/python3.7/site-packages/ruffus/task.py", line 544, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/usr/local/Cellar/ocrmypdf/8.3.2/libexec/lib/python3.7/site-packages/ocrmypdf/_pipeline.py", line 859, in metadata_fixup
    pdf = pikepdf.open(working_file)
  File "/usr/local/Cellar/ocrmypdf/8.3.2/libexec/lib/python3.7/site-packages/pikepdf/__init__.py", line 44, in open
    return Pdf.open(*args, **kwargs)
pikepdf._qpdf.PdfError: /var/folders/4f/bzlj5ndj7050qw4l0cgbg3680000gn/T/com.github.ocrmypdf.ztyr1zer/pdfa.pdf: unable to find trailer dictionary while recovering damaged file

**Comment by jbarlow83** [comment]
I'd like to help you with this issue, but you did not provide some of the information requested in the issue template, and I will need that information to help with this problem.

Please provide the information requested in the issue template. In this case, the input file is necessary.

If you cannot provide the input file, try:
1. `ocrmypdf 1.pdf 2.pdf -l chi_sim+eng --force-ocr --output-type pdf`
2. upgrade to the latest version of Ghostscript

**Comment by fuzihaofzh** [comment]
The pdf file is  http://157.7.135.42/books/政治·历史/%5B美%5D弗朗西斯·福山/%5B美%5D弗朗西斯·福山《政治秩序的起源--从前人类时代到法国大革命》.pdf  
I use MacOS. 10.14.5

**Comment by fuzihaofzh** [comment]
@jbarlow83  Any fix for this? Thanks

**Comment by jbarlow83** [comment]
From the log above you have Ghostscript 9.21 which is quite old, and probably an old version of ocrmypdf as well. With the current version of Ghostscript and ocrmypdf on macOS 10.14.6, the file can be processed without issue.

You can use Homebrew (`brew install ocrmypdf; brew upgrade ocrmypdf`) to get the latest version of ocrmypdf and all of its dependencies.

There is an error that Ghostscript reports like this:
```                                                                                                                                                                                                                                                                                                 
   **** Error: File has insufficient data for an image.
               Output may be incorrect.
```

The image in question is on page 455. The image data seems to be corrupt so this page appears blank. I suspect that between versions 9.21 and 9.27, Ghostscript improved its ability to handle this type of invalid image. It used to fail with an exception and now reports it as an error.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by fuzihaofzh** [comment]
@jbarlow83  Actually, my ghostscript is 9.27_1. Any idea?

**Comment by The-Real-Thisas** [comment]
@fuzihaofzh Hey I tested your pdf and it worked for me. Had to delete some pages for file size limitations but you can see that the OCR worked. You say your ghostscript is 9.27.1 but the error says `Ghostscript 9.21` so did you update later ?

PS: Just realised it's been a while so has it been sorted. 

[2 copy.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/10148812/2.copy.pdf)
