### ISSUE TITLE
Python error message opening OCRMYPDF

### ISSUE THREAD

**Issue by etanus11** [jbarlow83/OCRmyPDF#412]
**Describe the issue**
When I open ocrmypdf I get this error message:
 
                                                                     

**To Reproduce**
What command line were you trying to run?
ocrmypd -help

ocrmypdf --output-type pdfa Sam_Nujoma.pdf output.pdf

Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.__main__ import run
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/__init__.py", line 18, in <module>
    from . import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/helpers.py", line 54
    raise FileExistsError(f"{soft_link_name} exists and is not a link")
                                                                     ^
SyntaxError: invalid syntax

**Example file**
Please include an example *input* PDF (or image). The input file is more helpful.

Please check any or all that apply about the test file:

- [ ] This is the input file
- [ x] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

Files that are not free for inclusion in this project are quite welcome, but we like to collect free files for our test suite when possible. Please do *not* submit files with confidential information. At your option you may encrypt files for OCRmyPDF's author only.

**Expected behavior**
A clear and concise description of what you expected to happen. Include screenshots if applicable.
Displaying the parameters
**System:**

- OS: [e.g. Linux, macOS] 
Linux Ubuntu 16.04
- OCRmyPDF Version: [e.g. v7.4.0]
 8.3.2

**Additional context**

What can I do about it?
Renate

**Comment by jbarlow83** [comment]
Looks like you are using Python 3.5. That is not supported. 3.6 or newer is
required.

**Comment by jbarlow83** [comment]
See installation procedure for Ubuntu 16.04
https://ocrmypdf.readthedocs.io/en/latest/installation.html#ubuntu-16-04-lts
