### ISSUE TITLE
DecompressionBombError: Image size exceeds limit of x pixels, could be decompression bomb DOS attack

### ISSUE THREAD

**Issue by tcurdt** [jbarlow83/OCRmyPDF#413]
**Describe the issue**

Forcing an OCR results in `PIL.Image.DecompressionBombError`

**To Reproduce**

```bash
$ ocrmypdf -v -l deu+eng --force-ocr --sidecar out.txt  /path/to/input.pdf out.pdf
  DEBUG - ocrmypdf 9.0.0
  DEBUG - os.symlink(/path/to/input.pdf, /var/folders/pf/7vhqx5bn41qddypw08w9jc4w0000gn/T/com.github.ocrmypdf.civmiyes/origin)
  DEBUG - os.symlink(/var/folders/pf/7vhqx5bn41qddypw08w9jc4w0000gn/T/com.github.ocrmypdf.civmiyes/origin, /var/folders/pf/7vhqx5bn41qddypw08w9jc4w0000gn/T/com.github.ocrmypdf.civmiyes/origin.pdf)
Scan: 100%|...| 1/1 [00:00<00:00, 59.04page/s]
   INFO - Using Tesseract OpenMP thread limit 4
   INFO -    1: page already has text! - rasterizing text and running OCR anyway                                                                                                 
  DEBUG -    1: Rasterize with png16m                                                                                                                                            
  DEBUG -    1: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r2897.060413x2897.060413', '-o', '/var/folders/pf/7vhqx5bn41qddypw08w9jc4w0000gn/T/tmpeam5vcbf', '-dAutoRotatePages=/None', '-f', '/var/folders/pf/7vhqx5bn41qddypw08w9jc4w0000gn/T/com.github.ocrmypdf.civmiyes/origin.pdf']
OCR:   0%|                                                                                                                                           | 0.0/1.0 [00:00<?, ?page/s]
  ERROR - An exception occurred while executing the pipeline
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/ocrmypdf/_sync.py", line 100, in exec_page_sync
    remove_vectors=False,
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/ocrmypdf/_pipeline.py", line 446, in rasterize
    filter_vector=remove_vectors,
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/ocrmypdf/exec/ghostscript.py", line 175, in rasterize_pdf
    with Image.open(tmp) as im:
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/PIL/Image.py", line 2690, in open
    im = _open_core(fp, filename, prefix)
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/PIL/Image.py", line 2677, in _open_core
    _decompression_bomb_check(im.size)
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/PIL/Image.py", line 2611, in _decompression_bomb_check
    (pixels, 2 * MAX_IMAGE_PIXELS))
PIL.Image.DecompressionBombError: Image size (811374000 pixels) exceeds limit of 256000000 pixels, could be decompression bomb DOS attack.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/ocrmypdf/_sync.py", line 338, in run_pipeline
    exec_concurrent(context)
  File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/ocrmypdf/_sync.py", line 269, in exec_concurrent
    page_result = results.next()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
PIL.Image.DecompressionBombError: Image size (811374000 pixels) exceeds limit of 256000000 pixels, could be decompression bomb DOS attack.
```

**Example file**

The file contains personal information. Happy to provide the encrypted version though.

**Expected behavior**

It worked for many similar PDFs. I would have expected this to just work the same way.

**System:**

- OS: macOS 10.13.6
- OCRmyPDF Version: 9.0.0

**Additional context**

This is not a scanned but rather a generated PDF.

**Comment by jbarlow83** [comment]
You'll need `--max-image-mpixels 900` and it will work but give a very large file. Maybe that makes sense.

It's trying to produce a 811 Mpixel image, a 2900 dpi rendering on an implied page size of about 10x10" or 25x25cm). This is all a bit unusual but could happen if you happen to be working with high resolution scans of large format film or microfiche or something like that. If not, there's probably some feature on the page that is causing us to think we need a really high resolution output. Manually scaling an image down could do it too.

You could try `pdfimages -list` on the file and paste the results here. That would tell me if another program also thinks there's a high resolution image in there.

It will also take a long time to OCR.

**Comment by tcurdt** [comment]
Thanks for the quick reply, @jbarlow83 

TBH I don't quite yet understand the why.

I now even have two files that are failing like this. One is 640k the other one just 40k in file size. Both are generated and not scanned. So I am wondering why this is trying to create such a huge image?! I already tried `--image-dpi 100` but that didn't seem to help.

I don't have a `pdfimages` installed and only found a similarly named cask on homebrew. Is that the one?

**Comment by jbarlow83** [comment]
It's `brew install poppler` for `pdfimages`.

**Comment by tcurdt** [comment]
Here is the output - which is insane:

```
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    5957  3992  rgb     3   8  jpeg   no        20  0  2898  2898  596K 0.9%
```

It's just a stupid logo.

**Comment by jbarlow83** [comment]
`--image-dpi` has no effect except when the input file is an image. There's supposed to be a warning message that explains this (although maybe it should be an error).

You can use Ghostscript to downsample:

```
$ gs -q -sDEVICE=pdfwrite  -dDownsampleColorImages=true -dDownsampleGrayImages=true -o out.pdf tests/resources/2400dpi.pdf
$ pdfimages -list out.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     250   179  gray    1   8  image  no         8  0   150   150 2491B 5.6%
```

In its documentation there are commands to fine tune the resolution.

Since Ghostscript can do this, I don't think ocrmypdf should implement the same feature.

**Comment by tcurdt** [comment]
@jbarlow83 Thanks, that worked perfectly! But shouldn't `ocrmypdf` use Ghostscript to do the downsampling automatically? In the end it seems to use it already anyway.

**Comment by jbarlow83** [comment]
The trouble is that the user could legitimately have a high DPI file, since they show in film scanning. Also, the DPI can be wrong, in which case downsampling ruins the output, and being able to run 'blind' without having to check the file is a key feature. Depending on the mode Ghostscript might be involved in the final pass, but not always. So, yes it can be improved, but there's a fine line.

**Comment by tcurdt** [comment]
I am sure it is a fine line. That said I believe the percentage of the people using `ocrmypdf` with DPIs higher than 300 will be rather small, no?

How about: Let the user pass in a command line parameter. If the DPI is higher than the given number run the downsampling first. No parameter, no downsampling. That would be backwards compatible and quite easy to use.

**Comment by AEgit** [comment]
As long as the default behaviour is not changed (since I regularly DO work with DPI >300), I would be ok with this.

**Comment by jbarlow83** [comment]
We now warn that `--image-dpi` is ignored when the input file is not an image so I will close this.

I'll open a new issue for feature request to implement downsampling.

**Comment by mohsin127** [comment]
Solved
Open File "/usr/local/Cellar/ocrmypdf/9.0.0/libexec/lib/python3.7/site-packages/PIL/Image.py"
and Change MAX_IMAGE_PIXELS = How much you want.
