### ISSUE TITLE
OcrMyPDF batch file

### ISSUE THREAD

**Issue by etanus11** [jbarlow83/OCRmyPDF#414]
**Describe the issue**
I am using the batch file for OcrMyPDF, but when I change the output type to for example 
--output-type pdfa
it will not ocr the documents and it is not pdfa compliant.
If i use the original batch dcript as downloaded with just --deskew it works.

**To Reproduce**
ocr_batch.sh with
```python
for dir_name, subdirs, file_list in os.walk(start_dir):
    logging.info('\n')
    logging.info(dir_name + '\n')
    os.chdir(dir_name)
    for filename in file_list:
        file_ext = os.path.splitext(filename)[1]
        if file_ext == '.pdf':
            **full_path = dir_name + '/' + filename
            print(full_path)
            cmd = ["ocrmypdf",  "--output-type pdfa", filename, filename]
            logging.info(cmd)**
            proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            result = proc.stdout.read()
            if proc.returncode == 6:
```

"ocrmypdf_batch_output.sh" 45L, 1398C               

```bash
ocrmypdf  ...arguments... input.pdf output.pdf
```
Is it possible to change the script to generate PDFA compliant files in batch mode?
Thanks
Renate

**Example file**

[UTO710S - URBAN TOURISM - 2ND OPP - JUL 2019.pdf](https://github.com/jbarlow83/OCRmyPDF/files/3472247/UTO710S.-.URBAN.TOURISM.-.2ND.OPP.-.JUL.2019.pdf)

Please check any or all that apply about the test file:

- [x] I am not the copyright holder, but this file is available under a free software license

**Expected behavior**
The file should be PDFA compliant and OCRed.

**Comment by jbarlow83** [comment]
You'll need to change 
```python
cmd = ["ocrmypdf",  "--output-type pdfa", filename, filename]
```

to
```python
cmd = ["ocrmypdf",  "--output-type", "pdfa", filename, filename]
```

The way you entered the command, it's as if you ran `ocrmypdf '--output-type pdfa' filename filename` (with the quotes), which if you try, you'll see will not work.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
