### ISSUE TITLE
Any way to remove text portion of image while keeping other images? 

### ISSUE THREAD

**Issue by gardar** [jbarlow83/OCRmyPDF#415]
Is there any known method to get rid of the text portion of the original pdf while keeping other images? Perhaps by combining ocrmypdf with other tools?

My use case would be that I have a ~400 page pdf in a foreign language that I want to ocr and then translate the text into english and then combine it again with the text in a similar position as it was before.

**Comment by jbarlow83** [comment]
You can rewrite the PDF using Ghostscript with `-dFILTERTEXT` to remove existing selectable text (whether real text or OCR) and retain images or vectors.

I don't quite understand what you're trying to do though. You want to be able to select text and get an English translation? I'd highlight "hors d'oeuvres", hit ctrl+C, and get "appetizers" in my clipboard? (Although maybe not word for word equivalent.)

You could use `--sidecar` to produce a pure text file broken up by pages, and then translate the pages and convert the text file to PDF in any program. That would get you the same content on each page, although not the same appearance....

**Comment by gardar** [comment]
Well no not exactly, what I want to do is to OCR the pdf and get the text in text format and not image format like it's now, ocrmypdf seems to do this great.
Now what I want to do is to remove the original text (which is in image format) and be left with just the text in text format, but I don't want to lose the other images that are present and I want to keep the position of the text.

The pdf in question is automotive repair guide in a foreign language, it contains a lot of pictures and text, and the position of the text is quite important since the text usually applies to the picture that's next to it.
Just extracting the text and would require quite a lot of manual work to put all the text in the right place.

Perhaps what I'm trying to achieve is impossible at the moment.

**Comment by jbarlow83** [comment]
Yes, I'd look at using Abbyy FineReader or Omnipage to create an editable Word document version of your file. I don't know of any free software that does the job.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
