### ISSUE TITLE
ocrmypdf-alpine not working

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#426]
@jbarlow83 pls help me out.!"
I cant able to pull the latest version of ocrmypdf.
If i use this command - docker pull jbarlow83/ocrmypdf-alpine am in the version of **8.2.2.post10+g6e49bb3.d20190403**
How to get the latest version of ocrmypdf in docker.?
Thanks

_Originally posted by @AmirthaKrishnan in https://github.com/jbarlow83/OCRmyPDF/issues/419#issuecomment-529342077_

**Comment by jbarlow83** [comment]
@AmirthaKrishnan Please use "New issue" in Github to open a new issue, and please refrain from commenting on issues that are unrelated to the problem you are having.

ocrmypdf-alpine is broken at the moment since the Alpine qpdf has not upgraded to 9.0.0. I suggest using `docker pull jbarlow83/ocrmypdf` instead for the Ubuntu based image.

**Comment by AmirthaKrishnan** [comment]
Thanks for the reply @jbarlow83 
Sry for the issues i am commenting unrelated to the problem.
Problem has been fixed by using **docker pull jbarlow83/ocrmypdf**

**Comment by valpo** [comment]
9.0.1-r0 is in edge, so it should be possible to upgrade the image.

**Comment by jbarlow83** [comment]
I think it's fine now.

**Comment by valpo** [comment]
Just pulled the image from docker hub, still getting the same error (trying via the webinterface): 

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikepdf/__init__.py", line 10, in <module>
    from . import _qpdf
ImportError: Error loading shared library libqpdf.so.26: No such file or directory (needed by /usr/lib/python3.6/site-packages/pikepdf/_qpdf.cpython-36m-x86_64-linux-gnu.so)

**Comment by valpo** [comment]
After building the image by myself (libqpdf.so.26 is in edge, so it should work...) I am getting this error from the web-frontend: 

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikepdf/__init__.py", line 10, in <module>
    from . import _qpdf
ImportError: Error relocating /usr/lib/libqpdf.so.26: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

Ok, it is the right version now, but still does not work.

**Comment by kykim** [comment]
from the [pikepdf docs](https://pikepdf.readthedocs.io/en/latest/installation.html)

> This command installs binary wheels. 64-bit wheels are available for Windows, Linux and macOS. (Except Alpine Linux.)

So, this is probably the problem.

**Comment by jbarlow83** [comment]
@kykim I wish it were that simple. From the build logs pip is already doing the right thing and building pikepdf from source.

I think the issue is that libqpdf is being compiled without C++11 and pikepdf requires C++11. On glibc this doesn't matter but it does for Alpine's musl libc.

**Comment by aradhell** [comment]
> I think it's fine now.

I am still having an issue with the latest version, 8.2.1 works fine

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikepdf/__init__.py", line 10, in <module>
    from . import _qpdf
ImportError: Error relocating /usr/lib/libqpdf.so.26: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/usr/lib/python3.6/site-packages/ocrmypdf/__init__.py", line 45, in <module>
    from . import pdfa
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfa.py", line 41, in <module>
    import pikepdf
  File "/usr/lib/python3.6/site-packages/pikepdf/__init__.py", line 12, in <module>
    raise ImportError("pikepdf's extension library failed to import")
ImportError: pikepdf's extension library failed to import`

**Comment by Vinc89** [comment]
Hello, the :latest version is not working, getting also the pikepdf import error. 

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pikepdf/__init__.py", line 10, in <module>
    from . import _qpdf
ImportError: Error loading shared library libqpdf.so.26: No such file or directory (needed by /usr/lib/python3.6/site-packages/pikepdf/_qpdf.cpython-36m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/usr/lib/python3.6/site-packages/ocrmypdf/__init__.py", line 18, in <module>
    from . import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/usr/lib/python3.6/site-packages/ocrmypdf/pdfa.py", line 40, in <module>
    import pikepdf
  File "/usr/lib/python3.6/site-packages/pikepdf/__init__.py", line 12, in <module>
    raise ImportError("pikepdf's extension library failed to import")
ImportError: pikepdf's extension library failed to import


v9.0.3 is working fine
Is the latest version working for someone? Is some further setting needed?

**Comment by jbarlow83** [comment]
Is there anyone who would object to me killing off ocrmypdf-alpine in favor of the Ubuntu based jbarlow83/ocrmypdf image?

@mawi12345 - want to make sure you're part of this discussion since you contributed the alpine image.

* The main issue is that Alpine Linux doesn't use glibc.
* The size difference between Alpine and Ubuntu is not that big.
* The fact that alpine does not support manylinux Python wheels makes it a difficult platform to support for Python, because a lot of dependencies need to be hand-compiled or otherwise require special attention.
* I'm no expert on Alpine Linux.
* I'm really busy right now and will be for several months.

I'd rather have a smaller set of installations that work reliably, and the Ubuntu image is quite stable because Travis CI implicitly tests it.

Alternately, is someone willing to volunteer to maintain ocrmypdf-alpine?

**Comment by valpo** [comment]
It is fine for me. I also prefer a stable solution over a set of choices which may work or may not work.

**Comment by jbarlow83** [comment]
I've made some improvements to the Ubuntu version and removed ocrmypdf-alpine.

**Comment by mawi12345** [comment]
@jbarlow83: The ubuntu image has improved a lot since my first alpine version. I prefer the simpler way to only support an image. Drop the `ocrmypdf-alpine` image and keep the user friendly ubuntu image.
