### ISSUE TITLE
Input paths can contain illegal characters which give errors

### ISSUE THREAD

**Issue by Quinten-gs** [jbarlow83/OCRmyPDF#430]
Dear, 

When running ocrmypdf on files with filenames which contain the accent 

> '

the program returns a 2 error indicating that the file is not a good PDF. However when renaming the files it works flawlessly. 

I did not find anything about this in the documentation. Ideally this would be picked up in the documentation somewhere that this might happen as it is easily fixed by just renaming the files.

**Comment by jbarlow83** [comment]
This may have to do with the system locale being misconfigured, which would cause the shell to pass the wrong filename to Python. Python 3.7 is better at handling this sort of issue.

In short I suspect the command `python3 -c 'open("yourfilenameherewithåcçénts")'` fails when that file exists, which would make it a local configuration issue.

**Comment by Quinten-gs** [comment]
Many thanks, it does seem to be a local configuration issue as the command python3 -c 'open("yourfilenameherewithåcçénts")' does not work indeed as you mentioned. 

I will look into this to solve it.
