### ISSUE TITLE
Question, need Help with DeliciousPickle Sample Script for Batch Processing

### ISSUE THREAD

**Issue by mastadook** [jbarlow83/OCRmyPDF#431]
Hi,

just try to add Language support to this Script.
This did not work, in the Log I found this Error:
> 2019-10-17 08:38:02,143 b'The installed version of tesseract does not have language data for the following requested languages:\n deu\n' <

The German Language is Installed:

> xxxx@xxxxx:~/home# tesseract --list-langs
List of available languages (4):
eng
equ
osd
deu
<
See script below, I changed some paths and all works fine until I add the Language Option.
Any Idea? Please Help :)

`#!/usr/bin/env python3
# Walk through directory tree, replacing all files with OCR'd version
# Contributed by DeliciousPickle@github

import logging
import os
import subprocess
import sys

script_dir = os.path.dirname(os.path.realpath(__file__))
print(script_dir + '/ocr-tree.py: Start')

if len(sys.argv) > 1:
    start_dir = sys.argv[1]
else:
    start_dir = '/home/xxxx/pdfmigration/Incomming'

if len(sys.argv) > 2:
    log_file = sys.argv[2]
else:
    log_file = script_dir + '/ocr-tree.log'

logging.basicConfig(
        level=logging.INFO, format='%(asctime)s %(message)s',
        filename=log_file, filemode='w')

for dir_name, subdirs, file_list in os.walk(start_dir):
    logging.info('\n')
    logging.info(dir_name + '\n')
    os.chdir(dir_name)
    for filename in file_list:
        file_ext = os.path.splitext(filename)[1]
        if file_ext == '.pdf':
            full_path = dir_name + '/' + filename
            print(full_path)
            cmd = ["ocrmypdf", "--deskew", **"-l eng+deu"**, filename, "/home/xxxx/pdfmigration/Done/" + filename]
            logging.info(cmd)
            proc = subprocess.run(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            result = proc.stdout
            if proc.returncode == 6:
                print("Skipped document because it already contained text")
            elif proc.returncode == 0:
                print("OCR complete")
            logging.info(result)`

System ist Elementary OS in actual Version (Ubuntu 18.4 I think)
As I said, all works fine until the Laguage Option is added.

**Comment by jbarlow83** [comment]
https://ocrmypdf.readthedocs.io/en/latest/languages.html

**Comment by mastadook** [comment]
No, I have installed everything.
Can not find the Answer in your Link.
As I said:
The German Language is Installed:

xxxx@xxxxx:~/home# tesseract --list-langs
List of available languages (4):
eng
equ
osd
deu
<
See script below, I changed some paths and all works fine until I add the Language Option.
Any Idea? Please Help :)

**Comment by mastadook** [comment]
for the People they are interested.
I found some help in German Pythom Forum, here is the correct CMD Line:
cmd = ["ocrmypdf", "--deskew", "-l", "eng+deu", filename, "/home/xxxx/pdfmigration/Done/" + filename]
"-l", "deu+eng" should no be written in one Argument like I do before "-l deu+eng" this is wrong.

The Link above did not help you here in this Case

Regards
