### ISSUE TITLE
Making changes to documents later

### ISSUE THREAD

**Issue by GuidoBo** [jbarlow83/OCRmyPDF#432]
Hi and first of all: this is marvelous work!
I am having a maybe stupid question: I would like to **later edit** the PDFs OCRmyPDF created, like **adding pages or deleting them** (using Acrobat Pro), but it appears that this does not work. I get an error saying that the file is write-protected (which - as far as file permissions are concerned - isn't true). I can - however do what I want after I copied the file. What am I doing wrong?

**Comment by jbarlow83** [comment]
The file isn't write-protected, but is marked as a PDF/A which Acrobat warns about. It is harmless to ignore Acrobat's message, make whatever changes you like, and save any file as a standard PDF or a PDF/A.

In ocrmypdf, you can create files with the option `--output-type pdf` to generate a standard PDF.

See https://ocrmypdf.readthedocs.io/en/latest/introduction.html#about-pdf-a for why you might want PDF/A. Generally speaking ocrmypdf users are interested in making archival documents so PDF/A is the default behavior.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by GuidoBo** [comment]
Thank you!
