### ISSUE TITLE
Add support for Producer, Creator, Created Date, Modify Date

### ISSUE THREAD

**Issue by homocomputeris** [jbarlow83/OCRmyPDF#434]
It would be nice to be able to set these fields, similarly to img2pdf, exiftool, pdfmark.

**Comment by jbarlow83** [comment]
In keeping with the PDF spec, ocrmypdf sets and updates these values when
it modifies a file. This is what PDF applications are supposed to do.

You can use my pikepdf library to edit these fields if you want. I don't
advise editing Producer or Creator because this is useful debugging
information.

**Comment by homocomputeris** [comment]
They also may be a privacy concern, and users might want to use custom values if they think it's necessary.

**Comment by jbarlow83** [comment]
I don't think this feature belongs in ocrmypdf, and other programs like the ones you mentioned are capable of metadata editing.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
