### ISSUE TITLE
Working with Multiple Versions

### ISSUE THREAD

**Issue by maamcs86** [jbarlow83/OCRmyPDF#435]
Hi,

Thank you very much for an amazing tool! :)

I have couple of questions. I would very much appreciate your help.

How can I install a local version and setup so that when I run the ocrmypdf command, it uses the scripts in my current folder rather than the main OCRmyPDF in the bin folder. Let's say I want to work on different OCRmyPDF versions in different directories.

Is there a way that I can run OCRmyPDF with a python command rather than a ocrmypdf command?

If the answer to the top questions is no, can I pass additional arguments while running my ocrmypdf command?(like a directory other than pdf input and output dir) if yes, which script should I modify?

Thank you again for all your time and contributions.

**Comment by jbarlow83** [comment]
On Linux and macOS you can use `pip3 install --user ocrmypdf` to install a local version. You might have to add `~/.local/bin` to `PATH`.

There is an API and suggestions about batch jobs in the docs:
https://ocrmypdf.readthedocs.io/en/latest/api.html

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
