### ISSUE TITLE
wsl ubuntu install will not update

### ISSUE THREAD

**Issue by ajweber** [jbarlow83/OCRmyPDF#441]
I followed the instructions to install in Win10-WSL (Ubuntu 18.04).

The default install went ok.  Version 6.1.2 installed.

However, running the pip3 install command (with or without the --user option) does not find a newer version (or does not install it).

I also tried with the --upgrade arg to pip3, and that seemed to find updated "wheels", but at the end of the command I was still left with the 6.1.2 version.

How can I get a 9.x version upgraded in WSL/Ubuntu?

Thanks.

**Comment by ajweber** [comment]
OK, actually I think it did install...to /usr/local/bin.  Ref Issue 402 (partially).  Somehow bash will only look at /usr/bin for ocrmypdf.

I double-checked, and /usr/local/bin is in front of /usr/bin in the PATH.  I even went and renamed the 6.1 version in /usr/bin.  Then I could issue "which ocrmypdf" and it finds the /usr/local/bin version (9.0.3).  However, if I do not specify an explicit path, if I try and run "ocrmypdf --version" it says "No such file or directory"???

My workaround is to simply symlink from /usr/bin/ocrmypdf to the /usr/local/bin version, but I'm really not clear as to why that is necessary, and what is forcing bash to only try and launch from /usr/bin.

**Comment by jbarlow83** [comment]
Sorry, I missed this issue somehow. 

There is no way I can get WSL to provide an upgraded version. Ubuntu 18.04 is a shipped product. Unless someone stepped up to the plate and offered to maintain a backport/PPA, but backports are unofficial. Failing this the only way is to install the pip version.

`pip3 install --user` should install the binary to `$HOME/.local/bin` which you have to add to PATH manually and relaunch your shell.

**Comment by ajweber** [comment]
Testing this process again, you have to know to skip through to the section about pip3 prerequisites and download/install those all from apt-get.

But even after all of that, running "pip3 install ocrmypdf" tells you that the requirement is already satisfied.  (The 6.1.2 version)

If you run "pip3 install --upgrade ocrmypdf", it will fail to find the wheel for pikepdf and it can not build it.  So I'm stuck again.

**Comment by jbarlow83** [comment]
You'll need to upgrade `pip`

**Comment by ajweber** [comment]
OK, thanks for that tip.  FWIW: You can't install pip from Ubuntu packages (i.e. apt-get) and then upgrade from pip.  It looks like it works, but it breaks things (there are a few github issues related to this in their pages).  For those searching/finding this, the best thing to do is to uninstall the ubuntu package, because it's too old. (apt remove python3-pip).  Then go fetch the current version using curl or wget (wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py).  Just note that things will install in /usr/local/bin instead of /usr/bin.

Thanks for your help.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
