### ISSUE TITLE
Barcode support 

### ISSUE THREAD

**Issue by AmirthaKrishnan** [jbarlow83/OCRmyPDF#442]
Hi @jbarlow83 I just want to know any support available for barcode extraction through this args --mask-barcodes.

**Comment by AmirthaKrishnan** [comment]
I have done some code to extract barcode / qrcode using zbar. how to integrate with ocrmypdf

**Comment by AmirthaKrishnan** [comment]
Can I get your contact number? we will discuss offline reg this. 
So that I will get some clear idea on this. :) 
Thanks

**Comment by jbarlow83** [comment]
Could you send me an email: jim@purplerock.ca 

I'd prefer to not post my phone number here. Thanks for your interest and understanding.

**Comment by AmirthaKrishnan** [comment]
yeah, buddy ;D

**Comment by jbarlow83** [comment]
To be clear, I'd quite be happy to carry on this conversation by email and exchange phone numbers that way if - I just don't want to give out my personal phone number here.

**Comment by strarsis** [comment]
This feature would be great! I use Alfresco and barcode/QR code reading would be great.
There is the [ZBar](https://github.com/ZBar/ZBar) library, would it be better suited?

**Comment by jbarlow83** [comment]
Yes, zbar would be a better fit and it seems to check the right boxes: reasonable license, wildly available, stable. I don't think it's available for Windows, that would be the main drawback.

It could be implemented as a plugin.
