### ISSUE TITLE
PDF/A 2b is not valid

### ISSUE THREAD

**Issue by aalmir** [jbarlow83/OCRmyPDF#444]
**Describe the issue**
I started with a valid pdf and the ocrmypdf output pdf is not valid.

Tested with:

Adobe Acrobat:
PDF document is not compliant with PDF/A-2b
XMP property is predefined but is nat used in accordance with the definition (XMP 2005)
An XMP Metadata property is used that is defined in the XMP specification from 2005, that is relevant for
the ISO PDF/A.2 standard and other ISO standards. However, the property is not used in accordance with
its definition in this XMP specification.

 and 

https://www.pdf-online.com/osa/validate.aspx
File | output.pdf
-- | --
Compliance | pdfa-2b
Result | Document does not conform to PDF/A.
Details | Validating file "conformout.pdf" for conformance level pdfa-2bxmp:MetadataDate :: Wrong value type. Expected type 'Date'.The document does not conform to the requested standard.The document's meta data is either missing or inconsistent or corrupt.The document does not conform to the PDF/A-2b standard.Done.

**To Reproduce**
ocrmypdf input.pdf output.pdf

```bash
ocrmypdf  input.pdf output.pdf
```

**Example file**
Please include an example *input* PDF (or image). The input file is more helpful.

Please check any or all that apply about the test file:

- [yes ] This is the input file
- [no ] The file contains no personal or confidential information
- [yes ] I am the copyright holder for this file
- [yes
[input.pdf](https://github.com/jbarlow83/OCRmyPDF/files/3798425/input.pdf)
[output.pdf](https://github.com/jbarlow83/OCRmyPDF/files/3798426/output.pdf)

 ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ no] I am not the copyright holder, but this file is available under a free software license

**Expected behavior**
Valid PDF/A2B

**System:**

- OS: kubuntu 19
- OCRmyPDF Version: 9.0.3+dfsg

**Additional context**
nothing

**Comment by jbarlow83** [comment]
As far as I can tell that validation service is incorrect.

According to the [XMP spec](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf), the date must been in this format:

`YYYY-MM-DDThh:mm:ss.sTZD`

The xmp:MetadataDate in your file is:

`2019-11-01T16:00:00.557618`

This is the result generated by Ghostscript.`TZD` is the optional timezone designator, omitted Decimal seconds are also allowed in the spec. So it's acceptable. Would be better to have a time zone, but it's acceptable as is.

[verapdf](https://verapdf.org/home/) finds your file to be compliant with PDF/A.

**Comment by aalmir** [comment]
Ok. Thank you. I will use VeraPDF in the future.
