### ISSUE TITLE
Cannot skip OCR for a PDF file that already has text layer

### ISSUE THREAD

**Issue by wpzdm** [jbarlow83/OCRmyPDF#449]
**Describe the issue** 

`  ERROR - PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR)`

**To Reproduce**
`ocrmypdf  --optimize 3 --jbig2-lossy --tesseract-timeout=0 input.pdf output.pdf`

**System:**

- OS: macOS 10.14.5
- OCRmyPDF Version: 9.0.3

**Comment by jbarlow83** [comment]
Try the option `--skip-text`

**Comment by wpzdm** [comment]
This works. Thank you!

I think it is better to update the document:
https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#don-t-actually-ocr-my-pdf

**Comment by jbarlow83** [comment]
Thanks for the suggestion - docs updated.
