### ISSUE TITLE
How to install the project on Centos 7 with yum?

### ISSUE THREAD

**Issue by miguelgarces123** [jbarlow83/OCRmyPDF#451]
I can't find a way to install the package in Centos 7, is it possible to do it?

**Comment by jbarlow83** [comment]
ocrmypdf was never packaged for Centos 7. It is Fedora now, but apparently was not included in RHEL 8 or Centos 8.

You should be able to install it with the standard procedure for Linux
https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-with-python-pip

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
