### ISSUE TITLE
Output larger than input

### ISSUE THREAD

**Issue by sje30** [jbarlow83/OCRmyPDF#452]
**Describe the issue**

When scanning a test file, I get the warning:

```
   INFO - Optimize ratio: 1.00 savings: 0.0%
   INFO - Output file is a PDF/A-2B (as expected)
WARNING - The output file size is 1.62× larger than the input file.
No reason for this increase is known.  Please report this issue.
```

hence reporting.  File has come from a colour scanner/printer.

**To Reproduce**

```bash
ocrmypdf  test_page.pdf out.pdf
```

**Example file**
Please include an example *input* PDF (or image). The input file is more helpful.

Please check any or all that apply about the test file:

- [x] This is the input file
- [x] The file contains no personal or confidential information
- [x ] I am the copyright holder for this file
- [x] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

Files that are not free for inclusion in this project are quite welcome, but we like to collect free files for our test suite when possible. Please do *not* submit files with confidential information. At your option you may encrypt files for OCRmyPDF's author only.

**Expected behavior**
Would expect error not to occur.  Although this is a test file, I get the same behaviour on real multi-page pdfs (confidential info on them, so would rather not post!)

**System:**

- OS: arch linux
- OCRmyPDF Version: 9.0.5

[test_page.pdf](https://github.com/jbarlow83/OCRmyPDF/files/3827189/test_page.pdf)

**Comment by jbarlow83** [comment]
I think that you do not have the optional dependency jbig2enc installed, so the main image in the file was converted from JBIG2 compressed (very efficient) to CCITT G4 (less efficient).

If `jbig2` is not on the PATH, ocrmypdf can't find it.

**Comment by sje30** [comment]
Thank you.  I didn't have jbig2enc, but do now.

**Comment by gmehta1996** [comment]
Hi , could anyone please tell me from where to install jbig2enc and unpaper. I am not able to use some commands of ocrmypdf due to these 2 optional dependencies not present. I tried to install them using chocolatey manager by using the commands 'choco install jbig2enc ' and 'choco install unpaper' but it shows that these do not exist and I'm not able to find a solution. My OS is Windows and ocrmypdf version is 9.8.1 .

**Comment by jbarlow83** [comment]
You'd have to use `wsl` or compile them manually for Windows. Packaging software for Windows is not my area of expertise.

**Comment by Metalrex0926** [comment]
My System Configuration :- 
System:    Host: metalrex-System-Product-Name Kernel: 5.3.0-51-generic x86_64 bits: 64 
           compiler: gcc v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME B450M-A v: Rev X.0x serial: <filter> 
           UEFI [Legacy]: American Megatrends v: 1823 date: 10/15/2019 
CPU:       Topology: 6-Core model: AMD Ryzen 5 3600X bits: 64 type: MT MCP arch: Zen  L2 
Graphics:  Device-1: NVIDIA vendor: Micro-Star MSI driver: nvidia v: 435.21
           OpenGL: renderer: GeForce GTX 1650/PCIe/SSE2 v: 4.6.0 NVIDIA 435.21 

Question :-
I am trying to install jbig2enc using github package it is giving me this error in linux?

ERROR:-

./autogen.sh 
Running aclocal
./autogen.sh: 45: ./autogen.sh: aclocal: not found

  Something went wrong, bailing out!

**Comment by jbarlow83** [comment]
@Metalrex0926 You need to install autotools, which should provide aclocal.
https://en.wikipedia.org/wiki/GNU_Autotools

**Comment by gmehta1996** [comment]
Hi,
I have been trying to use the command --rotate-pages on some rotated pdfs
but the pdfs are not being rotated. I've tried many combinations of
commands woth rotate-pages but I don't seem to get the result.
Can I have some help regarding it.
Thank you

Gavya Mehta
(RPA Developer)
