### ISSUE TITLE
deskew and roate but skip ocr?

### ISSUE THREAD

**Issue by barrars** [jbarlow83/OCRmyPDF#458]
**Describe the issue**
I want to deskew and rotate without performing OCR regardless if the pdf has text - is this possible?

- OS: linux
- OCRmyPDF Version: latest

**Comment by jbarlow83** [comment]
If you don't care about losing existing text or OCR or flattening vector
art (that is you already have bag-of-images PDFs),

--deskew --orce-ocr --tesseract-timeout=0 --rotate-pages

Deskew as currently implemented requires rasterizing the whole page.

**Comment by barrars** [comment]
I'm getting `ocrmypdf: error: unrecognized arguments: --orce-ocr`

**Comment by NassimBentarka** [comment]
@barrars: I think you had a typo on --ocre-ocr, it should be --force-ocr.

**Comment by mehmetgogebakan** [comment]
@barrars : here is the answer: ocrmypdf **--tesseract-timeout=0 --deskew**  input.pdf output.pdf
