### ISSUE TITLE
--optimize N does not work

### ISSUE THREAD

**Issue by RalfKo** [jbarlow83/OCRmyPDF#462]
Hi You describe in the cookbook https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#pdf-optimization the option **--optimize N** or **-o N**
If I try it i only get **ocrmypdf: error: unrecognized arguments: --optimize**
Also I can't find this in the man-page.

Is this a bug or is the cookbook is outdated?

(run ocrmypdf on a ubuntu aus WSL on Windows10)
Thank you!

**Comment by jbarlow83** [comment]
Needs to be capital `-O` not lowercase.

Otherwise I don't know why `--optimize` is not working for you. Maybe paste a full shell session? The test suite is fairly comprehensive and definitely exercises that feature.

**Comment by RalfKo** [comment]
mmmh, am I missing something fundamental? All I get is this:

ocrmypdf --optimize 3  Bild.png ocr-des-rem-opt.pdf
usage: ocrmypdf [-h] [-l LANGUAGE] [--image-dpi DPI]
                [--output-type {pdfa,pdf,pdfa-1,pdfa-2}] [--sidecar [FILE]]
                [--version] [-j N] [-q] [-v [VERBOSE]] [--title TITLE]
                [--author AUTHOR] [--subject SUBJECT] [--keywords KEYWORDS]
                [-r] [--remove-background] [-d] [-c] [-i] [--oversample DPI]
                [-f] [-s] [--skip-big MPixels] [--max-image-mpixels MPixels]
                [--tesseract-config CFG] [--tesseract-pagesegmode PSM]
                [--tesseract-oem MODE]
                [--pdf-renderer {auto,tesseract,hocr,sandwich}]
                [--tesseract-timeout SECONDS]
                [--rotate-pages-threshold CONFIDENCE]
                [--pdfa-image-compression {auto,jpeg,lossless}]
                [--user-words FILE] [--user-patterns FILE] [--skip-repair]
                [-k] [-g] [--flowchart FLOWCHART]
                input_pdf_or_image output_pdf
ocrmypdf: error: unrecognized arguments: --optimize ocr-des-rem-opt.pdf

ocrmypdf -O 3  Bild.png ocr-des-rem-opt.pdf
usage: ocrmypdf [-h] [-l LANGUAGE] [--image-dpi DPI]
                [--output-type {pdfa,pdf,pdfa-1,pdfa-2}] [--sidecar [FILE]]
                [--version] [-j N] [-q] [-v [VERBOSE]] [--title TITLE]
                [--author AUTHOR] [--subject SUBJECT] [--keywords KEYWORDS]
                [-r] [--remove-background] [-d] [-c] [-i] [--oversample DPI]
                [-f] [-s] [--skip-big MPixels] [--max-image-mpixels MPixels]
                [--tesseract-config CFG] [--tesseract-pagesegmode PSM]
                [--tesseract-oem MODE]
                [--pdf-renderer {auto,tesseract,hocr,sandwich}]
                [--tesseract-timeout SECONDS]
                [--rotate-pages-threshold CONFIDENCE]
                [--pdfa-image-compression {auto,jpeg,lossless}]
                [--user-words FILE] [--user-patterns FILE] [--skip-repair]
                [-k] [-g] [--flowchart FLOWCHART]
                input_pdf_or_image output_pdf
ocrmypdf: error: unrecognized arguments: -O ocr-des-rem-opt.pdf

**Comment by jbarlow83** [comment]
You're using an older version from before optimization was added.

**Comment by jbarlow83** [comment]
See here for procedure on updating WSL to the latest version
https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-on-windows-subsystem-for-linux

**Comment by RalfKo** [comment]
I already did all of that. Only the "`python3 get-pip.py`" did not work: 
`ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/pip' Consider using the `--user` option or check the permissions.`

So I ran `python3 get-pip.py --user` 
which resulted in: `Successfully installed pip-19.3.1`

But after `python3 -m pip install --user ocrmypdf` I only got:
`Requirement already satisfied: ocrmypdf in /usr/lib/python3/dist-packages (6.1.2)`

So I am stuck with 6.1.2
```
:~$ sudo ocrmypdf --version
6.1.2
```

**Comment by jbarlow83** [comment]
@RalfKo You may need to create a virtual environment and install ocrmypdf in that.
