### ISSUE TITLE
How to actually search the generated PDF/As

### ISSUE THREAD

**Issue by bendspoons** [jbarlow83/OCRmyPDF#463]
Maybe im mislead by my brain, but how do i search, lets say 1000, converted PDFs? Seems like its obvious to everybody except me, cause i couldnt find a single bit about that....

**Comment by jbarlow83** [comment]
Usually I use the poppler `pdftotext` utility to generate individual text files for the content of each PDF and then run a search on the text files.

There are also programs that will index PDFs. e.g. Paperless, Mayan EDMS.

**Comment by femifrak** [comment]
Some pdf viewers like acrobat or foxit reader allow to search for words in pdfs below a certain directory.
I like pdfgrep very much.
Recoll creates a database and is therefore much faster.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
