### ISSUE TITLE
Error - text already exist

### ISSUE THREAD

**Issue by wisdomlight** [jbarlow83/OCRmyPDF#467]
the command `ocrmypdf --sidecar output.txt input.pdf output.pdf` is supposed to create two extra files the pdf with the searchable text and a .txt file only with the text.

I am interested in the .txt file
When I ocrmypdf i get the` Error:  1: page already has text! – aborting (use --force-ocr to force OCR)` which reading the Docs means that the text is already searcable.
and so ocrmypdf does nothing and i cannot get my hands on the .txt file.
What can I do ??
Thank you

**Comment by jbarlow83** [comment]
You can use the third party tool `pdftotext` to extract the text that is already present in PDF.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
