### ISSUE TITLE
enhance status message

### ISSUE THREAD

**Issue by Binog** [jbarlow83/OCRmyPDF#468]
Hey, it would be nice to sho the path-to-file in the terminal to know how long the scan needs to Finnish the task.
Sometime it seems to lag.. and I am not sure, if I should kill the process..

are there any clues?

**Comment by Binog** [comment]
e.g.: 
"WARNING - Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata."
which one is it? no sign of which file to examine!

**Comment by jbarlow83** [comment]
Some of the console messages are obtuse. I'd like to improve them but I know people pattern match based on them in their scripts, so I try to keep them stable and treat changes to them as backward incompatible.

In any event - if you enable debug messages `-v1` you should be able to see a more detailed explanation of PDF/A metadata problems. Often the list of issue is brief but it can be quite complex and difficult to present in a human readable format.

**Comment by jbarlow83** [comment]
I think there are enough ways to customize this now. e.g. you can do a small Python script that calls `ocrmypdf.ocr()` after configuring logging according to your preferences. I'm reluctant to make this an argument.
