### ISSUE TITLE
ffi.error: symbol 'setMsgSeverity' not found in library '<None>'

### ISSUE THREAD

**Issue by mb720** [jbarlow83/OCRmyPDF#471]
**Describe the issue**

I just installed OCRmyPDF using `sudo pip install ocrmypdf` on Arch Linux. When trying to run OCRmyPDF using

    ocrmypdf in.pdf out.pdf

or

    ocrmypdf --version

I get this error:

    Traceback (most recent call last):
      File "/usr/bin/ocrmypdf", line 6, in <module>
        from ocrmypdf.__main__ import run
      File "/usr/lib/python3.8/site-packages/ocrmypdf/__init__.py", line 18, in <module>
        from . import helpers, hocrtransform, leptonica, pdfa, pdfinfo
      File "/usr/lib/python3.8/site-packages/ocrmypdf/leptonica.py", line 64, in <module>
        lept.setMsgSeverity(lept.L_SEVERITY_WARNING)
    ffi.error: symbol 'setMsgSeverity' not found in library '<None>': /usr/bin/python: undefined symbol: setMsgSeverity

I know about [this issue](https://github.com/jbarlow83/OCRmyPDF/issues/332) that hints at installing the missing dependency leptonica but `pip install  leptonica` produced the error:

    ERROR: Could not find a version that satisfies the requirement leptonica (from versions: none)
    ERROR: No matching distribution found for leptonica

**System:**

- OS: Arch Linux zurich 5.4.6
- OCRmyPDF Version: The one you get with `sudo pip install ocrmypdf`. I don't know the version number since `ocrmypdf --version` crashes.

**Comment by jbarlow83** [comment]
Specifically you need to install the ArchLinux package of leptonica
https://www.archlinux.org/packages/community/x86_64/leptonica/

There is no Python version. It's a C dependency, so pip cannot install it.

It's usually easiest to install the ArchLinux version of ocrmypdf (or whatever your platform is). Even if that is a little out of date it will usually satisfy all dependencies. Then use pip if you want to get a newer version, after getting the OS packaged version to work.

(Also, `sudo pip install` can get you into trouble depending on the OS. It can install things over top of files managed by the system package manager. I think they've resolved this by Python 3.8 but it's generally better to avoid it. See: https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice)
