### ISSUE TITLE
--rotate-pages not working - no hint why

### ISSUE THREAD

**Issue by philippendrulat** [jbarlow83/OCRmyPDF#481]
**Describe the issue**
I am trying to auto rotate pages during the OCR. My command is:
`docker run -it -v C:/Users/Philipp/Downloads:/tmp jbarlow83/ocrmypdf:latest -l eng --rotate-pages /tmp/rotatetest-90.pdf /tmp/result.pdf`
I already saw the issue https://github.com/jbarlow83/OCRmyPDF/issues/454 where I took the test pdf from. 
In older version of ocrmypdf (tested on 6.1.2) there is still the hint "pdf is facing.. confidence ... too low to rotate" but in the newest version in the docker container (9.4.0), there is no such hint.
My goal is to read this hint and give the user a list of pages that may be rotated, but the service was not confident enough. But since this hint seems to be missing, I see no possibility to do so.
This is the output:
`Scan: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 261.34page/s]
   INFO - Start processing 2 pages concurrent
   INFO - Using Tesseract OpenMP thread limit 3
OCR: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.0/2.0 [00:09<00:00,  4.59s/page]
WARNING - Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
JPEGs: 0image [00:00, ?image/s]
JBIG2: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 45.62item/s]
   INFO - Optimize ratio: 1.05 savings: 4.4%
   INFO - Output file is a PDF/A-2B (as expected)`

**To Reproduce**
See command 

**Example file**
See https://github.com/jbarlow83/OCRmyPDF/issues/454

**Expected behavior**
I want to see the hint that tesseract was not confident enough to rotate the page

**System:**

- OS: [Windows with docker]
- OCRmyPDF Version: [9.4.0]

**Comment by jbarlow83** [comment]
`ocrmypdf -v1 --rotate-pages` (debug messages) shows the hints

I will considering converting them back to info level messages.

**Comment by philippendrulat** [comment]
Okay thank you! I see it now.
Do you know what the original Threshold is?
And also, what the number means? I tried googling it but found only references to the lucene source code.

**Comment by jbarlow83** [comment]
The number is something like:
`likelihood of best direction / likelihood of worst direction`, i.e. 15 (default) means we are 15 times more confidence in the best direction.

Either way, it's an easily fooled test.

**Comment by jbarlow83** [comment]
Re-enabled message for next release
