### ISSUE TITLE
Provide tsv and hocr output files

### ISSUE THREAD

**Issue by ArlindNocaj** [jbarlow83/OCRmyPDF#483]
For some usecases the tsv or hocr files from tesseract might be very usefull for further processing.

Is it possible to provide these output files using cmd?

e.g. we could have
```bash
ocrmypdf  ...arguments... input.pdf output.tsv
ocrmypdf  ...arguments... input.pdf output.hocr
```

What would be the best way to add that?

**Comment by jbarlow83** [comment]
`ocrmypdf --tesseract-config tsv --tesseract-config hocr --keep-temporary-files` will generate the files you are looking for.

You could also use the API to automate capturing these files and then delete the temporary folder.

**Comment by yasoob** [comment]
@jbarlow83 I think we should mention this in the docs. I was looking for something similar and couldn't find how to do it via the docs. Only this issue had the solution. 

Thanks for maintaining such a wonderful piece of software ❤️
