### ISSUE TITLE
Container Folder Watching does not resume after restart of system and container

### ISSUE THREAD

**Issue by martinsteffel** [jbarlow83/OCRmyPDF#485]
**Describe the issue**
After Restart of the system and thus the container, folder watching does not resume / work anymore

**To Reproduce**
sudo docker run -d --restart always -v /media/scan:/input -v /mnt/scan:/output -e OCR_OUTPUT_DIRECTORY_YEAR_MONT=0  -i --name ocrmypdf --restart always --entrypoint python3 jbarlow83/ocrmypdf watcher.py  

**Example file**
Any File placed in the folder will not be processed. Even files that where being processed before system restart are not being processed when copied to the folder again.

**Expected behavior**
After restarting the system the container should resume watching the input-folder for new files and processing them with ocr.

**System:**
- OS: Linux Ubuntu 18.04 LTS Server

Thank

**Comment by jbarlow83** [comment]
Can you confirm that this docker command actually restarts the watcher.py observer? Try running it without `docker run -d` or in some way that you can monitor the container's standard output and see that the "Starting OCRmyPDF watcher" message reappears.

You could also login to the container and check if the mount points still reference the correct files on the host.

Docker is always going to be more fragile than a native instance especially if your watched folders are network folders mounted to the Docker host. Then you're two layers of abstraction away from the real file system.

**Comment by martinsteffel** [comment]
running it without -d does not resume the output when docker-demon is restarted (connection to the docker container´s output is lost when demon is stopped).
I confirmed the mount points remain connected when demon and container are restarted - the mountpoint for input is actually a local folder, no mapped drive. Output mountpoint is a mapped network drive but as i understand ist it is not being watched.

The Container log does not print any  information about restarting the watcher.
The log remains the same upon restarting and now just prints

_ 
Scan: 100%|██████████| 3/3 [00:00<00:00, 202.83page/s]
Starting OCRmyPDF watcher with config:
Input Directory: /input
Output Directory: /output
Output Directory Year & Month: False
New file: /input/alt/test - Kopie - Kopie.pdf.
Attempting to OCRmyPDF to: /output/test - Kopie - Kopie.pdf
OCR: 100%|██████████| 3.0/3.0 [00:07<00:00,  2.34s/page]
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Scan: 100%|██████████| 3/3 [00:00<00:00, 223.18page/s]
New file: /input/alt/test - Kopie - Kopie.pdf.
Attempting to OCRmyPDF to: /output/test - Kopie - Kopie.pdf
OCR: 100%|██████████| 3.0/3.0 [00:07<00:00,  2.34s/page]
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Scan: 100%|██████████| 3/3 [00:00<00:00, 253.31page/s]
New file: /input/test - Kopie - Kopie.pdf.
Attempting to OCRmyPDF to: /output/test - Kopie - Kopie.pdf
OCR: 100%|██████████| 3.0/3.0 [00:07<00:00,  2.41s/page]
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Scan: 100%|██████████| 3/3 [00:00<00:00, 211.30page/s]
New file: /input/test - Kopie - Kopie.pdf.
Attempting to OCRmyPDF to: /output/test - Kopie - Kopie.pdf
OCR: 100%|██████████| 3.0/3.0 [00:07<00:00,  2.55s/page]
JPEGs: 0image [00:00, ?image/s]
_
Seems like watcher is not being started again.

**Comment by martinsteffel** [comment]
Is there a parameter to the docker run command that causes watcher to restart or any other solution to the problem? Maybe handling folder-watch outside the container and starting the container on a per-file-basis when some new / changed files appear?

**Comment by jbarlow83** [comment]
It sounds to me like this is more an issue with Docker configuration or perhaps python-watchdog.

I have a feeling from what you've described a trivial script running python-watchdog only without ocrmypdf would have the same problem. Can I suggest you take this up with python-watchdog to see if they have guidance about using their program in Docker?

**Comment by martinsteffel** [comment]
It seems to be an issue with the "docker run" command.
Running the container with docker-compose seems to work as watcher seems to restart.
My docker-compose.yml contains the following definition:
_version: 2.0
services:
...
  ocrmypdf:
    restart: always
    container_name: ocrmypdf
    image: jbarlow83/ocrmypdf
    volumes:                                                                                                                  - '/media/scan:/input'
      - '/mnt/scan:/output'
    environment:
      - OCR_OUTPUT_DIRECTORY_YEAR_MONT=0
    entrypoint:
      - python3
    command: "watcher.py"_

Using this I can restart the host and watcher.py is still monitoring the input folder.
Thanks for the help and for the great software!

**Comment by jbarlow83** [comment]
Thanks - added docker-compose to docs

**Comment by martinsteffel** [comment]
Sorry, this was to quick.
Trying today unfortunately I realised that Folder Watching did not resume after Restart of the Server.
Probably the issue still persists.

**Comment by jbarlow83** [comment]
Again, please try to find a way to do this with a simple watchdog script
that copies files from A to B or similar because the issue is probably in
watchdog or your configuration of it.

**Comment by fimholz** [comment]
I also ran into this issue and like to share my changes to watcher.py for others. [This answer](https://stackoverflow.com/a/61207411) helped me.
```
...
from watchdog.events import PatternMatchingEventHandler, FileCreatedEvent
...
def main():
...
    handler = HandleObserverEvent(patterns=PATTERNS)
    # handling pre-existing files
    for file in os.listdir(INPUT_DIRECTORY):
        filename = os.path.join(INPUT_DIRECTORY, file)
        log.debug(f"Processing pre-existing file {filename}")
        event = FileCreatedEvent(filename)
        handler.on_any_event(event)
...
```
A few notes:
- I had to enable `OCR_USE_POLLING` in docker-compose, otherwise new added files, while processing another one at the same time, were not detected
- also `OCR_ON_SUCCESS_DELETE` should be enabled to prevent re-processing all the existing files every time the container restarts

There may exist better solutions and this one does no error-handling, but it seems to work well.
