### ISSUE TITLE
landscape orientation with 90 deg rotation not correctly handled

### ISSUE THREAD

**Issue by XuRuHang** [jbarlow83/OCRmyPDF#50]
I have a scanner that produces PDF files with lansdcape layout but with 90 degrees rotation. This kind of files is displayed correctly in nautilus file manager for example (Linux) as portrait file.
I have other scanned files from other scanner that produced portrait files directly. They are correctly handled.
As an example take attached test2.pdf which is a standard test print page scanned.
But in ocrmypdf I got a wrong file (see test2b.pdf)
[test2.pdf](https://github.com/jbarlow83/OCRmyPDF/files/129303/test2.pdf)
[test2b.pdf](https://github.com/jbarlow83/OCRmyPDF/files/129304/test2b.pdf)

**Comment by HuitingLiu** [comment]
I encounter the same problem.

**Comment by jbarlow83** [comment]
Fixed in v4.0
