### ISSUE TITLE
file permissions after ocr with docker

### ISSUE THREAD

**Issue by deisi** [jbarlow83/OCRmyPDF#500]
**Describe the issue**
I use the docker container with watcher to run ocr on scanned files. All ocr results are owned by root after scan. I guess that is due to docker running as root.  Is there any way having the watcher of ocrmypdf eg. run a `chmod 776` after the successful orc? Or maybe change the owner with `chown`?

**Comment by deisi** [comment]
After inspecting the watcher.py I figured this is currently not possible. Thus I made a PR adding this posibility to water.py. https://github.com/jbarlow83/OCRmyPDF/pull/501

**Comment by jbarlow83** [comment]
As noted, discussion moved to #501
