### ISSUE TITLE
Bash autocompletion not workin on MacOS 10.14

### ISSUE THREAD

**Issue by AlexanderWillner** [jbarlow83/OCRmyPDF#502]
**Describe the issue**
Bash autocompletion not working on MacOS 10.14. Error: `-bash: _init_completion: command not found`

**To Reproduce**

```bash
ocrmypdf  <tab> <tab>
```

**Example file**
none

**Expected behavior**
Autocompletion of PDF files.

**System:**

- OS: macOS 10.14.6 (18G3020)
- OCRmyPDF Version: 9.6.0

**Additional context**
Other bash autocompletion scripts are working. Maybe have a look how others are [implementing](https://github.com/rclone/rclone/blob/ae340cf7d93fe394deb6b723805cbd2259c5bce3/cmd/help.go#L43) and [fixing](https://gitlab.kitware.com/cmake/cmake/commit/2ecf168f19096e63c43f3c524d1e43218446e3c3) this. Probably [this issues](https://github.com/mobile-shell/mosh/issues/675) explains the underlying issue best ([homebrew](https://brew.sh) / ancient bash related).

**Comment by jbarlow83** [comment]
Is there any chance you can submit a PR to address this? I tried blind-copying both the cmake and mosh fixes but both produces syntax errors in macOS bash. I don't know how bash completions work under the hood or where one finds the documentation about these magic functions and variables it uses. This script was contributed by another user in #384.

**Comment by jbarlow83** [comment]
@FPille Pinging you too to see if you can help with this issue.
