### ISSUE TITLE
[Feature Request] OCR only specific pages

### ISSUE THREAD

**Issue by gorgobacka** [jbarlow83/OCRmyPDF#503]
**Describe the issue**
Often, I have the issue that I want to perform OCR only on a subset of pages. All other pages do not make any sense to perform OCR and result in many false positives.

Therefore, it would be nice to have a command line argument to specify the pages (e.g. --pages 1-3,6). For all other pages use "--tesseract-timeout 0" per default.

Thanks for the great software.

**Comment by jbarlow83** [comment]
There is an argument `--pages` in recent versions that works in the way you describe.

**Comment by gorgobacka** [comment]
Oh, really? That's fantastic. (I searched the documentation before, but haven't seen it.)

I will try it. Thanks for the fast reply.

**Comment by homocomputeris** [comment]
@jbarlow83 Is ocrmypdf supposed to scan all the pages when it's passed `--pages`?
```
ocrmypdf --pages 17 --tesseract-timeout=0 book.pdf output.pdf
Scan:   1%|▍               | 3/233 [00:02<02:57,  1.29page/s]
```
Can this scanning be skipped without extracting the page from the PDF?
