### ISSUE TITLE
File size increase - monochrome with color profile promoted to full RGB

### ISSUE THREAD

**Issue by jens-f** [jbarlow83/OCRmyPDF#506]
**Describe the issue**
When producing black and white PDF files with my scanner and then processing them with OCRmyPDF, I'm getting a warning every single time about the files size increase. 
```
Scan: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 457.00page/s]
   INFO - Using Tesseract OpenMP thread limit 3
OCR: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.0/1.0 [00:00<00:00,  1.08page/s]
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
   INFO - Optimize ratio: 1.00 savings: 0.0%
   INFO - Output file is a PDF/A-2B (as expected)
WARNING - The output file size is 1.91× larger than the input file.
No reason for this increase is known.  Please report this issue.
```

The size increase is usually around 2x to 3x. 

**To Reproduce**

```bash
ocrmypdf --skip-text input.pdf output.pdf
```

**Example file**
[input.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4303823/input.pdf)

Please check any or all that apply about the test file:

- [x] This is the input file
- [x] The file contains no personal or confidential information
- [x] I am the copyright holder for this file
- [x] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [ ] I am not the copyright holder, but this file is available under a free software license

Files that are not free for inclusion in this project are quite welcome, but we like to collect free files for our test suite when possible. Please do *not* submit files with confidential information. At your option you may encrypt files for OCRmyPDF's author only.

**Expected behavior**
The file size increase should be small (to account for the include text layer) but not double or tripple. 

**System:**

- OS: macOS 10.14.6
- OCRmyPDF Version: 9.6.0

**Additional context**

This issue started to happen a while ago (maybe 1 to 2 years ago) with a then newer version of OCRmyPDF. Ever since then I have been following the improvements and similar issues but so far the issue has persisted.

**Comment by jbarlow83** [comment]
Issue is that the file contains a 1 bit/component image with ICC profile and we don't inspect the ICC profile to see if it's grayscale, so it gets promoted to full color.

**Comment by jbarlow83** [comment]
After being taught to consult ICC profiles, we produce a pngmono for Ghostscript, but Ghostscript still converts to full color because of our ColorConversionStrategy. DeviceIndependentColor works. Work continues....

**Comment by jens-f** [comment]
Thanks for investigating. Is there a way trough command line parameters to force it to use black and white (instead of converting to grayscale or full color) - in case that's easier to implement then a fully automatic handling?

**Comment by jbarlow83** [comment]
There's no command line parameter. What I was documenting was, I found have a way to fix it, but I don't fully understand what the fix does or what the implications would be for other files, so I'm holding off until I can find a satisfactory explanation. Unfortunately the Ghostscript documentation is rather thin on this subject.

**Comment by jens-f** [comment]
I reran `ocrmypdf --skip-text input.pdf output.pdf` with version 12.6.0 of ocrmypdf.
I'm happy to report that size increase is gone and the output file is actually smaller again as in the past. Please see output below.

Out of curiosity, was this a fix made by ocrmypdf or through Ghostscript?

Output:
```
Scanning contents: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.21page/s]
OCR: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.0/1.0 [00:01<00:00,  1.28s/page]
Postprocessing...
PDF/A conversion: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.02page/s]
JPEGs: 0image [00:00, ?image/s]
JBIG2:   0%|                                                                                                                                     | 0/1 [00:00<?, ?item/s]
Optimize ratio: 1.14 savings: 11.9%
Output file is a PDF/A-2B (as expected)
```

file sizes:
```
input.pdf: 37958 bytes
output.pdf: 18931 bytes 
```

**Comment by jens-f** [comment]
Understand. Thanks for building this great tool! Closing this issue
