### ISSUE TITLE
Python stuck in loop

### ISSUE THREAD

**Issue by savageja** [jbarlow83/OCRmyPDF#517]
**Describe the issue**
OCRmyPDF runs without issue via the command line but when run from python gets stuck in a loop and keeps creating the origin.pdf in a new temp folder repeatedly until the program is killed

**To Reproduce**
In python 3.7.7 ocrmypdf.ocr('input.pdf', 'output.pdf')

```bash
This works fine
OCRmyPDF.exe input.pdf output.pdf
```
**System:**

- OS: Windows 10
- OCRmyPDF Version: 9.6.1

**Additional context**
I have also tried starting with a single png image and it gives the same issue converting this to origin.pdf continously into new temp folders

**Comment by jbarlow83** [comment]
Can you provide an example of your input.pdf and png image?

The function `ocrmypdf.ocr()` is exercised hundreds of times in the test suite, on all platforms including Windows 10.

**Comment by savageja** [comment]
This was the pdf and the png I was using. As I mentioned it converted fine
when using the command line but not when I use it via python3.

Thanks
James

**Comment by savageja** [comment]
It happens with all pdfs I have tried, they all work fine from the Command Window but loops when in the Python Function.
I have attached a sample PDF that it does the same on
[scansmpl.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4398594/scansmpl.pdf)

**Comment by jbarlow83** [comment]
I still can't reproduce this. Can you run 
```python
ocrmypdf.configure_logging(logging.DEBUG, manage_root_logger=True)
ocrmypdf.ocr('input.pdf', 'output.pdf')
```
and send me the output?

You could also try setting a breakpoint in the function `ocrmypdf._pipeline.triage()` and stepping through.

Also, is `input.pdf` already in a temp folder?

**Comment by savageja** [comment]
It gets to here before it starts looping on the creation of the temp foler and the origin.pdf

ocrmypdf._validation -   DEBUG - No language specified; assuming --language eng
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--list-langs']
ocrmypdf.exec.gswin64c -   DEBUG - Running: ['gswin64c', '--version']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--version']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--version']
ocrmypdf.exec -   DEBUG - Found tesseract v5.0.0-alpha.20200223
ocrmypdf.exec -   DEBUG - Found gs 9.52
ocrmypdf.exec -   DEBUG - Found qpdf 9.0.2
ocrmypdf.exec.gswin64c -   DEBUG - Running: ['gswin64c', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=txtwrite', '-dTextFormat=0', '-o', '-', 'C:\\Users\\James\\AppData\\Local\\Temp\\com.github.ocrmypdf.nu1cyxe7\\origin.pdf', '-sstdout=%stderr']

Scan:   0%|          | 0/1 [00:00<?, ?page/s]
Scan: 100%|██████████| 1/1 [00:00<00:00, 21.33page/s]
ocrmypdf -    INFO - Using Tesseract OpenMP thread limit 3

OCR:   0%|          | 0.0/1.0 [00:00<?, ?page/s]

I have attached a copy of the folders etc that are created
![output](https://user-images.githubusercontent.com/62811114/77885776-8c540e80-725f-11ea-8831-a82ef260f3e8.PNG)

Could you give me the options for the triage as I lept getting an errro when I tired to run it.

**Comment by jbarlow83** [comment]
Try 9.7.0.
I made a change that might have had an effect -  #515 
Not sure though

**Comment by savageja** [comment]
I am afraid it does the same, except in the temp folder it now leaves origin.pdf and origin (with no extension) both files are the same size

**Comment by jbarlow83** [comment]
Another thing to try: `ocrmypdf.ocr(...use_threads=True)`

Does the script that calls `ocrmypdf.ocr()` have a `if __name__ == "__main__"` guard?

**Comment by savageja** [comment]
Another thing to try: ocrmypdf.ocr(...use_threads=True)
This solved the problem, worked straight away :)

For info. for debugging this wasnt part of a larger script the whole script was 
import ocrmypdf
ocrmypdf.ocr('input.pdf', 'output.pdf')

**Comment by jbarlow83** [comment]
Good! On Windows, you either need to use threads or ifmain guard. You might get performance with

```python
import ocrmypdf
if __name__ == "__main__":
    ocrmypdf.ocr('input.pdf', 'output.pdf')
```
