### ISSUE TITLE
OCRmyPDF on WSL

### ISSUE THREAD

**Issue by Johnnyt12** [jbarlow83/OCRmyPDF#519]
**Describe the issue**
I followed the instructions for installing OCRmyPDF on Windows Subsystem for Linux provided by the documentation. After creating a symlink to use ocrmpdf in the Windows command prompt (typing "wsl sudo ln -s  /home/user/.local/bin/ocrmypdf /usr/local/bin/ocrmypdf"), every command results in:

/bin/bash: ocrmypdf: command not found

**To Reproduce**
Install OCRmyPDF on WSL following the documentation. Enter "wsl ocrmypdf --version".

**Expected behavior**
Using OCRmyPDF in Windows command prompt or Powershell.

**System:**
- Windows 10 Pro 
- Ubuntu 18.04 LTS
- OCRmyPDF Version: 9.6.1

**Additional context**
Using OCRmyPDF within the WSL Shell itself does work well.

**Comment by caiofacchinato** [comment]
You need change the "user" for your user inside wsl, in my case:

Example: "wsl sudo ln -s /home/**user**/.local/bin/ocrmypdf /usr/local/bin/ocrmypdf"
Correct: "wsl sudo ln -s /home/**caiofs**/.local/bin/ocrmypdf /usr/local/bin/ocrmypdf"

**Comment by jbarlow83** [comment]
Thanks. Will correct the documentation
