### ISSUE TITLE
Running 9.6.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by jfs-egs** [jbarlow83/OCRmyPDF#521]
Running 9.6.1 on Ubuntu 18.04.  II can operate from the command line and in a bash script, so long as I hard-code the input and output files.  When I use bash variables in double quotes (' " ' ${startvar} ' " ', e.g.), I get: ocrmypdf: error: unrecognized arguments: part of path/to start var" "/full path/to endvar/test.pdf"  Is there a way to run ocrmypdf with bash variables? I need the double quotes because the paths contain space.

**Comment by jbarlow83** [comment]
It sounds like this is a general question about using bash, not anything specific to ocrmypdf.

**Comment by jfs-egs** [comment]
Well, it is not if you say it is not.  If you have experience using variables with ocrmypdf in bash, I presume you would say so.  If not, it might have to do with bash or it might have to do with ocrmypdf.

**Comment by jbarlow83** [comment]
There is nothing unusual about how ocrmypdf handles command line arguments. As the bash documentation should explain, it does not share local variables with any subprocess; it expands them first.
