### ISSUE TITLE
Can't run ORCmyPDF as daemon by crontabs

### ISSUE THREAD

**Issue by pedrohcmds** [jbarlow83/OCRmyPDF#522]
**Describe the issue**
I've been triyng to make a watcher to OCR all files in a directory, and it's done (Here's the script - teste.sh):

```
#!/bin/bash
# set path to watch
DIR="/media/lantrivm03-hd01/labri_pedro/awesomeocr/OCRmyPDF/Arquivos/input" 
# set path to copy the script to
target_dir="/media/lantrivm03-hd01/labri_pedro/awesomeocr/OCRmyPDF/Arquivos/processamento" 

inotifywait -m -r -e moved_to -e create "$DIR" --format "%f" | while read f

do
    echo $f
    # check if the file is a .sh file
    if [[ $f = *.pdf ]]; then
      # if so, copy the file to the target dir
      mv "$DIR/$f" "$target_dir" 
      # and rum it
    ocrmypdf $target_dir/$f "/media/lantrivm03-hd01/labri_pedro/awesomeocr/OCRmyPDF/Arquivos/output/"$f
    echo "$f removido" 
    rm "$target_dir/$f" 
    echo "OCR de $f concluído com sucesso" 

    fi
done

```
I've put it to run from crontabs from a intermediary script to run from /urs/bin (chamador.sh)

```
#! /bin/bash

cd  /media/lantrivm03-hd01/labri_pedro/awesomeocr/OCRmyPDF/Arquivos && ./teste.sh

```
But i can't run it in background everytime my oc reboot, for this i've tried to create a a crontab:

 `@reboot chamador.sh >> /media/lantrivm03-hd01/labri_pedro/awesomeocr/OCRmyPDF/Arquivos/erros.log`

But the script can't do the OCRs even if all massages are in the log file. How may i fix it?

**Comment by jbarlow83** [comment]
There is a watcher script in `misc/watcher.py` and documentation on its use at ocrmypdf.readthedocs.io. Please have a look at that first.

I suggest using systemd rather than cron to manage it, since it does a better job of ensuring multiple instances of the script do not run simultaneously.

**Comment by pedrohcmds** [comment]
Thanks a lot! It's working perfectly with systemd. I had some problems with watcher.py, but now this shell is working pretty good.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
