### ISSUE TITLE
Latest version on homebrew is broken with ghostscript 9.52

### ISSUE THREAD

**Issue by mmathys** [jbarlow83/OCRmyPDF#525]
**Describe the bug**
The latest version is not tagged or uploaded on Homebrew.

**To Reproduce**

```bash
brew update
brew install ocrmypdf
brew upgrade ocrmypdf
ocrmypdf  --version
```

**Expected behavior**
Installs version 9.7.0

**Actual behavior**
Only installs 9.6.1

**System**
 - OS: macOS
 - How did you install ocrmypdf: brew

**Comment by mmathys** [comment]
This is important since version ocrympdf 9.6.1 is broken with the latest ghostscript (9.52), but ocrympdf 9.7.0 works again.

**Comment by jbarlow83** [comment]
PR here
https://github.com/Homebrew/homebrew-core/pull/52709/

**Comment by mmathys** [comment]
very cool

**Comment by mmathys** [comment]
I appreciate your work, @jbarlow83
