### ISSUE TITLE
Position of text not accurate. 

### ISSUE THREAD

**Issue by karasjoh000** [jbarlow83/OCRmyPDF#530]
`ocrmypdf -l eng --rotate-pages --deskew --title "My PDF" --jobs 4 --output-type pdfa in.pdf out.pdf`  
Created a OCR pdf with command above and position of text is not accurate. See gif below. It skips the last letter and highlights the space after it. 
![Apr-10-2020 11-25-29](https://user-images.githubusercontent.com/21280439/79013786-4d0aa500-7b1e-11ea-82e4-8b499e5c1154.gif)

**Comment by jbarlow83** [comment]
This is mainly a Tesseract issue for which is possible fix exists but is not yet accepted.
https://github.com/tesseract-ocr/tesseract/issues/2879

It is also to some extent a PDF viewer dependent behavior. Poor PDF viewers (macOS Preview) will look worse than better ones (Acrobat).

You can get better results from ocrmypdf with `--pdf-renderer hocr` at the cost of being limited to the Latin alphabet.

**Comment by jcuenod** [comment]
Is there any update on this?

**Comment by shadylpstan** [comment]
Any update on this please? Or do we have any web PDF viewer which can handle this.
