### ISSUE TITLE
OCRmyPDF fails due to wrong version comparison (qpdf)

### ISSUE THREAD

**Issue by publicimageltd** [jbarlow83/OCRmyPDF#531]
**Describe the bug**
Calling  OCRmyPDF fails because it demands qpdf > version 8, even though version 10 is installed. Seems like the version numbers are compared the wrong way.

**To Reproduce**
What command line or API call were you trying to run?

```bash
$ ocrmypdf -l deu original.pdf output.pdf
  ERROR - 
OCRmyPDF requires 'qpdf' 8.0.2 or higher.  Your system appears
to have 10.0.1.  Please update this program.
   INFO - 
On systems with the aptitude package manager (Debian, Ubuntu), try these
commands:
    sudo apt-get update
    sudo apt-get install qpdf

On RPM-based systems (Red Hat, Fedora), search for instructions on
installing the RPM for qpdf.
  ERROR -
```

Run with verbosity or higher `-v1` to see more detailed logging. This information may be helpful.

**Expected behavior**
Expected to accept the installed version of qpdf, since "10" is higher than "8"

**System**
 - OS: Arch Linux
 - OCRmyPDF Version: ``9.7.0.post1+gc152710``
 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image?
Installed from cloned git repo.

**Comment by jbarlow83** [comment]
#527
