### ISSUE TITLE
Installing dependencies for ocrmypdf: ffmpeg and unpaper Error: ffmpeg is already installed from homebrew-ffmpeg/ffmpeg!

### ISSUE THREAD

**Issue by walksonair** [jbarlow83/OCRmyPDF#533]
Trying to install on Mac OS Catalina 10.15.4 using "brew install ocrmypdf" and receive install failure stating 

`==> Installing dependencies for ocrmypdf: ffmpeg and unpaper
Error: ffmpeg is already installed from homebrew-ffmpeg/ffmpeg!
Please 'brew uninstall ffmpeg' first."`

Should I really uninstall my tapped FFmpeg installation first? I have a custom install w/ some options that I couldn't get with a default FFmpeg install.

Please advise and thank you for your great work!

**Comment by jbarlow83** [comment]
The dependency chain is

Ocrmypdf -> unpaper -> ffmpeg

Strictly speaking the ocrmypdf-unpaper dependency is optional, but homebrew
policy is to opt-in all the time. You could manually edit ocrmypdf.rb to
drop the dependency on unpaper and ffmpeg if you don't need those features.

You might be able to get away with
Uninstall custom ffmpeg
Install ocrmypdf
Brew unlink ffmpeg (not uninstall)
Brew install custom ffmpeg

**Comment by walksonair** [comment]
A perfect solution for me. Thank you!
