### ISSUE TITLE
"OCRmyPDF requires 'qpdf' 8.0.2 or higher.  Your system appears to have 10.0.1.  Please update this program"

### ISSUE THREAD

**Issue by hista** [jbarlow83/OCRmyPDF#536]
**Describe the bug**
When I try to launch ocrmypdf, I get this error message:

> OCRmyPDF requires 'qpdf' 8.0.2 or higher.  Your system appears to have 10.0.1.  Please update this program

ocrmypdf is already up-to-date, qpdf too.

Should I actually _downgrade_ qpdf, or is there a better fix?

**System**
 - OS: Linux, debian sid
 - OCRmyPDF Version: 9.6.0+dfsg
 - How did you install ocrmypdf? apt-get or pip, I think I tried both :D

Thanks for your kind help :)

**Comment by jbarlow83** [comment]
Ocrmypdf 9.6.0 is the most recent version on Debian. You will have to wait
for Debian to update or install 9.7.2 yourself.

**Comment by hista** [comment]
Hi,
and thanks for your quick answer!
Good news: debian updated it this morning, I could update to ocrmypdf version
9.7.2+dfsg from apt-get.

Thanks for your good job, your software is great!
