### ISSUE TITLE
Japanese language produces UTF-8 decode error 

### ISSUE THREAD

**Issue by PythonNut** [jbarlow83/OCRmyPDF#543]
**Describe the bug**
Here is an example command and the resulting output
```
$ ocrmypdf -v2 -l jpn a b
ocrmypdf -   DEBUG - ocrmypdf 9.7.2
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--list-langs']
ocrmypdf.exec.gs -   DEBUG - Running: ['gs', '--version']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '-l', 'jpn', '--print-parameters', 'pdf']
ocrmypdf -   ERROR - 'utf-8' codec can't decode byte 0xb0 in position 29486: invalid start byte
```
Note that `a` does not need to be a real file. The error is produced before `ocrmypdf` checks if it exist.

The output of `tesseract -l jpn --print-parameters pdf` can be found [here](http://ix.io/2jPA). Although admittedly if there is a unicode error in the output then this may not faithfully represent the error.

The decoding error is caused by the following line in the above output, reproduced here in escaped form:
```
tessedit_char_blacklist\t\xb0\t
```

**Expected behavior**
Ideally, OCRmyPDF should progress to the point where it checks if `a` exists.

**System**
 - OS: Arch Linux with [`tesseract-data-jpn`](https://www.archlinux.org/packages/community/any/tesseract-data-jpn/) and [`tesseract 4.1.1-1`](https://www.archlinux.org/packages/community/x86_64/tesseract/). The same results were obtained with [`tesseract-data-jpn-git`](https://aur.archlinux.org/packages/tesseract-data-jpn-git/).
 - OCRmyPDF Version: `9.7.2`
 - How did you install ocrmypdf? Using [`AUR/ocrmypdf`](https://aur.archlinux.org/packages/ocrmypdf/). The same results were obtained with [`AUR/ocrmypdf-py3`](https://aur.archlinux.org/packages/ocrmypdf-py3/).

**Comment by jbarlow83** [comment]
Please make sure your locale is set to something in UTF-8 and use Python
3.7 or newer. E.g. the environment variable LANG should contain ".utf-8".

**Comment by PythonNut** [comment]
> Please make sure your locale is set to something in UTF-8 . . . E.g. the environment variable LANG should contain ".utf-8".

On my system, I have
```
$ echo $LANG
en_US.UTF-8
```

> use Python 3.7 or newer
My Python version is `3.8.2`.
