### ISSUE TITLE
Processing multiple files in a batch and it hangs

### ISSUE THREAD

**Issue by scott8** [jbarlow83/OCRmyPDF#544]
**Describe the bug**
Processing hangs.

**To Reproduce**
I kicked this off on my system. 

```find . -iname \*.PDF -exec echo {} \; -exec ocrmypdf --verbose --optimize 0 {} {} \; > /mnt/pdrive/ocrmypdf_output.txt 2>&1&```

The PDF file is 51MB so I can't upload it here.  Here is a link to the file:
https://drive.google.com/file/d/1KHcnqpl3yBC4TTObVae0_Ua10K_bAAIo/view?usp=sharing

According to the log, it had not selected another input file. This is the 173'rd PDF it processed out of about 7700.

Here's the log. There is nothing following:

./Maker/HackSpace Magazine/HackSpaceMag06.pdf
  DEBUG - ocrmypdf 9.6.0+dfsg
  DEBUG - Running: ['tesseract', '--list-langs']
  DEBUG - Running: ['gs', '--version']
  DEBUG - Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
  DEBUG - Running: ['tesseract', '--version']
  DEBUG - Running: ['tesseract', '--version']
  DEBUG - Found tesseract 4.1.1
  DEBUG - Found gs 9.50
  DEBUG - Found qpdf 9.1.1
  DEBUG - os.symlink(./Maker/HackSpace Magazine/HackSpaceMag06.pdf, /tmp/com.github.ocrmypdf.viv4860k/origin)
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.viv4860k/origin, /tmp/com.github.ocrmypdf.viv4860k/origin.pdf)
  DEBUG - Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=txtwrite', '-dTextFormat=0', '-o', '-', '/tmp/com.github.ocrmypdf.viv4860k/origin.pdf', '-sstdout=%stderr']
   INFO - Start processing 4 pages concurrently
  DEBUG -    2: Rasterize with png16m
  ERROR - PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR)

ps -e f shows this:
438510 pts/1    S      0:00  \_ find . -iname *.PDF -exec echo {} ; -exec ocrmypdf --verbose --optimize 0 {} {} ;
 441085 pts/1    SNl    0:11      \_ /usr/bin/python3 /usr/bin/ocrmypdf --verbose --optimize 0 ./Maker/HackSpace Magazine/HackSpaceMag06.pdf ./Maker/HackSpace Magazine/HackSpaceMag06.pdf

Here's the details when I try to OCR that file by itself:

$ ocrmypdf -v2 --optimize 0 HackSpaceMag06.pdf HackSpaceMag06_ocr.pdf 
ocrmypdf -   DEBUG - ocrmypdf 9.6.0+dfsg
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--list-langs']
ocrmypdf.exec.gs -   DEBUG - Running: ['gs', '--version']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--version']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--version']
ocrmypdf.exec -   DEBUG - Found tesseract 4.1.1
ocrmypdf.exec -   DEBUG - Found gs 9.50
ocrmypdf.exec -   DEBUG - Found qpdf 9.1.1
ocrmypdf.helpers -   DEBUG - os.symlink(HackSpaceMag06.pdf, /tmp/com.github.ocrmypdf.do30q4i_/origin)
ocrmypdf.helpers -   DEBUG - os.symlink(/tmp/com.github.ocrmypdf.do30q4i_/origin, /tmp/com.github.ocrmypdf.do30q4i_/origin.pdf)
ocrmypdf.exec.gs -   DEBUG - Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=txtwrite', '-dTextFormat=0', '-o', '-', '/tmp/com.github.ocrmypdf.do30q4i_/origin.pdf', '-sstdout=%stderr']

Scan: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [00:04<00:00, 27.11page/s]
ocrmypdf -    INFO - Start processing 4 pages concurrently
ocrmypdf -   DEBUG -    2: Rasterize with png16m                                                                                                                                              
ocrmypdf -   DEBUG -    2: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=2', '-dLastPage=2', '-r180.072325x180.072325', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/com.github.ocrmypdf.do30q4i_/origin.pdf']
ocrmypdf.exec.gs -   DEBUG - Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=2', '-dLastPage=2', '-r180.072325x180.072325', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/com.github.ocrmypdf.do30q4i_/origin.pdf']
OCR:   0%|                                                                                                                                                      | 0.0/132.0 [00:00<?, ?page/s]
ocrmypdf._sync -   ERROR - PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR)
scott@ODROID-H2:~/tmp$

**Expected behavior**
Continued processing.

**System**
 - OS: Ubuntu 20.04 LTS
 - OCRmyPDF Version: $ 9.6.0+dfsg
 - How did you install ocrmypdf? Synaptic Package Manager.

**Comment by jbarlow83** [comment]
If I'm not mistaken the command you supplied did not hang; rather, it was set up in such a way that it stop processing if an error occurred.

The error was:
ERROR - PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR)

See here for a description of why this happens and what actions you can take
https://ocrmypdf.readthedocs.io/en/latest/errors.html

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
