### ISSUE TITLE
ImportError: cannot import name 'uint_value' from 'pdfminer.pdftypes' (/home/zber/anaconda3/lib/python3.7/site-packages/pdfminer/pdftypes.py)

### ISSUE THREAD

**Issue by Henry-nlp** [jbarlow83/OCRmyPDF#547]
**Describe the bug**
when run "import ocrmypdf", it appears
ImportError: cannot import name 'uint_value' from 'pdfminer.pdftypes' (/home/zber/anaconda3/lib/python3.7/site-packages/pdfminer/pdftypes.py)

about 2 weeks ago, it didn't appear this error when I tried.

**To Reproduce**

```bash
import ocrmypdf
```

![screenshot 1](https://user-images.githubusercontent.com/12026761/80565516-38d20d80-8a23-11ea-8a21-12aef8ee7e5b.png)
![screenshot 2](https://user-images.githubusercontent.com/12026761/80565520-3b346780-8a23-11ea-9409-3faab5094a7f.png)

**System**
 - OS: [Ubuntu 18.04]
 - OCRmyPDF Version: ``ocrmypdf --Latest version``
 - I tried both "pip install ocrmypdf" and "apt-get install ocrmypdf" to install.

**Comment by jbarlow83** [comment]
Your Python installation involves anaconda in some way, and I'm really not sure what's going on with that. I suspect you somehow have `pdfminer` installed instead of `pdfminer.six`.

Maybe try to uninstall or disable anaconda? Try using the system Python /usr/bin/python explicitly?

**Comment by Henry-nlp** [comment]
Yeah, you're right! It's because of the python version. It worked when I used the /usr/bin/python3.6.

Best regards

**Comment by SWT-chem** [comment]
> Your Python installation involves anaconda in some way, and I'm really not sure what's going on with that. I suspect you somehow have `pdfminer` installed instead of `pdfminer.six`.
> 
> Maybe try to uninstall or disable anaconda? Try using the system Python /usr/bin/python explicitly?

I ended up resolving this issue by removing the 'pdfminer' package directory and reinstalling 'pdfminer.six'.
