### ISSUE TITLE
Brewfile does not exist as listed in documentation for manual macOS install

### ISSUE THREAD

**Issue by Geordon** [jbarlow83/OCRmyPDF#553]
https://ocrmypdf.readthedocs.io/en/latest/installation.html#manual-installation-on-macos

Documentation mentions downloading a Brewfile but the file does not exist on GitHub:

wget https://github.com/jbarlow83/OCRmyPDF/raw/master/.travis/Brewfile
--2020-05-03 17:23:09--  https://github.com/jbarlow83/OCRmyPDF/raw/master/.travis/Brewfile
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-03 17:23:10 ERROR 404: Not Found.

**Comment by jbarlow83** [comment]
Use the list of packages specified in azure-pipelines.yml or ``brew edit ocrmypdf``. The dependencies usually aren't much different from what is listed in these places.

**Comment by Geordon** [comment]
I thought you might want to update the documentation to reflect that.

**Comment by jbarlow83** [comment]
I did, just not pushed yet... thanks
