### ISSUE TITLE
An exception occurred while executing the pipeline: StopIteration

### ISSUE THREAD

**Issue by Denis-Oakley** [jbarlow83/OCRmyPDF#555]
**Describe the bug**
An exception occurred while executing the pipeline: StopIteration

**To Reproduce**

```bash
$ ocrmypdf -v1 -l chi_sim+eng /home/*/计算机组成与设计:硬件,软件接口_第4版.pdf /home/*/计算机组成与设计:硬件,软件接口_第4版_.pdf
DEBUG - ocrmypdf 9.8.0
DEBUG - Running: ['tesseract', '--list-langs']
DEBUG - Running: ['gs', '--version']
DEBUG - Running: ['tesseract', '-l', 'chi_sim+eng', '--print-parameters', 'pdf']
DEBUG - Running: ['tesseract', '--version']
DEBUG - Running: ['tesseract', '--version']
DEBUG - Found tesseract 4.1.1
DEBUG - Found gs 9.52
DEBUG - Found qpdf 10.0.1
DEBUG - os.symlink(/home/*/计算机组成与设计:硬件,软件接口_第4版.pdf, /tmp/com.github.ocrmypdf.ftz8rvld/origin)
DEBUG - os.symlink(/tmp/com.github.ocrmypdf.ftz8rvld/origin, /tmp/com.github.ocrmypdf.ftz8rvld/origin.pdf)
Scan:   0%|                                                                                    | 0/552 [00:01<?, ?page/s]
ERROR - An exception occurred while executing the pipeline
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 384, in run_pipeline
pdfinfo = get_pdfinfo(
File "/usr/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 149, in get_pdfinfo
return PdfInfo(
File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 765, in __init__
self._pages, pdf = _pdf_get_all_pageinfo(
File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_get_all_pageinfo
page = PageInfo(pdf, n, infile, page_xml, detailed_analysis)
File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 651, in __init__
self._pageinfo = _pdf_get_pageinfo(pdf, pageno, infile, xmltext)
File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 578, in _pdf_get_pageinfo
miner = get_page_analysis(infile, pageno, pscript5_mode)
File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/layout.py", line 288, in get_page_analysis
interp.process_page(next(page))
StopIteration
```

Run with verbosity or higher `-v1` to see more detailed logging. This information may be helpful.

**Example file**
https://1drv.ms/b/s!AmT9nSObs5IDhzsXLoM9i_TlSFLd?e=b9jiqW

**Expected behavior**
ocrmypdf will not crash

**Screenshots**

**System**
 - OS: `Arch Linux`
 - OCRmyPDF Version: `9.8.0`
 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image?
```sh
yay -Sy ocrmypdf
pacman -Sy tesseract-data-chi_sim community/tesseract-data-eng
```

It looks like a PDF format problem, if so, I will change a PDF to read.

**Comment by jbarlow83** [comment]
You can use `qpdf test-file.pdf test-file-fixed.pdf` to fix some problems in the file. After that, it appears to work, but I did not try running to completion given its large file size.

The issue seems to be a problem with pdfminer.six interpreting this file, perhaps due to the problems that qpdf identifies.

**Comment by jbarlow83** [comment]
Please consider submitting a new issue at https://github.com/pdfminer/pdfminer.six - I suspect you'll find it fairly easy to trigger this same behavior with that program.

(If you like I could submit it for you but I'd prefer to not submit someone else's file.)

**Comment by Denis-Oakley** [comment]
Thanks. After running `qpdf test-file.pdf test-file-fixed.pdf`, OCRmyPDF works. So it isn't problem of OCRmyPDF.
