### ISSUE TITLE
[Question] How to extract text only?

### ISSUE THREAD

**Issue by matt32106** [jbarlow83/OCRmyPDF#559]
I would like to generate N .txt files from N .pdf with the txt files containing the result of ocrmypdf + any pre-existing text in the pdf. Is it possible?

**Comment by jbarlow83** [comment]
`pdftotext` (from poppler utils) will do this.

(ocrmypdf's `--sidecar` does not - that just gives you the OCR text.)

**Comment by matt32106** [comment]
So if I do orig.pdf > ocrmypdf > ocrd.pdf > pdftotext > result.txt I will get both the ocr'd text and the pre-existing text?

**Comment by jbarlow83** [comment]
That's correct.
You can even pipe it: `ocrmypdf orig.pdf - | pdftotext -enc UTF-8 - -`

**Comment by matt32106** [comment]
Thanks a lot
