### ISSUE TITLE
setup problem (setuptools_scm_git_archive)

### ISSUE THREAD

**Issue by Wikinaut** [jbarlow83/OCRmyPDF#56]
```
sudo pip3 install .
Processing /usr/local/src/OCRmyPDF
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm_git_archive/: [Errno 2] No such file or directory -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm-git-archive/: [Errno 2] No such file or directory -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm_git_archive' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 2] No such file or directory -- Some packages may not be found!
    No local packages or download links found for setuptools-scm-git-archive
...
```

System: openSUSE Tumbleweed

Please, can you assist ?

I have python3-setuptools_scm installed (1.10.1-1.1)

**Comment by jbarlow83** [comment]
Not sure, but a few things to try:

* setuptools_scm is more cooperative when working with a git clone as opposed to zipball.
* You could try explicitly the package it wants: https://pypi.python.org/pypi/setuptools_scm_git_archive
* Or perhaps try creating a virtual environment (`pyvenv`) and installing there?

**Comment by Wikinaut** [comment]
First: I already use (only) git versions.
Secondly: regarding https://pypi.python.org/pypi/setuptools_scm_git_archive , shouldn't the setup.py be corrected/modified ?

**Comment by Wikinaut** [comment]
Okay. Setup works after ```sudo pip3 install setuptools_scm_git_archive```.

**Comment by Wikinaut** [comment]
version say now ```4.0.5.post4+ng1734c01```. This looks okay.

**Comment by jbarlow83** [comment]
```
   ...
   setup_requires=[
        'setuptools_scm',
        'setuptools_scm_git_archive',
        'cffi>=1.5.0',
        'pytest-runner'
    ],
   ...
```

It's already in setup.py. Not sure why it caused trouble in your case.

**Comment by Wikinaut** [comment]
@jbarlow83 this is, why I filed this issue. I had the scm, but apparently not the scm-git, and such a test failed.
