### ISSUE TITLE
9.8.0 is 30-50% slower performance than 6.1.2

### ISSUE THREAD

**Issue by ctoma** [jbarlow83/OCRmyPDF#561]
**Describe the bug**
I've tested across many different combinations of ocrmypdf and tesseract and found in general upgrading to the latest version of ocrmypdf results in 30-50% performance decrease even when tesseract version remains the same.

Here are some results I collected, each test was run multiple times on a clean aws instance.
|Setup |  PDF 1 (2 pages) | PDF 2 (2 pages)|
|------------ | -------------|---------|
|ocrmypdf 6.1.2 (apt-get) + tesseract 4.0.0-beta.1 | 8900ms | 8800ms |
|ocrmypdf 9.8.0 + tesseract 4.0.0-beta.1  | 13000ms | 12600ms |
|ocrmypdf 9.8.0 + tesseract 5.0.0-alpha | 12000ms | 11700ms |

As we can see upgrading to the latest ocrmypdf results in slower performance. Upgrading tesseract to the latest version gives a marginal performance increase but still not much. Overall, using the latest versions of tesseract and ocrmypdf give much slower performance than simply using those in the apt repository. 

The 6.1.2 version is the standard one from the apt repository. When upgrading to 9.80 I followed the instructions in the docs exactly.

**To Reproduce**
All my documents I am running --force-ocr on, not sure if this is affecting it or not. 

```bash
ocrmypdf input.pdf output.pdf --force-ocr
```

**Example file**
Unable to include examples for confidentiality reasons but this behavior was universal for me regardless of file.

**System**
Ubuntu 18.04

Would be good to figure out what's causing this slowdown as I'm writing an application where speed is essential so any tips on how to improve this would be fantastic so I could use the latest version.

Thanks for the great library by the way.

**Comment by jbarlow83** [comment]
* Version 7 added PDF file and image optimization which takes some time. Use `-O0` to disable and set `--fast-web-view 0`. Likely the main reason.
* In the last few versions, OCRmyPDF added more checks to confirm that the PDF can processed safely and correct errors in input PDFs.
* A feature in Ghostscript we used to rely has become broken in recent versions, so I've removed that dependency in favour of a Python library which is slower. Older versions of Ghostscript like the one in Ubuntu 18.04 can still use this.
* The next major version will parallelize page scanning which brings some improvements.

There may be specific reasons why your files give lower performance, but if you can't produce non-confidential files or identify publicly available files with similar issues, I can't help you with anything more specific.

You can encrypt files with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by ctoma** [comment]
Adding `-O0` and `--fast-web-view 0` increases the speed as you predicted. 

The performance penalty when using latest version and these flags is only about 4-5% which is definitely acceptable given the extra error checking etc. 

Awesome, thanks!

**Comment by chiragbpatil** [comment]
> Adding `-O0` and `--fast-web-view 0` increases the speed as you predicted.
> 
> The performance penalty when using latest version and these flags is only about 4-5% which is definitely acceptable given the extra error checking etc.
> 
> Awesome, thanks!

while i am using -O0 and --fast-web-view 0 , output pdf is not generating.

**Comment by jbarlow83** [comment]
If this concerns v9.8.0, please use a newer version
