### ISSUE TITLE
page is facing ⇨, confidence 0.75 - confidence too low to rotate

### ISSUE THREAD

**Issue by SreenijaK** [jbarlow83/OCRmyPDF#562]
**Describe the bug**
when i try to rotate image , i get the following :
page is facing ⇨, confidence 0.75 - confidence too low to rotate.
and the pdf  doesnt rotate

ocrmypdf  --verbose 1  --remove-background --clean --deskew  --rotate-pages --rotate-pages-threshold 3 --skip-text ip.pdf oppdf
```

**System**
 - OS:Linux
 - OCRmyPDF Version: 9.8.0

**Comment by jbarlow83** [comment]
`` --rotate-pages-threshold 3`` means the page will not be rotated unless confidence is about 3.

As the message says, the algorithm is not confidence enough about rotation direction to rotate the page. Averaged over a large set, it would give an annoying number of false positives.

**Comment by SreenijaK** [comment]
Thanks, is there a way where i can get an output as as a png or jpg instead of pdf without ocr

**Comment by jbarlow83** [comment]
Use `-k` to generate a folder with the intermediate images if you want those instead. Or use any PDF to image method e.g. Ghostscript.

For the latter, some work is still required even if there is no OCR. Would need to see the input file to see if anything is wrong.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
