### ISSUE TITLE
gs 9.52 crashes testing Japanese doc

### ISSUE THREAD

**Issue by ajweber** [jbarlow83/OCRmyPDF#565]
Running OCRmyPDF v9.6.1 on windows with tesseract 5.0a and gs9.52.  Test document includes English and Japanese text.  Process crashes during ghostscript step (ghostscript seems to crash based upon inputs from ocrmypdf).

Command: ocrmypdf -v 1 -l eng+jpn kanji_test.pdf kanji_test_OUT.pdf

Output:
  DEBUG - ocrmypdf 9.6.1
  DEBUG - Running: ['tesseract', '--list-langs']
  DEBUG - Running: ['gswin64c', '--version']
  DEBUG - Running: ['tesseract', '-l', 'jpn+eng', '--print-parameters', 'pdf']
  DEBUG - Running: ['tesseract', '--version']
  DEBUG - Running: ['tesseract', '--version']
  DEBUG - Found tesseract v5.0.0-alpha.20200223
  DEBUG - Found gs 9.52
  DEBUG - Found qpdf 9.0.2
  DEBUG - Running: ['gswin64c', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=txtwrite', '-dTextFormat=0', '-o', '-', 'C:\\temp\\4\\com.github.ocrmypdf.cbj5uz5o\\origin.pdf', '-sstdout=%stderr']
  ERROR - SubprocessOutputError: Ghostscript text extraction failed
C:\temp\4\com.github.ocrmypdf.cbj5uz5o\origin.pdf

Installed via choco steps.  Added additional languages' traineddata to tesseract.

If sample file is needed, please LMK.  I do not know if it is confidential, but can check.

**Comment by jbarlow83** [comment]
Newer versions of ocrmypdf added a workaround to this ghostscript bug.

**Comment by ajweber** [comment]
Dang. I tried to use pip to upgrade to 9.8.0, but now I get python errors:
`ocrmypdf --version
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\ocrmypdf.exe\__main__.py", line 4, in <module>
  File "c:\python38\lib\site-packages\ocrmypdf\__init__.py", line 18, in <module>
    from . import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "c:\python38\lib\site-packages\ocrmypdf\leptonica.py", line 46, in <module>
    os.environ['PATH'] = shim_paths_with_program_files()
  File "c:\python38\lib\site-packages\ocrmypdf\exec\__init__.py", line 148, in shim_paths_with_progr
am_files
    latest_gs = max(
  File "c:\python38\lib\site-packages\ocrmypdf\exec\__init__.py", line 150, in <lambda>
    key=lambda d: float(d[2:]),
ValueError: could not convert string to float: 'st.txt'`

Appreciate any ideas.

**Comment by jbarlow83** [comment]
What's the name of the folder where ghostscript is installed?

**Comment by ajweber** [comment]
C:\Program Files\gs\gs9.52
