### ISSUE TITLE
TypeError: render_string() missing 2 required positional arguments: 'ncs' and 'graphicstate'

### ISSUE THREAD

**Issue by klartext** [jbarlow83/OCRmyPDF#567]
**Describe the bug**
Error message as in subject, complete output see below.

**To Reproduce**
ocrmypdf -v 2 _43.pdf _43-OCR.pdf

Can't provide the pdf, sorry.
But xpdf, evince and okular can display it without problems.
It's scanned stuff (not by me, so I can't reproduce the pipeline).

The comand and it's output:
```
$ ocrmypdf -v 2 _43.pdf _43-OCR.pdf
ocrmypdf -   DEBUG - ocrmypdf 9.8.1
ocrmypdf._validation -   DEBUG - No language specified; assuming --language eng
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--list-langs']
ocrmypdf.exec.gs -   DEBUG - Running: ['gs', '--version']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '-l', 'eng', '--print-parameters', 'pdf']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--version']
ocrmypdf.exec.tesseract -   DEBUG - Running: ['tesseract', '--version']
ocrmypdf.exec -   DEBUG - Found tesseract 4.1.1
ocrmypdf.exec -   DEBUG - Found gs 9.52
ocrmypdf.exec -   DEBUG - Found qpdf 10.0.1
ocrmypdf.helpers -   DEBUG - os.symlink(_43.pdf, /tmp/com.github.ocrmypdf.8_7pqt3g/origin)
ocrmypdf.helpers -   DEBUG - os.symlink(/tmp/com.github.ocrmypdf.8_7pqt3g/origin, /tmp/com.github.ocrmypdf.8_7pqt3g/origin.pdf)
Scan:   0%|                                                                                                                                                                                              | 0/95 [00:00<?, ?page/s]
ocrmypdf._sync -   ERROR - An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 384, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 149, in get_pdfinfo
    return PdfInfo(
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 765, in __init__
    self._pages, pdf = _pdf_get_all_pageinfo(
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_get_all_pageinfo
    page = PageInfo(pdf, n, infile, page_xml, detailed_analysis)
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 651, in __init__
    self._pageinfo = _pdf_get_pageinfo(pdf, pageno, infile, xmltext)
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 578, in _pdf_get_pageinfo
    miner = get_page_analysis(infile, pageno, pscript5_mode)
  File "/usr/lib/python3.8/site-packages/ocrmypdf/pdfinfo/layout.py", line 288, in get_page_analysis
    interp.process_page(next(page))
  File "/home/oliver/.local/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 841, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/oliver/.local/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 854, in render_contents
    self.execute(list_value(streams))
  File "/home/oliver/.local/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 879, in execute
    func(*args)
  File "/home/oliver/.local/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 767, in do_Tj
    self.do_TJ([s])
  File "/home/oliver/.local/lib/python3.8/site-packages/pdfminer/pdfinterp.py", line 762, in do_TJ
    self.device.render_string(self.textstate, seq)
TypeError: render_string() missing 2 required positional arguments: 'ncs' and 'graphicstate'
$ 
```

This is what pdfinfo is telling:

```
$ pdfinfo _43.pdf 
Title:          
Subject:        Image
Author:         
Creator:        Canon iR7105                    
Producer:       Adobe Acrobat 9.51 Paper Capture Plug-in
CreationDate:   Wed Mar 21 15:35:54 2012 CET
ModDate:        Wed Apr 25 21:30:32 2012 CEST
Tagged:         no
UserProperties: no
Suspects:       no
Form:           AcroForm
JavaScript:     no
Pages:          95
Encrypted:      no
Page size:      611.28 x 790.92 pts
Page rot:       0
File size:      1510688 bytes
Optimized:      no
PDF version:    1.6
$ 
```

**Example file**
Can't be provided.

**Expected behavior**
Expected behaviour: ocrmypdf adds OCR-layer to the pdf.

**System**
Arch-Linux /AUR-package of ocrmypdf.
ocrmypdf 9.8.1

**Comment by jbarlow83** [comment]
Try updating pdfminer.six to the latest version - `pip install -U pdfminer.six`. It appears that you have an older version installed, going by line numbers, which is about all I have to work with, since there is no input file.

**Comment by klartext** [comment]
> Try updating pdfminer.six to the latest version - `pip install -U pdfminer.six`. It appears that you have an older version installed, going by line numbers, which is about all I have to work with, since there is no input file.

Other testfile. Same problem.
used the pip-command (btw: -U switch not explained in manpage).

Result:
```
Requirement already up-to-date: pdfminer.six in /usr/lib/python3.8/site-packages (20200517)
(...)
```

**Comment by jbarlow83** [comment]
From `pip install --help`
```
-U, --upgrade
```

If you note in your stack trace, it switches from a system installation of ocrmypdf (`/usr/lib/python3.8/site-packages/ocrmypdf`) to a user installation of pdfminer (`/home/oliver/.local/lib/python3.8/site-packages/pdfminer`) in which the wrong version of pdfminer is installed. The line numbers make it clear that is an old version of pdfminer.

You should probably uninstall the user version of pdfminer (`pip uninstall --user pdfminer.six`) so that it does not override the system version.

See here for an explanation of user installs.
https://pip.pypa.io/en/stable/user_guide/#user-installs

You could also create a virtual environment and install ocrmypdf in there, isolated from system packaging, and it should work there. It may be also be something is wrong with how Arch packaged ocrmypdf.

**Comment by klartext** [comment]
> From `pip install --help`
> 
> ```
> -U, --upgrade
> ```

Ah, yes ok.
It was in  a seperate manpage, which I was not aware of in my unpatience.

> 
> If you note in your stack trace, it switches from a system installation of ocrmypdf (`/usr/lib/python3.8/site-packages/ocrmypdf`) to a user installation of pdfminer (`/home/oliver/.local/lib/python3.8/site-packages/pdfminer`) in which the wrong version of pdfminer is installed. The line numbers make it clear that is an old version of pdfminer.

Yes, pdfminer.six was not available as package, so I used pip.
The main package (without pdfminer.six) was from AUR, so it was not an official ARCH-package.
I removed all pdfminer and ocrmypdf and so on, then installed ocrmypdf via pip.

Again an error message, but a different one:
```
ERROR - PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR)
```
So this looks much nicer to me.
But it took about one minute for scanning until this message came up just after the OCR-part had begun. If this could be detected earlier, it would be nice. (Maybe worth an issue.)
