### ISSUE TITLE
Increase in file size - No reason for this increase is known

### ISSUE THREAD

**Issue by mr-onion-2** [jbarlow83/OCRmyPDF#569]
**Describe the bug**
Hi.
Reporting this as requested. I'm not sure if it is the same cause as the other similar issues.
Scanner - Brother DS-640

```ocrmypdf    |    INFO - New file: /input/test.pdf. Waiting until fully loaded...
ocrmypdf    |    INFO - Attempting to OCRmyPDF to: /output/test.pdf
Scan: 100%|██████████| 1/1 [00:00<00:00, 428.87page/s]
ocrmypdf    |    INFO - Using Tesseract OpenMP thread limit 3
OCR: 100%|██████████| 1.0/1.0 [00:02<00:00,  2.01s/page]
ocrmypdf    | WARNING - Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
ocrmypdf    |    INFO - Optimize ratio: 1.00 savings: 0.0%
ocrmypdf    |    INFO - Output file is a PDF/A-2B (as expected)
ocrmypdf    | WARNING - The output file size is 1.52× larger than the input file.
ocrmypdf    | No reason for this increase is known.  Please report this issue.
ocrmypdf    |    INFO - OCR is done. Deleting: /input/test.pdf
```

**To Reproduce**
Latest docker image - 
```jbarlow83/ocrmypdf                            latest                  cab97f9a4d32        3 days ago          480MB```

```bash
version: "3.3"
services:
  ocrmypdf:
    restart: always
    container_name: ocrmypdf
    image: jbarlow83/ocrmypdf
    volumes:
      - "/home/xxx/Desktop/papers/input:/input"
      - "/home/xxx/Desktop/papers/output:/output"
    environment:
      - OCR_OUTPUT_DIRECTORY_YEAR_MONT=0
      - OCR_ON_SUCCESS_DELETE=1
    user: "1000:1000"
    entrypoint: python3
    command: watcher.py
```

**Example file**
Attached [test.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4711291/test.pdf)

**Expected behavior**
Not to see "WARNING - The output file size is 1.52× larger than the input file"

**System**
 - OS: Docker on Linux
 - OCRmyPDF Version: 9.8.0.post11+g642ebc6.d20200528

Thanks in advance

**Comment by jbarlow83** [comment]
Thanks for reporting - nothing was wrong in particular. I improved the calculation to account for the overhead of adding OCR to small files, as was the case here.

**Comment by rbrito** [comment]
Just for the record, @jbarlow83, there is another source of size increase that OCRmyPDF says that is unknown, but which is pretty obvious: if a file contains JBIG2 files compressed with a dict with many files (say, 50 or even the whole document), then ocrmypdf will say that the file size increased for an unknown reason, despite the fact that using 10 pages per dict makes it loose the inter-page redundancies...

**Comment by jbarlow83** [comment]
@rbrito Can you open a new issue for that and provide an example file? 

I've found 10 pages/JBIG2 dictionary is optimal empirically (for English text anyway). However if you use PDF/A the JBIG2 dictionary will be lost because Ghostscript eats it. There is a parameter to set the jbig2 dictionary size....

**Comment by rbrito** [comment]
On Jun 04 2020, jbarlow83 wrote:
> @rbrito Can you open a new issue for that and provide an example file?

Sure, but I'm not sure if I made myself clear in my point before.

> I've found 10 pages/JBIG2 dictionary is optimal empirically (for English
> text anyway).

Yes, it works well with values around 10--15 or even 20 pages in my
experience (and I'm talking about a broader use of Portuguese too here, not
only restricted to English).  Much more and it becomes way too slow to
decode when being decoded.

> However if you use PDF/A the JBIG2 dictionary will be lost because
> Ghostscript eats it.

I **think** that you mean if the **input** file has a JBIG2 dictionary here,
right?

In my experience, ghostscript will reencode everything in CCITT group 4, to
err on the side of caution regarding simplicity (fewer algorithms) and/or
legal stuff, which means that, yes, *input* files with jbig2 images
(regardless if they use multipage dictionaries) will be "downgraded" to
CCITT.

What I meant originally (sorry if it wasn't clear) is that if your input
file consists of, say, 100 pages where all the pages are in a single JBIG2
document and ask ocrmypdf to optimize it, then it will chop the pages in 10
groups with 10 pages per dict and, then, say that "No reason for this
increase is known". It's simply that what I meant. Sorry if I wasn't clear.

> There is a parameter to set the jbig2 dictionary size....

In ocrmypdf? I couldn't find it in Debian's version in testing/unstable. Is
it new?  I would be willing to test a version of ocrmypdf that allowed me to
change the number of pages per dict a bit (say, besides editing ocrmypdf and
hardcoding a 15 in place of 10).


Thanks,

Rogério Brito.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by steveu75** [comment]
I unsubscribed but I keep getting these messages

Warm Regards,

Steve
310-308-4489

**Comment by jbarlow83** [comment]
You can use `--jbig2-page-group-size` to make adjustments. (It's a hidden argument.) You also need `--jbig2-lossy --optimize 3` for it to be noticeable.

You are correct in what happens. Ghostscript doesn't include a JBIG2 encoder, so it rewrites as CCITT G4, and then ocrmypdf's optimizer converts G4 to JBIG2 without page group. This downgrades a JBIG2 input when `--output-type pdfa` is set the (default). If `--output-type pdf`, then Ghostscript's reencoding is skipped.

jbig2enc also cannot do group encoding without also doing lossy JBIG2 encoding. It's possible in the algorithm to do group + lossless but jbig2 crashes whenever it's to do this.

The "increase in file size" detector cannot detect this fairly complicated situation, which is an issue. Its main purpose is really to catch the obscene file size increases.
