### ISSUE TITLE
Add Metadata to PDF

### ISSUE THREAD

**Issue by oregano87** [jbarlow83/OCRmyPDF#570]
It would be helpful to add metadata to the final PDF. For example, keywords can be added to make it easier to search the file without the need to include the keyword in the file name. 

I think the easiest way to handle these options is to have separate parameters like `--meta-title`, `--meta-author`, `--meta-subject` and `--meta-keywords`.

**Comment by jbarlow83** [comment]
There are arguments for this - check --help

**Comment by oregano87** [comment]
Sorry, I did not see it.
