### ISSUE TITLE
File not found error (Docker)

### ISSUE THREAD

**Issue by Vinayak-kadu** [jbarlow83/OCRmyPDF#572]
i get "ERROR - InputFileError: File not found" when i run ocrmypdf from docker command line/cmd for that matter; where does ocrmypdf looks for file?
also
am trying to run ocrmypdf from docker toolbox it just runs and stops i know this is explained in docs that docker is used to deliver application for one job and it terminates
but i container starts and stops. nowhere i get to enter input file names?

**Comment by jbarlow83** [comment]
You'll need to run it from the command line as described in the documentation, where you specify the input and output filename, or run the mini-webserver version.

**Comment by Vinayak-kadu** [comment]
well am doing that already, even from the directory where file sits. still it didnt picked up in ocrmypdf thats why my first question persists.

**Comment by jbarlow83** [comment]
What's the full command you're running?

**Comment by Vinayak-kadu** [comment]
start with 
`docker tag jbarlow83/ocrmypdf ocrmypdf`
and then 
`docker run --rm -i ocrmypdf m1.pdf m2.pdf`

am not setting alias as i dont have fish shell, neither i find its necessary.

i tried with file in docker toolbox directory and also running docker from directory where the file is.

**Comment by jbarlow83** [comment]
The Docker container cannot see the local file system, i.e. the file m1.pdf on the host. 

The simplest thing to do is pipe the file into the container with shell directs

```
   docker run --rm -i ocrmypdf --version  # runs docker version
   docker run --rm -i ocrmypdf - - <m1.pdf >m2.pdf
```

You can also mount the local file system to do the container with the `docker run -v` argument as the other examples in the documentation describe. The shell method is simpler.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by 2yRc8D9Gp** [comment]
please how did you resolve the problem @Vinayak-kadu Vinayak Kadu ?
