### ISSUE TITLE
License question: Is it possible to use this in closed software without Pymupdf

### ISSUE THREAD

**Issue by johnsindhu** [jbarlow83/OCRmyPDF#574]
I am interested to use or even enhance the library. But the GPL v3 prevents me since I work for my employer.
Is it possible to run this without Pymupdf? 

Have you considered an MIT license without that dependency?

**Comment by jbarlow83** [comment]
PyMuPDF is no longer in ocrmypdf, but Ghostscript is, and Ghostscript is AGPLv3. 

My understanding of these matters is limited, but I believe ocrmypdf's dependencies could constrain it to be at least GPLv3. I do not think I could change the license at this point without getting legal advice on my options.

Many employers are able to work with GPLv3 - other users with corporate connections have already contributed.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
