### ISSUE TITLE
OCR process "died with <Signals.SIGKILL: 9>

### ISSUE THREAD

**Issue by philled** [jbarlow83/OCRmyPDF#575]
When running ocrmypdf on Ubuntu the software crashes and I get an error:

```
$ ocrmypdf 1949-50-Annual-Report-PDF.pdf 1949-50-Annual-Report-OCR.pdf 
  ERROR - Error occurred while running this command:
(Command '['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/com.github.ocrmypdf.h_9tory_/000001.ocr.png', '/tmp/com.github.ocrmypdf.h_9tory_/000001.text', 'pdf', 'txt']' died with <Signals.SIGKILL: 9>.)
```

I've only just installed the software and this is the first file I've tried to OCR. The software was installed from Ubuntu's repo. I can't attach the input file as it's > 10MB but a downloadable copy is available at https://manlycricket.com/wp-content/uploads/2020/06/1949-50-Annual-Report-PDF.pdf

Please check any or all that apply about the test file:
- [x] This is the input file
- [x] The file contains no personal or confidential information
- [x] I am the copyright holder for this file
- [x] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license

**System:**

- OS: Ubuntu 18.04.4 LTS running as a virtual machine. 1GB RAM.
- OCRmyPDF Version: 6.1.2

**Comment by philled** [comment]
Since submitting this I learned that there is a newer version. So I followed the instructions for installing the latest version on Ubuntu 18.04 at https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-the-latest-version-on-ubuntu-18-04-lts. So I'm now running version 9.8.2.

Unfortunately I'm getting a different error when running the OCR:
`ERROR - SubprocessOutputError`

I've attached a file of the verbose level 1 output which will hopefully let someone see where things are going wrong. 
[ocrmypdf.log](https://github.com/jbarlow83/OCRmyPDF/files/4742154/ocrmypdf.log)

**Comment by jbarlow83** [comment]
I believe you've found an image that triggers a fatal error in the old version of `tesseract-ocr` (`tesseract` binary, probably 4.0.0-beta) that ships with Ubuntu 18.04. That is why a tesseract-related error message appears regardless of which ocrmypdf version is used.

You could install a new version Tesseract by setting up the Ubuntu PPA `ppa:alex-p/tesseract-ocr`, or updating to a newer version of Ubuntu, or building Tesseract from source.

I was not able to reproduce the issue with tesseract 4.1.1 which I have installed.

**Comment by philled** [comment]
Thanks for your help/ I've got this working now by doing the following:

1. I created a Xubuntu 20.04 virtual machine. 
2. I installed tesseract-ocr from ppa:alex-p/tesseract-ocr,
3. I installed the latest version of OCRmyPDF using pip as per the instructions at https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-the-latest-version-on-ubuntu-18-04-lts

**Comment by jbarlow83** [comment]
Thanks. I added a Ubuntu 20.04 procedure.
