### ISSUE TITLE
OCR generates Textlayer based on upside down page, even when --rotate-pages is used

### ISSUE THREAD

**Issue by TimGe21** [jbarlow83/OCRmyPDF#581]
**Describe the bug**
After pages of my pdf are rotated, the ocr still runs on the non-rotation-corrected version of the page, making the outputted text layer unusable.

**To Reproduce**
What command line or API call were you trying to run?

```bash
ocrmypdf --language deu+eng --rotate-pages in.pdf out.pdf
```

**Expected behavior**
properly recognized text based on the right page rotation

**Screenshots**
![image](https://user-images.githubusercontent.com/60972976/85069829-0cca4180-b1b5-11ea-8454-faf96b6ddfeb.png)

**System**
 - OS: Ubuntu 18.04
 - OCRmyPDF Version: 10.1.0
 - How did you install ocrmypdf? pip

**Comment by jbarlow83** [comment]
I won't be able to examine this without an example file as there is likely something unusual about how your PDF was generated. Page rotation is extensively tested in tests/test_rotation.py and works on all known inputs in a lot of elaborate combinations.

One page excerpt will do.

If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by TimGe21** [comment]
> I won't be able to examine this without an example file as there is likely something unusual about how your PDF was generated. Page rotation is extensively tested in tests/test_rotation.py and works on all known inputs in a lot of elaborate combinations.
> 
> One page excerpt will do.
> 
> If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
> https://github.com/jbarlow83/OCRmyPDF/wiki

Thank you very much, here the demanded file (raw and unprocessed from my Brother ADS-2800W in PDF mode.
test.pdf.gpg

**Comment by cesiddhartha** [comment]
This behavior doesn't happen in ocrmypdf version 9.6.0+dfsg. But it happens in later versions. It is still present in the latest version.

**Comment by guydepauw** [comment]
I'm having the same issue. If I do 2 passes, one for rotating and another one with `--redo-ocr` for the actual OCR, it's all good, but I have a large amount of PDFs to process, so that's not really practical.

Let me know if I can help by sending an example.

**System**

- OS: MacOS 10.15.6 (Catalina)
- OCRmyPDF Version: 11.1.2
- How did you install ocrmypdf? git clone and `python setup.py install`

**Comment by jbarlow83** [comment]
@guydepauw Please open a new issue with a test file and steps to reproduce because you probably found some variant or special case. The problem originally described in this issue is fixed.
