### ISSUE TITLE
PDF without title will get the title "Untitled"

### ISSUE THREAD

**Issue by zonk0101** [jbarlow83/OCRmyPDF#582]
**Describe the bug**
A PDF without title will get the title "Untitled" after processing

**To Reproduce**
Use any file without title, (e.g. use Chromes Print-to-PDF function from an opened picture
ocrmypdf -l deu "input.pdf" "output.pdf"

Run with verbosity or higher `-v1` to see more detailed logging. This information may be helpful.
-> I didn't find any hint regarding title in the verbose output

**Example file**
[input.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4805299/input.pdf)
[output.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4805300/output.pdf)

**Expected behavior**
I would expect that there is no Title in the output file when there is none in the input-file

**Screenshots**
Chrome shows the Filename if there is no Title:
![image](https://user-images.githubusercontent.com/25272864/85148141-12c13080-b250-11ea-90cd-f8e4662d18e1.png)

**System**
 - OS: Linux (Raspbian GNU/Linux 10 (buster) on Raspberry4)
 - OCRmyPDF Version: 8.0.1+dfsg
 - How did you install ocrmypdf? "apt install ocrmypdf tesserac..."

**Comment by jbarlow83** [comment]
You can use `--title` to set the title if desired and `--title ''` should function as a workaround.

You will need to install ocrmypdf using `pip` to get the fix when released.

**Comment by zonk0101** [comment]
Thanks for fixing, that was fast!
I'm running it on a Raspbian Buster, the HEAD-Build using pip3 is not successful during wheels compilation - Probably the same as the 32bit-problem described in https://github.com/jbarlow83/OCRmyPDF/issues/389

**Comment by zonk0101** [comment]
Another Note: the workaround only works when `--title ''` is not empty but instead a blank like `--title ' '`

**Comment by ipo0x** [comment]
I may be wrong, but I get the impression that the error is occurring again, this time in the latest version installed via `brew`:
```
$ ocrmypdf --version
17.7.0
```
Or have I missed something? Am I doing something wrong if PDFs that previously had no title are suddenly given the title "'Untitled'"?

**Comment by kt767** [comment]
> I may be wrong, but I get the impression that the error is occurring again, this time in the latest version installed via `brew`:
> 
> ```
> $ ocrmypdf --version
> 17.7.0
> ```
> 
> Or have I missed something? Am I doing something wrong if PDFs that previously had no title are suddenly given the title "'Untitled'"?

I'm seeing the same problem with version 17.8.0 (installed via `brew`). When I run `exiftool` on the original PDF file, there was no Title field, but running `exiftool` on ocrmypdf's output shows:

> Title                           : 'Untitled'
