### ISSUE TITLE
test_corrupt_font_detection[type3_font_nomapping.pdf] failing

### ISSUE THREAD

**Issue by QuLogic** [jbarlow83/OCRmyPDF#585]
After fixing #583, I've found one remaining test failure:
```pytb
=================================== FAILURES ===================================
____________ test_corrupt_font_detection[type3_font_nomapping.pdf] _____________
[gw1] linux -- Python 3.9.0 /usr/bin/python3

resources = PosixPath('/builddir/build/BUILD/ocrmypdf-10.1.0/tests/resources')
testfile = 'type3_font_nomapping.pdf'

    @pytest.mark.parametrize(
        'testfile', ('truetype_font_nomapping.pdf', 'type3_font_nomapping.pdf')
    )
    def test_corrupt_font_detection(resources, testfile):
        filename = resources / testfile
        pdf = pdfinfo.PdfInfo(filename, detailed_analysis=True)
>       assert pdf[0].has_corrupt_text
E       assert False
E        +  where False = <PageInfo pageno=0 8.5"x11" rotation=0 dpi=0.000000x0.000000 has_text=True>.has_corrupt_text

tests/test_pdfinfo.py:172: AssertionError
```

**To Reproduce**
```bash
pytest -ra -n auto
```

**System**
 - OS: Fedora Rawhide
 - OCRmyPDF Version: 10.1.0
 - How did you install ocrmypdf? Building a package; not yet installed

**Comment by jbarlow83** [comment]
I couldn't replicate this in a Rawhide Docker image. (Although I did many other errors, but you didn't so I'll take comfort in that....)

What version of pdfminer are you using? I used `pdfminer.six==20200517`. Maybe you're using regular pdfminer?

**Comment by QuLogic** [comment]
Rawhide seems to have 20181108, but I see requirements are now  >= 20191110, but I'm not sure why it didn't point this out earlier. I'll try updating that and see if that helps.

**Comment by QuLogic** [comment]
Ah, I guess it only complains if it isn't installed, not if it's not a sufficient version, which is unfortunate. Upgrading pdfminer fixes it.
