### ISSUE TITLE
Patch for documentation : Installation steps for Mageia 7

### ISSUE THREAD

**Issue by yannick56** [jbarlow83/OCRmyPDF#586]
Hello,

The OCRmyPDF installations steps  for Mageia 7 in the attached file : ocrmypdf-install-steps-v2.txt
Can you add it in https://ocrmypdf.readthedocs.io/en/latest/installation.html

Best regards.

**Comment by yannick56** [comment]
[ocrmypdf-install-steps-v2.txt](https://github.com/jbarlow83/OCRmyPDF/files/4830660/ocrmypdf-install-steps-v2.txt)

**Comment by jbarlow83** [comment]
Is there any chance you're in a position to contribute a package to Mageia 7 that would simplify installation?

**Comment by yannick56** [comment]
> Is there any chance you're in a position to contribute a package to Mageia 7 that would simplify installation?

Hello, I have no access and rights to upload rpm package(s) in Mageia repositeries.
