### ISSUE TITLE
OCRmyPDF fails on Windows Server 2008, no error output

### ISSUE THREAD

**Issue by emerysteele** [jbarlow83/OCRmyPDF#592]
**Describe the issue**
OCRmyPDF fails on "Scanning contents" with no error message. Not sure how to diagnose further.

**To Reproduce**

```
ocrmypdf scansmpl.pdf scansmplout.pdf -v 2
```

**Example file**
[scansmpl.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4894193/scansmpl.pdf)

Please check any or all that apply about the test file:

- [x] This is the input file
- [x] The file contains no personal or confidential information
- [ ] I am the copyright holder for this file
- [ ] I permit this file to be included in the OCRmyPDF test suite under the CC-BY-SA 4.0 license
- [x] I am not the copyright holder, but this file is available under a free software license

Files that are not free for inclusion in this project are quite welcome, but we like to collect free files for our test suite when possible. Please do *not* submit files with confidential information. At your option you may encrypt files for OCRmyPDF's author only.

**Expected behavior**
Should output file or tell why conversion failed.

**System:**

- OS: Windows Server 2008
- OCRmyPDF Version: v10.2.0

**Additional context**
When trying to run OCRmyPDF on a PDF file on Windows Server 2008, OCRmyPDF will find all required modules, installed by chocolaty. But will fail at "Scanning contents: 0%". Does not output a file or any type of error, even when using -v 2.
File works fine on a Windows 10 machine. Cant seem to make it work on Windows Server 2008, even though all dependencies are installed.

**Comment by emerysteele** [comment]
![2020-07-08_20-49-41](https://user-images.githubusercontent.com/1169001/86991807-372c7080-c15d-11ea-82d4-c8d048abdc58.jpg)

**Comment by jbarlow83** [comment]
Windows 2008 is older than any platform I've attempted to support. 

You would need to get a C++14 capable version of Microsoft VC++ (probably 2017 or later) installed on that machine and do a full compile of QPDF, all its dependencies, and pikepdf. If Microsoft never backported their runtime libraries that far back, you may have to compile it all with mingw instead.

The offical pikepdf release gets compiled with VC++2017 running on Windows Server 2016.

I probably can't do much about the lack of feedback. It's probably a low level, dynamic library loading error that should be up to Windows to explain.

**Comment by jbarlow83** [comment]
You may have better luck running a Linux virtual machine (or even newer Windows) on your Windows Server 2008. I'd normally suggest Docker, but Docker for Windows doesn't support most older Windows Server versions.

**Comment by jbarlow83** [comment]
I am closing this issue because I don't believe I can do anything about it other than the suggestions above.
