### ISSUE TITLE
Does OCRmyPDF do dilation or erosion of text automatically? 

### ISSUE THREAD

**Issue by BroderickHigby** [jbarlow83/OCRmyPDF#598]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to erode the text before passing it in to OCRMyPDF. I'm wondering if OCRMyPDF already does this?
**Describe the solution you'd like**

**Additional context**

**Comment by jbarlow83** [comment]
No, it doesn't, and it could. You could create a [plugin](https://ocrmypdf.readthedocs.io/en/latest/plugins.html) that hooks `filter_ocr_image` if you want to influence the image for OCR, or `filter_page_image` if you want to alter the image that the user sees.

I'd be surprised if this improved OCR (unless you trained OCR on your eroded text). You could improve the appearance of text though.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
