### ISSUE TITLE
My script ocr doesn t work on Ubuntu startup but work on terminal

### ISSUE THREAD

**Issue by Manucciu** [jbarlow83/OCRmyPDF#60]
Hello,

I have done one Shell script who is working on terminal (Ubuntu 14) but on startup When i put a pdf the script doesn't work (inotifiwait for launch the script) the error is tesseract 1 ns lookup ans tesseract ns lookup 2.

My command is python3 /usr/bin/local/ocrmypdf input output

Thank you for your Time 
Regards

**Comment by Manucciu** [comment]
ERROR -    1: [tesseract] tesseract: symbol lookup error: tesseract: undefined symbol: _ZN9tesseract16TessHOcrRendererC1Ev
  ERROR -    2: [tesseract] tesseract: symbol lookup error: tesseract: undefined symbol: _ZN9tesseract16TessHOcrRendererC1Ev
  ERROR - Error occurred while running this command:
(Command '['tesseract', '-l', 'fra', '/tmp/com.github.ocrmypdf.74zwq1rr/000002.pp-clean.png', '/tmp/com.github.ocrmypdf.74zwq1rr/000002.badxml', 'hocr']' returned non-zero exit status 127)
L'error en CRON

**Comment by jbarlow83** [comment]
Ça veut dire que tesseract ne peut pas trouver une function provisionné
normallement par libtesseract. Est-ce que tesseract fonctionne toute seule?
(Par exemple: tesseract -l fra inputfile.png output.xml hocr)

**Comment by Manucciu** [comment]
Bonsoir jbarlow83 et merci de prendre de ton temps pour me répondre.
Alors oui la commande à marcher 

tesseract -l fra /home/dematco/test.png /home/dematco/test.xml hocr
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
OSD: Weak margin (3.26) for 94 blob text block, but using orientation anyway: 0

On a vraiment bloquer pour lancer ocrmypdf par cron, ou meme en cron avec screen, on est obligé de le lancer manuellement.
On n'a vraiment pas de solution.

Merci pour ta réponse en tout cas.

**Comment by jbarlow83** [comment]
Est-ce que tesseract fonctionne si lancé par cron ou screen?

**Comment by Manucciu** [comment]
Merci, mais j'ai trouvé la solution pour lancer le script au démarrage en fait ça n'a rien avoir, c'est cron qui embete il ne prend pas les variables comme tout le monde le plus simple pour lancer au démarrage avec intofiwait et tout le reste est 



Create /etc/init/myjob.conf 
vi /etc/init/myjob.conf 


with content like the following 
description     "my job"
start on startup
task
exec /path/to/my/script.sh 
Merci Encore. 
Bonne soirée. 



De: "jbarlow83" <notifications@github.com> 
À: "jbarlow83/OCRmyPDF" <OCRmyPDF@noreply.github.com> 
Cc: "Manucciu" <contact@dematco.fr> 
Envoyé: Mardi 15 Mars 2016 22:55:00 
Objet: Re: [OCRmyPDF] My script ocr doesn t work on Ubuntu startup but work on terminal (#60) 

Est-ce que tesseract fonctionne si lancé par cron ou screen? 

On Tue, 15 Mar 2016 at 14:19 Manucciu <notifications@github.com> wrote: 

> Bonsoir jbarlow83 et merci de prendre de ton temps pour me répondre. 
> Alors oui la commande à marcher 
> 
> tesseract -l fra /home/dematco/test.png /home/dematco/test.xml hocr 
> Tesseract Open Source OCR Engine v3.04.00 with Leptonica 
> OSD: Weak margin (3.26) for 94 blob text block, but using orientation 
> anyway: 0 
> 
> On a vraiment bloquer pour lancer ocrmypdf par cron, ou meme en cron avec 
> screen, on est obligé de le lancer manuellement. 
> On n'a vraiment pas de solution. 
> 
> Merci pour ta réponse en tout cas. 
> 
> — 
> You are receiving this because you commented. 
> Reply to this email directly or view it on GitHub 
> <https://github.com/jbarlow83/OCRmyPDF/issues/60#issuecomment-197024417> 
> 


— 
You are receiving this because you authored the thread. 
Reply to this email directly or view it on GitHub 


--

**Comment by jbarlow83** [comment]
Bonne soirée.

For those looking up this issue and wanting a summary in English, the problem was related to environment variables or permissions in the execution context of `crond`, not any particular problem with ocrmypdf.
