### ISSUE TITLE
RFC - License change to MPL-2.0 (Mozilla Public License)

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#600]
I am considering changing the license for OCRmyPDF to [MPL-2.0](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) (Mozilla Public License 2.0).

I believe this "nonviral copyleft" license strikes a good balance: software may be freely used with other projects, no technical restrictions on the nature of linking as with LGPL, and users are still asked to contribute improvements back.

The question is really what is the most effective distribution strategy is best for the project, in terms of attracting contributions. Recently some users have expressed that they would like to use OCRmyPDF in their proprietary software, but can't because of GPLv3. GPLv3 isn't working if it drives would-be contributors away. And it's a waste of time, energy, human resources and CO2 for people to replicate existing technology in OCRmyPDF for licensing reasons.

OCRmyPDF originally changed to GPLv3 to use PyMuPDF, which is GPLv3. We ended up removing PyMuPDF, because Linux distributions can't package it for technical reasons. There's also a small piece of GPLv3 in src/ocrmypdf/pdfa.py which can be replaced. We do invoke Ghostscript (AGPLv3) and pngquant (GPLv3), via fork-exec, which is acceptable usage of both programs that does not require us to use GPLv3 licenses. Both are also used in a way that another program could be substituted for them.

If this goes through, test files will keep the same  licenses they already have, and misc/webservice.py would remain AGPLv3 for now anyway, because of Ghostscript.

@mawi12345 After me, you have the most commits (about 15) that are still "live" in the current code. Do you have any objections?

@ianalexander Any objections to this change for misc/watcher.py?

@spwhitton @QuLogic  Is this proposed license change a problem for Debian or Fedora?

**Comment by ianalexander** [comment]
No concerns here! Agree that GPL can sometimes be too restrictive and MPL seems like a good compromise.

**Comment by spwhitton** [comment]
Hello,

Thank you for the notification.

It's certainly not a problem for Debian for the code to be under the MPL rather the GPL, since they're both free software licenses.  Debian would want to be satisfied that the relicensing is legitimate.  That basically means that everyone who has a copyrightable contribution remaining in the code base should explicitly re-release their code under the new license.  Otherwise, things get difficult, as the GPL (unlike for example the MIT license) explicitly forbids sublicensing.  But IANAL; maybe there is a simpler way.

A copyrightable contribution is roughly ten lines of code or more.

**Comment by jbarlow83** [comment]
@spwhitton What constitutes an "explicit re-release"? Is it satisfactory if the user makes a comment here approving of the change, or do they need to make a commit?

**Comment by mawi12345** [comment]
I have no concerns and agree to the license change to MPL-2.0 (Mozilla Public License 2.0). I believe that unrestrictive licenses strengthen the distribution in companies which in turn strengthens the OCRmyPDF community (in terms of attracting contributions). I also believe that the use of MIT license would have the same effect.

**Comment by spwhitton** [comment]
@jbarlow83 comments here are fine.  Would you mind sharing how you're finding the list of authors with significant code remaining?  I don't know how to get that info out of git.

**Comment by mawi12345** [comment]
Found `git ls-files | while read f; do git blame -w --line-porcelain -- "$f" | grep -I '^author '; done | sort -f | uniq -ic | sort -nr`
[source](https://gist.github.com/amitchhajer/4461043)
```
52804 author James R. Barlow
 330 author Martin Wind
 202 author Jim Barlow
 147 author mawi
  90 author fritz-hh
  67 author jbarlow83
  67 author Frank
  49 author Pig Monkey
  38 author Elliott Sales de Andrade
  34 author jhgarrison
  26 author Alex
  22 author Ian Alexander
  11 author Matthias Braun
   5 author jumblies
   5 author Peter Hogg
   5 author Julien Ma
   4 author Ivan Kuchin
   2 author Tucker Barbour
   2 author Lars K.W. Gohlke
   2 author Fabian Rodriguez
   1 author tlwhitec
   1 author fcatus
   1 author Stefan Weil
   1 author Sean Whitton
   1 author Mateus Seenem Tavares
```

- [x] 52804 James R. Barlow
- [x] 330 Martin Wind
- [ ]  202 Jim Barlow
- [x] 147 mawi (Martin Wind)
- [ ]  90 author fritz-hh
- [x]  67 jbarlow83
- [ ]   67 Frank
- [ ]   49 Pig Monkey
- [ ]   38 Elliott Sales de Andrade
- [ ]   34 jhgarrison
- [ ]  26 Alex
- [x]   22 Ian Alexander
- [ ]   11 Matthias Braun

**Comment by jbarlow83** [comment]
I made a `.mailmap` to merge the aliases. (I won't share it here because that would publish email addresses.)

I think it's fair to say this license change only affects people who made a copyrightable contribution that falls under GPLv3, so I tweaked the command to remove docs/ and hocrtransform.py which are licensed under Creative Commons and MIT respectively. 

```
git ls-files | grep -v '^docs/' | grep -v 'hocr[tT]ransform.py'  | while read f; do git blame -w --line-porcelain -- "$f" | grep -I '^author '; done | sort -f | uniq -ic | sort -nr
```

With the command above and a mailmap, the list is trimmed to:
- 47440 James R. Barlow
- 477 Martin Wind
- 90 Julien Pfefferkorn - all contributions MIT licensed
- 67 Frank - modified only `misc/completions/ocrmypdf.bash`
- 26 Alex Willner - modified only `misc/completions/ocrmypdf.bash`
- 18 Ian Alexander
- 11 Matthias Braun - copyedited `README.md`

Matthias Braun's contribution is just over one line over "roughly 10" and since it's all copyediting, I don't think it qualifies as copyrightable.

Julien Pfefferkorn is the original author of the shell script version of OCRmyPDF, and all of his work was under MIT and predates the change to GPL. 

I did a separate search using `git-quick-stats` which lists commits by author, to account for the possibility that e.g. code relocation or reformatting by me buried their authorship. I did not find any such cases. This search did turn up some other contributors, all of whom contributed before the change to GPLv3 (on March 14, 2018 in commit 6756016):
- Shem Pasamba
- Tucker Barbour
- findingorder aka DeliciousPickle: misc/batch.py submitted a script via issue #120, first placed in docs/ and later misc/batch.py; contributed in December 2016
- Enantiomerie: submitted a script via issue #180 based on the above, first placed in docs/ and later, misc/synology.py; contributed in August 2017

Since these contributions were before GPLv3 I believe it's reasonable to treat them as MIT-licensed as well.

After this analysis, the only contributors with GPLv3 code in `src/` or `tests/` are:
- [x] 47440 James R. Barlow
- [x]  477 Martin Wind
- [ ] Artifex - Postscript in src/ocrmypdf/pdfa.py

That means the license change can proceed for the core code.

I'd like to put all of `misc/*` under MIT for easier reuse (except webservice.py). To these people, please reply here if you approve of your contributions being placed under the MIT license.
- [ ]   67 Frank - @FPille - `misc/completion/ocrmypdf.bash`
- [ ]   26 Alex Willner - @AlexanderWillner - `misc/completion/ocrmypdf.bash`
- [ ]  18 Ian Alexander - @ianalexander - `misc/watcher.py`
- [ ] @findingorder - `misc/batch.py`
- [ ] @Enantiomerie - `misc/synology.py`

**Comment by AlexanderWillner** [comment]
Fine for me.

**Comment by FPille** [comment]
Agreed!

**Comment by jbarlow83** [comment]
This is now implemented. I haven't heard from two seemingly inactive users about the status of their contributions, but I think the circumstances justify MIT unless they explicitly say otherwise. This is also not core code.

**Comment by QuLogic** [comment]
I don't think there would be any packaging problems; I just make an announcement and that's it, unless something else depends on it.

**Comment by QuLogic** [comment]
> There's also a small piece of GPLv3 in src/ocrmypdf/pdfa.py

This is still listed as GPL-3+ in `debian/copyright`.

**Comment by jbarlow83** [comment]
I forgot to update debian/copyright - will fix. Commit 8c90f7 removes the GPL3 copyrighted portion of pdfa.py.

**Comment by mb720** [comment]
> Matthias Braun's contribution is just over one line over "roughly 10" and since it's all copyediting, I don't think it qualifies as copyrightable.

I know I'm late, just saying that even if my corrections are copyrightable, I'm fine with the change in licensing.

I hope that companies using OCRmyPDF indeed contribute back to this outstanding project.
