### ISSUE TITLE
Efficient text extraction

### ISSUE THREAD

**Issue by macrakis** [jbarlow83/OCRmyPDF#604]
I have 60000 PDFs to index. Some are scans, some are native PDFs.

The help says that sidecar files "contain the same text recognized by Tesseract". But I would like to extract _all_ text to the sidecar, not just the OCR text. I don't see how to do that unless I use --force-ocr, which seems awfully inefficient in time (can't I extract the text without OCR?) and space (I don't want rasterized text).

Do I need to somehow distinguish between the files with text and those without before calling OCRmyPDF?

I don't see any way to suppress the updated PDF on output. Should I just send it to /dev/null if I don't want it? Or is there some way to turn off PDF output to (maybe) save some time?

Sorry for the very basic questions and thanks for a nice package!

**Comment by jbarlow83** [comment]
`--sidecar` really only makes sense for pure image PDFs.

You can use `ocrmypdf --skip-text`, meaning skip pages that have text already, on all of your files if you want them processed (optimize images, PDF/A conversion, etc.) but no OCR added to pages that already have text. If you don't use any "mode arguments", ocrmypdf will default to aborting processing on documents that appear to already have any text.

To extract text, use `pdftotext` from poppler (poppler-utils), which extract text whether from OCR or "regular" cases. Or pdfminer (Python utility used by ocrmypdf). These tools usually work well. But with 60k files, you have enough that you may encounter some poorly formatted PDFs. Internally PDF identifies text characters by a glyph number, which is sufficient to display that character in the PDF. It needs a Unicode mapping table to tell what character number is associated with what glyph, and sometimes those tables are missing, wrong or corrupt - in which case you have a legible document whose text extracts as gibberish. Forcing OCR will fix that.

**Comment by macrakis** [comment]
Thanks for the help! Even with skip-text, processing all the files is taking multiple days at 100% CPU utilization (multithreaded)!

Thanks, too, for mentioning the possible problems with poorly formatted PDFs. Sure enough, when I call pdftotext on the output pdfs, I get errors on a significant fraction of the files. Many of them are "Unknown character collection" (PDFAUTOCAD, PDFTron, callas-xxx), others seem to be PDF syntax errors (Got 'EI' operator, No current point in closepath, xref num ### not found but needed, Unknown operator, Too few args to J operator). I'm hoping that most of these come from embedded graphics, not the running text. I wonder if forcing OCR helps with any of these....

Any additional advice you have on handling these would be welcome!

**Comment by jbarlow83** [comment]
Yes, it takes a few seconds per page, not much way around that other than parallelizing. I've done cloud batch jobs.

>"Unknown character collection" (PDFAUTOCAD, PDFTron, callas-xxx), 

Possibly missing a font. This could easily lose visualize information, worth looking at. Acrobat's Preflight tools can sometimes help you find the problem, but it can be cryptic.

>others seem to be PDF syntax errors (Got 'EI' operator, 

Seems like an embedded image without a header.

>No current point in closepath, 

I think this is an error in an embedded font.

>xref num ### not found but needed, 

Could be a missing image or font.

>Unknown operator, 

Hard to say

>Too few args to J operator). 

The software generating the PDF probably made a mistake

>I'm hoping that most of these come from embedded graphics, not the running text. I wonder if forcing OCR helps with any of these....

Unfortunately, in many cases, no. The files have problems and every PDF viewer (including Ghostscript) will do its best at error recovery - which is not easy or even possible for cases where the PDF itself is missing information that ought to be there. It's like a website with HTML errors - some web browers will detect and fix the issue, others will choke. Forcing OCR will construct a new, properly formatted PDF with Ghostscript's best guess as to how it should look. It would be worth keeping the originals in case they are needed for making repairs.

**Comment by jbarlow83** [comment]
I'll close the issue now due to its age. If you have further related questions feel free to reopen it.
