### ISSUE TITLE
Add support for AWS lambda

### ISSUE THREAD

**Issue by GLeurquin** [jbarlow83/OCRmyPDF#606]
**Is your feature request related to a problem? Please describe.**
I am using part of the ocrmypdf module to execute a routine on AWS lambda. AWS lambda does not support multiprocessing (semaphores etc...). The `use_threads=True` option almost solves this entirely. The last issue is in `_concurrent.execute_progress_pool`, which uses a multiprocessing.Queue, which uses semaphores, which makes AWS lambda crash...

**Describe the solution you'd like**
Replace `multiprocessing.Queue` by `queue.Queue` when `use_threads=True`. This way no more semaphores, and AWS lambda is happy

**Comment by jbarlow83** [comment]
The test suite spreads when this change is made on account of not being able to pickle a `_thread.lock` in most cases. If you have more information about how you set this up, please let me know.

**Comment by GLeurquin** [comment]
Hi, I did not try to add it fully to ocrmypdf and running the tests. I only tried it for my use case, and that seemed to work. Maybe there is a better solution, I'm unfortunately not an expert with queues and multithreading....

**Comment by jbarlow83** [comment]
This is now complete but not merged

**Comment by jbarlow83** [comment]
Currently merged in master - might split out in separate project - either way, it's in.

**Comment by fgiopp** [comment]
I'm trying to run OCRmyPDF on AWS lambda but I get 
OSError: [Errno 38] Function not implemented.

Do you know what is going wrong?

Below the complete stack trace:
`
output_path = handle_ocrmypdf(document_path, key_output_file)  File "/var/task/index.py", line 55, in handle_ocrmypdf    ocrmypdf.ocr(input_path, output_path, force_ocr=True, use_threads=True)#deskew=True)  File "/opt/python/lib/python3.8/site-packages/ocrmypdf/api.py", line 326, in ocr    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)  File "/opt/python/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 359, in run_pipeline    pdfinfo = get_pdfinfo(  File "/opt/python/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 155, in get_pdfinfo    return PdfInfo(  File "/opt/python/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 834, in __init__    self._pages = _pdf_pageinfo_concurrent(  File "/opt/python/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 620, in _pdf_pageinfo_concurrent    exec_progress_pool(  File "/opt/python/lib/python3.8/site-packages/ocrmypdf/_concurrent.py", line 93, in exec_progress_pool    log_queue: multiprocessing.Queue = multiprocessing.Queue(-1)  File "/var/lang/lib/python3.8/multiprocessing/context.py", line 103, in Queue    return Queue(maxsize, ctx=self.get_context())  File "/var/lang/lib/python3.8/multiprocessing/queues.py", line 42, in __init__    self._rlock = ctx.Lock()  File "/var/lang/lib/python3.8/multiprocessing/context.py", line 68, in Lock    return Lock(ctx=self.get_context())  File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)  File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__    sl = self._semlock = _multiprocessing.SemLock( | [ERROR] OSError: [Errno 38] Function not implemented Traceback (most recent call last):   File "/var/task/index.py", line 24, in handler     output_path = handle_ocrmypdf(document_path, key_output_file)   File "/var/task/index.py", line 55, in handle_ocrmypdf     ocrmypdf.ocr(input_path, output_path, force_ocr=True, use_threads=True)#deskew=True)   File "/opt/python/lib/python3.8/site-packages/ocrmypdf/api.py", line 326, in ocr     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)   File "/opt/python/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 359, in run_pipeline     pdfinfo = get_pdfinfo(   File "/opt/python/lib/python3.8/site-packages/ocrmypdf/_pipeline.py", line 155, in get_pdfinfo     return PdfInfo(   File "/opt/python/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 834, in __init__     self._pages = _pdf_pageinfo_concurrent(   File "/opt/python/lib/python3.8/site-packages/ocrmypdf/pdfinfo/info.py", line 620, in _pdf_pageinfo_concurrent     exec_progress_pool(   File "/opt/python/lib/python3.8/site-packages/ocrmypdf/_concurrent.py", line 93, in exec_progress_pool     log_queue: multiprocessing.Queue = multiprocessing.Queue(-1)   File "/var/lang/lib/python3.8/multiprocessing/context.py", line 103, in Queue     return Queue(maxsize, ctx=self.get_context())   File "/var/lang/lib/python3.8/multiprocessing/queues.py", line 42, in __init__     self._rlock = ctx.Lock()   File "/var/lang/lib/python3.8/multiprocessing/context.py", line 68, in Lock     return Lock(ctx=self.get_context())   File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)   File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__     sl = self._semlock = _multiprocessing.SemLock(
-- | --



`
