### ISSUE TITLE
Resolution (DPI) is not credible , DpiError

### ISSUE THREAD

**Issue by shanmuka-chowdary** [jbarlow83/OCRmyPDF#608]
**Issue I'm facing**
I'm trying to convert a .tif file to searchable PDF, which is having only one page.
I'm using python library to convert  by using the below code and getting the below issue

**_Input file is an image, but the resolution (DPI) is not credible. Estimate the resolution at which the image was scanned and specify it using --image-dpi. DpiError_**

The Image Size in the .tif file is **2550*3300**

Please suggest me, How to set the Max dpi in the python code implementation.

```bash
ocrmypdf.ocr(inputpath, outputpath, deskew=True)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/68992368/89247425-4a572280-d5db-11ea-87ed-66e99d477b60.png)

**System**
 - OS: [Windows]
 - OCRmyPDF Version: 10.1.0
 - Installed using chocolaty

**Comment by jbarlow83** [comment]
Try `ocrmypdf.ocr(inputpath, outputpath, deskew=True, image_dpi=(150, 150))`

**Comment by shanmuka-chowdary** [comment]
It's worked,
I've used `ocrmypdf.ocr(inputpath, outputpath, deskew=True, image_dpi=150)`

I'm just curious if i put 150, will there be any impact for smaller dpi Images.

**Comment by jbarlow83** [comment]
That parameter influences how Tesseract OCR interprets the image. In particular when DPI is low, Tesseract has to consider small clumps of pixels as possibly textual or too small to be text given the DPI. The lower the DPI, the less likely it will be possible to find text.

The other use is that PDFs must have a page size in physicals, and image_dpi combined with pixel dimensions of the image will give you the page size.
