### ISSUE TITLE
Use OCRmyPDF in a cluster / Docker Swarm?

### ISSUE THREAD

**Issue by cocinfar** [jbarlow83/OCRmyPDF#611]
Hello all,

I am trying to implement OCRmyPDF in a Docker Swarm environment but I can't seem to make it work in a distributed / cluster way.

I can instantiate several containers with OCRmyPDF image and they all start ok. The problem is that since they are all monitoring the **same** "in" folder, the **ALL** get any file that lands there and process it.

**Question**: Is there a way to distribute the load through multiple containers in a way that only one of them picks up a new document and prevents the others from also getting it?

Thank you,

Fernando

**Comment by jbarlow83** [comment]
This is really an issue that needs to be solved from outside of OCRmyPDF. I have no experience with Docker Swarm so there's not much I can do for you on that. Generally, you want some kind of broker that that picks the files to process and streams them to an available container or tells them where they can get their files.

Note that unless you are using web service mode, the container is intended as a one-shot. It processes one file and terminates - it's a wrapper around a command line application, and it behaves like.
