### ISSUE TITLE
Running OCRMYPDF in jupyternotebook

### ISSUE THREAD

**Issue by Akshaydirisala** [jbarlow83/OCRmyPDF#617]
**Describe the issue**
I want to execute ocrmypdf to read on a pdf file in my local using jupyter IDE
**To Reproduce**

```bash
ocrmypdf.ocr('test.pdf','output_file.pdf',deskew=True)```
.
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'
 is the error notified.Please help me to understand oh how to execute ocrmypdf

**Comment by jbarlow83** [comment]
Please read the installation instructions at ocrmypdf.readthedocs.io

**Comment by jbarlow83** [comment]
Oh, in jupyter - you'll have to make sure Tesseract is installed and on the system PATH.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
