### ISSUE TITLE
PDF Corrupted after being processed through OcrMyPdf

### ISSUE THREAD

**Issue by servoronine** [jbarlow83/OCRmyPDF#618]
**Describe the issue**
OcrMyPdf appears to create a corrupted file when trying to overwrite the original (i.e. input.pdf and output.pdf are the same name). Changing the output.pdf parameter to a different name results in larger but non-corrupted file.

**To Reproduce**
ocmypdf input.pdf input.pdf

```bash
ocrmypdf  ...arguments... input.pdf output.pdf
```

**Example file**
Happy to provide a file, but not sure how to encrypt the file to be uploaded.

**Expected behavior**
File is OCR'd and saved under the same file name.

**System:**

- Ubuntu 18.04
- OCRmyPDF Version: 6.1.2

**Additional context**

**Comment by jbarlow83** [comment]
That version of ocrmypdf is now quite out of date. Please see the
documentation for steps to install a newer version.

**Comment by servoronine** [comment]
Thank you for your response. I have now installed the latest version (11.0) however I am still facing the same issue :( 

The output has changed slighly:
Scanning contents: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 36.56page/s]
Start processing 3 pages concurrently
OCR: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.0/4.0 [00:13<00:00,  3.43s/page]
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.00 savings: 0.0%
Output file is a PDF/A-2B (as expected)

So no issues visible, but the file is still corrupted in the end. Interestingly, if the output is directed to a different file name, everything works.

**Comment by jbarlow83** [comment]
What are you doing to test if the file is corrupt?

Try running `qpdf --check` on the input and output file. You can install this on Ubuntu with `apt install qpdf`.

You could also run `ocrmypdf --keep-temporary-files` and check all of the intermediate files to see if any are invalid.

ocrmypdf already explicitly accounts for the possibility of the input and output file being the same file and already takes precautions to not write invalid files. The message "Output file is a PDF/A-2B (as expected)" means certain tests had to be passed.

Chances are, if you can't provide the file, I probably can't fix this issue.

**Comment by jbarlow83** [comment]
It will be easier if I can look at the actual file. If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by servoronine** [comment]
Sure. I am attaching the GPG-encrypted file. It almost appears as if ocrmypdf does not want to exceed the original file size when overwriting - when I specify a different file name it works fine and creates a slightly bigger PDF file. But when I try to overwrite the file size stays exactly the same and I cannot see the "end" of the file (e.g. %%EOF, etc).
[test.pdf.zip](https://github.com/jbarlow83/OCRmyPDF/files/5128501/test.pdf.zip)

**Comment by jbarlow83** [comment]
I named your file `issue618.pdf` did the following:

```
$ ll issue618.pdf
-rw-r--r--@ 1 jb  staff   202K Aug 26 16:19 issue618.pdf
$ ocrmypdf issue618.pdf issue618.pdf
Scanning contents: 100%|| 4/4 [00:00<00:00, 11.45page/s]
Using Tesseract OpenMP thread limit 3
Start processing 4 pages concurrently
OCR: 100%|| 4.0/4.0 [00:04<00:00,  1.08s/page]
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
JPEGs: 0image [00:00, ?image/s]
JBIG2: 15item [00:00, 261.80item/s]                                                                                                
Optimize ratio: 1.08 savings: 7.6%
Output file is a PDF/A-2B (as expected)
$ qpdf --check issue618.pdf
checking issue618.pdf
PDF Version: 1.7
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
$ ll issue618.pdf
-rw-r--r--@ 1 jb  staff   306K Aug 26 16:19 issue618.pdf
$ 
```

File overwritten in place without issue and original size exceeded. Acrobat also reports no syntax errors (before and after). `qpdf --check` reports no errors. VeraPDF reports that the output file is a valid PDF/A-2B. `%%EOF` present.

Maybe the file system is out of disk space or corrupt. Something uncommon like disk quotas maybe? SELinux? ocrmypdf 6.1.2 and 11.x are far enough apart that they use different PDF libraries.

Try going through the intermediate temporary files.

**Comment by servoronine** [comment]
I have done some more investigation and it was indeed my mistake. The file I was processing was stored in NextCloud and I had assumed that, since the file name has not changed, file scan did not need to be performed. Once I re-scanned the folder structure, the file size updated and I could open the file.
Apologies for the confusion and thanks a lot for your support!
