### ISSUE TITLE
Can you tell me what docker command I should run in order to make the docker image work?

### ISSUE THREAD

**Issue by 5aumy4** [jbarlow83/OCRmyPDF#623]
**Describe the bug**
I tried running the following command:
`$ docker run jbarlow83/ocrmypdf C:/Users/s/Downloads/pdfsforocr/pr.pdf C:/Users/s/Downloads/ocred/pocr.pdf`
To which I got the following error:
`usage: ocrmypdf [-h] [-l LANGUAGES] [--image-dpi DPI]`
                `[--output-type {pdfa,pdf,pdfa-1,pdfa-2,pdfa-3}]`
                `[--sidecar [FILE]] [--version] [-j N] [-q] [-v [VERBOSE]]`
                `[--title TITLE] [--author AUTHOR] [--subject SUBJECT]`
                `[--keywords KEYWORDS] [-r] [--remove-background] [-d] [-c]`
                `[-i] [--unpaper-args UNPAPER_ARGS] [--oversample DPI]`
                `[--remove-vectors] [--threshold] [-f] [-s] [--redo-ocr]`
                `[--skip-big MPixels] [-O {0,1,2,3}] [--jpeg-quality Q]`
                `[--png-quality Q] [--jbig2-lossy] [--pages PAGES]`
                `[--max-image-mpixels MPixels]`
                `[--pdf-renderer {auto,hocr,sandwich}]`
                `[--rotate-pages-threshold CONFIDENCE]`
                `[--pdfa-image-compression {auto,jpeg,lossless}]`
                `[--fast-web-view MEGABYTES] [--plugin PLUGINS] [-k]`
                `[--tesseract-config CFG] [--tesseract-pagesegmode PSM]`
                `[--tesseract-oem MODE] [--tesseract-timeout SECONDS]`
                `[--user-words FILE] [--user-patterns FILE]`
                `input_pdf_or_image output_pdf`
`ocrmypdf: error: unrecognized arguments: C:/Users/Saumya Sah/Downloads/ocred/pocr.pdf`

Also on running the following command:
`$ docker run jbarlow83/ocrmypdf C:/Users/s/Downloads/pdfsforocr/pr.pdf `
I get the following error:
`OutputFileAccessError: Output file location (Sah/Downloads/pdfsforocr/pr.pdf) is not a writable file.`

Can you please tell me exactly what command i should write to ocr the pdf pr.pdf?

OS:Windows 10
python 3.7
 I am using docker toolbox

**Comment by jbarlow83** [comment]
https://ocrmypdf.readthedocs.io/en/latest/docker.html#using-the-docker-image-on-the-command-line

Best method: `docker run -i --rm jbarlow83/ocrmypdf - - <input.pdf >output.pdf`

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by rasoga** [comment]
Hi there, I have the exact same issue currently:
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/29510533/368693ac-05eb-482f-95a1-6883064e46c6)

if I provide two arguments (with output) I get two unrecognized arguments. Tried it with and without sudo (for the sake of testing).

am I missing something?
This was executed on Debian running in Windows WSL2 and Docker Desktop.

**Comment by jbarlow83** [comment]
`docker run -i --rm jbarlow83/ocrmypdf - - <input.pdf >output.pdf`

You're missing the `<` and `>` redirects.

(Also docker should not need sudo!)

**Comment by rasoga** [comment]
Ah! I totally misinterpreted the < and >
Thank you!
