### ISSUE TITLE
qpdf version requirement

### ISSUE THREAD

**Issue by b787abel** [jbarlow83/OCRmyPDF#626]
**Describe the bug**
When I tried to convert a pdf using the
`ocrmypdf thesis.pdf output.pdf`
command, I got the following error message:
ERROR - OCRmyPDF requires 'qpdf' 8.0.2 or higher.  Your system appears to have 10.0.1.  Please update this program.

I used `brew info` to check the package versions, OCRmyPDF version is 11.0.1 and qpdf version is 10.0.1.  

 OS: macOS 10.15.6
 Python version: 3.8

**Comment by jbarlow83** [comment]
I think you may have a different version of ocrmypdf on the PATH than is
installed with brew.

**Comment by jbarlow83** [comment]
To be more precise, it looks like `which ocrmypdf` is picking up an older ocrmypdf install, since you are getting an error that was reported as #527 and fixed in ocrmypdf v9.7.1.

**Comment by b787abel** [comment]
Thanks for the quick reply. The problem was indeed a different version on the PATH. I had two separate versions installed, one with brew and another one with pip, which was the old version.

**Comment by luikluikluik** [comment]
i'm having the same issue, how do i fix this?
