### ISSUE TITLE
optimization leads to text multiple times side by side

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#629]
ocrmypdf is great, also for conversion to pdf/a.
For saving file space I like to use optimize. However, this leads to a change in the graphic layer, which is scaled down and placed several times next to each other. The position of the text layer, however, remains unchanged and correct.

`ocrmypdf -j 1 --skip-text --optimize 2 in.pdf out.pdf`

[in.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5202171/in.pdf)
[out.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5202156/out.pdf)

Thanks for troubleshooting!!

**Comment by jbarlow83** [comment]
Probably same issue as #620, although different manifestation. Seems like Leptonica is again misidentifying the file type, so we end up with a `/BitsPerComponent 1 /ColorSpace /DeviceRGB` when we should have preserved the palette.

**Comment by femifrak** [comment]
Can I manually force the code to use the right type? Maybe in optimize.py or somewhere else?

pdfimages gives this info:

in.pdf:
color: icc comp:1 bpc:1  enc: jbig2

out.pdf:
color: rgb comp:3 bpc:1  enc: jbig2

**Comment by jbarlow83** [comment]
Yes if you manually correct the color and comp to the values in in.pdf that will fix it.

**Comment by femifrak** [comment]
laughing, thanks for the hint.
Actually I was hoping you would give me a hint where in the code I have to do that ...
Would you please? :)

**Comment by jbarlow83** [comment]
Would probably be easier to use a pikepdf script to fix if after the output is generated. 

```python
for im in outpdf.pages[0].images.values():
    im.ColorSpace = pikepdf.Name.DeviceGray
    im.BitsPerComponent = 1
```

**Comment by femifrak** [comment]
ah, I start to understand. 3 times side by side and 3 times narrower instead of all three (equal) image components overlaid. With only one component we have the right dimensions again.

That was my first python code with pikepdf. I start to like it. :+1: :) Your method works, nice! Thanks for the help and the code snippet!!


```
import pikepdf
with pikepdf.open('out.pdf') as outpdf:
    for im in outpdf.pages[0].images.values():
        im.ColorSpace = pikepdf.Name.DeviceGray
        im.BitsPerComponent = 1
    outpdf.save('new.pdf')
```
