### ISSUE TITLE
PDF Exported from Microsoft Word is not recognized as PDF with text and get processed

### ISSUE THREAD

**Issue by dibu28** [jbarlow83/OCRmyPDF#632]
**Describe the bug**
PDF Exported from Microsoft Word is not recognized as PDF with text and get processed by OCRmyPDF.

**To Reproduce**
Create Document in Microsoft Word (new version) or Microsoft Word 365.
Go to Export menu.
Select Export to PDF and Save.
OCR exported PDF with OCRmyPDF.
OCRmyPDF did not recognize exported PDF as PDF containing text.

**Example file**
If your issue is a problem that affects only certain files, and we will require an input file (PDF or image) that demonstrates your issue.

*(Issues without example files usually cannot be resolved. It's like reporting an issue against a web browser without providing a URL.)*
[MS Word Test.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5231280/MS.Word.Test.pdf)
[MS Word Test.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5231283/MS.Word.Test.pdf)

**Expected behavior**
OCRmyPDF will find text in exported PDF and will not process PDF.

**System**
 - Windows.
 - OCRmyPDF Version: 9.1.0
 - How did you install ocrmypdf? Windows installer.

**Comment by jbarlow83** [comment]
Interesting. I can't reproduce this on v11.0.3. I also tried creating a document like this with my own version of Word.

Let me know if you can reproduce this on a newer version.

**Comment by jbarlow83** [comment]
Closed due to lack of response
