### ISSUE TITLE
11.1 committed?

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#635]
I tried to update to ver. 11.1 but pip doesn't show this version (`python3 -m pip install --user ocrmypdf==`):

> ERROR: Could not find a version that satisfies the requirement ocrmypdf== (from versions: 3.0rc6, 3.0rc7, 3.0rc8, 3.0rc9, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 4.0, 4.0.1, 4.0.2, 4.0.3, 4.0.5, 4.0.7, 4.1, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 4.3, 4.3.1, 4.3.2, 4.3.3, 4.3.4, 4.3.5, 4.4.post1, 4.4.1, 4.4.2, 4.5, 4.5.1, 4.5.2, 4.5.3, 4.5.4, 4.5.5, 4.5.6, 5.0, 5.0.1, 5.1, 5.2, 5.3, 5.3.2, 5.3.3, 5.4, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.5, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.7.0, 6.0.0, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4, 6.2.5, 7.0.0rc1, 7.0.0rc2, 7.0.0rc4, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.0.4, 7.0.5, 7.0.6, 7.1.0, 7.2.0, 7.2.1, 7.3.0, 7.3.1, 7.4.0, 8.0.0, 8.0.1, 8.1.0, 8.2.0, 8.2.2, 8.2.3, 8.2.4, 8.3.0, 8.3.1, 8.3.2, 8.4.0b1, 9.0.0b1, 9.0.0, 9.0.1, 9.0.2, 9.0.3, 9.0.4, 9.0.5, 9.1.0, 9.1.1, 9.2.0, 9.3.0, 9.4.0, 9.5.0, 9.6.0, 9.6.1, 9.7.0, 9.7.1, 9.7.2, 9.8.0, 9.8.1, 9.8.2, 10.0.0, 10.0.1, 10.1.0, 10.2.0, 10.3.0, 10.3.1, 10.3.2, 10.3.3, 11.0.0, 11.0.1, 11.0.2)
> ERROR: No matching distribution found for ocrmypdf==

All "Requirement already satisfied"

**Comment by jbarlow83** [comment]
It's up now.

**Comment by femifrak** [comment]
Thanks a lot! Works.

(BTW: According to the docs #612 is solved but still marked open.)
