### ISSUE TITLE
b/w inverted

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#636]
**Describe the bug**
colors of a 1 component pdf were inverted

```bash
ocrmypdf --skip-text --optimize 2 in.pdf out.pdf

```

[in.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5243707/in.pdf)
[out.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5243708/out.pdf)

**Comment by jbarlow83** [comment]
Can't reproduce here, curiously. (Your out.pdf is clearly inverted, but running the command on my end produces a correct out.pdf.)

What versions of ocrmypdf, pngquant, gs (ghostscript), do you have, and what platform are you on?

**Comment by femifrak** [comment]
sorry that I missed this information in my first comment.

I use
ocrmypdf  11.1.0
pngquant 2.5.0 
gs 9.26
ubuntu 18.04

Strangely enough, the identical in.pdf (#629) in the second last version of ocrmypdf (11.0.2) resulted in correct colors (but multiple adjacent graphics).

**Comment by femifrak** [comment]
Some additional info:

1.) The output is okay without optimization and with `--optimize 1` (and not with 2 and 3)
2.) After installing the latest pngquant (2.12.6) with snap and changing the order in $PATH (so that /snap/bin/pngquant is used instead of /usr/bin/pngquant which has version 2.5.0) I get some errors (see below) and a correct (but large) outfile.

```  error: cannot open /tmp/com.github.ocrmypdf.v3ebfy95/images/00000038.png for reading
  error: cannot open /tmp/com.github.ocrmypdf.v3ebfy95/images/00000042.png for reading
  error: cannot open /tmp/com.github.ocrmypdf.v3ebfy95/images/00000040.png for reading
  error: cannot open /tmp/com.github.ocrmypdf.v3ebfy95/images/00000044.png for reading
```
Hope this is helpful.
(BTW: Is there are more elegant way to tell ocrmypdf which pngquant to use?)

**Comment by femifrak** [comment]
I remember that I once extracted images from a "correct" pdf with pdfimages and the image colors appear inverted. 

I found a possible explanation for this (among several other hits):
https://graphicdesign.stackexchange.com/questions/12894/cmyk-jpegs-extracted-from-pdf-appear-inverted

If I understand it correctly, some color information could have been saved in the metadata. In fact I get the following message from ocrmypdf:
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.


Could this be the reason for inversion?

**Comment by jbarlow83** [comment]
Setting PATH is the way to define what third party programs should be used. You can always make a little script to "memorize" the settings.

Yes, it's an image metadata issue.

The error messages are saying it's not working with the snap version of pngquant because the snap does not have permission to the /tmp folder created by a regular system application. snaps get their own chroot'ed filesystem or something along those lines. That also means the image was not changed so the issue you saw wasn't triggered one way or the other.

I'll make a change that makes pngquant independent of temporary files.

**Comment by femifrak** [comment]
perfect! Thanks 1111 lots, for the explanations and the troubleshooting! :)

Works with pngquant 2.12.6 and not with 2.5.0
