### ISSUE TITLE
Help -Request (SimpleDocumentManagement)

### ISSUE THREAD

**Issue by JuXReal** [jbarlow83/OCRmyPDF#64]
Hello Jbarlow83 and Community.

Thanks for this realy great Project. Based on OCRmyPDF i have set up a Github Project to turn every Scanner to a realy Simple Document Management System. 

For the Project i have used the OCRmyPDF 1.1 stable. (realy Old version). With the Jessie Update from Raspberry this Version is broken ( 001hocr.hocr instad  001hocr.html is generated).

It was not possible (for me) to Fix this error. After that i have try to use the latest Version with a clean Jessie Image. But it doesent work.  

Can somebody can give me a Hand to fix the Code. Or to implement the new Version?

https://github.com/JuXReal/SimpleDocumentManagement

**Comment by jbarlow83** [comment]
If the idea is to capture the output text you could use the `pdftotext` program from poppler-utils.

Instructions are available to get ocrmypdf working on Debian stretch/sid (see the Dockerfile for example). Some of the required packages in jessie are old and not tested, but you might be able to get it working. There's also a Docker image if you prefer to isolate the specifics of its configuration.
