### ISSUE TITLE
Auto rotate sometimes out by 180 degrees

### ISSUE THREAD

**Issue by C-monC** [jbarlow83/OCRmyPDF#641]
Hi,

Is it possible to retrieve per page OCR information? The pages I'm OCR'ing are rotated and are sometimes OCR'ed upside down. Specifically I want to access the rotation confidence and if it's high enough OCR the page twice - ocrmypdfs recommended rotation and then flipped.

Thanks,
Simon

**Comment by jbarlow83** [comment]
Kind of. You'd need to write a plugin to do this, using builtin_plugins/tesseract_ocr.py as a template. You could then implement a custom OCR engine that implements this special behavior.

Page rotation detection is not always reliable, and that's a Tesseract issue as long as ocrmypdf is just doing whatever Tesseract advises correctly.

**Comment by C-monC** [comment]
okay cool, thanks for the quick reply. I'll check it out.

**Comment by C-monC** [comment]
Hi,

In pluginspec there's a get_orientation function. Is it possible to get the orientation confidence using the default OCR engine?

**Comment by jbarlow83** [comment]
@C-monC Yes. Just call `ocrmypdf.builtin_plugins.tesseract_ocr.TesseractOcrEngine.get_orientation`.
