### ISSUE TITLE
Custom plugin help

### ISSUE THREAD

**Issue by C-monC** [jbarlow83/OCRmyPDF#644]
Hi,

How does one go about using a custom plugin?  
`ocrmypdf.ocr(input_file=filename , output_file=OCRdone+ "/" + company + '/' + pdf, jobs=10, rotate_pages=True, plugins="tesseract_ocr")`
Returns the following error: `TypeError: ocr() got an unexpected keyword argument 'plugins'` but there's clearly a plugins parameter in the function.

I've also tried first creating the engine with `engine = ocrmypdf.OcrEngine()` which returns `AttributeError: module 'ocrmypdf' has no attribute 'OcrEngine'`. 

I haven't found way to access TesseractOcrEngine in tesseract_ocr.py - get_ocr_engine is also missing if I try call it.

Sorry, this is probably more a python question than OCRmyPDF. If I can just manage to get builtin_plugins/tesseract_ocr.py working I'll probably be able to modify it for my needs.

**Comment by jbarlow83** [comment]
I suspect the version keyword argument error is from having a different version of ocrmypdf imported then the one installed for your command line. In Python check `ocrmypdf.__version__` and see if it matches `ocrmypdf --version`. That is the correct name of the parameter. Also the `plugins` parameter should be a list of strings, not a single string.

See `misc/example_plugin.py` for another example.

If you install the plugin to a virtual environment you can also activate by its Python module name.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
