### ISSUE TITLE
Problem ocrmypdf when use in local server 

### ISSUE THREAD

**Issue by dasapa** [jbarlow83/OCRmyPDF#645]
Begineer question, code below works correctly for me when I run it in jupyter lab, but if I create the .py file and use in local server (xampp) , it does not generate the output.pdf file

import os
import pdfplumber
import ocrmypdf

for filename in os.listdir('tmp/'):
	file= 'tmp/'+filename
	os.system(f'ocrmypdf --remove-background --force-ocr {file} output.pdf')

[..]

Thanks

**Comment by jbarlow83** [comment]
Jupyter Lab is probably running a different Python environment than the .py file. Look up selecting the Python kernel for Jupyter Lab, and use `which python` to find what program executes .py files.
