### ISSUE TITLE
OCR after page rotation still garbled

### ISSUE THREAD

**Issue by guydepauw** [jbarlow83/OCRmyPDF#646]
**Describe the bug**

The pages are rotated correctly and the text spans seem to be correctly identified, but OCR output text is still garbled as if the page was not rotated.

**To Reproduce**
`ocrmypdf --rotate-pages --rotate-pages-threshold 1 test.small.pdf test.small.ocr.pdf`

**Example file**

[test.small.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5322988/test.small.pdf)

**Expected behavior**

Actual text from rotated page is returned

**System**
- OS: MacOS 10.15.6 (Catalina) (same on Ubuntu 18.0.4)
- OCRmyPDF Version: 11.1.2
- How did you install ocrmypdf? git clone and python setup.py install

**Comment by jbarlow83** [comment]
I believe this issue is fixed as of v11.3.0. If that's not the case please reopen.
