### ISSUE TITLE
Bad image after optimization

### ISSUE THREAD

**Issue by wpzdm** [jbarlow83/OCRmyPDF#648]
**Describe the bug**
See screenshots.

**To Reproduce**

```bash
ocrmypdf --optimize 3 --jbig2-lossy --tesseract-timeout=0.0 input.pdf output.pdf
```

**Example file**
http://library.lol/main/112249BB612C64411A678403673C1648

**Screenshots**
Before: https://ibb.co/SwLTWRv
After: https://ibb.co/djJVJbx

**System**
  - OS: macOS 10.15.4 
 - Python version: Python 3.8.1
 - OCRmyPDF version: 11.1.2

**Comment by femifrak** [comment]
I would say, this is why the compression is called --jbig2-**_lossy_**

**Comment by jbarlow83** [comment]
@femifrak It shouldn't be *that* lossy. The main concern is the "6-8" problem, i.e. in certain fonts and at low resolution 6 and 8 can be a pixel or two apart and lossy JBIG2 can substitute one for the other them, and because it's monochrome you can't tell it happened.

**Comment by jbarlow83** [comment]
Reproduced - page 46

**Comment by wpzdm** [comment]
Sorry, maybe I did not describe my problem clearly. I meant, after optimization, there are some black color blocks appear. 
Page 23~25, 27 have similar problems.

**Comment by wpzdm** [comment]
Ah, maybe you meant you need to add `-s` to reproduce the problem? That would be possible, I was possibly already used　`redo-ocr` or `force-ocr`.

**Comment by wpzdm** [comment]
I read your notes on 11.1.3. Seems I only need to wait for the new version.

Thanks!

**Comment by jbarlow83** [comment]
v11.2.0, I changed the numbers. Yes it should be fixed.
