### ISSUE TITLE
Problems with installing and running ocrmypdf

### ISSUE THREAD

**Issue by BlisterFister** [jbarlow83/OCRmyPDF#649]
Hi, when i try to run ocrmypdf --help from the .exe's location (...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts) i get this error. 

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\ocrmypdf.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'ocrmypdf'
PS C:\Users\Simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts>

Any idea what im doing wrong? I installed everything following the instructions. Im on windows10 and i have pip 20.2.1, Ghostscript 9.53.2, Python 3.8.6 and tesseract v5.0.0-alpha.20200328 installed. I have added both Ghostscript and tesseract to my path. 
![image](https://user-images.githubusercontent.com/54404312/95380855-9e39fc80-08e7-11eb-8dd6-4dc42e5742cd.png)

**Comment by jbarlow83** [comment]
Can't say for sure but usually this happens when the software is not installed for the current user. Did you use `pip install` or `pip install --user`? Maybe you installed ocrmypdf as the administrator and tried to run it as the user?

Try installing a simpler program like img2pdf, and see if you can run `img2pdf --help`.

**Comment by BlisterFister** [comment]
Ok, i will give it a try

**Comment by BlisterFister** [comment]
Wait, i got it to work. For some reason ocrmypdf had not installed even tho i have the .exe file on my pc. Anyway i think it works now. Thanks for the help!

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
