### ISSUE TITLE
wishlist: disable page rotation if orientation detection confidence below a user-supplied threshold

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#65]
I scan a lot of multipage documents, some of which are typed and suitable for OCR and some of which are handwritten notes I took that do not OCR well.  OCRmyPDF with `-r` tends to rotate the handwritten pages incorrectly.  It would be great if I could specify e.g. `--rotate-threshold=15` and then OCRmyPDF would only rotate pages where its confidence in the detected orientation is 15 or above.

**Comment by jbarlow83** [comment]
Added in 4.1
The default threshold is 14.0, the same value that tesseract uses if `-psm` tells it to autorotate.

**Comment by spwhitton** [comment]
Thanks for this.
