### ISSUE TITLE
Default name for the output PDF

### ISSUE THREAD

**Issue by jay24rajput** [jbarlow83/OCRmyPDF#651]
**Is your feature request related to a problem? Please describe.**
A feature could be implemented to give a default name to the output file. So that the user could just run `ocrmypdf <filename>.pdf` and the output pdf could be just just some extension added to the file name eg: `<filename_SomeExtension>.pdf`

**Describe the solution you'd like**
The solution could be getting the input file name and adding an extension to it and outputting the file by that name incase the output filename is not provided my the user.
For example, input file is `myfile.pdf` and no output file name is provided then by default we can make output file as `myfile_ocr.pdf`

**Comment by jbarlow83** [comment]
My reasons for not doing it this:

- most common CLI utilities like `cp`, `convert` (ImageMagick), `gs`, don't assume an output filename - modifying a single file in place is more common analogous, e.g. `mogrify`, `pngquant`. I'd expect a bare `ocrmypdf file.pdf` would update `file.pdf` in place not produce a file with a new name
- scripting errors that use this mode could run indefinitely, creating _ocr_ocr.pdf, _ocr_ocr_ocr.pdf etc.; or we introduce special behavior based on a filename which does not strike me as a good practice
- in my experience it's not a good file management practice to mix OCR'd files and non-OCR'd files in the same folder anyway. I think it's best to create a parallel directory tree for OCR files (`files/scanned/**/file.pdf -> files/ocr/**/file.pdf`), or to overwrite in place and use file system features to restore old versions if necessary
- it's easy enough to write a bash or fish script to add any desired suffix: `fish> set f myfile.pdf ; ocrmypdf $f.pdf $f_ocr.pdf`

I'm not saying I can't be persuaded to make changes like what you're proposing, but I'll need to be convinced that it's really the better way.

**Comment by jbarlow83** [comment]
I'll close the issue now, since it doesn't seem like there's anyone speaking up in support of it.
