### ISSUE TITLE
can't find the Leptonica library

### ISSUE THREAD

**Issue by jaan143** [jbarlow83/OCRmyPDF#652]
**Describe the bug**
i install everything my python location is in user/appdata
but my Tesseract OCR location is c:/programming files

**To Reproduce**
File "C:\Users\vicky\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ocrmypdf\__init__.py", line 21, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "C:\Users\vicky\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ocrmypdf\leptonica.py", line 69, in <module>
    """
ocrmypdf.exceptions.MissingDependencyError:
        ---------------------------------------------------------------------
        This error normally occurs when ocrmypdf can't find the Leptonica
        library, which is usually installed with Tesseract OCR. It could be that
        Tesseract is not installed properly, we can't find the installation
        on your system PATH environment variable.

        The library we are looking for is usually called:
            liblept-5.dll   (Windows)
            liblept*.dylib  (macOS)
            liblept*.so     (Linux/BSD)

        Please review our installation procedures to find a solution:
            https://ocrmypdf.readthedocs.io/en/latest/installation.html

**System (please complete the following information):**
 - OS: windows
 - Python version: 3.6.0
 - OCRmyPDF version: latest install today

**Comment by jbarlow83** [comment]
As the error message suggests, you will need to edit the system environment variable called PATH so that the location of the tesseract executable can be found. Microsoft has documentation on how to do this.

If you open a command prompt and type `tesseract` you should get a help message from the tesseract program. If you don't the system doesn't know where Tesseract is.

If your Tesseract is at `c:/programming files` (not `C:\Program Files`) then it is in a non-standard location.

**Comment by jaan143** [comment]
@jbarlow83  my tesseract location is this (C:\Program Files) 
so how can i set path i mean command of path

**Comment by jbarlow83** [comment]
https://superuser.com/a/989665/142651

**Comment by jaan143** [comment]
@jbarlow83  brother i know how to add path but i dont know exact command of location 
so i added this location path but its still not working (C:\Program Files;C:\Program Files\Tesseract-OCR)

**Comment by jaan143** [comment]
@jbarlow83  i got the problem 
if i run cmd as admin then it is find Tesseract 
but as normal user cmd its not finding so should i need to install in user directory or need to set path of user envirenment ?

**Comment by jbarlow83** [comment]
I realize English may not be your first language, but please be aware that it is not appropriate in a professional context to call someone a "brother".

Ideally you run the software as a normal user. It does not need administrative permissions. So, set the path for the user environment and ensure that a normal command prompt can run `tesseract`.

**Comment by jaan143** [comment]
@jbarlow83  i installed it in user directory (C:\Users\vicky\AppData\Local\Tesseract-OCR)
after that i set user path in envirenment (C:\Users\vicky\AppData\Local;C:\Users\vicky\AppData\Local\Tesseract-OCR)

but still didnt finding
any mistake i am doing ?

**Comment by jaan143** [comment]
@jbarlow83  got solved now
thank you very much for your help

**Comment by jaan143** [comment]
@jbarlow83  let me ans you about your question "brother"
i don't know where you are living 
but i visited 18 countries included 3 Continentals. And in my experience every continental have different Cultures evan its counrtries have different cultures
my continental have different culture my country have different culture and evan my Region have different culture than our continental and country
we call brother as respect to senior person who is elder than you or who is expert person.

**Comment by jbarlow83** [comment]
I understand you meant it respectfully. What was I explaining is that it's not appropriate in standard business English.
