### ISSUE TITLE
Anyway to get ocrmypdf.ocr() to release its lock on the origin.pdf file?

### ISSUE THREAD

**Issue by zweissman** [jbarlow83/OCRmyPDF#654]
**Describe the bug**
My existing Python code requires the use of an HOCR file to do some post OCR processing. I am able to accomplish this with setting the tesseract_config=["hocr"] and keep_temporary_files=True That works fine. 

My issue is when I call my cleanup method to get rid of all my temp files and all of the com.github.ocrmypdf.napxtzzb temp files, I cannot get rid of the origin.pdf file because ocrmypdf (or one of the tools it uses) appears to have a lock on it. I don't see any close() or release() functions available. Is there anyway to determine what has the lock on it and get it to release so I can clea

**To Reproduce**
                result_code = ocrmypdf.ocr(os.path.join(FOLDER_TEST_FILES, pdf_file), 
                                           os.path.join(FOLDER_TEST_FILES, pdf_file.replace(".pdf", "_ocr.pdf")), 
                                           sidecar=sidecar_file,
                                           use_threads=(os.name == 'nt'),  # required to run on Windows
                                           jbig2_lossy=True,
                                           output_type="pdf", 
                                           redo_ocr=True, 
                                           optimize=1,
                                           tesseract_config=["hocr"],  
                                           keep_temporary_files=True,
                                           progress_bar=False)

Temporary working files retained at:
C:\Users\ZWEISS~1\AppData\Local\Temp\com.github.ocrmypdf.ctbinveo

temp_folder = 'C:\Users\ZWEISS~1\AppData\Local\Temp\com.github.ocrmypdf.ctbinveo'
shutil.rmtree(temp_folder, ignore_errors=True)

**Expected behavior**
All the files in temp_folder are removed. origin.pdf is still there

**System (please complete the following information):**
 - OS: Winows 10 
 - Python version:  3.7
 - OCRmyPDF version: 11.2.1

**Comment by jbarlow83** [comment]
I'm not aware of any lock held on this file but Windows has strange behavior around symlinks. Try the solution proposed here.
https://superuser.com/questions/167076/how-can-i-delete-a-symbolic-link

**Comment by zweissman** [comment]
Thanks for the response. Just want to add to my original post that since the locks don't release, I just get a temp folder that has thousands of com.github.ocrmypdf folders. Somewhere around 8-10k (leaving a process running for the night), I got a `IOError: [Errno 24] Too many open files` and my program dies.

From my quick attempt to debug through the code in the ocrmypdf repo, I find that you do not create the symlink (helpers.py line 89) when you see that the os.name == 'nt' and can confirm that works as expected. 

The lock doesn't occur until you get to info.py line 800 with:

`with pikepdf.open(infile) as pdf:`

That should release the lock at line 819, but it is not. I am definitely not a threading / concurrency expert, but I am guessing something is holding on to the lock in the _pdf_pageinfo_concurrent code (If I comment this call out, the lock is released as expected at line 819).

I will keep digging to see if I can find an answer or workaround but I am pretty over my head here. Let me know if you have any ideas that you'd like me to try. 

Thank you.

**Comment by zweissman** [comment]
That looks to do the trick.

I agree that the with block "should" release the lock, but it is not. If I comment out the exec_prgoress_pool block of code, then the lock is set and released in the right places.

Thanks for your quick response. This was driving me nuts trying to get this cleaned up.

**Comment by jbarlow83** [comment]
The change has been merged into v11.3.0 so I'll assume this can now be closed. If there are further issues please open a new issue referencing this one.
