### ISSUE TITLE
Arabic characters are reversed

### ISSUE THREAD

**Issue by Goblin80** [jbarlow83/OCRmyPDF#655]
**Describe the bug**
While tesseract correctly identify the word, OCRmyPDF misses up the output pdf somehow by reversing the order of the letters of every arabic word.

**To Reproduce**
1. Pick any document that has arabic text.
2. Run OCRmyPDF aganist it.
3. Try copying any word from the result PDF.

**Expected behavior**
If you try to copy for example the arabic word for "cat" `قطة` OCRmyPDF generates it in the output pdf as `ةطق`.

**Screenshots**
This screenshot show an attempt to select the word for "the earth" `الارض` and the result is reverse ` ضرألا`
![ocr-ar-rev](https://user-images.githubusercontent.com/1815268/96378828-0cf04300-118f-11eb-953e-41712004b7e5.png)

**System (please complete the following information):**
 - OS: 5.8.11-1-MANJARO
 - Python version: 3.8.5
 - OCRmyPDF version: 11.2.1

**Comment by jbarlow83** [comment]
Please convert your PDF to an image, and try using Tesseract OCR directly to create a PDF of that image. If a PDF produced in that way has this issue too, then please report the issue to Tesseract.

The problem may also be the PDF viewer. If the PDF viewer doesn't understand right to left languages it will not handle them properly.

**Comment by Goblin80** [comment]
> The problem may also be the PDF viewer. If the PDF viewer doesn't understand right to left languages it will not handle them properly.
The PDF viewer I am using can handle Arabic text from other documents just fine.

I did try a couple of different PDF viewers (just to make sure), all of them produced the same result as shown in the screenshot above.

> Please convert your PDF to an image, and try using Tesseract OCR directly to create a PDF of that image. If a PDF produced in that way has this issue too, then please report the issue to Tesseract.
I did exactly that and the output text was accurate and correctly displayed (as mentioned in my bug description).

The problem is in the conversion step from text to PDF.

**Comment by jbarlow83** [comment]
Try processing your file with these combinations
- `--output-type pdf`
- `--force-ocr`
- `--output-type pdf --force-ocr`

and let me know if any of them give correct results.

**Comment by Goblin80** [comment]
> Try processing your file with these combinations
> 
> * `--output-type pdf`
> * `--force-ocr`
> * `--output-type pdf --force-ocr`
> 
> and let me know if any of them give correct results.

All of them produce the same problem mentioned above. letters written from left to right instead of right to left.

**Comment by Goblin80** [comment]
Sorry guys my bad. some package update ruined my locale settings. OCRmyPDF works fine with arabic text.

**Comment by 0lm** [comment]
> 
> 
> Sorry guys my bad. some package update ruined my locale settings. OCRmyPDF works fine with arabic text.

Can you explain me how you solved this issue? I have the same issue and I have no clue why. I am on Windows 10 64bit and using ocrmypdf via pythin 3.9.5 64bit for windows. tesseract 5.0 beta is installed in my c/program files/ folder.
