### ISSUE TITLE
Running ocr in a loop, with keep_temporary_files = True, fails to write to error log after cleaning up the temp folder

### ISSUE THREAD

**Issue by zweissman** [jbarlow83/OCRmyPDF#657]
**Describe the bug**
I am running ocrmypdf.ocr in a loop to process multiple documents. I am doing so with the hocr and keep_temporary_files=True so that I can grab the hocr file and do some post-processing. Once I am done processing a pdf, I cleanup the temp com.github.ocrmypdf manually. After the first run through, if I have an error, logging will fail. It looks like the logging is setup to write to the temp folder of the first run through rather than use the current temp folder.

**To Reproduce**
`def test_ocr(source, destination, sidecar):
    result_code = ocrmypdf.ocr(source,
        destination,    
        sidecar=sidecar,
        use_threads=(os.name == 'nt'), # required to run on Windows
        jbig2_lossy=True,
        output_type="pdf",
        redo_ocr=True,
        optimize=1,
        tesseract_config=["hocr"],
        keep_temporary_files=True,
        progress_bar=False)

if __name__ == "__main__":
    for counter in range(10):
        source = "C:\\development\\test\\one_page.pdf"
        destination = f"C:\\development\\test\\one_page_ocr_{counter}.pdf"
        sidecar = f"C:\\development\\test\\sidecar_{counter}.json"

        test_ocr(source, destination, sidecar)
        get_hocr()    # code that pulls the hocr file from the temp folder and does something with it.
        clean_up_temp()    # code that finds the temp folder and deletes it.

`

Run 1
Temporary working files retained at:
C:\Users\ZWEISS~1\AppData\Local\Temp\com.github.ocrmypdf.ctbinveo

Run 2
Temporary working files retained at:
C:\Users\ZWEISS~1\AppData\Local\Temp\com.github.ocrmypdf.hn4y6rpn

[Errno 2] No such file or directory: 'C:\\Users\\ZWEISS~1\\AppData\\Local\\Temp\\com.github.ocrmypdf.ctbinveo\\debug.log'

**Expected behavior**
I would expect that the log file would be in a location that is either outside the scope of the first run or that it would create a new log file for each run (C:\Users\ZWEISS~1\AppData\Local\Temp\com.github.ocrmypdf.hn4y6rpn)

Where does the log get written to if I had set keep_temporary_files=False? Not sure, but I would have to guess in a different locations since this temp folder would have been automatically cleaned up.

**System (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.7
 - OCRmyPDF version: 11.2.1

**Additional context**
The location the error is being raised is ghostscript.py line 125 `log.error(stderr)` 

The error in this case is:
**** Error: stream operator isn't terminated by valid EOL.\r\n               Output may be incorrect.\r\n   **** Error: stream operator isn't terminated by valid EOL.\r\n               Output may be incorrect.\r\n

I can deal with the GhostScript issue, but the logging fails thus squashing the underlying issue.

**Comment by jbarlow83** [comment]
You should manage logging in your script to put log files where you want them, rather than trying to intercept ocrmypdf's debug logging. For example you could create a `logging.FileHandler` and attach it to the root logger of your process.

Based on this issue report I am going to remove the debug log when `ocrmypdf.ocr()` is called. When used as a library ocrmypdf shouldn't make policy decisions, like where to put a log file. The application (your script in this case) should do that. You can use the function `ocrmypdf.configure_logging` to ask ocrmypdf to set up logging similar to its command line interface.

**Comment by zweissman** [comment]
I can handle that. 

I took out line 332-334 in _sync.py run_pipeline that calls configure_debug_logging when keep_temporary_files is set to true and will setup my own logging.

Thanks again.

**Comment by jbarlow83** [comment]
No problem
