### ISSUE TITLE
Problem with auto rotate

### ISSUE THREAD

**Issue by sstefanov** [jbarlow83/OCRmyPDF#658]
**Describe the bug**
What's the problem?

When pages are rotated OCR is not done properly

**To Reproduce**
Steps to reproduce the behavior.

Try attached file with following command line:

`ocrmypdf -v 2 -r --rotate-pages-threshold 1 -l eng+fra+deu+ita+nld+pol --jobs 4 --tesseract-timeout 300 -s a4lr.pdf a4lr_ocr.pdf`

Then open pdf file, select text and paste selection in the text editor, or make sidecar text file and open it.

**Expected behavior**
What did you expected to happen?

When page is auto rotated OCR should be done right way.

**System (please complete the following information):**
 - OS: Debian testing
 - Python version: 3.8.6
 - OCRmyPDF version: 11.1.1.post1+g82b8b41e

[a4lr.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5414144/a4lr.pdf)

**Comment by jbarlow83** [comment]
If the problem is that autorotation sometimes chooses to rotates pages in the wrong direction, I can't help. Especially when the rotate-pages-threshold is set much lower than the default value, which means that Tesseract is not confident in the rotation direction.

**Comment by sstefanov** [comment]
I see no problems in orientation.
After checking temporary images I think that tesseract is started only one time before page is rotated. Orientation is detected properly, but text is garbage.
May be tesseract must be started again after page is rotated to get proper text?

**Comment by jbarlow83** [comment]
Please try using v11.2.1 instead of the version you're using.

**Comment by sstefanov** [comment]
Just tested. Result is the same.
Attached are debug.log and 2 images. May be second one (000001_ocr.png) should be rotated?

[debug.log](https://github.com/jbarlow83/OCRmyPDF/files/5414380/debug.log)

000001_rasterize_preview.png:
![000001_rasterize_preview](https://user-images.githubusercontent.com/302806/96694334-04fff100-1391-11eb-87f0-cb1e8f40db36.jpg)

000001_ocr.png:
![000001_ocr](https://user-images.githubusercontent.com/302806/96694592-53ad8b00-1391-11eb-9b26-046f738ec57e.png)

**Comment by sstefanov** [comment]
Hello
I just tested new version 11.0.3 with test file from here.
All seems the same!

**Comment by jbarlow83** [comment]
Here's what I get, using 11.3.0.

[a4lr_ocr.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5440815/a4lr_ocr.pdf)

**Comment by sstefanov** [comment]
It's excellent! Why I still get garbage?
May be dependencies?

**Comment by jbarlow83** [comment]
Probably not dependencies. Check your logs and temporary work folder again
to see if you can identify a disconnect or decision to not rotate.
You'll need 11.3.0 not 11.0.3 too.

**Comment by sstefanov** [comment]
I made tests with more than 10 files and all seems to be fine!
Thank you very much!!!

**Comment by lnicalo** [comment]
I am having the same issue. 

Text is parsed correctly (you can see that in sidecar file) but then you open the pdf file and image and text are oriented in diferent directions.

How can I fix this? My ocrmypdf version is 11.3.0

**Comment by lnicalo** [comment]
I confirm that the problem is with the version 11.3.0. 11.2.1 is OK.

**Comment by jbarlow83** [comment]
Please submit a new issue and attach your example file, command line and
debug.log.
