### ISSUE TITLE
ocr corrections

### ISSUE THREAD

**Issue by femifrak** [jbarlow83/OCRmyPDF#66]
No OCR software is perfect. Thus there is sometimes the need to correct the underlying text in the pdf output (from ocrmypdf). There are some commercial tools for this, but they struggle from the special format (single words without blanks instead of text as complete lines; different font sizes per word; no vertical alignment within one line).
Has somebody an idea how the text can be edited? My only ideal is to uncompress the pdf and correct the source code, but this is not really feasible.
Thanks and kind regards,

Femi

**Comment by jbarlow83** [comment]
The OCR output by tesseract is probably not good enough at page, line and word segmentation and doesn't recognize enough fonts to get good results. I look at tesseract as a tool for generating keywords, not for reconstructing an editable digital version.

You can supply tesseract with a dictionary that may help it resolve ambiguities in words if your documents have a technical vocabulary for example. (Given a word with a corrupted letter, tesseract refer to the dictionary to find a sensible word.) You can also train it to use specific fonts, although training it is very difficult. You have to run several command line programs and I've never succeeded in training a trivial test case, never mind a whole font.

Using Abbyy FineReader to do OCR and manual correction is your best bet if you want to correct the underlying text. It has the ability to tag sections of the document as particular kinds of content (e.g. table, figure, vertical text) which assists the OCR accuracy. It's quite tedious though, bad enough that it does not necessarily save time compared to retyping the document.

**Comment by femifrak** [comment]
Abbyy allows corrections at the time of pdf creation. What I am looking for is a possibility to edit the underlying text of pdfs which are already generated by software like Abbyy or ocrmypdf. There is one from iceni, but this has difficulties with the output of ocrmypdf.

**Comment by jbarlow83** [comment]
PDF is fundamentally a graphical page description and word processing features that indicate the document's logical structure are afterthoughts and not done consistently by different products, so it's a challenging problem. Tesseract doesn't produce logical structure annotations so Acrobat can't fix its output (or even detect that the file was OCRed). 

Until Tesseract adds that feature, I don't see a way around redoing the OCR in the program you want to use to correct it.

**Comment by femifrak** [comment]
I did not want to give the impression that I am not satisfied with ocrmypdf or tesseract. Sorry if it sounded like that. I am perfectly happy with ocrmypdf.
I don't understand what you mean with "redoing the OCR". I just wanted to replace some characters by others. I found a way to do this with pdftk uncompress. Together with regular expressions and sed I was able to correct repeating errors.
Furthermore infix from iceni generally allows editing the text layer. I only was wondering whether there is a more elegant or stable way to do what I want to do. There is no question that pdf is not meant to be edited, but in general editing is not impossible. I did not want to omit having asked this question. 
Anyhow, thanks for your estimation.

**Comment by jbarlow83** [comment]
No worries, I didn't think you were dissatisfied. I use ocrmypdf in the course of providing commercial data analysis for clients. For most documents I recommend automatic OCR (ocrmypdf) but for high value or high traffic documents or clients that needed accessible Tagged PDFs, I recommend Abbyy as a "supervised OCR" option to ensure accuracy. Different tools for different problems.

You can use pdftk uncompress. `qpdf --qdf` works better for hand editing – it does a better job of rebuilding the PDF after hand edits. That is a good strategy for correcting common misspellings in OCR output and such. Of course, editing text directly will throw off text highlighting (since the text width is specified in the PDF) and if you're working in Unicode everything is hex-encoded.

**Comment by endolith** [comment]
There's no way to interrupt the ocrmypdf process in between OCR and creation of the PDF and allow us to edit the plain text to fix misspellings, etc?

**Comment by jbarlow83** [comment]
You could split into two stages so it can resume. Use the hocr renderer and stop after all hocr files are produced. Then stop so the user can edit the hocr files, and finish. I don't think it would be practical to edit hocrs with a GUI, and I don't see myself having the time to do this.

You can supply a word list which can help Tesseract with spelling, especially for documents with a lot of jargon.

Abbyy FineReader (commercial) has the ability to correct OCR text. Acrobat can also edit the text in a PDF directly but it's clunky.

**Comment by mattention** [comment]
gImageReader can open pairs of hOCR+PDF files, and edit the hOCR with a GUI. It can then export everything to a new PDF.
