### ISSUE TITLE
Optimise performance on single pages

### ISSUE THREAD

**Issue by cedeling** [jbarlow83/OCRmyPDF#660]
Please advise fastest settings for these requirements: We convert each pdf (they range in size from 1 page to over 100 pages each) to single page png images and send those to ocrmypdf using parallel. The conversion to png is to avoid errors like "unable to find trailer dictionary while recovering damaged file" and to sanitize potentially dangerous pdfs. We also need a single png image for every page, so this recipe works well. Output is a single PDFA and a sidecar .txt page for every page - we use that txt to insert into DB for full text text searches and your ocrmypdf product with Tesseract 4 is outstanding . very close to the quality we were getting with ABBYY and OmniPage - but ABBY is too expensive and Omnipage runs Windows so ocrmypodf is a lifesaver.

As to speed, your 21 Feb 2018 comment above indicates that since I am doing OCR on many single pages a high clock speed is more important than having many cores. I usually set -j 4 to send 4 at a time, but I get the fastest speed without any -j setting which I assume used all available resources. We need speed but it must be sustainable hour after hour without frying the machine.

I shall appreciate your advices, and if we must use your consulting services please advise contact details and rates.

**Comment by cedeling** [comment]
Oops, the "21 Feb 2018 comment above" was from another issue which you answered and then closed.  See How do i Increase the Performance #220

**Comment by jbarlow83** [comment]
You will probably get better results if you run ocrmypdf -j1 and
parallelize it N times for an N core CPU.

Alternately, use img2pdf to combine your PNGs into multi page PDFs before
ocrmypdf. This will work better if, on average, the page count is much
larger than the number of cpu cores.

**Comment by cedeling** [comment]
Thanks for fast response.  I shall try the img2pdf suggestion.

Sorry I do not understand "You will probably get better results if you run
ocrmypdf -j1 and
parallelize it N times for an N core CPU."

I want to try that since I do need to end up with single pages of pdf, txt
and png.

For a 100 page pdf I split to 100 pngs and then do
parallel --tag -j 4 ocrmypdf --sidecar '{.}.txt'  --pdf-renderer hocr
--optimize 3 --tesseract-pagesegmode 6  --deskew --clean --clean-final
 '{}' '{.}.pdf' :::  /path/to/thesingles/*.png   > /dev/null & ;

Chris

**Comment by cedeling** [comment]
Thanks for fast response.  I shall try the img2pdf suggestion.

Sorry I do not understand "You will probably get better results if you run ocrmypdf -j1 and
parallelize it N times for an N core CPU."

I want to try that since I do need to end up with single pages of pdf, txt and png.  

For a 100 page pdf I split to 100 pngs and then do
parallel --tag -j 4 ocrmypdf --sidecar '{.}.txt'  --pdf-renderer hocr --optimize 3 --tesseract-pagesegmode 6  --deskew --clean --clean-final  '{}' '{.}.pdf' :::  /path/to/thesingles/*.png   > /dev/null & ;

Chris

**Comment by cedeling** [comment]
WHat I dont understand is how to parallelize it N times

**Comment by jbarlow83** [comment]
For an 8 core cpu

parallel -j8 ocrmypdf -j1

Which lets parallel run 8x single worker instances of ocrmypdf.

**Comment by cedeling** [comment]
That works thanks.  Does itr matter whether there is a space after the -j ?

**Comment by jbarlow83** [comment]
No

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by cedeling** [comment]
OK thanks for your help
