### ISSUE TITLE
--pdfa-image-compression argument has no effect when --output-type is not 'pdfa', 'pdfa-1', or 'pdfa-2'

### ISSUE THREAD

**Issue by totti4ever** [jbarlow83/OCRmyPDF#663]
**Describe the bug**
I do get the warning stated in the title

**To Reproduce**
```
ocrmypdf --output-type pdfa-2 \
	--pdfa-image-compression jpeg \
	--rotate-pages \
	--clean \
	--remove-background \
	--deskew \
	--optimize 3 \
	-l deu \
	--skip-text \
	-j 2 \
	infile \
	out.pdf
```

**Expected behavior**
As I have output type set to *pdfa-2* I would have thought, the argument _pdfa-image-compression_ has an effect

**System (please complete the following information):**
 - OS: `Docker`
 - Python version: *?*
 - OCRmyPDF version: `v11.2.1.post9+gb0dcaa75.d20201024`

**Additional context**
-

**Comment by jbarlow83** [comment]
Yes, the logic about when to show this message is incorrect. Thanks, fixed.
