### ISSUE TITLE
OCRmyPDF exits after Ghostscript unrecoverable error

### ISSUE THREAD

**Issue by mrzool** [jbarlow83/OCRmyPDF#67]
I'm trying to OCR [this PDF](https://bin.sc/Teaching/2014/JavaScript/Resources/The%20Unix%20Programming%20Environment.pdf) without success.

This is the command I've run and the output I've got after ~1 hour:

```
ocrmypdf the_unix_programming_environment.pdf the_unix_programming_environment-ocred.pdf
WARNING -   36: [tesseract] lots of diacritics - possibly poor OCR
WARNING -  366: [tesseract] lots of diacritics - possibly poor OCR
Error: /typecheck in --pdfmark--
Operand stack:
   --nostringval--   Title   ()   Author   ()   Subject   ()   Keywords   ()   Creator   (\376\377\000o\000c\000r\000m\000y\000p\000d\000f\000 \0004\000.\0001\000 \000/\000 \000T\000e\000s\000s\000e\000r\000a\000c\000t\000 \000O\000C\000R\000 \0003\000.\0000\0004\000.\0000\0001)   DOCINFO   false   false   2
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1894   1   3   %oparray_pop   1893   1   3   %oparray_pop   1877   1   3   %oparray_pop   1771   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   1901   12   3   %oparray_pop   --nostringval--
Dictionary stack:
   --dict:1159/1684(ro)(G)--   --dict:1/20(G)--   --dict:78/200(L)--
Current allocation mode is local
Current file position is 644
GPL Ghostscript 9.02: Unrecoverable error, exit code 1
  ERROR - Error occurred while running this command:

<very long traceback log>
```

Any idea what can I do about it?

**Comment by jbarlow83** [comment]
Sorry I missed this issue when you first opened it. 

That's a very long file with several hundred pages. It will make a good test case. I will investigate.

But I'm pretty sure it hit some kind of memory limit in Ghostscript (which ocrmypdf uses). I recommend upgrading Ghostscript (your version is about 5 years old) and possibly splitting the file into several PDFs and then merging them. `pdftk` is a command line program that can split PDFs.

**Comment by jbarlow83** [comment]
It ran successfully on my machine in 13 minutes. (Intel i5 3.2 GHz, OS X El Capitan, Ghostscript 9.18, ocrmypdf 4.1.2)

**Comment by mrzool** [comment]
It worked! The problem was indeed my outdated version of Ghostscript.

Thanks for the help.
