### ISSUE TITLE
Proper OCR with mixed text orientation

### ISSUE THREAD

**Issue by sstefanov** [jbarlow83/OCRmyPDF#670]
**Is your feature request related to a problem? Please describe.**
If the document contains some letters in different orientation, even if they are few, sometimes all OCR is done wrong orientation.

**Describe the solution you'd like**
Ideal variant is to have each group of text his own proper rotation.
Another variant is to have all text in same rotation, but orientation is where most text is in it.

**Describe alternatives you've considered**
nothing

**Additional context**
Attached is screenshot of original document with small text in left (marked in red) which cause wrong orientation of whole text (selected in second screenshot)

![Screenshot_20201105_153350](https://user-images.githubusercontent.com/302806/98248199-47265680-1f7d-11eb-9dc3-0f4a89c67531.png)
![Screenshot_20201105_153338](https://user-images.githubusercontent.com/302806/98248218-4d1c3780-1f7d-11eb-83ea-69965b6e2613.png)

**Comment by jbarlow83** [comment]
Please confirm this is an issue in ocrmypdf 11.3.2 and provide a test file.

**Comment by sstefanov** [comment]
Seems that I used older version.
When use 11.3.2 all seems to be OK!
