### ISSUE TITLE
unpaper with ocrmypdf on Fedora 33

### ISSUE THREAD

**Issue by Mike81269** [jbarlow83/OCRmyPDF#671]
Hello
I try to use unpaper together with ocrmypdf on the new Fedora 33.
I took the last version of unpaper from GitHub and ocrmypdf which is delivered together with Fedora 33.
The command is
```
ocrmypdf -l deu -c -d -i <input.pdf> <output.pdf>
```

I would be happy about every hint to solve this problem.
By the way, with the unpaper which is delivered with Fedora 33 is not working - version >=6.1 needed

Error output:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 189, in exec_page_sync
ocr_image, preprocess_out = make_intermediate_images(
File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 132, in make_intermediate_images
preprocess_out = preprocess(
File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 105, in preprocess
image = preprocess_clean(image, page_context)
File "/usr/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 476, in preprocess_clean
unpaper.clean(input_file, output_file, dpi.x, page_context.options.unpaper_args)
File "/usr/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 129, in clean
run(input_file, output_file, dpi, unpaper_args)
File "/usr/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 83, in run
proc = external_run(
File "/usr/lib/python3.9/site-packages/ocrmypdf/subprocess.py", line 54, in run
proc = subprocess_run(args, env=env, **kwargs)
File "/usr/lib64/python3.9/subprocess.py", line 503, in run
stdout, stderr = process.communicate(input, timeout=timeout)
File "/usr/lib64/python3.9/subprocess.py", line 1117, in communicate
stdout = self.stdout.read()
File "/usr/lib64/python3.9/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 351: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 362, in run_pipeline
exec_concurrent(context)
File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 269, in exec_concurrent
exec_progress_pool(
File "/usr/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 111, in exec_progress_pool
result = results.next()
File "/usr/lib64/python3.9/multiprocessing/pool.py", line 870, in next
raise value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 351: invalid start byte
```

**Comment by jbarlow83** [comment]
Since you built unpaper from source, have a look at this possibly related issue: https://github.com/unpaper/unpaper/issues/79
In particular, does make check work?

The immediate problem is that unpaper is produce a non UTF-8 character in its output, while ocrmypdf assumes unpaper only outputs UTF-8. I will relax that assumption, but most likely unpaper went off the rails and is dumping some binary data to stdout or stderr.

**Comment by Mike81269** [comment]
I build it like you wrote - nothing changed. 
I understood that from ypur point of view unpaper do wrong things, send back non UTF-8 character.
on the other hand I worte to the unpaper guys (https://github.com/unpaper/unpaper/issues/81)  and they told me that ocrmypdf is the problem. 
In the end it is a interface issue from my point of view.
ocrmypdf fails is unpaper send non UTF-8 character and maybe this is a failure!?
On the other hand maybe ocrmypdf should be able to handle this?
I see only two solutions:
- the ocrmypdf and unpaper team defines how the interface should be in implement this like defined
- someone from any team tell me what the I have to change in my local code that these both app work together. I can do it for ocrmypdf or unpaper - I have programmed both in my life Python less and C/C++ a lot but not in the last 10 year.
I would be very happy about a solution because with fedora 32 everything works fine!

**Comment by jbarlow83** [comment]
Did you try ocrmypdf 11.3.3?

**Comment by Mike81269** [comment]
Hi,
thanks for the quick response.
Not yet. But I will do. Any recommendations regarding setup?
Normally I would use the fedora standard python 3.9 and do
python setup.py build
python setup.py install --home=~
for test I would change my PATH to ~/.local/bin
Arre you fine with this?

**Comment by Mike81269** [comment]
I checked the fedora packages - pikepdf is not in the needed version available;
from setup.py:        
"pikepdf >= 1.14.0, < 3 ; python_version < '3.9'",
"pikepdf >= 2.0.0 ; python_version >= '3.9'",
dnf ouput: 
Package python3-pikepdf-1.19.3-1.fc33.x86_64 is already installed.

Independent of this the outout of python setup.py build is

Traceback (most recent call last):
  File "/home/m/Downloads/OCRmyPDF-master/setup.py", line 32, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.9/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 429, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib64/python3.9/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 721, in finalize_options
    ep(self)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 728, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/m/Downloads/OCRmyPDF-master/.eggs/setuptools_scm-4.1.2-py3.9.egg/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/home/m/Downloads/OCRmyPDF-master/.eggs/setuptools_scm-4.1.2-py3.9.egg/setuptools_scm/__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "/home/m/Downloads/OCRmyPDF-master/.eggs/setuptools_scm-4.1.2-py3.9.egg/setuptools_scm/__init__.py", line 110, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/home/m/Downloads/OCRmyPDF-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

**Comment by Flameeyes** [comment]
> Since you built unpaper from source, have a look at this possibly related issue: [unpaper/unpaper#79](https://github.com/unpaper/unpaper/issues/79)
> In particular, does make check work?

Unrelated. It seems like there's more bit flips/pixel flips that there used to be between the output and the expected golden, but that's an unfortunate problem with the way testing is done: if the skew calculations end up being 1° off, it's usually not a big deal for humans (or even OCR tools), but it does cause most of the image to "not match" the golden. Unfortunately perceptual diff is hard and I never managed to get that working.

> The immediate problem is that unpaper is produce a non UTF-8 character in its output, while ocrmypdf assumes unpaper only outputs UTF-8. I will relax that assumption, but most likely unpaper went off the rails and is dumping some binary data to stdout or stderr.

Two things here:

 1. there's no promise that the output of unpaper is valid UTF-8: it will print what the user provided as filenames, and if their locale is not set to an UTF-8 locale, it won't be output in UTF-8; Python 3 explicitly uses utf-8 everywhere, but that is not true of C;
 2. there's no way for unpaper to throw binary data to stdout/stderr, but there might be non-ascii-safe logs in ffmpeg libraries, that are outside of my control.

My recommendation is to not assume that unpaper output is utf-8, because there's no guarantee of that. I would also strongly recommend not to rely on the text of the output a tall.

While I'm not actively developing unpaper, I would be very happy to see someone implementing a JSON output flag that switches the output from the current human-centric view to structured data that can be consumed by another tool.

**Comment by jbarlow83** [comment]
@Mike81269 Please consider using the Docker image instead and wait for Fedora to update its ocrmypdf and pikepdf packages, which its maintainers will do at their convenience. You may find this easier than trying to build various things from source. If you want to continue a direct install you'll need to compile pikepdf 2.0 from source (1.19 is not compatible with Python 3.9, as setup.py says), provide a test file and a copy of your temporary folder (`--keep-temporary-files`).

@Flameeyes In this case the issue reporter did not provide a test file or steps to reproduce. ocrmypdf has worked with unpaper 6.1 for several years expecting the output to be encoded correctly, without this triggering any decoding errors. The issue report does mention that unpaper was built from source, so I considered it possible based on this limited information that unpaper was somehow not compiled or linked correctly, and that may still be the case. Some programs do emit binary data when they fail. I realize there is no universal expectation of UTF-8, however programs should output text in the environment's locale or the user will see mojibake (Python actually expects subprocess stdout/stderr to be consistent with the system locale, not necessarily UTF-8, but it's UTF-8 99% of the time on Linux now.) I already modified ocrmypdf to treat unpaper's output as binary as of v11.3.3; the output of unpaper was only ever captured for logging.

**Comment by Mike81269** [comment]
@jbarlow83:
First of all thanks a lot.
I am not very familar with docker, therefore I tried it with venv. After some faults I found this part of your documentation.
https://ocrmypdf.readthedocs.io/en/latest/installation.html#id23
Additional I downloaded the latest data and copied these to the venv. 
Now it is working.
The only thing what I ask me is why I got first 
ocrmypdf         11.3.2.post8+g71f0e7f5
after the copy 
ocrmypdf-11.3.2.post8+g71f0e7f5 pikepdf-2.0.0
and on the website I can read version 11.3.3.
But these details :-)
Cheers
Mike

**Comment by jbarlow83** [comment]
#665 has become a duplicate of this issue

**Comment by jbarlow83** [comment]
@Mike81269 I did the release but forgot to push the tag. The version you were using is equivalent to v11.3.3. Just to clarify, are you saying that ocrmypdf now works *without* Docker?

**Comment by Mike81269** [comment]
Yes, as I mention I set up like described a python env etc.
Gerat - thanks for you help!!
