### ISSUE TITLE
Quesiton: Performance Increase

### ISSUE THREAD

**Issue by blueteq** [jbarlow83/OCRmyPDF#672]
OCRmyPDF has performed incredible work for us to date, we have over 1 000 000 files in PDF format where only 70% have some kind of OCR. 
We run the basic OCR process with his command with pdf and PDF variant on 150 000 of the files (one year): 

`sudo find . -name '*.pdf' | parallel --tag -j 7 ocrmypdf '{}' '{}' \;
`
This takes about two to three days to run with the help of parallel spreading the load over 7 threads. 
We then wrote a python script that takes a CSV as input with search terms, this then finds files with text matching the search term and moves them into a folder. This script not OCRmyPDF related take 5 hours. 

Then the remaining files after the sort is around 50 000, these would be ones where OCR did not work properly and this is where we run into problems, I use this command. With rotate, deskew clean and force to redo OCR hoping for better result 

`sudo find . -name '*.pdf' -exec ocrmypdf --jobs 7 --rotate-pages --deskew --clean --force '{}' '{}' \;`

However, this last command on 50 000 files has been running for a week now and no idea how long it has to go. 

And advice would be great, we still have another 4 years of files to go and then after that manually sort the mistakes.

**Comment by jbarlow83** [comment]
Always nice to hear when things are working well for people.

Your commands introduce two different job management approaches. Using `parallel -j 7`, parallel will create up to 7 ocrmypdf processes, *which will create their own child processes*. Using `ocrmypdf --jobs 7` without parallel, you will get a single ocrmypdf process with up to 7 workers.

You should set: (parallel workers) * (ocrmypdf workers) ~= number of CPU threads (could be more, could be less)

If your files tend to be long (10+ pages), use more ocrmypdf workers. If files are short, use more parallel workers. If you are not sure, set each to the square root. So on my 8 core/16 thread CPU I might do 6x3. I'd use a program like `htop` to check that we're using the system efficiency but not running too many workers at once. 3.5-5s per page is realistic on current generation hardware.

For large files `--output-type pdf` may be faster, if you do not require PDF/A conversion. Likewise, if you disable image optimization with `--optimize 0`, it may be faster.

Beyond that, I think I'd need to look at some of your actual files and see what can be done. You can contact me at james@purplerock.ca if you want to explore a consulting arrangement. I have helped people use OCRmyPDF at your scale before.

**Comment by jbarlow83** [comment]
Closing this since we are discussing it in private channels.
