### ISSUE TITLE
"Tesseract failed to report available languages."

### ISSUE THREAD

**Issue by Mennaruuk** [jbarlow83/OCRmyPDF#674]
**Describe the bug**
I'm getting the error:
```
Tesseract failed to report available languages.
Output from Tesseract:
-----------
```
**To Reproduce**
1. Install ocrmypdf via brew: `brew install ocrmypdf`
2. Download [this PDF](https://web.archive.org/web/20201111054743/http://graphics8.nytimes.com/packages/pdf/archives/black-thursday-10-24-1929.pdf)(from _The New York Times_ archives). Save it to Desktop or Downloads. Rename image to input.pdf
3. `cd` into the folder where the PDF is saved
4. Run via terminal: `ocrmypdf input.pdf output.pdf`

**Expected behavior**
Tesseract should have began OCRing the PDF. Instead, an error occurs.

**Screenshots**

**System (please complete the following information):**
 - OS: macOS 10.14.6
 - Python version: Python 2.7.10 and Python 3.9.0
 - OCRmyPDF version: 11.3.2

**Additional context**
When I run` tesseract --list-langs,` I obtain the error:`Illegal instruction: 4`

**Comment by jbarlow83** [comment]
Looks like a Tesseract configuration issue.

Try reinstalling Tesseract and also check if `tesseract-lang` is installed. Ideally both from Homebrew.

**Comment by Mennaruuk** [comment]
I reinstalled both via brew. Unfortunately, the issue persists. I uninstalled Homebrew ocrmypdf and installed ocrmypdf via pip3. Didn't work. Unsure what the problem is ;(

**Comment by jbarlow83** [comment]
If you can't do `tesseract --list-langs` the problem lies with Tesseract or Homebrew.

You could try `brew install --build-from-source tesseract`.

**Comment by Mennaruuk** [comment]
Alas, nothing worked to solve the issue. I installed both tesseract and tesseract-lang by building them from source, did `brew update`, `brew upgrade`, `brew upgrade --cask`, `brew cleanup`. Still the same puzzling error. It's confusing because I can see both tesseract and tesseract-lang folders in the Cellar folder, and inside the tesseract-lang folder, all the language files are found.

**Comment by jbarlow83** [comment]
Have a look here:
https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

Are you running a hackintosh?

**Comment by jbarlow83** [comment]
I'm going to close this now since it is likely a user configuration or Homebrew issue and will need to be resolved at that level. Feel free to reopen if you have information that "implicates" ocrmypdf itself.
