### ISSUE TITLE
"InputFileError: File not found - input.pdf"

### ISSUE THREAD

**Issue by Mennaruuk** [jbarlow83/OCRmyPDF#676]
**Describe the bug**
I'm getting the error:
```
InputFileError: File not found - input.pdf
```
**To Reproduce**
1. Install ocrmypdf via chocolatey: `choco install ocrmypdf`
2. Download [this PDF ](https://web.archive.org/web/20201111054743/http://graphics8.nytimes.com/packages/pdf/archives/black-thursday-10-24-1929.pdf)(from _The New York Times_ archives). Save it to Desktop or Downloads. Rename to input.pdf
3. `cd` into folder where the PDF is saved
4. Run via terminal: `ocrmypdf input.pdf output.pdf`

**Expected behavior**
Tesseract should have began OCRing the PDF. Instead, an error occurs.

**Screenshots**
![Screenshot 2020-11-11 121723_censored_censored](https://user-images.githubusercontent.com/52135169/98843025-61967f00-2418-11eb-933a-f11bed1f33eb.jpg)

**System (please complete the following information):**
 - OS: Windows 10 20H2
 - Python version: Python 3.9.0
 - OCRmyPDF version: 11.3.3

**Additional context**
Both Tesseract and Ghostscript were installed via Chocolatey via:
```
choco install --pre tesseract
choco install ghostscript
```

**Comment by jbarlow83** [comment]
Where did you find the ocrmypdf chocolatey page? I get nothing on this page:
https://chocolatey.org/search?q=ocrmypdf

I wonder if a virus scanner embargoed the file or Windows has special rules for the Downloads folder. Can you try it on a local PDF?

Also try:
```
type input.pdf | ocrmypdf - output.pdf
```

**Comment by Mennaruuk** [comment]
My apologies, I meant `pip install ocrmypdf.`

Thank you for your help, I got it working by reinstalling ocrmypdf. Not sure what went right here, but that did it for me.
