### ISSUE TITLE
'ocrmypdf' has no attribute 'ocr'

### ISSUE THREAD

**Issue by MartinPoupa** [jbarlow83/OCRmyPDF#677]
**Describe the bug**
"AttributeError: module 'ocrmypdf' has no attribute 'ocr'"

**To Reproduce**

**Expected behavior**
when I try to run the code:
"
import ocrmypdf
ocrmypdf.ocr('test.pdf', 'output.pdf')
"

**Screenshots**

**System (please complete the following information):**
 - OS: ubuntu 18.04
 - Python version: Python 3.6.9
 - OCRmyPDF version: 4.1

**Additional context**

thanks for the help

**Comment by jbarlow83** [comment]
Ocrmypdf 4.1 is far too old for that API.

**Comment by MartinPoupa** [comment]
Thank you
