### ISSUE TITLE
Tightened dependency on ruffus

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#68]
OCRmyPDF version 4.1 tightens the dependency on python3-ruffus from >=2.6.3 to ==2.6.3.  Is OCRmyPDF version 4.0.7 also incompatible with python3-ruffus >2.6.3?  Or is it only this new version that is incompatible?

**Comment by jbarlow83** [comment]
Both versions use a workaround to a Rufus 2.6.3 bug that I reported. I
don't know how my workaround will behave when the bug is fixed (author said
its fixed but not pushed yet), so to be defensive both should be ==2.6.3.

**Comment by spwhitton** [comment]
Okay, thanks for that information.  I'm not sure yet whether it will be best to upload 4.1 to Debian or just leave things as they are until the bug in ruffus gets fixed.
