### ISSUE TITLE
Can't encrypt file for maintainer

### ISSUE THREAD

**Issue by sstefanov** [jbarlow83/OCRmyPDF#688]
**Describe the bug**
When I try to encrypt file I receive error message

**To Reproduce**
```bash
gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-keys 8ea702b420664133
```
Error message:
```bash
gpg: keyserver receive failed: General error
```
**System (please complete the following information):**
 - OS:
Debian linux test
 - Python version: 
3.8.6
 - OCRmyPDF version:
11.3.4

**Additional context**
Tested on several systems and same error on all of them.

**Comment by jbarlow83** [comment]
`gpg --keyserver https://keys.openpgp.org/ --send-keys 7270A56980543E957377F8478EA702B420664133`

**Comment by sstefanov** [comment]
It's done without any messages.
What's next?

**Comment by jbarlow83** [comment]
The first command downloads the key. Silence means it worked. Now run the
second gpg command to encrypt the file as listed on the wiki.

**Comment by Iey4iej3** [comment]
I have modified the wiki page (the modification is open to all) by changing `https` to `hkps` as indicated in https://keys.openpgp.org/about/usage
