### ISSUE TITLE
sRGB_IEC61966-2-1_black_scaled.icc is non-free

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#69]
The license of sRGB_IEC61966-2-1_black_scaled.icc does not permit modification of the file.  That makes it non-free, so I can't include it in the Debian packaging of OCRmyPDF.  Can OCRmyPDF be patched so that it does not require this file?  If so, I would be grateful if you could tell me where to start in constructing such a patch.

**Comment by jbarlow83** [comment]
sRGB.icc from icc-profiles-free should work.
https://packages.debian.org/unstable/all/icc-profiles-free/filelist

Patching line 13 of pdfa.py to point to the absolute path of the system ICC
profile would do the job, and of course making icc-profiles-free a
dependency.

That said, I am thinking it will be easier if I just replace the existing
ICC profile with a copy of Debian's. I doubt anyone would notice a
perceptible difference between the two profiles. The file is only 500 bytes
and will probably never be updated by Debian, so it's not really worth
deduplicating. But if the Debian policy is to studiously avoid duplication
then we need some way to link to icc-profiles-free anyway. What do you
suggest here?

**Comment by spwhitton** [comment]
Thanks for your feedback on this issue.

(1) If you include a copy of sRGB.icc from icc-profiles-free in the OCRmyPDF repository, I will just exclude it from being installed, and patch pdfa.py to point to the system's version.

(2) If you keep sRGB_IEC61966-2-1_black_scaled.icc in your repository, I will prepare a DFSG-clean version of ocrmypdf (e.g. version 4.1+dfsg) and then, as above, patch pdfa.py to point to the system's version.

(3) Finally, you could just remove all *.icc files from your repository and point to the system version yourself, and then I don't need to do any patching.

From my point of view, option (3) is the most convenient.  But since you probably want ocrmypdf to be usable outside of the Debian universe, option (2) is a good compromise.  Please avoid option (1).  It makes the test suite less useful if we're running it with different colour profiles.

**Comment by jbarlow83** [comment]
Thinking about this further:

Don't (2) and (1) have the same problem with test suite divergence?

I might as try to keep all of my content under MIT license as well, so I'd
like to remove the IEC version and switch to the Debian version. If
ocrmypdf uses Debian's sRGB profile by default, then the test suite runs
with the same profile on all regularly tested platforms.

On your end, after install you could delete sRGB.icc and replace it with a
symlink to the system version. That eliminates the duplication, any code
patching, and any special casing of Debian within ocrmypdf. setup.py should
place all files uncompressed in Python site-packages. You could still do
code patching if that works out to be easier.

**Comment by spwhitton** [comment]
(1) doesn't have the problem, but you're right, (2) does.

You're right: it would be much easier for me just to replace the file with a symlink to the system version, and not do any patching.  Thanks for pointing that out!

I'm looking forward to a release containing the free file.

**Comment by jbarlow83** [comment]
It's up now.
