### ISSUE TITLE
Option -O0 decrease bitmap quality, it is avoided after setting --output-type pdf

### ISSUE THREAD

**Issue by mvsoliveira** [jbarlow83/OCRmyPDF#691]
**Describe the bug**
Disabling optimization keeps image quality degradation 

**To Reproduce**
ocrmypdf Page_test.pdf Page_test_O0.pdf -O0

**Expected behavior**
That the file size would be similar and quality would remain
A good result is only achieved after:
ocrmypdf Page_test.pdf Page_test_O0-pdf.pdf -O0 --output-type pdf

**Screenshots**

**System (please complete the following information):**
 - OS: MacOS
 - Python version: 3.9.0
 - OCRmyPDF version:

**Additional context**

**Comment by jbarlow83** [comment]
This is "as designed" behavior - the default is PDF/A conversion, which implies possibly converting the image as needed, and can be adjusted with `--pdfa-image-compression` or by disabling PDF/A.

But if you have an example file of the output being severely degraded by this conversion, I'd like to see that.
