### ISSUE TITLE
German language not found in docker-container

### ISSUE THREAD

**Issue by dklinger** [jbarlow83/OCRmyPDF#694]
Hi, 

i'm (sucessfully) using the docker container with LSTM and language deu for months.
Because of a few problems, I did a test with the legacy mode (oem = 0) and language deu and get the following error:

                    ERROR ocrmypdf._exec.tesseract -    1  [tesseract] Error: Tesseract (legacy) engine requested, but components are not present in /usr/share/tesseract-ocr/4.00/tessdata/deu.traineddata!!
                     INFO ocrmypdf._exec.tesseract -    1  [tesseract] Failed loading language 'deu'
                     INFO ocrmypdf._exec.tesseract -    1  [tesseract] Tesseract couldn't load any languages!
                     INFO ocrmypdf._exec.tesseract -    1  [tesseract] Could not initialize tesseract.

Any guess on what might be the problem? I'm using the docker-image with Tag "latest":

**Comment by dklinger** [comment]
The Docker image uses the Ubuntu packages tesseract-ocr-deu which is based on https://github.com/tesseract-ocr/tessdata_fast.
Tessdata_fast does not include the models for the legacy engine. Therefore only --tesseract-oem 1 is currently working for ocrmypdf.

The models for legacy + LSTM are in the repo https://github.com/tesseract-ocr/tessdata and need to be downloaded manually.

To fix this, ocrmypdf needs to be expanded to check the value of --tesseract-oem and download/extract the legacy+LSTM version on the fly. I don't think this is/should be in scope of this project as the legacy engine is, in fact, "legacy".

A switch to select the desired package would still be nice to select, for example, the tesseract_best (https://github.com/tesseract-ocr/tessdata_best) version instead of the default tesseract_fast. If this switch is going to be implented, it shouldn't be a problem to also add the legacy+LSTM repo as an option as the download/extract process would be the same as for tesseract_best.

**Comment by jbarlow83** [comment]
It's possible to fork and modify the Docker image to include the legacy
training data for any languages required. I believe the documentation gives
an example of adding another language beyond the standard set.

I wouldn't want to change the imahe from fast to best traineddata as this
would impact performance - it's slower and would affect users that expect
the OCR to behave in some ways.

**Comment by dklinger** [comment]
Thanks for your answer.

The fork to create my own docker file is a possibility. But I would try to avoid that. Also because I'm using synOCR for Synology NAS which uses your docker container. So, if I create my own docker file for OCRmyPDF I have to also fork synOCR. As I'm not having the intention to change any logic, just pure configuration on which files to use, that's not a good coding/architectural approach.
My thougt was, as we have the information which tesseract language engine the user wants, we can use that information and do the work for the user. Otherwise the switch "--tesseract-oem" is more or less useless at the moment, without the user doing more or less extra work, as only "1" is currently working.
It's ok for me and nothing which should be done now or in a short term. But having a switch to let the user the choice on which tesseract language engine to use would be very nice. In fact, the switch is already here with "--tesseract-oem", it's just not fully implemented.
If it's never going to be implemented, that's also ok. But now other user facing the same problem may get here and have the whole story and an approach on how to proceed.

**Comment by jbarlow83** [comment]
All you need is to set up something like
```
FROM synOCR
RUN # download tessbest and install
```
On Docker Hub you can configure this to automatically rebuild when the source image does. 

There are people who do not use the Docker image or who use custom language training data. The `--tesseract-oem` argument remains useful to them. Most of the `--tesseract*` parameters are passed to Tesseract verbatim, and errors are returned verbatim.

>Also regarding fast vs. best: It wasn't my intention to suggest a change from fast to best.

Understood. The point was, to do what you proposed I would have to change from fast to best, or otherwise do some "magic" behind the scenes (such as checking an alternate install location) that would only work in the Docker container.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
