### ISSUE TITLE
Error when trying to build jbig2enc

### ISSUE THREAD

**Issue by sgjohnson1981** [jbarlow83/OCRmyPDF#696]
**Describe the bug**
Received the following error when trying to build jbig2enc following given instructions
```
Running aclocal
./autogen.sh: 45: ./autogen.sh: aclocal: not found

Something went wrong, bailing out!
```

**System (please complete the following information):**
 - OS: Debian 10.7
 - Python version: 3.8.5
 - OCRmyPDF version: 8.0.1

**Comment by jbarlow83** [comment]
You'll need to do `apt install automake`.
(I found this by searching for the error message `./autogen.sh: aclocal: not found`. Always search for the error message :) .)

**Comment by sgjohnson1981** [comment]
Hm. I searched for aclocal but didn't find anything. Just decided to do it in windows 10.
