### ISSUE TITLE
watcher.py ignores OCR_LOGLEVEL env variable

### ISSUE THREAD

**Issue by Zaxim** [jbarlow83/OCRmyPDF#702]
**Describe the bug**
When I try to set a more verbose log level via an environment variable, `watcher.py` only prints the log.info level messages and not log.debug level messages.

**To Reproduce**

1. Set the environment variable `export OCR_LOGLEVEL DEBUG`
2. run `python3 watcher.py`

**Expected behavior**
I expected debug information such as DESKEW and OCR_JSON_SETTINGS to print to the console. Instead it only printed 
```
Starting OCRmyPDF watcher with config:
Input Directory: /input
Output Directory: /output
Output Directory Year & Month: False
```

**System (please complete the following information):**
Docker image, commit 4b8ccbe8cb76480b03ab42b0c61814acd1c59a60

**Additional context**

**Comment by jbarlow83** [comment]
Thanks, fixed for next release

**Comment by Zaxim** [comment]
Thank you so much!
