### ISSUE TITLE
Integration with Windows and VB.Net

### ISSUE THREAD

**Issue by perrygarrod** [jbarlow83/OCRmyPDF#71]
Hi
By way of background, I've written a vb program that uses ImageMagick Convert and Tesseract to read PDF's, convert each to a Tif and then to a text searchable PDF/A.
Works fine but found OCRmyPDF and having loaded Docker and OCRmyPDF, have completed test file conversion. Great.
What I'd like to know is, is it possible to integrate my existing VB code, to use OCRmyPDF?
For example:
Have my VB.NET program pass parameters to Docker/OCRmyPDF, i.e. Windows folder path & source pdf filename and output pdf filename; VB.Net code either waiting for file creation or like a vb function, waiting on the return of a parameter 
Ideally I do not want to abandon my VB engine, and the solution needs to run on Windows.
Any assistance can offer, great.  Thanks
Perry

**Comment by perrygarrod** [comment]
Alternatively, if integration is not possible, could I perhaps "mount" a shared drive, and somehow have OCRmyPDF monitor the folder/drive and simply convert any PDF, creating new PDF/A in 2nd folder as well as deleting the source.  THen wait for another.
Not my first choice, as would prefer old fashioned call between vb and docker but not sure possible
Best
Perry

**Comment by jbarlow83** [comment]
I really don't know much about the .NET platform.

Certainly you can have a VB.NET program pass parameters to Docker and take
responsibility for monitoring folders. Just think of Docker/OCRmyPDF as if
it were a command line Windows program. The example commands for "docker
run" map a location on the host machine (Windows) to a location in the
Docker container. Use the return code to find out what happened; several
are defined and ocrmypdf is careful about using them and does not leave
incomplete output files if it errors out.

It will almost certainly work better to have VB.NET do Windowsy things like
watch folders and move files around.

Set up a working folder (on a local drive) on Windows and ensure that the
Docker service has full permissions on it. It looks like the syntax is
"docker run -v //c/WorkingFolder:/home/docker ..." for Windows, but see
also https://github.com/docker/toolbox/issues/241.

Then your VB.NET program would copy files into that folder, "docker run",
and if successful delete the input and copy the output. Docker should
interact with only one folder; it's a world of pain to try to give it
access to other locations.

Alternately you could try to get ocrmypdf working on Cygwin. I imagine that
is more tractable than native Windows.

**Comment by perrygarrod** [comment]
Thanks, I'll take on board the above and provide feedback later this week as to outcome.  Quite excited about the approach though, just hope doesnt end in tears.  Will report & close hopefully after the w/e

**Comment by perrygarrod** [comment]
Ok, hit the high, and now the low.
Everything works independantly, and by that I mean if I launch Docker Quickstart Terminal, I get "docker is configured to use the default machine with IP 192.168.99.100 and prompt perry@Asus_X550CA MINGW64
docker run -v "$(pwd):/home/docker"   ocrmypdf --skip-text test.pdf output.pdf
However, and this is the brick wall - of ingnorance on my part - that despite Path to C:\Program Files\Docker Toolbox, when I launch CMD, and enter the same "docker run" command I get
docker: An error occurred trying to connect: Post http://%2F%F.%2Fpipe%2Fdocker_engine/v1.23/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'docker run --help

I'm guessing its because it can't locate OCRmyPDF executable, whereas Docker Quickstart recalls the fact that I imported it previously and it's in the "container"? So, a little knowledge is a dangerous thing but how do I resolve so I can execute from CMD?

Thanks in advance
Perry

**Comment by jbarlow83** [comment]
I'm not quite sure but it sounds like you might be trying to launch the
docker client within a docker container, or the virtual machine is not
running.

You'll have to get docker working with a hello world container first to get
the workflow down.

Getting container volumes to work is harder.

**Comment by perrygarrod** [comment]
Not sure but you pointed me in the right direction.  
So, story thus far, ran the following in CMD
docker-machine env default --shell cmd

SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\perry\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
@FOR /f "tokens=*" %i IN ('"C:\Program Files\Docker Toolbox\docker-machine.exe" env default --shell cmd') DO @%i

Then tested by 
docker run hello-world 
and reported all ok.

So need to run the above in order to create VM,

Then retried 
docker run -v "$(pwd):/home/docker"   ocrmypdf --skip-text test.pdf output.pdf
But doesnt like the $ characters, remembering the above works in Docker Quiskstart

So tried
docker run -v //c/WorkingFolder:/home/docker  ocrmypdf --skip-text test.pdf output.pdf
 But not quite right as got this
ERROR - No way to run job: Input file 'test.pdf' does not exist
But the $(pwd) works so /home/docker is ok but the Windows bit is not right.  
Googled but nothing.  Is WorkingFolder a parameter or should it equate to something
Thanks
Perry

**Comment by jbarlow83** [comment]
//c/WorkingFolder would correspond to C:\WorkingFolder. It's a Unix-y
representation of a Windows path.

**Comment by perrygarrod** [comment]
But what windows path. Have tried various options but it's like breaking a code. Out by 1 character or one /.  I'll continue digging tomorrow, but how is it with all the users out there, this isnt common knowledge to Windows Docker users, or maybe it is and I'm to blind to it.  Thanks for all your help.  Couldnt have gotten this far without it.

**Comment by perrygarrod** [comment]
Got it
docker run -v /c/Users/perry://home/docker  ocrmypdf --skip-text test.pdf output.pdf

Thanks.  It's amazing how important it is to have a sounding board

**Comment by jbarlow83** [comment]
Forgot to mention you'll want to do "docker run --rm" to tell it to clean
up the container on exit, or else docker will eventually fill all available
memory in a serverlike setting.

**Comment by perrygarrod** [comment]
Noted. Thanks
