### ISSUE TITLE
how to solve exempiloaderror in python

### ISSUE THREAD

**Issue by gratefuldead68** [jbarlow83/OCRmyPDF#711]
I am getting an exempiloaderror while trying to use the XMP-toolkit in Python.

I have downloaded the exempi library but am unable to add it manually to Python in Windows (I am using Jupyter notebook to code)

Any help in working around this error and also with the code that I have to run in order to use the XMP-toolkit to access, edit and write-back the XMP metadata of a PDF file, particularly the modified date, and metadate.

Thanks

**Comment by jbarlow83** [comment]
That library is a Python wrapper around a C library, libexempi. The C
library has not been ported to Windows and the project is not maintained.
Ocrmypdf only uses it its test suite, and the relevant tests are skipped on
Windows.

**Comment by gratefuldead68** [comment]
Thanks Jbarlow83. So if I cannot use XMP-toolkit for Python on windows (since the libexempi is not available for windows), is there any other utility/library that I can use to access, edit and write back the XMP metadata (particularly the dates)
Any help will be much appreciated
Thanks

**Comment by jbarlow83** [comment]
pikepdf can (another library I wrote to support ocrmypdf). Its metadata
support is more basic than exempi, but I think easier to use.

**Comment by gratefuldead68** [comment]
Hi Jbarlow83,

I installed pikepdf as you have recommended. But when I am trying to call this as a code in Jupyter I am getting an error as below :
![Screenshot (73)](https://user-images.githubusercontent.com/76737670/104275852-a64a9f00-54c9-11eb-8387-1bff670d46f0.png)

**Comment by jbarlow83** [comment]
I am now locking this conversation, because this is not a general support forum.

Your original issue and follow up questions do not concern ocrmypdf. I also removed your screenshot because it may reveal your personal information.
