### ISSUE TITLE
Creating a custom plugin for improved rotation

### ISSUE THREAD

**Issue by C-monC** [jbarlow83/OCRmyPDF#712]
Hi,

Where is the get_orientation's returned value passed to tesseract and how do you execute the ocr when making your own plugin?

I would like to ocr the page in all 4 orientations if the rotation confidence is low. Then compare the total English words and only add the highest to the output pdf. I'm struggling to find the file in which the ocr is executed and where the pdf is generated.

Kind regards,
Simon

**Comment by jbarlow83** [comment]
The default plugins are in src/ocrmypdf/builtin_plugins/ and some plugins are used for testing (e.g. to bypass OCR for a test) in tests/plugins/. Have a look at the file `tesseract_cache.py` for a template; this "subclass" the standard OCR engine class to add caching for the test suite.

At low confidence, the input is probably quite noisy and will give a low number of word matches in all orientations. Your strategy might help in some cases but will probably give results quite similar to the existing orientation confidence.

I would instead invest effort in cleaning the input image before sending it to Tesseract. Sometimes you can apply domain specific knowledge - you probably know something about your input that Tesseract doesn't. That's usually where you can help it most.

**Comment by C-monC** [comment]
Thank you for the insight. Do you think adding --user-words will improve the ocr significantly? The documents are full of engineering jargon/acronyms. 
I see the documentation does not have a section on adding user words but you mentioned it in a previous release several years ago.

**Comment by C-monC** [comment]
I see there is the option for parsing keywords and user_words. I assume the user_words points to your word list like in Tesseract's docs. What is the difference between the two?

**Comment by jbarlow83** [comment]
`--keywords` is a list of metadata keywords to attach to the document. There is no parsing - your keywords are added verbatim.

The improvement from a word list is modest, not significant. ocrmypdf just passes the information on to Tesseract. --user-words means use a Tesseract word list.

**Comment by C-monC** [comment]
Thank you for the help. The main rotation issues come from powerpoint slides that are rotated - The text is very clear but I believe the background gradients/colouring is throwing tesseract.

**Comment by jbarlow83** [comment]
In that case I suggest looking into how ocrmypdf implements the --threshold
function and doing this for rotation. Tesseract isn't that good at
thresholding color to binary (where OCR happens).
