### ISSUE TITLE
How to disable logging when using the api ?

### ISSUE THREAD

**Issue by WhoAteDaCake** [jbarlow83/OCRmyPDF#713]
**Describe the bug**
How can I disable or change logging level to ERROR for all logs?

**To Reproduce**
Call `ocrmypdf.configure_logging(-1, False)` then
Calling `ocrmypdf.ocr` from python

**Expected behavior**
All logs to be less verbose

**Screenshots**
Just logs

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.6.9
 - OCRmyPDF version: 11.5.0

**Additional context**
I tried running `getLogger` and `setLevel`, but that did not fix it either. It still spams my logs with entries like:
```
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
DEBUG:ocrmypdf.subprocess:Running: ['jbig2', '--version']
```

**Comment by jbarlow83** [comment]
Please read the documentation for the function `ocrmypdf.configure_logging()`. I believe, as it explains, that you have a different case from its intended purpose and you'll want to configure logging manually. Instead of `.configure_logging()`, use `logging.getLogger('ocrmypdf').setLevel(...)` and similarly adjust `pdfminer` and `PIL`.
