### ISSUE TITLE
Error: Failed to download resource "ghostscript--patch"

### ISSUE THREAD

**Issue by sunnyjiechao** [jbarlow83/OCRmyPDF#724]
**Describe the bug**
Error: Failed to download resource "ghostscript--patch"

**To Reproduce**
brew install --build-from-source ocrmypdf

**Screenshots**
![image](https://user-images.githubusercontent.com/19250012/105655354-e3b42100-5efa-11eb-9fea-c372688b5a23.png)

**System (please complete the following information):**
 - OS: macOS 10.13
 - Python version: 3.8
 - OCRmyPDF version:  ocrmypdf

**Additional context**

I can access the link: https://raw.githubusercontent.com/Homebrew/formula-patches/98c39e09/ghostscript/config.patch

![image](https://user-images.githubusercontent.com/19250012/105655462-0f370b80-5efb-11eb-9168-210674a1c45e.png)

this is the complete error info:

11111111:~ jay$ brew install --build-from-source ocrmypdf
Updating Homebrew...
^CWarning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://homebrew.bintray.com/bottles/freetype-2.10.4.high_sierra.bottle.tar.gz
Already downloaded: /Users/jay/Library/Caches/Homebrew/downloads/1d757b4de24a73c51df08e047faa1a4941d5dc7510ea07de1420b1fb0848cb33--freetype-2.10.4.high_sierra.bottle.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/98c39e09/ghostscript/config.patch

curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
Error: Failed to download resource "ghostscript--patch"
Download failed: https://raw.githubusercontent.com/Homebrew/formula-patches/98c39e09/ghostscript/config.patch

**Comment by jbarlow83** [comment]
As the error message suggests, the problem is that Homebrew does not support your version of macOS. Because of this, the dependency Ghostscript cannot be installed, causing OCRmyPDF's install to fail as well. There is no option except to upgrade macOS.
