### ISSUE TITLE
PDF generated with OCRmyPDF doesn't display well with evince

### ISSUE THREAD

**Issue by so-o** [jbarlow83/OCRmyPDF#726]
[Test_1.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5870309/Test_1.pdf)

The text in Caladea-Regular is gibberish using evince even though the program says it's using the right TTF in /usr/share/fonts.
Firefox and Chrome display it properly. Gimp fails too.

**Comment by jbarlow83** [comment]
Caladea-Bold is present in the file, but Caladea-Regular is not embedded. If a font is not embedded, it can only be shown if it happens to be installed on the system. You might be able to repair it with Acrobat if you can find this font.

There is no way OCR can help with issues like a missing font.
