### ISSUE TITLE
Converting a simple PDF containing a JPEG to PDF/A-1b fails check with veraPDF

### ISSUE THREAD

**Issue by so-o** [jbarlow83/OCRmyPDF#729]
The file is a small JPEG put in a PDF by convert from ImageMagick. Before the PDF is normalized, veraPDF reports these errors: 6.1.2-2 6.2.3-2 6.7.2-1 6.7.3-1. After the PDF is turned into a PDF/A-1b by OCRmyPDF, veraPDF reports just one error: 6.7.3-1.

If I just run the last gs command used by OCRmyPDF directly on the same file:

```
gs -dBATCH -dNOPAUSE -dSAFER -dCompatibilityLevel=1.6 -sDEVICE=pdfwrite -dAutoRotatePages=/None -sColorConversionStrategy=RGB -dAutoFilterColorImages=true -dAutoFilterGrayImages=true -dJPEGQ=95 -dPDFA=1 -dPDFACompatibilityPolicy=1 -o pdfa.pdf fox.pdf
```

veraPDF reports another error in the PDF/A-1b: 6.2.3-2.

So it looks like one error wasn't corrected by OCRmyPDF but could have been by Ghostscript when Ghostscript didn't correct another error corrected by OCRmyPDF, somehow before calling Ghostscript.

I guess my question is quite simple: Is OCRmyPDF  supposed/able to convert any PDF to a PDF/A? I guess I could ask the same question about Ghostscript.

The complete trace by OCRmyPDF:
```
    1 Rasterize with png16m, rotation 0                                                                                             
    1 Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r71.120001x71.120001', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.kdy_qwgm/origin.pdf']
    1 Rotating output by 0                                                                                                          
    1 resolution (71, 71)                                                                                                           
    1 Running: ['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', PosixPath('/tmp/ocrmypdf.io.kdy_qwgm/000001_ocr.png'), '/tmp/ocrmypdf.io.kdy_qwgm/000001_ocr_tess', 'pdf', 'txt']
    1 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                              
    1 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                          
Image processing: 100%|█████████████████████████████████████████████████████████████████████████| 1.0/1.0 [00:00<00:00,  6.92page/s]
Postprocessing...
Running: ['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=RGB', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=1', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.kdy_qwgm/fix_docinfo.pdf', '/tmp/ocrmypdf.io.kdy_qwgm/pdfa.ps']
GPL Ghostscript 9.50 (2019-10-15)
Copyright (C) 2019 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
GPL Ghostscript 9.50: UTF16BE text string detected in DOCINFO cannot be represented in XMP for PDF/A1, discarding DOCINFO
Processing pages 1 through 1.
Page 1                                                                                                                              
PDF/A conversion: 100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.12page/s]
os.symlink(/tmp/ocrmypdf.io.kdy_qwgm/metafix.pdf, /tmp/ocrmypdf.io.kdy_qwgm/optimize.pdf)
/tmp/ocrmypdf.io.kdy_qwgm/optimize.pdf -> output.pdf
Output file is a PDF/A-1B (as expected)
```
[fox.pdf](https://github.com/jbarlow83/OCRmyPDF/files/5901093/fox.pdf)

**Comment by so-o** [comment]
The same JPEG converted to a PDF with img2pdf then converted to a PDF/A-1b with Ghostscript fails with the same error: 6.2.3-2 - BUT no more errors if converted to a PDF/A-1b by OCRmyPDF. Interesting and very confusing. Note that veraPDF reported a different set of errors on the PDF generated by img2pdf: 6.2.3-2 6.7.2-1 6.7.3-1. img2pdf and convert do different job like explained in the documentation.

**Comment by so-o** [comment]
Now I have a problem converting a PNG to a PDF with img2pdf. I could force convert to do it by changing its policy.xml. No way to do this with OCRmyPDF? How does `convert file.img jpeg:file.img `followed by `img2pdf -o file.pdf file.img` sound to you. The resulting file.pdf is converted by OCRmyPDF to a PDF/A-1b just fine.

**Comment by so-o** [comment]
Thanks for you time ;)

**Comment by jbarlow83** [comment]
```
gs -dBATCH -dNOPAUSE -dSAFER -dCompatibilityLevel=1.6 -sDEVICE=pdfwrite -dAutoRotatePages=/None -sColorConversionStrategy=RGB -dAutoFilterColorImages=true -dAutoFilterGrayImages=true -dJPEGQ=95 -dPDFA=1 -dPDFACompatibilityPolicy=1 -o pdfa.pdf fox.pdf
```

This command will not produce a valid PDF/A. The `pdfa.ps` file that ocrmypdf generates is essential to creating a valid PDF/A with Ghostscript.

Some PDFs cannot be converted to PDF/A.

Please always provide version numbers for the software you are currently using and fill out all of the details requested in the issue template. I [recently asked you do this on another issue](https://github.com/jbarlow83/OCRmyPDF/issues/698#issuecomment-748537856). It wastes both of our time to omit information that is necessary to resolving your issue.

**Comment by so-o** [comment]
I just installed the latest qpdf (2021-01-31), pikepdf (2.5.2.dev5+g5cb1631) and OCRmyPDF 11.6.0. If I forget to enter an `export LDFLAGS='-L/usr/local/lib'` before installing pikepdf, ocrmypdf coredumps.

**Comment by jbarlow83** [comment]
Thank you for providing the version numbers. You still have not provided other details requested in the issue template that I need. In particular: what operating system are you using, and steps to reproduce the problem including the command line you passed to OCRmyPDF.

Did you upgrade any of qpdf, pikepdf, OCRmyPDF or Ghostscript between opening this issue and your comment above?

>If I forget to enter an export LDFLAGS='-L/usr/local/lib' before installing pikepdf, ocrmypdf coredumps.

That sounds like a new and probably unrelated issue. Please open a new issue to discuss that problem. It will help us both stay organized.

**Comment by so-o** [comment]
The issue about LDFLAGS isn't new. We have talked about it already. You said the documentation was corrected.

I can't install the latest pikepdf on Ubuntu 16.04. No problem on Ubuntu 20.04. wheel fails. I think it's an issue with gcc. I installed python3.8 and python3.8-dev on this machine.

**Comment by so-o** [comment]
Making a PDF/A-1b with pikepdf 2.1.2 fails with error 6.7.3-1. The error goes away with pikepdf 2.5.2. Did you change something after the issue I reported about this error?

**Comment by jbarlow83** [comment]
I did not make any changes to pikepdf code in the timeline of this issue. (I did tag commit 5cb1631 as v2.5.2.) All of this information is in the git history and release notes.

I take it to mean that your issue is resolved by upgrading to the latest version of pikepdf, so I will close this.
