### ISSUE TITLE
Bug in matrix concatenation in pageinfo.py

### ISSUE THREAD

**Issue by kleins05** [jbarlow83/OCRmyPDF#73]
Hi,

just to let you know there is a mistake in matrix concatenation in pageinfo.py:95+96.
The two matrices are multiplied the wrong way round (matrix multiplication is not commutative). This does not affect scaling and since pageinfo.py is only extracting width and height of the image, you don't notice the mistake. It does, however, affect translation. I used and extended your code in my own project to extract the x and y coordinates of the image on the page and this is were you notice the mistake, the resulting coordinates are completely wrong.

All you need to do is swap the order of the operands for it to work properly, i.e. matrix_mult(_matrix_from_shorthand(operands), ctm). For details see the PDF 1.7 reference by Adobe, section 4.23, especially the second half from the bottom of page 208 onwards (http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf)

**Comment by jbarlow83** [comment]
Good catch - thanks. Feel free to contribute any other work from your project that might be of interest to others.
