### ISSUE TITLE
Potential regression: hang at the last steps of OCR with versions >= 10.3

### ISSUE THREAD

**Issue by rbrito** [jbarlow83/OCRmyPDF#733]
**Describe the bug**

I'm seeing, for a few releases, but starting with anything post 10.2 a hang at the last step of OCR (or Image Processing, or whatever it is called in recent releases). I guess that I'm seeing some kind of deadlock or something similar that I have yet to investigate further. I'm hoping that other people have seen it also.

**To Reproduce**

I'm using the following to "optimize" the PDF files (essentially, to just reencode the consecutive JBIG2 pages with dictionaries):

```bash
for i in *.pdf ; do ocrmypdf --verbose 1 --language eng --jbig2-lossy --optimize 3 --skip-text --jpeg-quality=75 --jbig2-page-group-size=25 "$i" "${i%%pdf}ocr.pdf"; done
```

The files in question are books that are already OCR'ed (taken from springer) and, usually, only their cover is not OCR'ed.

**Expected behavior**

Each process finishes.

**System:**

 - OS: Debian testing/sid, amd64
 - Python version: Python 3.9
 - OCRmyPDF version: 10.3 or later.

**Installation**

I'm seeing the problem with both Debian's testing/sid apt or pip (in a virtual environment). It doesn't matter.

**Additional context**

I have tried to strace the process, but I get too much output and I have not yet sorted things out. With ocrmypdf 10.2, everything is guaranteed to work in my environment. With anything else (RELEASED, not exactly inter-release commits), I get a very low chance of the process finishing.

Before I go on and try to play with concurrency stuff (setting `OMP_THREAD_LIMIT=1` doesn't make any difference so far) or git bisect'ing, I wonder if other people have seen anything like this?

**Comment by jbarlow83** [comment]
There are a few nontrivial changes in 10.3 that could be responsible. Bisecting 10.2.1 to 10.3 would helpful if you can't share the file.

strace would be too noisy but using a debugger to attach to a stuck process can be helpful sometimes. For debugging you may get better results by commenting out this line in _concurrent.py:
```
    # Ignore SIGINT (our parent process will kill us gracefully)
    signal.signal(signal.SIGINT, signal.SIG_IGN)
```

This makes Ctrl+C more orderly and allows us to present a clean error message when terminating this way, but has a side effect of preventing any debugger from stop child processes.

#732 may be related.

**Comment by Kyle-Johansen** [comment]
(Hi, I'm new to this so not sure if I should add it here or make a new ticket. Apologies if this is not right.)

I've recently upgraded my OCRMYPDFs after clearing my UbuntuForWindows10 environment. It now fails to finish some of the time. (I would say 10%). The following is what I get when I Ctrl-C.

Thank you, I can't share the files, but I don't think there's anything special about the files in which it hangs. My OCRMYPDF command was just 'ocrmypdf "$file" "$file"d' ($file being the variable containing the name of the PDF.)

![OCRMYPDF](https://user-images.githubusercontent.com/80254687/110309365-289e9d80-7ff9-11eb-9985-bb24574160df.png)

**Comment by jbarlow83** [comment]
@Kyle-Johansen  Please create a new ticket and provide as much as information as possible including the full output of ocrmypdf and full stack trace. While people often believe there is nothing special about their PDFs, you'd be surprised how often this is precisely the case, so please provide a file if you can. You can GPG-encrypt it, or if it's easy to reproduce, perhaps find a file that is not so private.

**Comment by AEgit** [comment]
I think I can reproduce this behaviour. If I use the current version of ocrmypdf (installed via pip3 for the current user only) within the Windows 10 WSL subsystem (both within Ubuntu 20.04 and 18.04), ocrmypdf gets stuck and no PDF is generated. The final message I get to see is:
![ocrmypdf_issue](https://user-images.githubusercontent.com/12767489/113150405-55c72000-9234-11eb-9dcb-d4c499b27097.png)

If, on the other hand, I use the ocrmypdf version (installed via apt) that is part of Ubuntu 20.04 (again as part of the Windows 10 WSL) then an OCR'ed PDF is generated.

This behaviour can be reproduced with the following PDF:
https://app.box.com/s/hccdcx5olwnl682g1xr2vg1zirhy4jhw


System:
OS: Ubuntu 20.04 (in Windows 10 WSL) (same behaviour also under Ubuntu 18.04 in Windows 10 WSL)
ocrmypdf 11.7.3
tesseract 4.1.1
gs 9.50

**Comment by AEgit** [comment]
I can confirm that the current version ocrmypdf 12.0.1 has solved the issue reported in https://github.com/jbarlow83/OCRmyPDF/issues/733#issuecomment-811075742

Thank you very much!
