### ISSUE TITLE
Windows: can't manage to install jbig2enc

### ISSUE THREAD

**Issue by principealex1** [jbarlow83/OCRmyPDF#737]
I'm trying to install jbig2enc as suggested from "OCRmyPDF" and it results in a failure. 

PS C:\WINDOWS\system32> choco install jbig2enc
Chocolatey v0.10.15
Installing the following packages:
jbig2enc
By installing you accept licenses for the packages.
jbig2enc not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'

Windows 10
Chocolatey v0.10.15
OCRmyPDF 11.6.2
PowerShell 5.1.19041.610

How can i install it? (i'm not a developer, just a standard user).

**Comment by jbarlow83** [comment]
jbig2enc is an optional add-on, but choco doesn't have a script to provide it for you. ocrmypdf will work without it so don't worry about its absence.

**Comment by principealex1** [comment]
> jbig2enc is an optional add-on, but choco doesn't have a script to provide it for you. ocrmypdf will work without it so don't worry about its absence.

So at the moment it's impossible to install this optional add-on of OCRmyPDF on Windows?, or there is a more "less user-friendly" way to do it?

**Comment by jbarlow83** [comment]
Not impossible, but I'm afraid there's no user friendly way to do get a precompiled jbig2 on any platform other than macOS. Most Linux distributions seen to be afraid of JBIG2 because it uses patented technology – even though the last patent expired in 2017.

If you can build it from source and put jbig2enc.exe on the system PATH then OCRmyPDF will find it and use it.

**Comment by principealex1** [comment]
> Not impossible, but I'm afraid there's no user friendly way to do get a precompiled jbig2 on any platform other than macOS. Most Linux distributions seen to be afraid of JBIG2 because it uses patented technology – even though the last patent expired in 2017.
> 
> If you can build it from source and put jbig2enc.exe on the system PATH then OCRmyPDF will find it and use it.

Maybe i managed to build it, i have 4 files now: **jbig2.exe** , jbig2.ilk, jbig2.pdb and libjbig2enc.lib.

1)jbig2.exe it's the only one that i need? (i need to rename it to "jbig2enc.exe"?)
2)i don't understand where i need to copy paste it, what you mean by "system PATH"?  😕 , sorry for the newbie questions.

**Comment by principealex1** [comment]
i've put only jbig2.exe on a system path and now OCRmyPDF recognize it...but i've done a test and it seems it's not used in the "image postprocessing", this is the output:

ocrmypdf --tesseract-timeout=0 --output-type pdf --optimize 3 --jbig2-lossy --skip-text input.pdf output.pdf
Scanning contents: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  6.54page/s]
Start processing 2 pages concurrently
Image processing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.0/10.0 [01:18<00:00,  7.82s/page]
Postprocessing...
JPEGs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 13.86image/s]
PNGs: 0image [00:00, ?image/s]
_**JBIG2: 0item [00:00, ?item/s]**_
Optimize ratio: 1.60 savings: 37.4%

It used just the standard JPEG optimization, what could be the reason?

**Comment by jbarlow83** [comment]
It won't use JBIG2 in a file that has no monochrome images.

**Comment by principealex1** [comment]
> It won't use JBIG2 in a file that has no monochrome images.

ok, thank you for your patience 😄 👍 , i'm used to "GUI softwares" but i think this software it's worth of my effort on trying to understand some command lines, it's surely the best in the free/open source category, great work 😃

**Comment by juanpablogd** [comment]
@principealex1  You can share jbig2.exe and libjbig2enc.lib files please? thank you in advance
