### ISSUE TITLE
Allow Group 4 -> JBIG2 (lossless) conversion with --output-type pdf

### ISSUE THREAD

**Issue by veikk0** [jbarlow83/OCRmyPDF#741]
I'm trying to achieve the best compression possible for PDF files that consist mostly of bitonal images compressed with CCITT Group 4 compression. OCRmyPDF's ability to convert bitonal images to lossless JBIG2 would make it ideal for this purpose. However, currently, it seems that OCRmyPDF does this only when using `--output-type pdfa`, which has implications for other format conversions.

By "best compression" here I mean "as few lossy conversions as possible while not increasing file size". In my case, I have Group 4 compressed text pages, JPEG pages, and some JPEG 2000 pages.

* With `--output-type pdfa`, I get the increased compression of JBIG2 over Group 4, but grayscale and color images are either lossily converted with JPEG or losslessly compressed with with "PNG-style" compression. The former involves loss of quality, and the latter results in a rather dramatic increase in file size.
*  With `--output-type pdf`, I get the benefit of images just being "passed through" and not being converted in any way, as this mode "preserves the original compression of all images". However, this also means that Group 4 images stay as they are and a space-saving JBIG2 conversion isn't being done.

Essentially, I'd like to be able to override the default behavior of `--output-type pdf` when it comes to bitonal image conversion.

I've considered a workaround of trying to create an input PDF that already uses JBIG2 instead of Group 4, but this would result in additional complexity, changes, and possible bugs to my current PDF creation process, even if it was possible to do. It seems that neither ImageMagick or GraphicsMagick support creating JBIG2 TIF or PDF files (at least the builds I have installed don't). I'd probably have to try to use the `jbig2` CLI tool directly and start dealing with joining individual PDF pages together instead of just using img2pdf to do everything in one simple command. I think I'd rather just stick with Group 4.

In terms of how this functionality would be invoked, it seems like none of the options listed under "Optimization options"  currently apply to `--output-type pdf`, so the value for `--optimization` is essentially 0 unless you've selected PDF/A output. So if this were to be implemented, the functionality could be activated by `--optimization 1`. And if preserving the file as it is by default is desired, have `--optimization 0` be the default for `--output-type pdf`.

**Comment by jbarlow83** [comment]
Optimization is definitely performed when the output type is pdf.

```
$ ocrmypdf tests/resources/ccitt.pdf --output-type pdf _.pdf
Scanning contents: 100%|| 1/1 [00:00<00:00, 154.63page/s]
OCR: 100%|| 1.0/1.0 [00:04<00:00,  4.34s/page]
Postprocessing...
JPEGs: 0image [00:00, ?image/s]
JBIG2: 100%|| 1/1 [00:00<00:00, 18.09item/s]
Optimize ratio: 1.39 savings: 27.9%

$ pdfimages -list _.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2550  3300  gray    1   1  jbig2  no        13  0   300   300 69.4K 6.8%
```

You probably have an atypical PDF whose bitonal images are being rejected as optimization candidates. The optimizer will reject any images if we're not confident the file will look the same if we optimize them. And during PDF/A conversion, it so happens Ghostscript normalizes images, so the optimizer probably considers them safe to optimize. 

Please fill out the rest of the details requested in the new issue template. I'll need that information to take this any further.

If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

You can also use `qpdf --json` to generate a structural skeleton of a PDF with all images and text removed. Sometimes this is enough.

**Comment by veikk0** [comment]
I see. I thought this was intended behavior, since AFAIK it's happened with every PDF I've run through the program (mostly self-authored and bitonal image based) and the help output talks about not touching the PDF contents in `pdf` output mode.

Here are some test and output/log files:

* [adventuresofsher00doylrich_0045.tif](https://github.com/jbarlow83/OCRmyPDF/files/6056789/adventuresofsher00doylrich_0045.tif.zip) (zipped)
* [input.pdf](https://github.com/jbarlow83/OCRmyPDF/files/6056790/input.pdf) (converted from TIF file with `img2pdf -o input.pdf adventuresofsher00doylrich_0045.tif`)
* Output of `gm identify -verbose adventuresofsher00doylrich_0045.tif`: [identify.txt](https://github.com/jbarlow83/OCRmyPDF/files/6056794/identify.txt)
* Output of `ocrmypdf -v1 --output-type pdf input.pdf output.pdf`: [ocrmypdf-output.txt](https://github.com/jbarlow83/OCRmyPDF/files/6056821/ocrmypdf-output.txt)

**System**
 - OS: Linux Mint 20.1
 - Python version: 3.8.5
 - OCRmyPDF Version: ``11.6.2``, installed from pip
 - img2pdf version: 0.4.0

**Additional context**

I've tried to `gm mogrify -compress Group4` the TIF file, but this doesn't make a difference.

Most of the files I'm having issues with are TIFs output by [ScanTailor-Universal](https://github.com/trufanov-nok/scantailor-universal) v0.2.10, installed from a 64-bit .deb available [from here](https://github.com/trufanov-nok/scantailor-universal/releases/tag/0.2.10). However, images from other sources I've converted with GraphicsMagick (`gm convert input.png -threshold 50% -compress Group4 output.tif`) also exhibit this issue.

**Comment by jbarlow83** [comment]
Thank you. My speculation was close: turns the issue was that img2pdf has changed the way it creates one of the data structures to describe CCITT images. pikepdf raised an exception when trying to access it this way, causing ocrmypdf to skip optimizing the image. Ghostscript rewrites it the same data structure to equivalent and more commonly used format.

Upgrading to pikepdf 2.8.0 will fix the issue.

**Comment by veikk0** [comment]
Thanks. Upgrading pikepdf did fix the issue.

**Comment by Iey4iej3** [comment]
I encounter a similar issue under Debian Buster with OCRmyPDF 12.3.2 installed by `pip`. I don't know whether it is an "atypical" PDF: [the file](https://www.dropbox.com/s/8tyteh4oftylltb/test.pdf.gpg?dl=0) should not be diffused.
