### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by kevin-kruse** [jbarlow83/OCRmyPDF#742]
**Describe the bug**
Hi, OCRmyPDF throws the `[WinError 2] The system cannot find the file specified` hundreds of times during the OCR process. This happens in my terminal, but also in my python environment (and there the first error message appears with the import of this tool).
Fortunately, the tool (seems to) works perfectly, this just messes up my progress bar.

**To Reproduce**
I just import the tool in python or type ```ocrmypdf test.pdf output.pd```

**Expected behavior**
No error messages disturbing the output.

**System (please complete the following information):**
 - OS: Windows 10
 - Python version: Python 3.7
 - OCRmyPDF version: 11.7.0

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
Using pip

**Additional context**
Here is the log with verbose 2 logging level:
```
C:\ ocrmypdf test.pdf output.pdf --verbose 2
[WinError 2] The system cannot find the file specified
  DEBUG ocrmypdf - ocrmypdf 11.7.0
  DEBUG ocrmypdf.subprocess - Running: ['C:\\Users\\ dummyuser \\AppData\\Local\\Programs\\Tesseract-OCR\\tesseract.EXE', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = List of available languages (7):
chi_sim
chi_sim_vert
chi_tra
chi_tra_vert
deu
eng
osd
 
  DEBUG ocrmypdf.subprocess - Running: ['C:\\Users\\ dummyuser \\AppData\\Local\\Programs\\Tesseract-OCR\\tesseract.EXE', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 5.0.0-alpha.20201127
  DEBUG ocrmypdf.subprocess - Running: ['C:\\Users\\dummyuser\\AppData\\Local\\Programs\\Tesseract-OCR\\tesseract.EXE', '-l', 'eng', '--print-parameters', 'pdf']
  DEBUG ocrmypdf.subprocess - Running: ['C:\\Program Files\\gs\\gs9.53.3\\bin\\gswin64c.EXE', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 9.53.3
  DEBUG ocrmypdf.helpers - pikepdf mmap disabled
Scanning contents:   0%|                                                                      | 0/12 [00:00<?, ?page/s][WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
  DEBUG ocrmypdf.helpers - pikepdf mmap disabled
  DEBUG ocrmypdf.helpers - pikepdf mmap disabled
```

Best,
kevin

**Comment by jbarlow83** [comment]
Can't reproduce on my Windows 10 machine and I tried many different things. I suggest upgrading to Python 3.9 in case that resolves it. I am suspicious that something is wrong with your Python installation, and these errors occur when the 

If you are adventurous enough to dig around the code you could try:
* Make `__main.py__` call `set_start_method('spawn')` always instead of just on darwin
* Set up an IDE/debugger to trap WinError whenever it happens that might help too.

**Comment by jbarlow83** [comment]
Out of curiosity, are you the historian Kevin M Kruse, or just someone named Kevin Kruse?

**Comment by kevin-kruse** [comment]
Hi, I upgraded to the newest python version and the error doesn't appear anymore..
It was weird, since the tool was working regardless of this error.

Regarding you question: No, I'm just someone named Kevin Kruse - I'm not ocring historical books.
