### ISSUE TITLE
--redo-ocr succeeds, but --force-ocr throws gs error

### ISSUE THREAD

**Issue by julianbarg** [jbarlow83/OCRmyPDF#750]
**Describe the bug**
--redo-ocr unfortunately removes some chunks of the pdf, so I want to use --force ocr on this file.

**To Reproduce**
```ocrmypdf input.pdf output.pdf --redo-ocr``` unfortunately removes some chunks of the pdf (text sections with markings).
```ocrmypdf input.pdf output.pdf --force-ocr``` gives this error:
```
ERROR - SubprocessOutputError: Ghostscript text extraction failed
/tmp/com.github.ocrmypdf.3k1am01w/origin.pdf
```

**Example file**
[input.pdf](https://github.com/jbarlow83/OCRmyPDF/files/6142395/input.pdf)

**System**
 - Ubuntu 20.04
 - OCRmyPDF Version: 9.6.0+dfsg
 - ```apt install ocrmypdf```

**edit**:
Forgot to mention, I already tried ```gs -o output.pdf -dSAFER -sDEVICE=pdfwrite input.pdf``` and ```pdftk input.pdf cat output output.pdf``` as preprocessing steps.

**Comment by jbarlow83** [comment]
Ghostscript broke its text extraction feature in recent versions. Newer versions of ocrmypdf (somewhere around 10+) implement text extraction a different way and also much more performant. You'll need to upgrade.

https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-with-python-pip
