### ISSUE TITLE
Python subprocess and ocrmypdf

### ISSUE THREAD

**Issue by KasprzykM** [jbarlow83/OCRmyPDF#752]
**Describe the bug/(issue?)**
I am running into a problem where I am trying to run ocrmypdf as a command using Pythons [subprocess](https://docs.python.org/3/library/subprocess.html) module. It throws an error like so 

```
ERROR:root:usage: ocrmypdf [-h] [-l LANGUAGES] [--image-dpi DPI]
                [--output-type {pdfa,pdf,pdfa-1,pdfa-2,pdfa-3}]
                [--sidecar [FILE]] [--version] [-j N] [-q] [-v [VERBOSE]]
                [--title TITLE] [--author AUTHOR] [--subject SUBJECT]
                [--keywords KEYWORDS] [-r] [--remove-background] [-d] [-c]
                [-i] [--unpaper-args UNPAPER_ARGS] [--oversample DPI]
                [--remove-vectors] [--threshold] [-f] [-s] [--redo-ocr]
                [--skip-big MPixels] [-O {0,1,2,3}] [--jpeg-quality Q]
                [--png-quality Q] [--jbig2-lossy] [--pages PAGES]
                [--max-image-mpixels MPixels]
                [--pdf-renderer {auto,hocr,sandwich,hocrdebug}]
                [--rotate-pages-threshold CONFIDENCE]
                [--pdfa-image-compression {auto,jpeg,lossless}]
                [--fast-web-view MEGABYTES] [--plugin PLUGINS] [-k]
                [--tesseract-config CFG] [--tesseract-pagesegmode PSM]
                [--tesseract-oem MODE] [--tesseract-timeout SECONDS]
                [--user-words FILE] [--user-patterns FILE]
                input_pdf_or_image output_pdf
ocrmypdf: error: unrecognized arguments: /tmp/tmpxu946a_5

```
Where `/tmp/tmpxu946a_5` is last argument and is a path to a temporary file. **The problem is that if I copy the command that is not working with subprocess and run directly in CLI it does work and does not throw error about unrecognized argument.** 

The exact line that executes my command looks like this:

`subprocess.check_output(command, env=os.environ.copy(), stderr=subprocess.STDOUT)` where `command` is list of strings that when joined by `' '.join(map(str, command))` looks as following:

```
ocrmypdf --force-ocr --deskew --keep-temporary-files --jobs=1 --oversample=600 --verbose=1 --max-image-mpixels=12000 --pdf-renderer hocr --tesseract-pagesegmode=1 --tesseract-timeout=3000 --tesseract-config=tesseract.cfg --language=eng --rotate-pages ocrscan.pdf /tmp/tmp1mla879b
```

I've noticed that if I remove `--pdf-renderer hocr` the command works both in subprocess call and in CLI, however it is very much needed. 

It is possible that I might have screwed something up but I am not entirely certain what could be wrong. What could it be? Why is same command not working in subprocess call but works in CLI?

**System (please complete the following information):**
 - OS: KUbuntu 20.04
 - Python version: 3.8
 - OCRmyPDF version: 11.7.2

**Installation**
Installed by pip.

**Comment by jbarlow83** [comment]
If one of your arguments is `'--pdf-renderer hocr'`, subprocess will read that as `--pdf-renderer\ hocr` and generally mess up the parsing. You need to do `'--pdf-renderer=hocr'` or `[..., '--pdf-renderer', 'hocr', ...]`

For a script you may find it easier to `import ocrmypdf; ocrmypdf.ocr(...)` and pass the arguments normally.

**Comment by KasprzykM** [comment]
Emm.. I feel so silly now, apologies. It did help. Thank you very much!
