### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by lokesh06051997** [jbarlow83/OCRmyPDF#754]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-eaddc7513712> in <module>
----> 1 import pdfplumber
      2 import re
      3 with pdfplumber.open("C:/Users/USER29/Downloads/DRAFT_Vol_I.pdf") as pdf:
      4     keyword_page = pdf.pages[5]
      5     a=keyword_page.extract_text()

~\anaconda3\lib\site-packages\pdfplumber\__init__.py in <module>
      8 
      9 from ._version import __version__
---> 10 from .pdf import PDF
     11 from . import utils
     12 import pdfminer

~\anaconda3\lib\site-packages\pdfplumber\pdf.py in <module>
      7 import itertools
      8 from pdfminer.pdfparser import PDFParser
----> 9 from pdfminer.pdfdocument import PDFDocument
     10 from pdfminer.pdfpage import PDFPage
     11 from pdfminer.pdfinterp import PDFResourceManager

~\anaconda3\lib\site-packages\pdfminer\pdfdocument.py in <module>
     12 from .psparser import PSEOF, literal_name, LIT, KWD
     13 from . import settings
---> 14 from .pdftypes import PDFException, uint_value, PDFTypeError, PDFStream, \
     15     PDFObjectNotFound, decipher_all, int_value, str_value, list_value, \
     16     dict_value, stream_value

ImportError: cannot import name 'uint_value' from 'pdfminer.pdftypes' (C:\Users\USER29\anaconda3\lib\site-packages\pdfminer\pdftypes.py)

**Comment by jbarlow83** [comment]
This does not look like an ocrmypdf issue. Try reporting to pdfplumber or pdfminer.
