### ISSUE TITLE
Output.pdf File Not Found

### ISSUE THREAD

**Issue by mrkgoh** [jbarlow83/OCRmyPDF#756]
@jbarlow83 , thanks for the work you do.

I have ocrmypdf running in my Synology NAS DS220+ via docker.

My test file is located in 'volume1/homes/idname/docker/test.pdf'

`idname@somesynologyname:~$ docker run -d -v $(pwd):/home/docker ocrmypdf test.pdf output.pdf
b4b3ec9c4e6deef9c26b72da8a5b7073cb3866b2b79144f412076d868061482a
`
I received the output above. However I am unable to locate output.pdf file. 

Here is the test.pdf file:
[test.pdf](https://github.com/jbarlow83/OCRmyPDF/files/6275894/test.pdf)

**Comment by jbarlow83** [comment]
Try using the stdin/stdout method suggested in the documentation:
https://ocrmypdf.readthedocs.io/en/latest/docker.html#using-the-docker-image-on-the-command-line

**Comment by mrkgoh** [comment]
@jbarlow83  thanks for the prompt reply.
Here is what I did and received a new error (seems that I am close):
`
idname@somesynologyname:~$ alias docker_ocrmypdf='docker run --rm  -i --user "$(id -u):$(id -g)" --workdir /docker -v "$PWD:/home/docker" ocrmypdf'
idname@somesynologyname:~$ docker_ocrmypdf /docker/test.pdf /docker/output.pdf
OutputFileAccessError: Output file location (/docker/output.pdf) is not a writable file.
`

**Comment by jbarlow83** [comment]
Don't use docker run -v at all.

Use the pure stdin/stdout method where you don't tell docker about your local file system.

**Comment by mrkgoh** [comment]
I have a feeling I am doing something stupid like missing a '/' or something here.
`admin@somesynologyname:~/docker$ docker_ocrmypdf </volume1/homes/admin/docker/test.pdf >/volume1/homes/admin/docker/output.pdf
usage: ocrmypdf [-h] [-l LANGUAGES] [--image-dpi DPI]
                [--output-type {pdfa,pdf,pdfa-1,pdfa-2,pdfa-3}]
                [--sidecar [FILE]] [--version] [-j N] [-q] [-v [VERBOSE]]
                [--title TITLE] [--author AUTHOR] [--subject SUBJECT]
                [--keywords KEYWORDS] [-r] [--remove-background] [-d] [-c]
                [-i] [--unpaper-args UNPAPER_ARGS] [--oversample DPI]
                [--remove-vectors] [--threshold] [-f] [-s] [--redo-ocr]
                [--skip-big MPixels] [-O {0,1,2,3}] [--jpeg-quality Q]
                [--png-quality Q] [--jbig2-lossy] [--pages PAGES]
                [--max-image-mpixels MPixels]
                [--pdf-renderer {auto,hocr,sandwich,hocrdebug}]
                [--rotate-pages-threshold CONFIDENCE]
                [--pdfa-image-compression {auto,jpeg,lossless}]
                [--fast-web-view MEGABYTES] [--plugin PLUGINS] [-k]
                [--tesseract-config CFG] [--tesseract-pagesegmode PSM]
                [--tesseract-oem MODE] [--tesseract-timeout SECONDS]
                [--user-words FILE] [--user-patterns FILE]
                input_pdf_or_image output_pdf
ocrmypdf: error: the following arguments are required: input_pdf_or_image, output_pdf
read unix @->/var/run/docker.sock: read: connection reset by peer`

But this time I have an output.pdf but it is 0 kb in size.
`
admin@somesynologyname:~/docker$ dir
total 3160
drwxrwxrwx+ 1 admin users      36 Apr  8 12:49 .
drwxrwxrwx+ 1 admin users     234 Apr  8 12:49 ..
-rwxrwxrwx+ 1 admin users       0 Apr  8 12:50 output.pdf
-rwxrwxrwx+ 1 admin users 3232012 Jun  2  2013 test.pdf`

**Comment by mrkgoh** [comment]
Here is my latest attempt: Error this time is that it is encrypted but the pdf is not encrypted.

`admin@MnASynology:~$ docker_ocrmypdf - - </docker/test.pdf >/docker/output.pdf
-sh: /docker/test.pdf: No such file or directory
admin@MnASynology:~$ dir
total 16
drwxrwxrwx+ 1 admin users 234 Apr  8 12:49 .
drwxrwxrwx+ 1 root  root   38 Mar  9 14:33 ..
-rwxrwxrwx+ 1 admin users 111 Feb 25 10:48 .bashrc
drwxrwxrwx+ 1 admin users  34 Mar 31 22:09 .cache
drwxrwxrwx+ 1 admin users  56 Apr  8 04:50 .config
drwxrwxrwx+ 1 admin users  16 Apr  8 12:57 docker
drwxrwxrwx+ 1 admin users 126 Mar 22 10:26 Drive
drwxrwxrwx+ 1 admin users   0 Mar 12 21:34 .ipynb_checkpoints
drwxrwxrwx+ 1 admin users  74 Feb 27 23:27 .ipython
drwxrwxrwx+ 1 admin users  44 Mar 12 21:37 .jupyter
drwxrwxrwx+ 1 admin users  34 Mar  1 07:30 .local
-rwxrwxrwx+ 1 admin users 440 Apr  8 05:00 .python_history
drwxrwxrwx+ 1 root  root  502 Apr  8 10:31 #recycle
drwxrwxrwx+ 1 admin users  22 Feb 25 01:17 .ssh
drwxrwxrwx+ 1 admin users  68 Feb 27 23:22 venv
-rwxrwxrwx+ 1 admin users 605 Feb 25 10:48 .viminfo
lrwxrwxrwx  1 admin users   9 Feb 18 11:15 volume1 -> /volume1/
admin@MnASynology:~$ docker_ocrmypdf - - <./docker/test.pdf >./docker/output.pdf
reading file from standard input
EncryptedPdfError: Input PDF is encrypted. The encryption must be removed to
perform OCR.

For information about this PDF's security use
    qpdf --show-encryption infilename

You can remove the encryption using
    qpdf --decrypt [--password=[password]] infilename`

**Comment by mrkgoh** [comment]
I tried the following again but this time with another pdf file and it works:

`someid@somenas:~$ docker_ocrmypdf - - <./docker/test.pdf >./docker/output.pdf
reading file from standard input
Start processing 2 pages concurrently
Postprocessing...
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
Optimize ratio: 1.15 savings: 13.3%
Output sent to stdout`

Here are my test.pdf and output.pdf: 
[test.pdf](https://github.com/jbarlow83/OCRmyPDF/files/6276203/test.pdf)
[output.pdf](https://github.com/jbarlow83/OCRmyPDF/files/6276204/output.pdf)

Thanks @jbarlow83
