### ISSUE TITLE
Use Multi-threading instead of multi-processing on platforms not supporting it

### ISSUE THREAD

**Issue by MrAdityaAlok** [jbarlow83/OCRmyPDF#760]
**Is your feature request related to a problem? Please describe.**

Android platform lacks `sem_open` implementation,

**Describe the solution you'd like**

so it would be very very grateful  to use multi-threading instead, on platforms not supporting it

**Additional context**

```
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

I am using Android terminal emulator [Termux](https://termux.com) on a non  rooted android device

**Comment by jbarlow83** [comment]
Can you check if awslambda works on Termux?

Using ocrmypdf v12.0.0b1:

`ocrmypdf --plugin extra_plugins/awslambda.py  in.pdf out.pdf...`

This is a semaphore free multiprocess implementation.

**Comment by MrAdityaAlok** [comment]
@jbarlow83  yes it works, but is there any way to fix this
```
16 [tesseract] OMP: Warning #96: Cannot form a team with 4 threads, using 1 instead.
   16 [tesseract] OMP: Hint Consider unsetting KMP_DEVICE_THREAD_LIMIT (KMP_ALL_THREADS), KMP_TEAMS_THREAD_LIMIT, and OMP_THREAD_LIMIT (if any are set).
   19 page already has text! - rasterizing text and running OCR anyway
   15 [tesseract] took too long to OCR - skipping
```

**Comment by jbarlow83** [comment]
`env OMP_THREAD_LIMIT=1 ocrmypdf ...` will likely fix that.

**Comment by MrAdityaAlok** [comment]
Thank you!  All worked

**Comment by jbarlow83** [comment]
@MrAdityaAlok  @tathastu871 can either of you try ocrmypdf 12.0.0b4 *without* ` --plugin extra_plugins/awslambda.py`? I believe I can detect termux now.

**Comment by tathastu871** [comment]
not working any of above solutions

**Comment by jbarlow83** [comment]
12.0.0b4 hadn't finished building at the time of your comment

**Comment by MrAdityaAlok** [comment]
@jbarlow83  yes it works and surprisingly faster then before.🎉
Thank you.

**Comment by tathastu871** [comment]
I installed ocrmypdf using pip install ocrmypdf on termux
and it shows above multiprrocessing not supported error

**Comment by MrAdityaAlok** [comment]
@tathastu871  You have to build from the master branch, [pypi](https://pypi.org/project/ocrmypdf/) has this 11.7.3 version
```
git clone -b master https://github.com/jbarlow83/OCRmyPDF.git
cd OCRmyPDF
pip install .
```

**Comment by eelalzep** [comment]
> @tathastu871  You have to build from the master branch, [pypi](https://pypi.org/project/ocrmypdf/) has this 11.7.3 version
> ```
> git clone -b master https://github.com/jbarlow83/OCRmyPDF.git
> cd OCRmyPDF
> pip install .
> ```

git clone -b master https://github.com/jbarlow83/OCRmyPDF.git
cd OCRmyPDF
pip install .
Cloning into 'OCRmyPDF'...
fatal: Remote branch master not found in upstream origin
cd: no such file or directory: OCRmyPDF
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
