### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by emshihab008** [jbarlow83/OCRmyPDF#765]
Hi,
When i try to run the below code, it is showing the output.

Output:
```
None
[WinError 2] The system cannot find the file specified
InputFileError: File not found - path
```

How can i solve this issue?

Code:
```
import os
import ocrmypdf
import pdfplumber
path= "G:\\RPA_testing\\scanpdf.pdf"
os.system(f"ocrmypdf {path} output.pdf")
!ocrmypdf path output.pdf
invoice= pdfplumber.open(path)
page=invoice.pages[14]
text=page.extract_text(x_tolerance=2)
print(text)
```

**Comment by jbarlow83** [comment]
`!ocrmypdf path output.pdf` won't substitute a variable.

Use `ocrmypdf.ocr(a, b)` when using ocrmypdf in a script rather than invoking from a command line.

**Comment by MislavSag** [comment]
I confirm I have the same problem. This is probbably related to this issue from yesterday: https://github.com/jbarlow83/OCRmyPDF/issues/764

**Comment by emshihab008** [comment]
thank you for your suggestion. It worked.
