### ISSUE TITLE
--unpaper-args: expected one argument

### ISSUE THREAD

**Issue by rafpaf** [jbarlow83/OCRmyPDF#767]
`ocrmypdf -l fra --clean --unpaper-args '--layout double' in.pdf out.pdf`

Response:

`ocrmypdf: error: argument --unpaper-args: expected one argument`

With Ubuntu 18.04.5 LTS, Python 3.6.9, OCRmyPDF version 12.0.0b3 (installed with pip).

**Comment by jbarlow83** [comment]
What shell were you using? 

You might need to do `ocrmypdf -l fra --clean --unpaper-args '--layout double' -- in.pdf out.pdf`

**Comment by rafpaf** [comment]
That works - thank you. I'm using zsh. Confused, I switched to ocrmypdf with docker which also worked.

**Comment by reticulatingsplines** [comment]
Sorry to resurrect, but I'm actually am having this same issue. The extra -- trick doesn't work in my case, but what did was changing my command:

`ocrmypdf --deskew --sidecar --remove-vectors --clean-final --unpaper-args "--no-mask-scan" in.pdf out.pdf`

to this, which does work as expected:

`ocrmypdf --deskew --sidecar --remove-vectors --clean-final --unpaper-args  \"--no-mask-scan\" in.pdf out.pdf`

macOS 12.4, python 3.10.4, ocrmypdf 13.4.6, shell is zsh.
