### ISSUE TITLE
PDF.js has had a major contribution to improve spacing

### ISSUE THREAD

**Issue by RNCTX** [jbarlow83/OCRmyPDF#774]
I thought of your project since I was using it back in 2018 or so when I got a notification about this, don't know if you've seen it, I looked for your email but unfortunately didn't save it so couldn't find a way to reach out other than here.

https://github.com/mozilla/pdf.js/pull/13257

I haven't tested this since I'm not doing much work with PDF searching projects anymore but if it brings PDF.js up to par with other rendering options that's a pretty big help, obviously, since the others aren't as easily 'pluggable' into other projects as PDF.js is.

**Comment by jbarlow83** [comment]
Thanks for the information.

Now, if only Apple would get around to improving Preview, we'd be able to improve spacing for everyone.

**Comment by RNCTX** [comment]
Indeed.
