### ISSUE TITLE
docker guide clarification

### ISSUE THREAD

**Issue by ahmedtds** [jbarlow83/OCRmyPDF#777]
Can you make how to use docker image with more language packs clearer please? https://ocrmypdf.readthedocs.io/en/v12.0.1/docker.html#docker-lang-packs

`"You can also copy training data to /usr/share/tesseract-ocr/<tesseract version>/tessdata."`

How? Should I put another line to dockerfile? What exactly is the line? And how will I know which "tesseract version" docker image have?

And how am I gonna use that dockerfile with the given example commands in the page?

Thanks in advance.

**Comment by jbarlow83** [comment]
I expanded the documentation.

The tesseract (data file) version is currently 4.00. The version is not the same as the installed tesseract binary unfortunately.

You create a new Dockerfile, which is based on the standard ocrmypdf Dockerfile (using FROM) and adds your customizations. You would use `docker build` to build the new image specified by the Dockerfile, and `docker tag` to give it a memorable name.

**Comment by ahmedtds** [comment]
Thank you so much this makes things much more clear @jbarlow83
