### ISSUE TITLE
documents with mixed contents

### ISSUE THREAD

**Issue by quizilkend** [jbarlow83/OCRmyPDF#78]
Hey,

is it possible to let ocrmypdf work on documents with mixed contents?
If a PDF-File is created with an office application there is already a text layer, but maybe there are graphics with text as well.
My question is if there is a way to keep the text layer as is and only work on the included graphics if that's possible.

I attached a document to maybe clear up my question.
[example.zip](https://github.com/jbarlow83/OCRmyPDF/files/341401/example.zip)

**Comment by jbarlow83** [comment]
It can't handle mixed contents in the way that you want.

`ocrmypdf --force-ocr` will rasterize the whole page as a graphic and OCR it. You will want `--lang deu` as well. This means that existing text will get forced through OCR and so accuracy will be lost, but maybe it's worthwhile.

If you have Acrobat you could create one copy of the PDF and delete all of the images manually, and another where you delete all the text. Then OCR the image-only version with ocrmypdf and watermark the text version on top using a tool like `pdftk`. Labour intensive, though.

I think Abbyy FineReader would let you do exactly what you want, marking the graphic regions you want to OCR, for another commercial solution.

`ocrmypdf --skip-text` will skip OCR on pages that contain text, if you have a document that is a mix of pages that need OCR and those that don't, this is the feature you would use, but it does not handle mix graphics and text on the same page.

**Comment by quizilkend** [comment]
Okay, thanks for the reply. 
I will see what fits best.

**Comment by eMPee584** [comment]
> ocrmypdf --force-ocr will rasterize the whole page as a graphic and OCR it.

This doesn't work for me. It gives
`   INFO -    1: page has no images - skipping OCR`
on a page that seemingly has CID fonts without a proper toUnicode map (?)


    name                                 type              encoding         emb sub uni object ID
    ------------------------------------ ----------------- ---------------- --- --- --- ---------
    KSUHMK+TT34o00                       Type 1C           Custom           yes yes yes      6  0
    GZOLON+TT3Do00                       Type 1C           Custom           yes yes yes     10  0

[sample-page.pdf](https://github.com/jbarlow83/OCRmyPDF/files/386930/sample-page.pdf)

**Comment by jbarlow83** [comment]
@eMPee584 I didn't picture that anyone would have a use for forcing OCR on pages without images, so it deliberate does not do this. Your example is a good use case for this. I'll address this in a separate ticket.
