### ISSUE TITLE
I have faint scans, what are the best settings to increase the contrast and have more reliable processing

### ISSUE THREAD

**Issue by BrianSHenderson** [jbarlow83/OCRmyPDF#780]
I have black and white scans where some of the writing was done with pencil, what settings can I use to improve reading with Tesseract/AWS Textract?

**Comment by jbarlow83** [comment]
Handwriting recognition is very, very difficult but Textract, Azure OCR, maybe Google Vision, with deep learning, have made some progress on it. Now, if you have handwriting that has converted to monochrome, you've taken a very hard problem in the first place and made it significantly. My advice would be to rescan in grayscale if you have pure black and white scans.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
