### ISSUE TITLE
Correcting recognition errors - possible with sidecar option?

### ISSUE THREAD

**Issue by jdescelliers** [jbarlow83/OCRmyPDF#781]
I haven't looked in the code but is it possible to:
1. run OCRmyPDF with sidecar option to perform a first pass of characters recognition,
2. make corrections to the output file generated by the sidecar option if needed,
3. re run OCRMyPDF using the corrected sidecar output file as input.

OCR is a heuristic approach after all.

**Comment by jbarlow83** [comment]
If getting recognized text 100% is your goal, there are no open source solutions I am aware of. Your best bet is to use Abbyy FineReader which lets you edit the OCR text in a GUI. Making the corrections in FineReader is quite tedious. On rough scans it can take 15-30 minutes per page. Frankly, they do a good job and the price is reasonable.

With ocrmypdf, you could run `--output-type hocr -k` to generate the .hocr file which contains a HTML-like description of the recognized characters and edit this file then manually use hocrtranform to finish the file. It won't be exactly right unless you also fiddle with the pixel coordinates.

OCRmyPDF's user story is closer to: "I have 10,000 PDFs each with 100-500 pages. I need them all to have decent OCR, and I want to completely confidence that the software will not damage any of them. They're confidential and I don't want to upload them to some cloud service; I want to use software that doesn't even know the internet exists. Would be great if the files were compressed too." Our user story is not "I have this very important scanned document and I need 100% accurate OCR no matter how much manual assistance is needed." Abbyy FineReader is not a "competitor" - OCRmyPDF solves a different problem.

**Comment by jdescelliers** [comment]
Thanks for your reply.

I'm not complaining, in fact I find OCRMyPDF to be quite useful and well documented. Are you open to suggestions to improve the documentation to document this use case?

I wouldn't mind contributing to the documentation.

**Comment by jbarlow83** [comment]
Yes, that sounds fine to me.

**Comment by endolith** [comment]
> With ocrmypdf, you could run `--output-type hocr -k` to generate the .hocr file which contains a HTML-like description of the recognized characters and edit this file then manually use hocrtranform to finish the file. It won't be exactly right unless you also fiddle with the pixel coordinates.

Can you give more specific instructions?

```
ocrmypdf: error: argument --output-type: invalid choice: 'hocr' (choose from 'pdfa', 'pdf', 'pdfa-1', 'pdfa-2', 'pdfa-3')
```

**Comment by endolith** [comment]
https://github.com/ocrmypdf/OCRmyPDF/discussions/1254
