### ISSUE TITLE
'skip-text' doesn't get recognized when OCRmyPDF is used in a python batch script

### ISSUE THREAD

**Issue by Scorpion008** [jbarlow83/OCRmyPDF#783]
**Describe the bug:**
Every time I try to use the 'skip-text' parameter when using OCRmyPDF in a python batch script, I get the following error:
```
  File "batch.py", line 49
    result = ocrmypdf.ocr(filename, end_path, deskew=True, skip-text=True, language="deu+eng")
                                                           ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
```
The same happens when I try to use force-ocr or redo-ocr. Other parameters seem to work fine.

**To Reproduce:**
I'm using the batch.py from https://ocrmypdf.readthedocs.io/en/latest/batch.html, but with different directories for input and output files and the following function call:
`result = ocrmypdf.ocr(filename, end_path, deskew=True, skip-text=True, language="deu+eng")`
Starting the script with python3 leads to this error.

**Expected behavior:**
The python script should run and OCRmyPDF should ignore PDFs that contain text.

**System:**
 - OS: Windows 10 using Ubuntu 20.04.2 LTS in the Windows Subsystem for Linux
 - Python version: 3.8.5
 - OCRmyPDF version: 12.0.2

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12973276/119233626-496f8d00-bb2a-11eb-916e-b84d92ed842b.png)

**Installation:**
I first installed an older version via apt-get and then updated it to 12.0.2 via pip3 to try to fix this problem.

**Additional context**
I get the same error when using 'force-ocr' or 'redo-ocr', but other parameters seem to work fine. And as shown in the screenshot, 'skip-text' also works when I start OCRmyPDF directly via Linux shell.

**Comment by jbarlow83** [comment]
Use an underscore: `skip_text`

**Comment by Scorpion008** [comment]
`skip_text` works, thanks! Maybe it's an idea to add this to the documentation if it isn't already there and I just missed it?
