### ISSUE TITLE
unpaper dies via SIGKILL: 9 while OCR'ing any input file with ocrmypdf

### ISSUE THREAD

**Issue by tedtms** [jbarlow83/OCRmyPDF#784]
**Describe the bug**
unpaper dies via SIGKILL: 9 while OCR'ing any input file with ocrmypdf

**To Reproduce**
Run ocrmypdf against any input file.

**Expected behavior**
ocrmypdf should deposit the output file appropriately.

**Logs**
[ocrmypdf.log](https://github.com/jbarlow83/OCRmyPDF/files/6527125/ocrmypdf.log)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.8.5
 - OCRmyPDF version: 12.0.1

**Installation**
pip

**Additional context**
I encountered this error while using [paperless-ng](https://github.com/jonaswinkler/paperless-ng/issues/1045) and was directed to use ocrmypdf standalone to try to reproduce the issue. To do so, I've attempted to run the same arguments that paperless-ng invokes while processing a document:

` ocrmypdf -v -d -r -c --output-type pdfa -j 2 -l eng --sidecar /tmp/paperless-xzsn3/sidecar.txt brother_05222021_152203_001128.pdf /tmp/paperless/paperless-xzsn3_6x/archive.pdf 2>&1 | tee ~/ocrmypdf.log`

I understand that unpaper is what experiences the error. I was directed here by the paperless-ng developer, but if this is actually an unpaper issue please let me know and I will post an issue there instead.

**Comment by jbarlow83** [comment]
If you `ocrmypdf -k ...` all of the temporary files will be saved, so you can get the image that was sent to unpaper.

The command was: `['unpaper', '-v', '--dpi', '599.682645', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmp8a8nmywc/input.pnm', '/tmp/tmp8a8nmywc/output.ppm']`

Unpaper's output was:
```
[ppm_pipe @ 0x5583d136b9c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
[image2 @ 0x5583d1371040] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```
Unless there's something wrong with the image, this is unpaper's issue. Looks as if unpaper is misusing a library it calls.
