### ISSUE TITLE
InputFileError

### ISSUE THREAD

**Issue by alexreg** [jbarlow83/OCRmyPDF#786]
**Describe the bug**
I get an `InputFileError` when running on a certain PDF.

```
  DEBUG ocrmypdf - ocrmypdf 12.0.2
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = List of available languages (3):
eng
osd
snum

  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 4.1.1
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 9.54.0
  DEBUG ocrmypdf.helpers - os.symlink(input.pdf, /var/folders/cp/qx0df5kx497_rygnyvv9xl8m0000gn/T/ocrmypdf.io.myzjwlj3/origin)
  DEBUG ocrmypdf.helpers - os.symlink(/var/folders/cp/qx0df5kx497_rygnyvv9xl8m0000gn/T/ocrmypdf.io.myzjwlj3/origin, /var/folders/cp/qx0df5kx497_rygnyvv9xl8m0000gn/T/ocrmypdf.io.myzjwlj3/origin.pdf)
  ERROR ocrmypdf._sync - InputFileError
```

**To Reproduce**

```bash
ocrmypdf  -v2 -l eng input.pdf output.pdf
```

**Example file**
https://mega.nz/file/rMUCzRrS#LCTt8QCPseC7gSmhJT17aMZMbgBdi2JequMRRKZ4NMI (This file opens fine in Preview.app, for the record)

**Expected behavior**
It should load and process the input PDF.

**System**
 - OS: macOS 11.3.1
 - OCRmyPDF Version: 12.0.2
 - How did you install ocrmypdf? Homebrew

**Comment by jbarlow83** [comment]
The file is corrupted to the point that it cannot be recovered without "forensic" tools and knowledge of the PDF format to partially reconstruct it. I tried to recover it with pikepdf, qpdf, and Ghostscript. A PDF viewer reported that it contains only empty pages.

**Comment by alexreg** [comment]
@jbarlow83 How is it corrupted? It opens fine with a PDF viewer and I can view it. It was downloaded from archive.org.

**Comment by alexreg** [comment]
@jbarlow83 My apologies; it looks like Preview.app itself might have accidentally corrupted it! I've got it working now.
