### ISSUE TITLE
feature Request  --output-type none

### ISSUE THREAD

**Issue by AntonioSoler** [jbarlow83/OCRmyPDF#787]
I'm creating a custom transformer for Alfresco 6.2 that is going to index the content of the pdfs uploaded to the system. 
I just need the sidecar file not the pdf file to feed my Solr instance with the output, but the system is wasting time generating the converted version of the pdf file (that is going to be deleted anyway).

So I manually have hacked the exec/ghostscript.py to disable execution of the output file generation.

I would like to have the option to select the the -output-type to none to save CPU time (another option could be --output-type txt that would be effectively the same as to use the --sidecar but specifying the target file)

**Comment by jbarlow83** [comment]
For the moment you could use `--optimize 0 --pdf-renderer hocr --output-type pdf`. While this will produce an unnecessary output PDF, it is faster than Ghostscript.

In the future I will refactor the existing PDF renderers into plugins so that they can be replaced (including with a null plugin).
