### ISSUE TITLE
Docker arm64 build is broken

### ISSUE THREAD

**Issue by unze** [jbarlow83/OCRmyPDF#808]
Since docker hub stopped free autobuild (see https://www.docker.com/blog/changes-to-docker-hub-autobuilds/), is there a plan to publish builds to docker hub again?

**Comment by jbarlow83** [comment]
We don't use autobuilds - we build with Github Actions and push. 

The Docker build is currently broken for arm64 which is breaking all others versions. I haven't got around to fixing it.

**Comment by jbarlow83** [comment]
Fixed now.
