### ISSUE TITLE
Document is not fully detected with OCR

### ISSUE THREAD

**Issue by njeri123** [jbarlow83/OCRmyPDF#811]
I use the Docker variant "OCRmyPDF" which runs on DSM7.
I have already tried different parameters and always get the same result.
Towards the end of the document words are not recognized and at the very end also the last line is not recognized.
The document is in German language.
The document to be scanned is in the attachment, as well as the scanned document.

I hope you can help me.

[2021-07-25__MobText 2010-09-01-005.pdf](https://github.com/jbarlow83/OCRmyPDF/files/6874094/2021-07-25__Mo
[To_be_scanned_MobText 2010-09-01-005.pdf](https://github.com/jbarlow83/OCRmyPDF/files/6874095/To_be_scanned_MobText.2010-09-01-005.pdf)
![4QUC1dssVN](https://user-images.githubusercontent.com/18693679/126904176-2aba9c3f-e161-415e-9a68-97c04ff8f441.png)
bText.2010-09-01-005.pdf)

**Comment by jbarlow83** [comment]
This is likely a result of the poor exposure/contrast ratio of the image.
Try `ocrmypdf --threshold...` and/or `--remove-background` which may help. No guarantees it with work though. The ideal solution is to redo the image. For that I'm going to close the issue at this point.
