### ISSUE TITLE
[--pdf_renderer=hocr] Can't select text separately on one column if page has 2 text columns

### ISSUE THREAD

**Issue by Mark-Joy** [jbarlow83/OCRmyPDF#813]
**Describe the issue**
When using `--pdf-renderer=hocr` to generate pdf, I couldn't select text separately on a column. Text on 2 columns acts like they are only one column. Is it a bug or by design?
I can do that with `sandwich` mode though.

I use Moon reader app for reading and annotating on my phone. What I realized is that pdf generated with `sandwich` option has more gaps between words than `hocr`. So I prefer `hocr` to `sandwich` if It let me select text seperately on 1 column.
I did a quick comparation with pdf generated by another tool. ocrmypdf gives smaller file but has more gaps. The other file has almost no gap when selecting text.

**To Reproduce**

```bash
time ocrmypdf --lang=eng --redo-ocr in.pdf out_hocr.pdf --tesseract-oem=0 --output-type=pdf --pdf-renderer=hocr
time ocrmypdf --lang=eng --redo-ocr in.pdf out_sandwich.pdf --tesseract-oem=0 --output-type=pdf --pdf-renderer=sandwich

```

**Example file**
[ocrmypdf.zip](https://github.com/jbarlow83/OCRmyPDF/files/6911367/ocrmypdf.zip)

**Expected behavior**
`hocr` option shall let me select text separately on one column if page has 2 text columns

**Screenshots**

https://user-images.githubusercontent.com/22109528/127744211-6a3f42a1-7204-4668-b2c8-6a3f8b72fc77.mp4

**System**
 - OS: Android Pie
 - OCRmyPDF Version: ``12.3.0`` 
 - Install ocrmypdf using system package manager `pip` on Termux

**Comment by jbarlow83** [comment]
Thank you very much for providing all of the information on the issue.

It looks to me like the issue is that hocr does not always the present OCR text in "reading order" but reorders it, and some PDF viewers (but not all) take their cues about columns from the order in which text elements are presented. I will need to address this.

In the meantime, you might that other PDF viewers work better and avoid the problem.

**Comment by Mark-Joy** [comment]
Thank you!!
Version 12.3.1 completely fixed it. Wonderful!!

**Comment by Mark-Joy** [comment]
@jbarlow83 any chance that the gaps between words can also be improved in a not so far future? :)

**Comment by jbarlow83** [comment]
The word gaps in sandwich? That's Tesseract's problem, although I have some contributed some changes on that end. It's proven very difficult to improve the display of OCR text without breaking second tier PDF viewers, using the glyphless font approach they use. You can usually improve something in most places, only to find out "now right to left text is broken on macOS Preview" or "copy paste text gotallsquishedtogetheragain". 

PDF viewers are like web browsers in the IE6 era. Many do find with simple things, but they're all over the map in terms of standards compliance.

hocr uses hidden Helvetica and horizontal scaling so it looks more like ordinary text to PDF viewers.

**Comment by Mark-Joy** [comment]
I like hocr a lot more than sandwich because it gives a more natural look. I understand that it's not in priority since it's already cover more than 90% gaps. Hopefully, It will cover 99% in some far future :)
