### ISSUE TITLE
--force-ocr refuses to apply OCR on pages that contain no images

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#82]
@eMPee584 reported an unanticipated use case in #78: using OCR to fix a PDF with text information but an invalid toUnicode table or more generally, invalid font data of some kind. Another possible use case is recovering text from documents where text had been rendered to curves e.g. a PDF generated by Ghostscript with `-dNoOutputFonts` which does exactly this.

**Comment by jbarlow83** [comment]
Fixed in 4.2

**Comment by eMPee584** [comment]
Really great! Now still, regarding the size issue (https://github.com/jbarlow83/OCRmyPDF/issues/79#issuecomment-233484856) no easy way to keep the original glyph layer visible, but not searchable? 
What about.. converting glyphs to curves..? [testing]
oh damn. Sample page with glyphs: 28.4K
converted to curves either with inkscape or gs: ~617K
So no, rendering the glyphs into vector curves seems not be a viable option.

**Comment by jbarlow83** [comment]
Generally you don't want to convert glyphs to curves. The feature in PDF exists to work around buggy printer drivers that don't understand newer font formats. It will definitely produce a larger file than a font because to my knowledge, the PDF will describe every individual stroke of every glyph. Output quality is also poorer than using the font because there is no hinting for small sizes.

I can't remember which file you sent in but recovering damaged is a pretty special case.

By default ocrmypdf selects the colorspace (mono/gray/RGB) needed to represent all objects in the PDF. If you happen to have a file that would look fine in monochrome, you could get a smaller file with a manual process such as:
* use Ghostscript to rasterize to monochrome PNG (see ocrmypdf/ghostscript.py for the arguments) assuming you don't need a wider colorspace
* use `img2pdf` to reconstruct the PDF
* use `ocrmypdf` to reconstruct the text layer

If you maximize compression and hassle, you could use [jbig2enc](https://github.com/agl/jbig2enc)  (note: patent-encumbered) along with its companion program `pdf.py` to create a JBIG2 encoded PDF, and then use `ocrmypdf --output-type pdf` to prevent ocrmypdf using Ghostscript which unfortunately downgrades JBIG2 to CCITT to avoid patent issues. Never use JBIG2 in [lossy mode](https://abbyy.technology/en:kb:tip:jbig2_compression_and_ocr). 

Acrobat can do JBIG2 encoding as well.
