### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by wpzdm** [jbarlow83/OCRmyPDF#820]
**Describe the bug**
`conda install ocrmypdf` cannot find package.

**Expected behavior**
But `conda install -c conda-forge ocrmypdf` is okay.
https://anaconda.org/conda-forge/ocrmypdf

**Comment by jbarlow83** [comment]
I believe this means that there is a community conda package of ocrmypdf in "conda-forge", but the maintainers have not adopted ocrmypdf as a standard package. I have no control over that process. If you have any concerns with the conda version of ocrmypdf, please report them at anaconda.org.

**Comment by wpzdm** [comment]
Thank you. 
I think it would be better to change the documentation to use `onda install -c conda-forge ocrmypdf`?
https://ocrmypdf.readthedocs.io/en/latest/installation.html
