### ISSUE TITLE
`--pdf-renderer hocr` not outputing text to pdf

### ISSUE THREAD

**Issue by jcuenod** [jbarlow83/OCRmyPDF#828]
**Describe the bug**
Running ocrmypdf with `--pdf-renderer hocr` is not producing a pdf with selectable text. I haven't checked the pdf for whether the text is there and somehow hidden but it's a regression on the latest version I installed from AUR.

**To Reproduce**
ocrmypdf --pdf-renderer hocr -d some.pdf output.pdf

**Expected behavior**
When running the default renderer, the text is there. I've been using hocr because of #450 but this no longer appears to be working.

**System (please complete the following information):**
 - OS: Arch
 - Python version: 3.9.6
 - OCRmyPDF version: 12.4.0-1

**Installation**
AUR (https://aur.archlinux.org/packages/ocrmypdf/)

**Comment by jcuenod** [comment]
Sorry, I realise that you have probably got a lot to do on this project but I thought that I followed the template for this bug report and it's not clear to me what I can do to better help the project if I encounter issues in future.

**Comment by jbarlow83** [comment]
Sorry about that, I didn't mean to close this issue. I hadn't seen it at all, in fact. I closed several yesterday with a group selection, so I must have accidentally closed this one.

You could run with `-k` mode and check the temporary files to see if Tesseract actually found text.
https://ocrmypdf.readthedocs.io/en/latest/advanced.html?highlight=temporary%20files#debugging-the-intermediate-files

Sharing the file may be necessary. If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by jbarlow83** [comment]
Nevermind the comments above. I found the issue & will have a fix out shortly.

**Comment by jcuenod** [comment]
Thanks
