### ISSUE TITLE
Documentation: confusing Introduction

### ISSUE THREAD

**Issue by Chealer** [jbarlow83/OCRmyPDF#832]
**Describe the bug**
[The _Introduction_ section](https://ocrmypdf.readthedocs.io/en/latest/introduction.html#introduction) reads:

> OCRmyPDF is a Python 3 application and library that adds OCR layers to PDFs.

It may not be clear what an "OCR layer" is. I would rather recommend:
> OCRmyPDF is an application and library that adds text layers to PDF files which contain images representing text (typically, scanned documents). It is written in the Python programming language and uses OCR to guess what text is represented by images.

**To Reproduce**
This does not report a behavioral bug.

**Expected behavior**
This does not report a behavioral bug.

**System (please complete the following information):**
 - OS: N/A
 - Python version: N/A
 - OCRmyPDF version: 12.4.0

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's package manager, or using pip? N/A

**Comment by jbarlow83** [comment]
Thanks for your feedback on the documentation.

Could you please open any further documentation changes as pull requests - it would be faster for both of us, since it shows the proposed change in context, making it easier to review and accept.

**Comment by Chealer** [comment]
Greetings @jbarlow83
My pleasure and honor!

I hope I understand your question correctly, but assuming you are referring to merge requests, I am sorry but we are currently only evaluating OCRmyPDF. We are not even using it, and are even further from having our own version (frankly, I hope we don't need that).

**Comment by jbarlow83** [comment]
Rest assured that making a fork is not any sort of commitment to ocrmypdf - I'm just asking you to use a workflow that will be easier for both of us.

**Comment by Chealer** [comment]
Thanks @jbarlow83 I understand that. What I meant is that our organization has no fork of OCRmyPDF which could be merged. In fact, we don't even have any copy of either the executable or the code yet!
But I agree that this workflow is inefficient for both of us; in fact, I did refrain from reporting quite a few issues due to the overhead's cost :-(

Thank you very much for solving this issue and others
