### ISSUE TITLE
[Docs] Does --optimize 3 force --jbig2-lossy?

### ISSUE THREAD

**Issue by homocomputeris** [jbarlow83/OCRmyPDF#834]
**Describe the bug**
`--help` states:

>   `-O {0,1,2,3}, --optimize {0,1,2,3}`
>                         Control how PDF is optimized after processing:0 - do not optimize; 1 - do
>                         safe, lossless optimizations (default); 2 - do some lossy optimizations; 3
>                         - do aggressive lossy optimizations (**including lossy JBIG2**)

The docs state:

> To turn on JBIG2 lossy mode, **add** the argument `--jbig2-lossy`. `--optimize {1,2,3}` are necessary for the argument to take effect also required.

**The question**
Which version is correct? Does `-O3` is sufficient to enable `--jbig2-lossy`? 

**System (please complete the following information):**
 - OS: Linux
 - Python version:
 - OCRmyPDF version: 12.4.0

**Comment by jbarlow83** [comment]
Thanks for pointing out this discrepancy. I'll update the text to clarify.

The current behavior is that lossy JBIG2 is attempted when `--jbig2-lossy` is explicitly given and optimize is >= 1. 
I suppose it's possible someone might want lossy JBIG2 but JPEGs not transcoding, so `--optimize 1 --jbig2-lossy` is a valid combination.

**Comment by homocomputeris** [comment]
To sum up, just `-O3` is safe in the sense it won't produce JBIG2 lossy artifacts. Right?

**Comment by jbarlow83** [comment]
Correct, you have to explicitly opt in to `--jbig2-lossy`.

**Comment by homocomputeris** [comment]
I feel there is no need for a separate issue for this small matter:

There is a phrase is the docs:
> Enables **lossless** optimizations, such as **transcoding** images to more efficient formats.

Well, as far as I understand converting TIFFs to JPEGs is an optimization but lossy. So the wording is a bit confusing.
Probably, it is the way to do it, but I feel the docs should be more precise in this regard.

**Comment by jbarlow83** [comment]
@homocomputeris This is a good suggestion. I added a few clarifying remarks.
