### ISSUE TITLE
Are special characters in file names supported (precisely umlauts)?

### ISSUE THREAD

**Issue by leschekfm** [jbarlow83/OCRmyPDF#835]
Thanks for your work on OCRmyPDF. This is rather a question than a bug report, for me to determine where i should debug, as i've got a more or less special setup.

**Describe the bug**
What's the problem?

Trying to process a file containing a umlaut (ö) throws an exception and therefore stops processing of any other files.
After replacing the umlaut with standard characters and restarting the container, files are processed again.

**To Reproduce**
Steps to reproduce the behavior.

Use the file watcher feature and copy a file with a name containing umlauts into the input folder

**Expected behavior**
What did you expected to happen?

All files would be processed successfully and/or erroring files would be skipped

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 11 + docker desktop + wsl2
 - Python version:
 - OCRmyPDF version: Docker image with Id e47eedd4bee7

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?

It's installed on windows 11 as a docker image in docker desktop using wsl2. The files are stored on a synology diskstation within a SMB share. The share is mounted as volume then inside the docker container.
Please see the following docker-compose file.

```
---
version: "3.5"
services:
  ocrmypdf:
    restart: always
    container_name: ocrmypdf
    image: jbarlow83/ocrmypdf
    volumes:
      - "ocr-input:/input"
      - "ocr-output:/output"
    environment:
      #- OCR_OUTPUT_DIRECTORY_YEAR_MONTH=1
      - OCR_ON_SUCCESS_DELETE=1
      - OCR_DESKEW=1
      - OCR_LOGLEVEL=DEBUG
      - 'OCR_JSON_SETTINGS={"force-ocr": true,"language":"deu+eng"}'
      - OCR_USE_POLLING=1
      - OCR_POLL_NEW_FILE_SECONDS=10
    user: "1000:1000"
    entrypoint: python3
    command: watcher.py
volumes: 
  ocr-input:
    driver: local
    driver_opts: 
      type: "cifs"
      o: "addr=diskstation,username=XXX,password=YYY,file_mode=0777,dir_mode=0777"
      device: "//diskstation/ocr/input"
  ocr-output:
    driver: local
    driver_opts: 
      type: "cifs"
      o: "addr=diskstation,username=QQQ,password=RRR,file_mode=0777,dir_mode=0777"
      device: "//diskstation/ocr/output"
```

**Additional context**

Log output of the docker container. Three files have been processed successfully previously

```
--------------------

New file: /input/2020-02-14-gesundheit-extra-2019-ausgesch\udcf6pft.pdf. Waiting until fully loaded...

Exception in thread Thread-1:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/api.py", line 199, in run

    self.dispatch_events(self.event_queue, self.timeout)

  File "/usr/local/lib/python3.9/dist-packages/watchdog/observers/api.py", line 372, in dispatch_events

    handler.dispatch(event)

  File "/usr/local/lib/python3.9/dist-packages/watchdog/events.py", line 403, in dispatch

    super().dispatch(event)

  File "/usr/local/lib/python3.9/dist-packages/watchdog/events.py", line 271, in dispatch

    self.on_any_event(event)

  File "/app/watcher.py", line 121, in on_any_event

    execute_ocrmypdf(event.src_path)

  File "/app/watcher.py", line 101, in execute_ocrmypdf

    if not wait_for_file_ready(file_path):

  File "/app/watcher.py", line 82, in wait_for_file_ready

    pdf = pikepdf.open(file_path)

  File "/usr/local/lib/python3.9/dist-packages/pikepdf/_methods.py", line 908, in open

    pdf = Pdf._open(

UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 48: surrogates not allowed
```

**Comment by jbarlow83** [comment]
Special characters are fully supported by ocrmypdf. I suspect that the encoding is being mangled in the somewhere in the Windows-Docker-WSL-SMB stack.

\udcf6 or U+DCF6 is not an umlaut, it is a Unicode surrogate character, usually used to transmit UCS-4 characters inside UTF-16. They are not permitted in normal Unicode strings. ŭ is U+00FC, or the equivalently the sequence U+0308 U+0075.

(Note that you may have inadvertently revealed a username and password in your config file. I removed it.)
