### ISSUE TITLE
[docs] API reference does not show up

### ISSUE THREAD

**Issue by mara004** [jbarlow83/OCRmyPDF#837]
[The API page](https://ocrmypdf.readthedocs.io/en/latest/api.html) section "Reference" is empty, although [according to the source](https://github.com/jbarlow83/OCRmyPDF/blob/master/docs/api.rst#reference) it should show API documentation for `ocrmypdf.ocr` and other methods/classes, which is quite strange because the syntax appears to be correct.

**Comment by mara004** [comment]
I just built the documentation locally and there it shows up correctly, so probably the issue is caused by readthedocs.io?

**Comment by macdeport** [comment]
@mara004 thank you for drawing my attention to this Python API and @jbarlow83 for designing it.
I used to use only the command line...

**Comment by jbarlow83** [comment]
Fixed the issue - yes it appeared to be related to RTD config - thank you for reporting it

**Comment by mara004** [comment]
Thanks!

**Comment by mara004** [comment]
Now the API documentation shows up currectly, but for some reason I am unable to link to :meth:`ocrmypdf.ocr` with intersphinx.
I added ocrmypdf to my `intersphinx_mapping` in `conf.py` like this:
```python3
'ocrmypdf': ('https://ocrmypdf.readthedocs.io/en/latest/', None),
```
Am I doing something wrong or is this an issue on the side of ocrmypdf/readthedocs?
