### ISSUE TITLE
Was the commit v12.6.0 points to changed?

### ISSUE THREAD

**Issue by dotlambda** [jbarlow83/OCRmyPDF#841]
That would a big no go and completely ruins trust in this piece of software.

**Comment by jbarlow83** [comment]
No, you can check the github actions logs if you want to see what's been pushed lately.

**Comment by jbarlow83** [comment]
@dotlambda That's twice now you've accused me personally of dishonesty, and without evidence presenting. You could, for example, assume good faith, as most of us in open source do. Upstream maintainers do mistakes sometimes, as do downstream packagers. I urge you to amuse good faith in the future, and this is a warning that I will not tolerate further accusations from you personally.

@fabaff @ryantm I am happy to work with the Nix project to resolve this issue. I do a two phase build. A release candidate gets pushed, usually with the *intended* version in the subject line but without a tag. Only if all tests pass do I push the tag on the same commit. If you happened to clone in between those steps, you would get a slightly different build of the same commit but a different version number. (It would be lovely if Git had the concept of a provisional tag to avoid this overhead but it does not.) I've used this process for years without it being an issue for anyone.

**Comment by dotlambda** [comment]
> That's twice now you've accused me personally of dishonesty, and without evidence presenting. You could, for example, assume good faith, as most of us in open source do.

@jbarlow83 I'm sorry for not assuming good faith in my first comment. However, you misinterpreted my second comment or I just didn't formulate it well. I did look at the GitHub Actions log and can confirm that it does not look like you changed the tag. I just wanted to express that I have no rational explanation for this mystery.

**Comment by dotlambda** [comment]
> A release candidate gets pushed, usually with the _intended_ version in the subject line but without a tag. Only if all tests pass do I push the tag on the same commit.

I can't find any indication of a force push in https://github.com/jbarlow83/OCRmyPDF/actions/workflows/build.yml, so I assume this time all tests passed and you just added a tag to that commit?



> If you happened to clone in between those steps, you would get a slightly different build of the same commit but a different version number.

We only ever fetched a tarbal for the tag `v12.6.0`, so that's not an issue. Since tarballs downloaded from GitHub don't include the `.git` directory, the build won't know from which commit or tag it's being run anyway.

**Comment by ryantm** [comment]
@jbarlow83 Sorry about the harsh words. When this kind of thing happens, I usually assume there is something wrong with GitHub, or my bot. Anyway, hopefully we can work together to get to the bottom of it.

@dotlambda I looked around on my server for a while, but wasn't able to find it. I'm not sure what nix calls the tarball file.

**Comment by dotlambda** [comment]
> @jbarlow83 Sorry about the harsh words. When this kind of thing happens, I usually assume there is something wrong with GitHub, or my bot. Anyway, hopefully we can work together to get to the bottom of it.

I had bad experiences with multiple other upstream projects doing this in the past. Sorry I let these affect my behaviour towards you @jbarlow83.

> @dotlambda I looked around on my server for a while, but wasn't able to find it. I'm not sure what nix calls the tarball file.

It should be `/nix/store/w38w56px10rvgvcxn5s1a7k0w0jkncy0-source`.

**Comment by ryantm** [comment]
@dotlambda Sorry, I do not see either of those paths on my system. Maybe it was garbage collected, but I also don't see it in the garbage collector logs.

Perhaps the [du listing](https://gist.github.com/r-ryantm/f73bd6b1d1e781b40c243214ae916ee5) of the result could provide a hint.

**Comment by jbarlow83** [comment]
I'm glad we've resolved our miscommunications and we're on the same page now. 

Would it be alright if this discussion continued on the nixpkgs issue linked above, unless there's some specific action someone wants me to take?

**Comment by ryantm** [comment]
https://github.com/NixOS/nixpkgs/pull/140378#issuecomment-936383685

Tracked down the problem to the .git_archival file being non-deterministic in that it gets affected by if the master branch is pointed at the same place as the tag or not. 

https://github.com/jbarlow83/OCRmyPDF/blob/7bdd1828a986a74b1784e4a617b88517d4998b3a/.gitattributes#L14

@jbarlow83 What purpose does the .git_archival.txt file serve? Can it be removed?

**Comment by dotlambda** [comment]
@jbarlow83 Thank you very much for helping us solve this mystery!
In case you're interested, what we do now is fetch the tarball, reomove `.git_archival.txt`, and then compute the hash. Setuptools-scm still works because we set the environment variable `SETUPTOOLS_SCM_PRETEND_VERSION`.
