### ISSUE TITLE
Invalid addopts line in pyproject.toml when using py.test-3(1)

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#847]
Hello,

I'm just updating ocrmypdf in Debian to version 12.7.0.  We execute py.test-3(1) with no arguments to run the test suite against the installed version of ocrmypdf.  I see this error:

    autopkgtest [16:24:37]: test test-suite: [-----------------------
    ERROR: usage: py.test-3 [options] [file_or_dir] [file_or_dir] [...]
    py.test-3: error: unrecognized arguments: -n
      inifile: /tmp/autopkgtest.ZVaTpP/build.uGG/src/pyproject.toml
      rootdir: /tmp/autopkgtest.ZVaTpP/build.uGG/src
    
    autopkgtest [16:24:38]: test test-suite: -----------------------]
    autopkgtest [16:24:38]: test test-suite:  - - - - - - - - - - results - - - - - - - - - -
    test-suite           FAIL non-zero exit status 4
    autopkgtest [16:24:38]: test test-suite:  - - - - - - - - - - stderr - - - - - - - - - -
    ERROR: usage: py.test-3 [options] [file_or_dir] [file_or_dir] [...]
    py.test-3: error: unrecognized arguments: -n
      inifile: /tmp/autopkgtest.ZVaTpP/build.uGG/src/pyproject.toml
      rootdir: /tmp/autopkgtest.ZVaTpP/build.uGG/src
    
    autopkgtest [16:24:38]: @@@@@@@@@@@@@@@@@@@@ summary
    test-suite           FAIL non-zero exit status 4

I can resolve this by deleting the line `addopts = "-n auto"` line from pyproject.toml, but I'm not sure whether that is the right solution.

Thanks.

**Comment by jbarlow83** [comment]
If you test with pytest-xdist (which would  be installed by `pip install ocrmypdf[test]`) `-n auto` makes testing much faster on multicore machines.

I think deleting that line is a good solution for Debian - parallel testing can introduce nondeterminism and test workers usually have limited CPU cores so there probably isn't much benefit.
