### ISSUE TITLE
Installation on nix for macOS

### ISSUE THREAD

**Issue by xave** [jbarlow83/OCRmyPDF#852]
**Is your feature request related to a problem? Please describe.**
There are many ways to install this. It would be nice for nix to be included as well.

**Describe the solution you'd like**
`nix-env -i ocrmypdf` doesn't work without setting an unsupported flag in nix.

**Additional context**
Thanks!

**Comment by jbarlow83** [comment]
Feel free to ask the nixOS maintainers to add this. I don't create any packaging and mostly wouldn't know where to start.

Ocrmypdf is currently available in Homebrew if that helps.
