### ISSUE TITLE
Invalid version number

### ISSUE THREAD

**Issue by vihnng** [jbarlow83/OCRmyPDF#853]
I can run "ocrmypdf --help"
After that I run command "ocrmypdf mypdf.pdf output.pdf"
and it returned me the error "invalid version number '5.0.0-rc1.20211030'

What did you expected to happen?
Add an OCR layer and convert to PDF/A

**System (please complete the following information):**
 - OS: Windows
 - Python version: Python 3.8.9
 - OCRmyPDF version: 12.7.1

**Installation**
How did you install OCRmyPDF? 
I downloaded it from github ( I did install all requirement )

**Comment by jbarlow83** [comment]
Yet another nonstandard tesseract version number....
Fixed for 12.7.2
