### ISSUE TITLE
[feature request] quality callback or filter

### ISSUE THREAD

**Issue by arc12** [jbarlow83/OCRmyPDF#859]
**My Problem**
I'm OCRing pre-existing PDFs created from scanning mixed typescript and diagrams/maps as part of a small project to build a searchable digital archive of mining history materials. Usually the diagram/map is on a page by itself (these are sometimes photocopies of originals made in the 1980's). OCR produces a page of crap, usually punctuation, whereas a smarter approach would be to declare "no text" and cut the crap!

**Describe the solution you'd like**
It occurs to me that a simple approach would be to apply a per page threshold on punctuation vs alphabetic character ratio, or something like that. Alternatively to supply the page content to a callback for a binary good/bad return value. OCRmyPDF would then either apply or not apply the text accordingly.

**Describe alternatives you've considered**
Post-processing the sidecar with a regex would be feasible but still leaves the pdf.

**Comment by jbarlow83** [comment]
I should be able to add a hook to filter OCR output - I can see that being interesting. I've long wished for Tesseract to improve in this area.

But before doing custom work you may want to try tuning Tesseract's parameters to more strongly penalize words not found its frequent word dictionary and general word dictionary respectively, e.g., make a plain text file containing
```
language_model_penalty_non_freq_dict_word 1
language_model_penalty_non_dict_word 1
```
save as a plain text file named e.g. `strict_dict` and run as `ocrmypdf --tesseract-config strict_dict ...`

**Comment by arc12** [comment]
Thanks for the tip concerning Tesseract's dictionary. I'll give it a go, although many important words are proper nouns like "Pindale", "Wormhill".

**Comment by jbarlow83** [comment]
You can also supply a word list with `--user-words` if you have Tesseract 4.1 or newer.
