### ISSUE TITLE
Ghostscript unrecoverable error on fresh install

### ISSUE THREAD

**Issue by supergrobi** [jbarlow83/OCRmyPDF#86]
Hello,
I have installed OCRmyPDF with pip3 on a fresh Fedora 24 installation. The script quits with an error message (see attached file error.txt).
I have used former versions of OCRmyPDF without problems. That is why I do not know where this error comes from.
see installed versions in attached file versions.txt
[versions.txt](https://github.com/jbarlow83/OCRmyPDF/files/433525/versions.txt)
[error.txt](https://github.com/jbarlow83/OCRmyPDF/files/433524/error.txt)

**Comment by jbarlow83** [comment]
For some reason ocrmypdf thinks the file has absurdly high resolution
(>100,000 dots/inch) so it attempts to create a massive image and hits a
memory limit..

Your file is pretty unusual (multiple images and multiple resolutions on
the same page). Could you send it to me? Dropbox is fine or attach here if
small.

You can use pip to install older versions if you want a quick workaround.

**Comment by supergrobi** [comment]
Thanks for your fast reply.
I attached a different file with the same error message. I created all these pdf files using a HP Officejet 8620 scanner.
I was not able to upload the pdf file, so I had to create a zip file.

[error.txt](https://github.com/jbarlow83/OCRmyPDF/files/433591/error.txt)
[test.zip](https://github.com/jbarlow83/OCRmyPDF/files/433593/test.zip)

**Comment by jbarlow83** [comment]
Fix is posted. The PDF contained a "stencil mask" and apparently those
follow their own set of rules rather unlike other images.

You should be able to install with

pip3 install --upgrade git+https://github.com/jbarlow83/OCRmyPDF.git


Would you mind scanning an image you are comfortable releasing to the
public domain (not a receipt with personal information, nor copyrighted)
created with your printer? I'd like to add to a test case for this, but I
don't have software that creates stencil masks.

**Comment by supergrobi** [comment]
The new version is working perfectly.
Sure I will provide a scan. I will come back to you on this topic during the weekend.

**Comment by supergrobi** [comment]
Please find attached a scan file that you may use.
By the way: The software is really good. Thanks for everything.

[scan0639.zip](https://github.com/jbarlow83/OCRmyPDF/files/439114/scan0639.zip)

**Comment by jbarlow83** [comment]
@supergrobi Thank you! I really appreciate it.
