### ISSUE TITLE
Question: Docker using watcher.py with multiple commands

### ISSUE THREAD

**Issue by Maximus48p** [jbarlow83/OCRmyPDF#862]
Very useful tool! Tnx!

I'm using Docker (QNap) and trying to use the watcher.py functionality together with multiple commands.
Code says more then text....;

**Docker-compose**
```
  ocrmypdf:
    restart: always
    container_name: Ocrmypdf
    image: jbarlow83/ocrmypdf:latest
    volumes:
      - /share/scanned_originals/OCR-pickup:/input
      - /share/scanned_originals/OCR-done:/output
      - /share/Container-volumes/ocrmypdf/tessdata:/usr/local/share/tessdata
    environment:
      - TZ=Europe/Amsterdam
      - OCR_ON_SUCCESS_DELETE=1
      - PYTHONUNBUFFERED=1
      - OCR_JSON_SETTINGS='{"rotate_pages": true}'
#      - TESSDATA_PREFIX=/usr/local/share/tessdata # i can't get this to work
    entrypoint: python3
    command: >-
      watcher.py
      --clean
      --deskew
      --remove-background
      --redo-ocr
      --rotate-pages
      -l nld+eng
      --optimize 1
      -j 2
```

I can't get TESSDATA_PREFIX to work, so i copy (manually) the different language files to the folder _/usr/share/tesseract-ocr/4.00/tessdata_

So the question is mainly, how do i get the commands to work in combination with using 'watcher.py'.
Any help is much appreciated.

Thanks.

**Comment by jbarlow83** [comment]
You might need to add some escapes, maybe `\"` or something, or use one of the YAML syntaxes like `>-` as a workaround.
