### ISSUE TITLE
The top part of the first page isn't OCRed, everything else is.

### ISSUE THREAD

**Issue by DUOLabs333** [jbarlow83/OCRmyPDF#866]
**Describe the bug**
When OCRing a file, the top half of page 1 isn't ORCred, but everything else after it is

**To Reproduce**
What command line or API call were you trying to run?

`ocrmypdf -l eng  --jobs 4 --force-ocr --output-type pdf "~/The Norton Field Guide to Writing - Compiling a Portfolio.pdf" test.pdf`

Run with verbosity or higher `-v1` to see more detailed logging. This information may be helpful.

**Example file**
If your issue is a problem that affects only certain files, and we will require an input file (PDF or image) that demonstrates your issue.
[The Norton Field Guide to Writing - Compiling a Portfolio.pdf](https://github.com/jbarlow83/OCRmyPDF/files/7643690/The.Norton.Field.Guide.to.Writing.-.Compiling.a.Portfolio.pdf)

Please provide an input file with no personal or confidential information. At your option you may [GPG-encrypt the file](https://github.com/jbarlow83/OCRmyPDF/wiki) for OCRmyPDF's author only.

Links to files hosted elsewhere are perfectly acceptable. You could also look in ``tests/resources`` and see if any of those files reproduce your issue.

*(Issues without example files usually cannot be resolved. It's like reporting an issue against a web browser without providing a URL.)*

**Expected behavior**
Everything is OCRed (have selectable text)

**Screenshots**

**System**
 - OS: [e.g. Linux, Windows, macOS] Arch Linux
 - OCRmyPDF Version: ``ocrmypdf --version`` 12.7.2
 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image? pip

**Comment by jbarlow83** [comment]
Most likely the OCR engine was unable to find any text in the image due to it being warped. Wavy text baselines are tricky to OCR, such as a photo of a page that is not flat.

Consider using a tool line like ScanTailor to process your images.

**Comment by DUOLabs333** [comment]
Interestingly enough `--redo-ocr` helps a bit, but it then causes the text to mix together when copying.

**Comment by DUOLabs333** [comment]
Also, the rest of the page was similarly warped, yet it was OCRed just fine.

**Comment by jbarlow83** [comment]
The baseline for text that recognized is straighter than the text that did not recognize.
If you like you can convert PDF to image and try feeding the images to Tesseract - the issue is that the OCR engine cannot interpret images distorted in this way.
