### ISSUE TITLE
About the path of input and output file

### ISSUE THREAD

**Issue by vihnng** [jbarlow83/OCRmyPDF#867]
Hi, thank your for your work
I want to ask 
1. How can I choose the direction(or path) of the input file and the output file.
I searched a lot but can't find anything about that
All I can is put the input file inside the folder "OCRmyPDF-master" 

 - OS: Windows 10
 - Python version: 3.8
 - OCRmyPDF version: 13

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
I downloaded it from git, it works fine but I don't know how to set the direction for input.pdf and output.pdf (I can only put it  inside the folder "OCRmyPDF-master" and run command)

2.When I choosed to use 2 languages
For examples: 
ocrmypdf -l eng -l vie --force-ocr --sidecar output.txt input.pdf output.pdf
The program can only run 1 language and it show that 
"[tesseract] Error opening data file eng.traineddata"
How can I fix this problem?

Thank you

**Comment by vihnng** [comment]
Or when I used this command
ocrmypdf -l eng+vie --force-ocr --sidecar output.txt input.pdf output.pdf
It can only run "eng" and showed"
 [tesseract] Error opening data file vie.traineddata

**Comment by jbarlow83** [comment]
1. You should be able to write `ocrmypdf C:\Users\me\input.pdf C:\Users\you\output.pdf` if you are using the Windows command prompt.

2. This error message seems to say you have not installed some of the Tesseract language packs. See here:
https://ocrmypdf.readthedocs.io/en/latest/languages.html#windows-users

(I assume you're using Windows 10 not WSL2.)
