### ISSUE TITLE
Blank pages cause the process to crash due to tesseract

### ISSUE THREAD

**Issue by philayres** [jbarlow83/OCRmyPDF#868]
**Describe the bug**

The following is from a tesseract issue https://github.com/tesseract-ocr/tesseract/issues/3675 I have raised, which they may choose not to fix and may need to be recognised in ocrmypdf.

### Environment

```
ocrmypdf --version
13.1.0
```

```
tesseract 5.0.0
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 9d : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.1 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.5.2 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.0
```

This is running on a Centos 7 machine running a GNOME desktop.

```
Linux hostname 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

ocrmypdf / tessaract was installed with Anaconda yesterday.

### Current Behavior:

I have a simple document that has some mostly blank pages. I run the following and it crashes on those pages:

`ocrmypdf -v 1 --deskew the_scientific_method-print10.pdf the_scientific_method-printed-ocr.pdf`

Without --deskew, this runs through fine, but the tesseract command being run is different (it does something like this...)

I extracted the blank pages from the ocrmypdf run, to test the mostly blank image file in tesseract

```
tesseract -l eng --psm 2 '/tmp/ocrmypdf.io.4npvxhru/000002_rasterize.png' stdout
```

It immediately returns with return code 1

Doing the same with a similar image `000001_rasterize.png` returns

```
Orientation: 0
WritingDirection: 0
TextlineOrder: 2
Deskew angle: 0.0000
```

Return code is 0 as expected.

If I run ocrmypdf without --deskew a different tesseract command is run, which is successful.

```
tesseract -l eng -c 'textonly_pdf=1' '/tmp/ocrmypdf.io.4npvxhru/000002_rasterize.png' new-file pdf txt
```

This returns code 0 and a blank .txt file as expected.

---

The files are downloadable from Google Drive:

[000002_rasterize.png](https://drive.google.com/file/d/1yfzqNAAH3zaz2-1C-JUkX513EvU8l_VS/view?usp=sharing)

[000001_rasterize.png](https://drive.google.com/file/d/1fmUBt7a8wrlfzUsKbf2Fcgqu4SKQIjF4/view?usp=sharing)

[the_scientific_method-print10.pdf](https://drive.google.com/file/d/1DUhOgVaha29DERz2zgIFRhPfURnsxz8a/view?usp=sharing)

---

I know this sits between two projects, but currently ocrmypdf is unusable for documents that may have blank pages.

**Comment by stweil** [comment]
> currently ocrmypdf is unusable for documents that may have blank pages

... if `--deskew` is used.

**Comment by azogue** [comment]
Hi @jbarlow83 👋, 

It seems that tesseract also fails (https://github.com/tesseract-ocr/tesseract/issues/3675) with **_almost-blank_ pages**, so the change introduced in https://github.com/ocrmypdf/OCRmyPDF/commit/d48254d477c45402134dfa4683781739346bf336 is not sufficient to cover all scenarios 😓

```
    except CalledProcessError as e:
         tesseract_log_output(e.stdout)
         tesseract_log_output(e.stderr)
         if b'Empty page!!' in e.output or (
             e.output == b'' and e.returncode == 1
         ):  # Not enough info for a skew angle - Tess 4 and 5 return different errors
             return 0.0
```

I have PDFs including pages like the **attached one** which are failing the same way, **with `--deskew` option enabled**, when calling `tesseract --psm 2 ...`, but filling the output with some data (in the attached example: `e.output == b'Error in boxClipToRectangle: box outside rectangle\nError in pixScanForForeground: invalid box\n'`)

Modifying the quick exit condition to just `if b'Empty page!!' in e.output or e.returncode == 1:` has solved the problem for me 🥳, but I think it would be interesting to **re-open this issue**, or create a new one, or **make a quick PR** with the proposed change 🤷

### Example files

* 1-page PDF v1.3 failing when called with `--deskew` option

  [almost-blank-page-ocrmypdf-tesseract-error.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7958432/almost-blank-page-ocrmypdf-tesseract-error.pdf)

* PNG image passed to tesseract, failing with `tesseract --psm 2 almost-blank-page-ocrmypdf-tesseract-error-rasterize.png stdout`

  ![almost-blank-page-ocrmypdf-tesseract-error-rasterize.png](https://user-images.githubusercontent.com/9748301/151544004-eb1af263-3d56-4aa8-8b85-e73aef6e32d5.png)

* Produced log file:
  [almost-blank-page-ocrmypdf-tesseract-error-debug.log](https://github.com/ocrmypdf/OCRmyPDF/files/7958437/almost-blank-page-ocrmypdf-tesseract-error-debug.log)

-----------


BTW, **pretty awesome work! 🍻thank you so much for this library!** 🥇😜

**Comment by stumpylog** [comment]
This is still still an issue with `13.4.1`, using the above test file and tesseract 4.1.1

**Comment by deexpabada** [comment]
Hello @jbarlow83 ! Thanks for your work with this library. It's pretty impressive 👏 
Any chance that the proposed change above https://github.com/ocrmypdf/OCRmyPDF/issues/868#issuecomment-1024159469 can be made?
