### ISSUE TITLE
Please document stdin/stdout streaming

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#88]
The `--help` output doesn't say anything about the new stdin/stdout streaming.  It would be great if it explained it.  I currently use help2man to generate a manpage for ocrmypdf in Debian from this `--help` output.

**Comment by jbarlow83** [comment]
Done in 4.2.2 along with some other expansion to documentation. 

My mistake, I only did stdin streaming so far since I'm not 100% sure I don't have some error path that prints to stdout.

**Comment by spwhitton** [comment]
Thanks: uploaded to Debian.  The new documentation is a welcome improvement.
