### ISSUE TITLE
Errors with with: bad operand type for unary -: 'IndirectObject' when trying to modify Rotation

### ISSUE THREAD

**Issue by lowesjam** [jbarlow83/OCRmyPDF#89]
When I run ocrmypdf on a simple 1-page text file, it errors with:

Task enters queue = 'ocrmypdf.main.add_text_layer' 
  DEBUG - 
    
    
    
Original exception:

    Exception #1
      'builtins.TypeError(bad operand type for unary -: 'IndirectObject')' raised in ...
       Task = def ocrmypdf.main.add_text_layer(...):
       Job  = [[.../com.github.ocrmypdf.nlxih0sf/000001.hocr.pdf, .../com.github.ocrmypdf.nlxih0sf/000001.image-layer.pdf] -> .../com.github.ocrmypdf.nlxih0sf/000001.rendered.pdf, <ocrmypdf.main.WrappedLogger>, [{'height_inches': Decimal('11.6806'), 'width_inches': Decimal('8.26389'), 'height_pixels': 3507, 'images': [{'dpi_w': Decimal('300.10084033613446763411047868430614471435546875'), 'dpi_h': Decimal('300.24256837098693040388752706348896026611328125'), 'name': '/Im0', 'comp': 1, 'bpc': 1, 'color': 'gray', 'height': 3507, 'enc': 'ccitt', 'width': 2480, 'dpi': Decimal('300.172')}], 'pageno': 0, 'has_text': False, 'width_pixels': 2480, 'xres': Decimal('300.10084033613446763411047868430614471435546875'), 'yres': Decimal('300.24256837098693040388752706348896026611328125')}], <unlocked _thread.lock>]
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/usr/lib/python3/dist-packages/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/usr/lib/python3/dist-packages/ocrmypdf/main.py", line 983, in add_text_layer
        rotation = -rotation % 360
    TypeError: bad operand type for unary -: 'IndirectObject'

This seems to be because the PyPDF2 lib returns an IndirectObject rather than a string value for the /Rotation object. 

I worked around this by modifying the main.py file to use a getObject() call on the rotation var before modifying its value.

    # TODO tweak to fix problem with IndirectObject resulotion
    log.debug("Rotation is %s" % (rotation))
    rotation = rotation.getObject()
    log.debug("Rotation is now: %s" % (rotation))

Not sure that this is the best way - can it sometimes be one and sometimes the other? - but might point you in the right direction.

File used for this (created by Epson multifunction device):

[Epson_31082016150347.pdf](https://github.com/jbarlow83/OCRmyPDF/files/447550/Epson_31082016150347.pdf)

Command run:
ocrmypdf /tmp/SchoolLetter.pdf /tmp/SchoolLetter.ocr.pdf -v 1

System is Debian jessie / sid.
$ ocrmypdf --version
4.2

**Comment by jbarlow83** [comment]
PDFs produced by printers seem to have many quirks. I'll create a fix.

Would you mind creating another page for inclusion in the test suite? I'd
rather not include personal identifying information. Just print and scan
the first page of a Wikipedia article.

**Comment by jbarlow83** [comment]
Never mind creating another file for me. There's a few interesting features in this file that I want for future test cases so I took the liberty of redacting the personal information which makes it fairly generic. If this is a problem please let me know.

**Comment by lowesjam** [comment]
Sounds OK for me - nothing too exciting in the file, I don't think (the
scan itself was just a mailshot from one of my children's school).

Thanks for the speedy response!

James
