### ISSUE TITLE
Possibility to correct the OCR text

### ISSUE THREAD

**Issue by raymanzarek1984** [jbarlow83/OCRmyPDF#91]
Hi, I congratulate you for the excellent job done.
Is there the opportunity to correct the OCR text before (or after) inserting it in the PDF file?
Thank you!

**Comment by jbarlow83** [comment]
You can sometimes improve OCR with the --clean argument. You could also modify tesseract.py to provide a [custom word list](https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#config-files-and-augmenting-with-user-data) to tesseract, or their advice on [improving quality](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality). 

Manual correction is not something I will be able to implement as it will require a full GUI to adjust glyph positions. I also want to keep this software automatic. 

Abbyy FineReader (commercial solution) lets you edit text post-OCR. It's quite a tedious process.

**Comment by jbarlow83** [comment]
Now that I think more about it, there is a pathway that makes this possible. If you were to run `ocrmypdf -k` (which keeps all intermediate files) you could manually edit the HTML-like .hocr file in that folder, and then run "hocrtransform.py" on the final files, you could achieve the desired corrections.

There are programs that can analyze .hocr
https://github.com/tmbdev/hocr-tools 

and programs to support editing it
http://jimgarrison.org/moz-hocr-edit/ (discontinued)

It is also possible to adjust the parameters that tesseract uses to suppress invalid words and unlikely symbol combinations.

I'll keep this issue open in the hopes of collecting ideas about the kind of corrections people want to make.

**Comment by raymanzarek1984** [comment]
I really appreciate all you do!
I will try these solutions.
Thank you

**Comment by raymanzarek1984** [comment]
I am trying to edit the temporary hocr file and running "hocrtransform.py" on the final file works to build a text only PDF file.
How is possible to build the entire PDF from all temporary files?
Thank you!

**Comment by jbarlow83** [comment]
You can call hocrtransform from the command line and give it the image you wish to use. ocrmypdf would normally use the filename `000001.image` as the image.

```bash
python3 -m ocrmypdf.hocrtransform --image 000001.image 000001.hocr manual_000001.pdf
```

You can use qpdf to combine the single page PDFs into a PDF. 

```bash
qpdf original.pdf --pages manual_*.pdf -- outputfile.pdf
```

`original.pdf` should be the original PDF, IIRC, from which it will gather overall document information. If you need outputfile to be a PDF/A you could write a script to invoke ocrmypdf.generate_pdfa for you.

So you're forewarned, I haven't actually tested this.

**Comment by raymanzarek1984** [comment]
Thank you, I will try!

**Comment by raymanzarek1984** [comment]
I generated the PDF file from all pages but i cannot achieve PDF/A outfile.
I used the command `python3 -m ocrmypdf.generate_pdfa outputfile.pdf` but I got 

> No module named ocrmypdf.generate_pdfa

**Comment by jbarlow83** [comment]
You will have to write a Python script to call that function. It's not a runnable module. 

It is also in ocrmypdf.ghostscript.

**Comment by SpencerRP** [comment]
You may want to close this.
