### ISSUE TITLE
Licensing of milk.pdf - organize any restricted fair use files for easy opt-out

### ISSUE THREAD

**Issue by spwhitton** [jbarlow83/OCRmyPDF#93]
Hello,

`tests/resources/README.rst` claims that `tests/resources/milk.pdf` is licensed by @lowesjam under the project's MIT license. Did @lowesjam write the text in the file, though?  It looks like it comes from a British primary school.  Is @lowesjam a representative of that school?  If not, they can't license it under MIT just because they made some changes to the PDF to make it suitable for the test suite.  The school hold copyright on the text.

Unless the intention is to invoke some fair use provision about use of the text?  Or something about crown copyright?  I'd be grateful for more information on the licensing of `milk.pdf`.

Thanks.

**Comment by jbarlow83** [comment]
It was a British school. 

If I understand correctly the UK Open Government License should apply although we'd need a version that does not redact the name of the provider.
https://en.wikipedia.org/wiki/Open_Government_Licence

There's a fair use exception for text and data mining that would seem to apply...
https://www.gov.uk/guidance/exceptions-to-copyright#text-and-data-mining-for-non-commercial-research

What either option work for Debian?

**Comment by spwhitton** [comment]
That Wikipedia article says "The works must have been expressly released under the OGL terms by the relevant rights owner or authorised information provider."  So unless the school did that, we can't use it under those terms.

The fair use exception isn't sufficient because files in Debian must not have any restrictions to only non-commercial use.

It looks like I'll have to start filtering this file out when I prepare the Debian packaging of OCRmyPDF.  Thank you for taking the time to reply, which helped me confirm that I need to do that.

**Comment by jbarlow83** [comment]
Okay. Since interesting test cases come from all sorts of places, this will probably happen again, so in a future release I'll organize the "restricted but fair use" files to a different place so they are easy to skip.

**Comment by spwhitton** [comment]
That would be ideal.

**Comment by lowesjam** [comment]
Since I think the interesting thing about this file is the scanner PDF
construction rather than the image bitmap, would you rather I scanned
something obviously public domain?

**Comment by jbarlow83** [comment]
@lowesjam it is very likely related to your scanner. It would be great if
you find a public domain scan that replicates the issue you reported -
probably any scanned image on your scanner, possibly linked to any page
rotation options it had.

For example print and scan the first page of your favourite Wikipedia
article.

**Comment by spwhitton** [comment]
You should know that I'm still going to have to do some filtering
because the non-free milk.pdf is now in your git history, which I can't
push to Debian's git servers.  However, it would be great to be able to
run the full test suite.

@lowesjam are you likely to be able to submit a replacement within the
next week or so?  If so, I'll just skip uploading the 4.2.4 release to
Debian.

Thanks!

**Comment by jbarlow83** [comment]
@spwhitton 

I'm going to be traveling for a few weeks and won't be able to work on this. 

I apologize for the timing because it looks like it would be pretty easy to use the BFG repo cleaner and rip out anything suspicious, but I'm just not comfortable pulling the trigger, pushing rewritten history and hoping nothing breaks. When I get back in October I will scrub the history properly.

My suggestion is to not wait for @lowesjam because I likely won't have time to commit it.

If you are filtering history now at least the following files (some from before I was handed control of the project) are also suspect:
```
2013_09_LED_und_Energiesparlampen.pdf
src/test/Test_Issue_#28.pdf
src/test/Test_Issue_28.pdf
test.pdf
ocrmypdf/data/sRGB_IEC61966-2-1_black_scaled.icc
```
(To check for yourself, `git log --pretty=format: --name-only --diff-filter=A | sort -u` )

At some point the entire source code of JHOVE v1 was included which is LGPL, in jhove/ with compiled output in ocrmypdf/jhove/, if that matters or if it's necessary to cite LGPL because of that.

In terms of non-free tests in the future I will explore:
* making a script to redact any potentially copyrighted content from PDF while preserving whatever interesting feature of the file broke ocrmypdf
* if necessary, creating a separate project to house any non-free test suite and files

**Comment by spwhitton** [comment]
Thanks for that info, and for taking these redistributibility issues
seriously.  I'll take appropriate action on the Debian end.  I'm not
sure whether it's wise for you to rewrite your history since there are
so many GitHub forks, but I'd appreciate it if you'd let me know what
you do decide to do so I can decide whether I need to use `git merge` or
`git merge --squash`.

-- 
Sean Whitton

**Comment by lowesjam** [comment]
PDF scan of Wikipedia article attached:

https://en.wikipedia.org/w/index.php?title=Optical_character_recognition&printable=yes

"Text is available under the Creative Commons Attribution-ShareAlike License
<https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License>;
additional terms may apply. By using this site, you agree to the Terms of
Use <https://wikimediafoundation.org/wiki/Terms_of_Use> and Privacy Policy
<https://wikimediafoundation.org/wiki/Privacy_policy>. Wikipedia® is a
registered trademark of the Wikimedia Foundation, Inc.
<https://www.wikimediafoundation.org/>, a non-profit organization."

It appears to have the same trouble as before (with ocrmypdf 4.2.2), so I
guess exhibits the same "features".

**Comment by jbarlow83** [comment]
@lowesjam I think you might have forgotten to include the attachment since no file made it through; or perhaps (probably) Github automatically filters emailed attachments. It should work if you drag and drop into the comment box on Github. Could you try again?

**Comment by lowesjam** [comment]
[Epson_Wikipedia_OCR.pdf](https://github.com/jbarlow83/OCRmyPDF/files/516441/Epson_Wikipedia_OCR.pdf)

Attached directly in GitHub (though I think it was my idiocy that prevented it before, rather than a GitHub filter).

- James

**Comment by jbarlow83** [comment]
Thanks! I've removed the non-free file.
